import { argument as a, group as g } from "./topic-unit";

// “方法”不是一套贯穿全史而保持不变的万能程序。这里比较的是：
// 不同时期怎样提出问题、组织论证、校正材料并公开自己的失败条件。
export const methodSummaryTree = [
  g("method-5-argument", "早期希腊至亚里士多德", "怎样把惊异和分歧变成可以检验的论证？",
    "早期自然哲学以共同来源、过程和比例压缩经验差异；爱利亚论证要求说法先通过概念一致性的检验。苏格拉底式定义与亚里士多德的分类、证明又把共同尺度和原因组织为可重复讨论的程序。这些方法并不等于现代实验科学，却共同改变了什么算作一个可争辩的解释。",
    "论证成为公共技艺以后，还要处理经文、翻译、注释与相互冲突的权威。", [
      g("method-10-hypothesis-refutation", "前苏格拉底哲学", "提出统一解释后，怎样检验它有没有说清变化？", "自然假说把多样追到来源和过程；巴门尼德与芝诺则检验生成、运动和多是否在概念上成立。后来的重组方案显示，反驳不必终止研究，也可能迫使解释改写前提。", "从反驳走向定义、分类和原因证明。", [
        a("method-20-natural-hypothesis", "米利都至赫拉克利特", "观察到差异和变化，怎样提出一种可比较的解释？", "共同来源、对立过程、稀薄凝聚与比例分别把现象压缩成较少原则。它们让解释可以互相比较，但观察、类比与大胆假说之间尚未形成现代意义上的统一验证程序。", "解释越统一，越要说明它是否在概念上允许生成和运动。", `difference-as-observation change-over-time-observation conditional-change-observation recurring-change-observation persistent-process-observation difference-derived-or-original identity-through-change order-not-arbitrary-agency one-source-many-states opposites-and-process rarefaction-condensation difference-as-ratio change-as-order`),
        a("method-20-eleatic-test", "巴门尼德、芝诺与多元论", "反直觉论证怎样迫使经验解释重写前提？", "巴门尼德拒绝让存在来自不存在，芝诺以悖论暴露关于运动和多的困难。多元论与原子论并非简单回到常识，而是保存不变成分、改用组合和排列解释变化。", "通过逻辑压力保存经验之后，还须形成共同定义和判断尺度。", `being-from-nonbeing stable-being motion-and-plurality-possible test-motion-and-plurality change-as-reconfiguration roots-love-strife mixture-nous-separation atoms-void-arrangement what-does-nous-explain`),
      ]),
      g("method-10-definition-demonstration", "苏格拉底至亚里士多德", "共同定义和原因怎样把意见变成知识？", "公共分歧使哲学追问不随个案改变的定义。柏拉图以稳定对象支撑知识，亚里士多德则把形式、分类与证明放回具体事物，并区分不同的原因问题。", "当论证进入宗教文本和跨语言传统，定义还须接受语境与翻译检验。", [
        a("method-20-definition-standard", "苏格拉底与柏拉图", "不同经验和意见冲突时，怎样寻找共同尺度？", "从相对显现转向共同定义，可以暴露例子与原则之间的矛盾；稳定形式则为知识提供对象。定义不是多数意见的平均值，也不能只靠命名就保证现实中有对应事物。", "共同尺度还需要说明怎样从经验材料得出原因。", `same-thing-different-appearance public-disagreement-observation what-does-perception-reveal perception-as-event appearance-relative-to-perceiver common-standard-of-judgment definition-beyond-instance what-stabilizes-knowledge stable-object-of-knowledge forms-and-particulars`),
        a("method-20-causes-demonstration", "亚里士多德", "分类、逻辑与四因分别承担什么解释工作？", "观察与分类帮助找到研究对象和起点，证明展示结论为何由原因成立；质料、形式、动力与目的则回答不同的为什么。形式化有效并不意味着前提已经由逻辑自身得到保证。", "证明的前提若来自继承文本和多种语言，知识还需要校勘与解释程序。", `immanent-form-matter organized-life-observation change-as-actualization-question potentiality-actuality what-makes-explanation-complete four-causes-teleology how-can-causes-be-known demonstration-classification`),
      ]),
    ], "先提出较少原则，再让概念反驳、共同定义和原因证明逐层检验解释。", [{ label: "SEP · Aristotle's Logic", url: "https://plato.stanford.edu/entries/aristotle-logic/" }]),

  g("method-5-text-authority", "教父时期至中世纪大学", "文本、翻译与权威冲突时，怎样继续推理？",
    "教父释经尝试让哲学理性在启示内部工作；跨语言翻译网络又把文本改造成新的课程和证明体系。中世纪学校把问题、反对、区分与答辩固定为公共程序，并通过词义、语境、心理语言与简约原则检查实体承诺。这里既有理性扩展，也有制度审查与权力边界。",
    "可传授的辩难仍可能积累错误，因此下一步转向校勘、测量、模型和实验的交叉纠错。", [
      g("method-10-exegesis-translation", "教父哲学与跨语言知识网络", "解释传统时，怎样避免任意寓意或机械照搬？", "多层释义要求说明字面、语境与哲学概念的关系；翻译和注释则必须区分保留的论证、改变的词汇和新增的课程问题。理性既可服务权威，也可校正较弱解释。", "解释规则进入学校后，需要稳定的反对、答辩与复核程序。", [
        a("method-20-exegesis-context", "教父哲学至加洛林复兴", "经文中的叙事和表面冲突，怎样进入理性讨论？", "逻各斯与多层释义让哲学概念参与经文解释；爱留根纳进一步主张真正理性与真正权威不会冲突。这个原则要求重查语境与解释强度，不赋予解释者任意制造寓意的权力。", "跨语言传播会让同一问题在新词汇和学科结构中改变。", `how-can-revelation-enter-reason logos-layered-exegesis-text carolingian-learning-revival-observation can-reason-judge-authority true-reason-true-authority-agree apparent-conflicts-require-context`),
        a("method-20-translation-commentary", "阿拉伯语、希伯来语与拉丁语传统", "翻译除了词句，还会改变哪些论证条件？", "翻译、注释、分类和原创论证共同把外来作品变成新的知识网络。证明、辩证和修辞面向不同读者；若哲学结论与经文冲突，还须核对证明是否成立以及解释规则是否适用。", "材料增多以后，争论需要能够重复教授和公开检查。", `greek-syriac-arabic-translation-observation what-translation-preserves-transforms translation-commentary-demonstration-network can-demonstration-and-revelation-share-world avicenna-demonstrative-sciences-system can-philosophy-be-criticized-with-own-tools logic-reused-metaphysics-contested how-can-law-and-demonstration-relate demonstration-dialectic-rhetoric-audiences hebrew-latin-translations-remake-curricula how-latin-schools-judge-new-authorities`),
      ]),
      g("method-10-disputation-language", "城市学校至晚期经院哲学", "怎样把分歧变成可重复的课程，并控制概念负担？", "问答、反对、区分和逐项答辩把争论从个人胜负转成程序；名称、意义、所指与心理词项的区分，则检验语法是否偷偷制造了额外实体。简约原则只在理性、经验和可靠权威都不要求增加实体时适用。", "程序化论证仍须面对文本异本、测量偏差和观察反例。", [
        a("method-20-disputation-curriculum", "十二世纪学校与大学", "公开反对和答辩怎样产生可积累的知识？", "竞争学校把问题、异议、区分和回应固定下来，并用词义、语境与作者意图辨析表面冲突。大学团体、学院分工和上诉程序使争论能够延续，但制度稳定不自动保证结论正确。", "概念分析还要检查共同名称是否迫使我们承诺共同实体。", `competing-school-masters-observation can-disagreement-become-teachable-method question-objection-distinction-method may-dialectic-examine-sacred-doctrine apparent-conflicts-require-context how-can-dispute-become-stable-curriculum repeatable-question-disputation-curriculum university-corporation-observation can-learning-community-govern-conflict corporate-privileges-faculty-jurisdictions`),
        a("method-20-signs-parsimony", "共相争论与奥卡姆", "语言的共同形式，何时足以支持一种实体承诺？", "共同谓词可以由心理概念自然指称多个个体，并不自动要求外物中另有一个共相实体。奥卡姆拒绝共相主要依论证困难，而非一句剃刀口号；是否增加实体仍要看理性、经验或可靠权威是否提供根据。", "语言节约不能代替事实纠错，研究必须返回文本和经验。", `common-terms-many-individuals-observation what-makes-common-term-true-of-many universality-in-name-not-common-entity universal-term-without-universal-thing does-language-analysis-clarify-trinity distinguish-sound-meaning-reference-doctrine do-common-predicates-require-common-natures individuals-and-universal-mental-signs how-do-mental-terms-signify-things intuitive-cognition-causes-mental-language is-nominalism-just-the-razor universals-rejected-by-incoherence-not-razor-alone when-is-extra-entity-warranted parsimony-bounded-by-reason-experience-scripture`),
      ]),
    ], "让解释公开语境，让争论保留反对意见，让语言分析核对自己增加了什么对象。", [{ label: "SEP · Medieval Theories of Demonstration", url: "https://plato.stanford.edu/entries/demonstration-medieval/" }]),

  g("method-5-public-test", "晚期中世纪至科学革命", "怎样让解释接受文本、数字、仪器和他人的共同纠错？",
    "罗吉尔·培根与人文主义校勘让权威材料面对语言、异文和测量误差；哥白尼与开普勒区分计算拟合、观测残差和物理解释；伽利略把仪器校准、理想化操作和数学关系相连；弗兰西斯·培根则诊断偏见、比较正反实例，并设想跨代研究组织。它们不是一种突然出现的唯一科学方法。",
    "公共检验提高了可靠性，却仍要回答：观察和推理的确定性究竟能走多远？", [
      g("method-10-correction-model", "罗吉尔·培根至开普勒", "材料或模型与细节冲突时，应该改动哪一层？", "文本错误可由语言和异本校正，天体模型则需区分计算便利、观测拟合和对真实结构的主张。顽固残差不是自动真理，但会迫使优美模型交代失败。", "观测本身依赖仪器和操作，因此还需检验看见的条件。", [
        a("method-20-text-measurement", "罗吉尔·培根与文艺复兴校勘", "继承材料出现异文和测量错误时，怎样定位并纠正？", "语言、数学、光学和经验可以交叉检查权威文本；回到原文、早期见证和历史语境则校正后来的译文与注释。纠正权威不等于取消传统，而是让继承材料公开可复核的差异。", "同样的纠错要求可转向模型与观测之间的偏差。", `translation-measurement-error-observation how-can-authority-correct-inherited-error languages-mathematics-optics-correct-authority what-certifies-conclusion-beyond-argument experience-certifies-theoretical-conclusions renaissance-text-variants-print-observation how-can-inherited-text-authority-be-corrected ad-fontes-philology-corrects-inheritance`),
        a("method-20-model-residual", "哥白尼与开普勒", "模型算得通、数据也大致吻合，是否已经证明世界结构？", "哥白尼用日心次序重排现象，计算拟合并不独自证明地球运动。开普勒让火星残差迫使匀速圆周让位于椭圆和面积关系，显示反例可以修改模型结构；规律的成功仍与原因解释不同。", "要判断新现象，还需说明仪器和理想化怎样取得证据资格。", `does-computational-fit-establish-cosmic-truth planetary-retrograde-models-observation copernican-model-reorders-appearances why-earth-motion-is-not-directly-felt shared-motion-reframes-earth-observation tycho-mars-residual-observation when-should-residual-overturn-beautiful-model keplerian-residuals-revise-geometry does-mathematical-law-describe-or-explain sun-centered-physical-causation-attempt`),
      ]),
      g("method-10-experiment-organization", "伽利略与弗兰西斯·培根", "一次观察怎样成为别人可以重做和反驳的检验？", "仪器观察需要校准、记录与重复，理想实验要交代删去了哪些干扰。培根的归纳表、排除和人工干预则试图对抗偏见与简单枚举；研究分工扩大纠错能力，也带来治理和用途边界。", "共同操作仍无法取消主体如何组织经验的认识论问题。", [
        a("method-20-instrument-idealization", "伽利略", "仪器和理想化是在扭曲自然，还是在暴露可检验关系？", "望远镜观察靠校准、记录和重复稳定；理想实验则把摩擦等干扰作为可说明的操作条件，借数学关系对照现实。多条证据汇合可以提高模型辨别力，但单一新奇现象很少独自裁决整个宇宙体系。", "可重复操作怎样跨个人积累成研究共同体？", `when-can-instrument-mediated-seeing-be-trusted telescope-new-heavens-observation calibration-record-repetition-stabilize-instruments can-one-observation-decide-between-cosmic-systems convergent-evidence-discriminates-models messy-fall-motion-observation how-can-ideal-experiment-test-real-motion idealization-controlled-operation-mathematical-law can-local-mechanics-detect-uniform-motion galilean-relativity-shared-frame acceleration-and-composed-projectile-motion is-scientific-revolution-one-method-sudden-break plural-methods-form-public-correction-network`),
        a("method-20-induction-collaboration", "弗兰西斯·培根", "怎样系统寻找反例，又避免研究组织放大共同偏见？", "四类偶像诊断个人、语言和体系偏见；出现、缺失、程度表与排除反对简单枚举。实验和共同自然史让事实跨代积累，但程序不能自动生成好假说，组织能力也不自动等于公共善。", "方法不能只依靠外部程序，还要检查判断者自己的确定性要求。", `why-do-trained-inquirers-repeat-systematic-errors mind-language-systems-bias-observation four-idols-diagnose-inquiry-obstacles positive-cases-underdetermine-causes-observation why-is-simple-enumeration-insufficient tables-and-exclusion-build-gradual-induction do-tables-generate-the-right-hypothesis first-vintage-remains-provisional-not-algorithmic can-artifice-reveal-rather-than-distort-nature artifice-and-experiment-make-causes-visible how-can-natural-history-accumulate-across-generations division-of-labor-and-salomons-house does-scientific-organization-guarantee-public-good organized-inquiry-needs-governance-boundaries how-can-discovery-be-organized-beyond-genius can-private-self-discipline-remove-idols shared-procedures-counter-idols-without-purity`),
      ]),
    ], "把纠错分散到文本、测量、模型、仪器、实验和研究组织，不让任何单项自动获得最终裁决权。", [{ label: "SEP · Scientific Method", url: "https://plato.stanford.edu/entries/scientific-method/" }]),

  g("method-5-critique", "霍布斯、笛卡尔至康德", "知识应从不可怀疑的起点重建，还是从可错经验中受限前进？",
    "霍布斯用名称、定义和计算组织推理，却承认定义不能独自证明自然事实。笛卡尔以方法怀疑寻找我思的确定性，再面对真理规则如何扩展的难题。洛克与休谟追问观念来源、概率和归纳根据；康德则改问经验对象得以成立的主体条件，同时限制知识于现象。方法之争由此成为对知识边界的争论。",
    "承认认识条件和限度之后，还要说明历史、价值和实践中的失败如何参与纠错。", [
      g("method-10-reconstruction", "霍布斯与笛卡尔", "定义和确定起点能否演绎出完整世界？", "名称与定义可防止语言推理滑动，我思则在怀疑行为中取得确定性；但两者都不能无桥梁地恢复全部事实。构造证明、自然经验和真理保证承担不同工作。", "经验主义改从观念材料与知识程度检验重建范围。", [
        a("method-20-definition-reckoning", "霍布斯", "严格定义能消除语言争议，也能直接证明外部事实吗？", "把推理视为名称后果的计算，可以提高一致性；人工共同体因为由人构造，更适合条件性演绎。自然事物并非由定义制造，因而定义一致不等于经验事实已经得到证明。", "笛卡尔进一步寻找连怀疑也无法取消的判断起点。", `words-enable-general-reason-and-dispute-observation how-can-reason-escape-verbal-absurdity names-definitions-reasoning-as-reckoning can-definitions-alone-prove-the-world made-commonwealth-supports-conditional-civil-science`),
        a("method-20-doubt-cogito", "笛卡尔", "撤回一切可疑信念后，什么能够作为重建起点？", "方法怀疑暂时悬置感官、梦境和系统欺骗下不可靠的信念；我思在被实际进行时不可否认。它首先保证当下思考者，并不直接证明持续人格、身体或整个外部世界，真理规则仍需额外论证。", "确定性路线的高门槛促使经验主义重新划分知识和概率。", `methodic-doubt-suspends-uncertain-beliefs does-any-judgment-survive-hyperbolic-doubt cogito-performed-certainty what-is-the-self-known-in-cogito can-cogito-yield-general-truth-rule thinking-thing-before-body clear-distinct-perception-provisional-rule can-finite-thinker-secure-clear-distinct-truth nondeceiving-god-secures-attended-clear-perceptions why-error-if-nondeceiving-god error-when-will-outruns-intellect`),
      ]),
      g("method-10-source-conditions", "洛克、休谟与康德", "观念来源、归纳习惯和经验条件分别能支持什么？", "洛克把材料追到感觉和反省，并以概率处理超出确定知识的行动；休谟用印象来源检验概念，揭示归纳不能非循环证明。康德则主张时空、范畴与统觉是客观经验的条件，不据此描述物自身。", "认识论批判之外，历史和实践也会暴露理论没有看见的前提。", [
        a("method-20-ideas-probability", "洛克", "经验提供材料以后，心灵怎样形成一般观念并判断现实？", "感觉与反省提供简单观念，心灵通过组合、比较和抽象形成复杂与一般思想。知识把握观念关系，超出确定范围时用经验一致、证言和概率指导行动；这比全然怀疑更实用，也保留误判风险。", "休谟把来源检验推进到因果和归纳的根据。", `sensation-and-reflection-supply-idea-materials how-do-simple-ideas-form-complex-general-thought combination-comparison-abstraction-organize-experience how-far-does-knowledge-extend-beyond-ideas knowledge-as-agreement-probability-for-practice`),
        a("method-20-induction-critical-conditions", "休谟与康德", "经验无法证明未来必然重复过去时，科学判断靠什么？", "休谟区分观念关系与事实问题，以习惯解释归纳期待，同时用缓和怀疑限制断言。他对自我统一的困难也显示，来源检验未必自动提供完整主体。康德转而追问时空、范畴与统觉如何使客观经验可能，并把因果限定为现象经验的条件。两者不是同一种回答，也都拒绝把方法无限外推。", "知识边界清楚以后，方法还要面对历史、权力和生活后果。", `simple-ideas-copy-impressions-source-test what-judgments-survive-experience-source-test relations-of-ideas-and-matters-of-fact novel-object-effects-not-a-priori-observation how-infer-beyond-memory-and-present-sense fact-inference-depends-on-cause-effect can-reason-demonstrate-causal-effect causal-effect-not-demonstrable-a-priori can-experience-prove-future-resembles-past uniformity-defense-circular-or-nondemonstrative does-custom-explain-or-justify-induction custom-naturally-sustains-calibrated-expectation can-scepticism-guide-life-without-paralysis mitigated-scepticism-limits-and-corrects-inquiry what-unifies-person-without-self-impression self-as-bundle-and-succession-of-perceptions can-association-explain-one-mind-and-responsibility association-explains-identity-fiction-not-full-unity can-objective-experience-have-necessity-beyond-habit copernican-turn-objects-conform-to-cognition how-are-synthetic-a-priori-judgments-possible how-manifold-becomes-one-objective-experience categories-and-apperception-unify-experience how-subjective-succession-becomes-objective-event causality-as-condition-of-objective-succession do-cognitive-conditions-describe-things-in-themselves knowledge-limited-to-phenomena-not-private-illusion`),
      ]),
    ], "比较演绎重建、经验来源审查与先验条件批判，并逐项限制它们能够支持的结论。", [{ label: "SEP · Epistemological Problems of Perception", url: "https://plato.stanford.edu/entries/perception-episprob/" }]),

  g("method-5-plural-correction", "黑格尔至实用主义与逻辑分析", "当历史和实践会改变问题本身，怎样继续保持清晰与可纠错？",
    "黑格尔让概念在自身失败中转化，马克思把思想批判放回生产关系与集体实践，尼采用谱系追踪价值的历史、情感和功能。詹姆斯与杜威以实际差异和疑难情境组织可错探究；弗雷格与罗素分析逻辑形式与指称。终点不是选出唯一方法，而是要求各方法公开对象、证据、范围和失败条件。",
    "回到任何主题时，都应说明当前使用了哪种尺度，以及它遗漏了什么。", [
      g("method-10-history-genealogy", "黑格尔、马克思与尼采", "概念和价值的失败，能否由历史形成过程解释？", "辩证法检验规定自身承诺，历史唯物主义追踪生产与制度限制，谱系考察起源、功能转移和情感训练。三者都反对孤立概念，却不能压成同一种历史决定论。", "历史诊断还要转化为可行动、可反馈的探究。", [
        a("method-20-dialectic-history", "黑格尔与马克思", "概念的内在矛盾和物质实践，分别怎样推动批判？", "黑格尔的辩证法不是机械正反合，而是让规定在贯彻自身时暴露不足；马克思则追问生产关系、制度和实践如何限制或改变观念。整体解释必须面对未获和解者，结构也不能自动产生行动主体。", "来源与结构说明仍不能单独决定一种价值是否值得保留。", `determinate-negation-transforms-opposition is-dialectic-fixed-thesis-antithesis-synthesis dialectic-is-immanent-not-fixed-triad can-conceptual-dialectic-describe-objective-world objective-idealism-reason-immanent-in-world does-world-history-redeem-suffering-and-exclusion totality-must-remain-answerable-to-unreconciled-lives do-ideas-or-material-practices-drive-history historical-materialism-constrains-without-mechanical-determinism does-class-position-automatically-create-agent class-agency-requires-organization-and-learning`),
        a("method-20-genealogy-perspective", "尼采", "揭示价值的来源，是否已经证明它虚假或无效？", "谱系把道德概念放回语言、惩罚、权力和情感形成史，显示现在的功能并非天然必然。来源本身不是简单反驳；评价还须比较解释能力、证据阻力与生命和政治后果。视角性也不等于所有解释同样正确。", "比较后果的评价需要能够在行动中继续修正。", `moral-concepts-change-observation what-can-genealogy-show-about-value genealogy-links-origin-function-affect-effect how-ressentiment-revalues-noble-power ressentiment-creates-reactive-good-evil how-debt-punishment-becomes-guilt bad-conscience-internalizes-aggression-and-debt is-perspectivism-simple-relativism perspectivism-compares-situated-interpretations can-revaluation-avoid-arbitrary-cruelty revaluation-tests-creative-flourishing-with-political-risk`),
      ]),
      g("method-10-inquiry-analysis", "詹姆斯、杜威、弗雷格与罗素", "实际后果与逻辑形式怎样共同减少伪问题？", "实用方法追问观念在经验和行动中的可辨差异，杜威把疑难情境转成共同实验；逻辑分析则重写量词、关系和摹状词，暴露语法制造的承诺。实践成功不替代真实性约束，形式清晰也不能独自裁决历史与价值。", "以多种公开尺度协作，而不是寻找吞并其余方法的总方法。", [
        a("method-20-pragmatic-inquiry", "詹姆斯与杜威", "观念的意义和真值，怎样在行动与持续探究中接受检验？", "实用方法用可经验的差异澄清争点，真理须经验证并承受现实阻力。杜威从疑难情境出发，用观察、假设和实验取得可断言结论；结论始终向新证据开放，公共探究还需要信息、教育和反权力制度。", "比较理由时，语言的表面形式仍可能制造伪对象和歧义。", `temperament-metaphysical-dispute-observation does-practical-difference-exhaust-meaning pragmatic-meaning-guides-inquiry-not-instant-verdict is-truth-whatever-is-currently-useful truth-grows-through-verification-and-reality-constraint problematic-situation-observation must-knowledge-begin-with-certainty warranted-assertibility-through-disciplined-inquiry how-institutionalize-fallible-plural-inquiry inquiry-transforms-problematic-situation does-public-inquiry-need-logical-analysis`),
        a("method-20-logical-analysis", "弗雷格与罗素", "澄清逻辑形式能解决什么，又不能替代什么？", "量词和关系逻辑超出传统主谓结构，意义—指称区分解释同指名称的认知差异，类型论与摹状词分析分别处理自指悖论和不存在对象。分析可使用相对简单项，却不能单独裁决历史、经验和价值。", "让逻辑、经验、历史、生活体验与规范批评各自公开失败条件并互相纠正。", `grammar-hides-logical-form-observation can-traditional-subject-predicate-logic-express-relations frege-quantification-function-argument-logic why-identity-statements-differ-in-cognitive-value frege-sense-reference-distinction set-foundation-paradox-observation how-block-self-referential-totality-paradox type-theory-restricts-illicit-self-application how-speak-truly-about-nonexistent-descriptions descriptions-as-quantified-incomplete-symbols must-analysis-reach-absolute-simples analysis-works-with-relative-simplicity can-formal-analysis-settle-history-value-experience plural-methods-correct-without-totalizing how-combine-clarity-history-experience-freedom-public-correction`),
      ]),
    ], "用历史诊断暴露前提，用实践反馈修正行动，用逻辑分析澄清承诺；任何尺度都必须说明自己的边界。", [{ label: "SEP · Pragmatism", url: "https://plato.stanford.edu/entries/pragmatism/" }, { label: "SEP · Logical Analysis", url: "https://plato.stanford.edu/entries/logical-analysis/" }]),
];
