import { argument as a, group as g } from "./topic-unit";

export const natureSummaryTree = [
  g("nature-5-change", "早期希腊", "万物不同又不断变化，怎样解释它们？",
    "早期希腊思想家尝试用共同本原、转化过程和比例解释差异。巴门尼德质疑：如果变化意味着从不存在变成存在，这个说法能成立吗？多元论者与原子论者则保留基本成分，用分合和排列解释变化。这不是一种答案逐渐改名，而是对什么必须保持不变的争论。",
    "即使说明东西由什么组成，还要解释它为什么形成这种结构、具有什么能力。", [
      g("nature-10-origin", "米利都至赫拉克利特", "不同事物是否有共同的来源？", "水、气、对立过程和比例提供不同的解释方案：差异可能来自共同材料的状态，也可能来自相反力量的关系。要区分提出可讨论的解释与已经获得实验证明。", "共同来源仍须说明变化如何发生。", [
        a("nature-20-source", "米利都学派", "一种本原怎样形成多种事物？", "泰勒斯等人把自然的差异追溯到共同来源。阿那克西曼德诉诸对立的分离，阿那克西美尼用稀薄与凝聚解释转化。它们把问题从逐个命名事物转到说明差异怎样产生，但这些方案并非现代物理学的定律。", "比较各方案：它交代了材料，还是也交代了转化过程？", `difference-derived-or-original difference-as-observation one-source-many-states opposites-and-process rarefaction-condensation`),
        a("nature-20-order", "毕达哥拉斯传统与赫拉克利特", "变化为什么不是毫无规则的混乱？", "比例使不同事物可以放在同一关系中理解；赫拉克利特则把相反力量和持续变化联系到共同秩序。两条思路都不满足于罗列现象，但比例解释与对立过程并不是同一种理论。", "若一切变化，什么仍可被稳定地认识？", `order-not-arbitrary-agency change-over-time-observation conditional-change-observation recurring-change-observation persistent-process-observation identity-through-change difference-as-ratio change-as-order`),
      ]),
      g("nature-10-being-motion", "爱利亚学派至原子论", "变化能否与存在的稳定性相容？", "爱利亚学派要求先检验关于存在和运动的说法是否自洽。多元论和原子论不直接放弃变化，而尝试让成分保持不变，把变化解释为关系改变。", "这种重组方案又留下秩序从何而来的问题。", [
        a("nature-20-eleatic", "巴门尼德与芝诺", "感觉到运动，就已经证明运动可理解吗？", "巴门尼德拒绝把非存在当作生成的来源；芝诺用悖论检验关于运动和多的通常说法。论证给变化提出解释负担，不能简化成他们没有看到运动。", "能否让基本成分不生不灭，而让它们的组合变化？", `being-from-nonbeing stable-being motion-and-plurality-possible test-motion-and-plurality`),
        a("nature-20-recombination", "恩培多克勒、阿那克萨戈拉与原子论", "成分不变，组合变化，能解释多少现象？", "四根的聚散、种子的分离、原子在虚空中的排列，都试图保存基本成分并解释可见变化。但推动变化的爱与争、努斯和原子运动并不等价；特别要问，命名一种动力是否已解释它怎样起作用。", "材料和运动之外，形式与目的是否也有解释作用？", `change-as-reconfiguration roots-love-strife mixture-nous-separation atoms-void-arrangement what-does-nous-explain`),
      ]),
    ], "先找共同来源，再追问：成分是否不变，变化是否只是重组？", [{ label: "SEP · 前苏格拉底哲学", url: "https://plato.stanford.edu/entries/presocratics/" }]),

  g("nature-5-explanation", "柏拉图至经院哲学", "知道材料之后，还缺少什么解释？",
    "柏拉图从稳定形式与善理解秩序，亚里士多德把形式放回具体事物，以质料、形式、动力和目的分别回答为什么。中世纪讨论又追问：如果世界依赖创造者，受造事物是否仍有真实的因果能力？自然解释与最高根据因此相接，却不能互相替代。",
    "接受一套原因说明之后，还需要判断它怎样被观察、论证和纠正。", [
      g("nature-10-form", "柏拉图与亚里士多德", "事物的结构在它自身，还是在不变的形式中？", "柏拉图以形式解释知识的稳定对象，并在宇宙论中联系秩序与善。亚里士多德则用具体事物中的形式与质料解释其是什么、能做什么。", "有了结构，还要交代从可能到现实的变化。", [
        a("nature-20-cosmic-form", "柏拉图", "认识和宇宙秩序为什么需要稳定形式？", "柏拉图用不变的可知对象回应感觉多变的问题，并以形式与善说明宇宙秩序。但可知形式怎样与具体事物相关，仍需要说明；宇宙论也不能被当成已验证的自然科学模型。", "亚里士多德将解释转向具体事物自身的结构。", `what-stabilizes-knowledge stable-object-of-knowledge forms-and-particulars how-can-cosmos-reflect-good cosmos-shaped-by-form-and-good`),
        a("nature-20-actualization", "亚里士多德", "一个事物怎样从可能状态变成现实？", "形式与质料共同构成具体事物。变化可理解为具有某种潜能的事物在相应条件下实现这种能力，因此不必把变化说成由绝对的无产生有。这里的潜能有具体条件，并非任何东西都可能变成任何东西。", "能力在何种条件下实现，需要进一步的原因说明。", `immanent-form-matter organized-life-observation change-as-actualization-question potentiality-actuality`),
      ]),
      g("nature-10-causes", "亚里士多德与中世纪", "自然事物能否凭自己的能力起作用？", "四因区分不同的解释任务。后来的争论则检验自然因果是否必然、受造事物是否有能力，以及第一因与具体原因怎样相容。共同用到“原因”，不表示各家的前提相同。", "原因说明还须接受经验和论证的约束。", [
        a("nature-20-four-causes", "亚里士多德", "解释一个生命或变化，为什么要问四种原因？", "质料说明由什么构成，形式说明它是什么，动力说明变化从何而起，目的说明活动趋向什么。亚里士多德并非给同一事件罗列四个先后推力，而是在区分解释任务；分类和证明还要把原因与可观察特征联系起来。", "目的解释能否适用于所有自然过程，是继续比较的地方。", `what-makes-explanation-complete four-causes-teleology how-can-causes-be-known demonstration-classification`),
        a("nature-20-created-causes", "安萨里、阿威罗伊与阿奎那", "依赖上帝的世界，还能有真实自然原因吗？", "安萨里质疑从通常相继直接推出必然联系。阿威罗伊维护自然事物的能力与论证；阿奎那认为第一因不取消受造者作为第二因的真实作用。创造的依赖关系又不同于证明世界在时间中有开端。", "不能把神学与自然学的复杂争论压成信仰阻碍科学的单线故事。", `are-created-causes-necessary regular-conjunction-not-logical-necessity natural-powers-support-demonstration do-secondary-causes-have-real-power created-causes-real-under-first-cause can-reason-prove-temporal-beginning creation-not-same-as-temporal-beginning`),
      ]),
    ], "从材料走向结构、能力与目的，再区分自然原因和世界的最高根据。", [{ label: "SEP · 亚里士多德的自然哲学", url: "https://plato.stanford.edu/entries/aristotle-natphil/" }]),

  g("nature-5-correction", "中世纪学术至近代科学", "怎样知道一种自然解释值得相信？",
    "罗吉尔·培根要求语言、数学和经验校正传统。哥白尼、开普勒和伽利略分别改变天体模型、处理观测偏差、发展仪器与数学实验。弗兰西斯·培根进一步讨论如何组织积累与检验。这里没有一种万能方法：模型、测量、实验和公共复核承担不同工作。",
    "解释越成功，越需要分清：它说明了可观察规律，还是也证明了世界的全部本性？", [
      g("nature-10-inheritance-models", "罗吉尔·培根至开普勒", "权威和优美模型遇到反例时，该修改什么？", "继承文本不意味着免于校正；数学上的整齐也不能代替观测。修订可以涉及翻译、测量或模型结构，而不是只选择相信传统或拒绝传统。", "观察本身也依赖仪器与可复查的操作。", [
        a("nature-20-correct-authority", "罗吉尔·培根", "继承的知识怎样发现并纠正自己的错误？", "罗吉尔·培根用语言、数学、光学和经验纠正翻译与推理中的问题。他把学术改革放在道德与宗教目标内，因此不能把他直接写成摆脱一切权威的现代实验主义者。", "纠错既需方法，也涉及课程和组织能否允许纠错。", `how-can-authority-correct-inherited-error translation-measurement-error-observation languages-mathematics-optics-correct-authority what-certifies-conclusion-beyond-argument experience-certifies-theoretical-conclusions is-experience-an-autonomous-end experimental-sciences-serve-moral-reform`),
        a("nature-20-celestial-models", "哥白尼与开普勒", "模型算得通，是否就说明世界真如此？", "哥白尼重排天体系统，计算上的配合并不独自确证地球运动。开普勒认真对待火星观测的残差，让数据迫使几何模型修改。预测、观测精度和物理解释是相关而不同的检验。", "运动中的地球为何不让人直接感到移动？需要新的运动解释。", `does-computational-fit-establish-cosmic-truth planetary-retrograde-models-observation copernican-model-reorders-appearances why-earth-motion-is-not-directly-felt shared-motion-reframes-earth-observation tycho-mars-residual-observation when-should-residual-overturn-beautiful-model keplerian-residuals-revise-geometry does-mathematical-law-describe-or-explain sun-centered-physical-causation-attempt what-can-publicly-correct-text-church-state-nature`),
      ]),
      g("nature-10-experiment", "伽利略与弗兰西斯·培根", "实验怎样从个人发现成为共同检验？", "伽利略把仪器、理想化和数学规律相连；弗兰西斯·培根强调反例、排除和分工积累。二者并不采用同一发现程序，但都让断言面对可纠正的操作。", "方法有效仍不意味着任何使用方式都造福公共生活。", [
        a("nature-20-galileo", "伽利略", "仪器与理想化会歪曲自然，还是揭示规律？", "望远镜观察需要校准和重复，不能只靠一次新奇景象。理想实验排除干扰，使数学关系可以与现实操作对照。共同运动解释为何某些局部经验不能辨别地球是否运动，证据的作用因此必须逐项判断。", "局部成功怎样积累为他人也能接续的研究？", `when-can-instrument-mediated-seeing-be-trusted telescope-new-heavens-observation calibration-record-repetition-stabilize-instruments can-one-observation-decide-between-cosmic-systems convergent-evidence-discriminates-models galilean-instruments-idealization-mathematics messy-fall-motion-observation how-can-ideal-experiment-test-real-motion idealization-controlled-operation-mathematical-law can-local-mechanics-detect-uniform-motion galilean-relativity-shared-frame acceleration-and-composed-projectile-motion is-scientific-revolution-one-method-sudden-break plural-methods-form-public-correction-network`),
        a("nature-20-bacon", "弗兰西斯·培根", "怎样避免只收集支持自己观点的例子？", "培根诊断心智、语言和学说的偏见，以正反事例和排除程序改进归纳。他也强调实验、自然史和研究分工。归纳表不是自动产生真理的算法，组织化的知识生产同样需要治理。", "规律和技术带来的能力，是否足以证明一种完整的世界观？", `why-do-trained-inquirers-repeat-systematic-errors mind-language-systems-bias-observation four-idols-diagnose-inquiry-obstacles positive-cases-underdetermine-causes-observation why-is-simple-enumeration-insufficient tables-and-exclusion-build-gradual-induction do-tables-generate-the-right-hypothesis first-vintage-remains-provisional-not-algorithmic can-artifice-reveal-rather-than-distort-nature artifice-and-experiment-make-causes-visible how-can-natural-history-accumulate-across-generations division-of-labor-and-salomons-house does-scientific-organization-guarantee-public-good organized-inquiry-needs-governance-boundaries how-can-discovery-be-organized-beyond-genius can-private-self-discipline-remove-idols shared-procedures-counter-idols-without-purity ordinary-nature-hides-powers-observation is-useful-control-the-same-as-understanding causes-and-works-connect-light-fruit-and-power scattered-crafts-private-facts-observation`),
      ]),
    ], "文本可以校正，模型可以修改；仪器、数学和实验要让他人能够复核。"),

  g("nature-5-knowledge", "笛卡尔至康德", "我们知道的是自然本身，还是认识它的方式？",
    "机械论尝试以广延和运动解释身体；斯宾诺莎与莱布尼茨提出不同的整体秩序。经验主义追问这些说法来自什么经验：洛克区分对象结构与感觉效果，贝克莱质疑物质基质，休谟追问因果必然性的根据。康德则从经验何以可能解释因果的作用，同时限制其超经验使用。",
    "这些限制对生命、时间和人的行动意味着什么？", [
      g("nature-10-world-order", "笛卡尔、霍布斯、斯宾诺莎与莱布尼茨", "统一的自然秩序要包含怎样的心灵与个体？", "身体机械论、单一实体和单子论给出不同的本体论。要分别检验每套理论怎样解释身体、知觉和个体，而不是把它们都称作自然规律。", "完整体系仍须说明我们怎样取得关于它的知识。", [
        a("nature-20-mechanism", "霍布斯与笛卡尔", "感觉和身体都能用运动来解释吗？", "霍布斯把感觉、想象与情感解释为身体过程；笛卡尔用广延与机械秩序说明物体，却坚持思维与广延的实在区分。两者不是同一套机械唯物论，笛卡尔还须解释心身怎样成为一个人。", "如果拒绝两个独立实体，统一的自然又怎样保存差异？", `can-mind-be-explained-without-immaterial-faculty bodily-impact-sensation-memory-observation sensation-imagination-passions-as-bodily-motion what-is-body-if-sensory-qualities-vary matter-as-extension-mechanical-order is-mind-really-distinct-from-body thought-extension-real-distinction how-can-distinct-mind-and-body-form-one-human mind-body-union-lived-not-mechanically-resolved what-can-thought-know-when-sense-and-words-mislead methodic-doubt-suspends-uncertain-beliefs does-any-judgment-survive-hyperbolic-doubt cogito-performed-certainty what-is-the-self-known-in-cogito thinking-thing-before-body can-two-created-substances-fit-one-intelligible-nature`),
        a("nature-20-substance-monads", "斯宾诺莎与莱布尼茨", "一个世界怎样容纳多种存在与视角？", "斯宾诺莎以一个实体的属性和样式说明差异，心与身是同一自然的不同表达。莱布尼茨则以多元单子和预定和谐说明共同世界。他区分必然真理与事实真理，不能把充分理由直接等同于一切都逻辑必然。", "这些形而上说明是否超过经验能够支持的范围？", `one-substance-god-or-nature how-can-finite-things-differ-within-one-substance attributes-and-modes-articulate-one-nature if-mind-and-body-do-not-interact-how-correspond mind-body-parallel-expression can-individuals-and-contingency-survive-complete-intelligibility monads-as-active-perspectival-unities how-can-windowless-monads-share-one-world preestablished-harmony-coordinates-perspectives does-complete-reason-make-every-truth-necessary truths-of-reason-fact-and-possible-worlds`),
      ]),
      g("nature-10-experience-causation", "洛克、贝克莱、休谟与康德", "感觉、物体与因果之间怎样连接？", "关于对象的观念从哪里来，物质基质增加了什么，因果推断又凭什么成立，是三层不同的问题。康德改变提问方式，考察客观经验所必需的条件，并不宣称因此认识物自身。", "知识边界让自然研究更明确，也留下行动与价值的地位。", [
        a("nature-20-qualities", "洛克与贝克莱", "颜色和形状都在经验中，为什么区别对待？", "洛克把第一性质与对象结构相连，把第二性质解释为对象产生感觉的能力。贝克莱质疑能否脱离感知构想第一性质，并用稳定的观念组合说明日常对象。他否认物质基质，并不否认人经验到石头和树木。", "即使承认稳定经验，仍要说明从过去推向未来的根据。", `which-qualities-belong-to-objects-themselves color-shape-vary-with-conditions-observation primary-structures-secondary-powers-distinction what-supports-clustered-qualities substance-as-unknown-support-and-real-essence if-only-ideas-are-immediate-what-does-matter-explain material-substratum-adds-no-experiential-content are-primary-qualities-independent-of-perception primary-qualities-also-perception-relative does-immaterialism-deny-stones-and-trees ordinary-objects-as-stable-idea-combinations sensory-ideas-arrive-involuntarily-observation what-causes-involuntary-sensory-ideas ideas-passive-spirits-active-god-orders-sense do-objects-exist-when-no-human-perceives divine-perception-and-natural-signs-preserve-order does-immaterialism-defeat-or-deepen-skepticism direct-idea-world-with-notions-of-spirit can-spirit-cause-and-self-survive-strict-experience-test`),
        a("nature-20-causal-knowledge", "休谟与康德", "多次相继发生，为什么能说存在必然联系？", "休谟指出，重复经验培养期待，却不能无循环地证明未来必定像过去。康德把因果规则看作客观事件经验的条件：我不只是先后感觉，还判断事情按规则发生。这不是证明物自身也必定如此。", "自然因果能否同时容纳自由行动？可从这里转入自我。", `how-infer-beyond-memory-and-present-sense fact-inference-depends-on-cause-effect can-reason-demonstrate-causal-effect causal-effect-not-demonstrable-a-priori can-experience-prove-future-resembles-past uniformity-defense-circular-or-nondemonstrative repetition-produces-expectation-observation what-impression-supplies-necessary-connection necessary-connection-as-customary-transition does-custom-explain-or-justify-induction custom-naturally-sustains-calibrated-expectation can-objective-experience-have-necessity-beyond-habit copernican-turn-objects-conform-to-cognition how-subjective-succession-becomes-objective-event causality-as-condition-of-objective-succession do-cognitive-conditions-describe-things-in-themselves knowledge-limited-to-phenomena-not-private-illusion simple-ideas-copy-impressions-source-test what-judgments-survive-experience-source-test relations-of-ideas-and-matters-of-fact how-are-synthetic-a-priori-judgments-possible are-space-time-things-or-forms-of-intuition space-time-a-priori-forms-of-intuition how-manifold-becomes-one-objective-experience categories-and-apperception-unify-experience`),
      ]),
    ], "从机械论和整体秩序，追到感觉的根据、因果的效力与知识的边界。"),

  g("nature-5-life", "康德至杜威；回看因果与自由", "生命、时间和人的行动怎样属于自然？",
    "康德用反思判断讨论有机体的合目的性，但不把它当作造物目的的科学证明。浪漫主义与柏格森分别关注活的整体和不可还原为钟表刻度的绵延。杜威把经验理解为有机体与环境的交互。人的自由也要在这些讨论中检验：有原因，不一定等于没有自己的行动能力。",
    "可沿同一节点转入自我看责任，或转入社会看共同探究怎样组织。", [
      g("nature-10-organism-time", "康德、浪漫主义与柏格森", "机械说明是否已经说尽生命与时间？", "判断有机体时，我们常以部分与整体的相互作用来理解它；经历时间时，也未必只是数出等长刻度。这些反思提醒我们区分解释任务，不能据此宣布物理学或生物学无效。", "比较解释范围，比让哲学替代科学更有助于学习。", [
        a("nature-20-organism", "康德与浪漫主义", "把生命理解为有目的，是否已证明它被设计？", "康德认为反思判断可借合目的性理解有机体，却不能由此获得超经验的理论知识。浪漫主义的有机自然观则反对把活的整体视为零件堆积。二者都关注整体，但其论证与认识边界不同。", "生命的成长也让我们追问新变化是否只是既定过程的重复。", `how-judgment-bridges-nature-and-freedom beauty-organisms-purposiveness-observation reflective-judgment-purposiveness-without-proof mechanistic-nature-alienation-observation is-nature-only-mechanical-system organic-living-nature-as-romantic-countermodel`),
        a("nature-20-duration", "柏格森", "钟表时间是否说尽真实的变化？", "柏格森区分测量时使用的均匀刻度与经验中相互渗透的绵延。测量仍有用途，却不穷尽记忆和成长。他以创造进化强调新异性；这种哲学解释不直接替代生物学证据和具体机制。", "在时间中形成的行动者，也处在自然原因与环境中。", `duration-as-qualitative-interpenetration clock-time-lived-time-observation is-measured-time-the-whole-of-time measured-time-useful-abstraction-not-lived-whole how-past-survives-without-static-storage memory-selects-past-for-present-action does-creative-evolution-replace-biology creative-evolution-marks-novelty-not-scientific-replacement is-intuition-irrational-guessing intuition-enters-process-analysis-still-needed is-freedom-an-uncaused-instant-choice free-act-expresses-whole-developing-self`),
      ]),
      g("nature-10-agency-environment", "斯宾诺莎、休谟、康德与杜威", "承认自然原因，怎样继续理解人的行动？", "斯宾诺莎强调理解原因带来的能力，休谟区分按意愿行动与免除一切原因，康德区分自然解释和实践立场。杜威则考察人在环境中如何探究、改变处境。这里是几种可比较的方案。", "行动能力也依赖共同生活提供的条件。", [
        a("nature-20-causality-freedom", "斯宾诺莎、休谟与康德", "行动有原因，就不能自由或负责吗？", "斯宾诺莎把自由与充分理解和行动能力相连；休谟认为可按自己的意愿行动与行为有因果规律相容。康德从实践立场讨论自由，不把它作为可观察的自然对象。三个方案的共同问题不等于它们共享答案。", "这个节点同时属于自我：可继续核对意愿、责任与自律。", `what-can-freedom-mean-in-necessary-nature conatus-and-adequate-understanding-increase-agency are-liberty-and-causal-necessity-compatible liberty-as-action-according-to-will can-caused-actions-ground-responsibility stable-character-links-action-and-attribution how-can-freedom-coexist-with-natural-causality two-standpoints-natural-causality-practical-freedom can-practical-reason-know-transcendent-freedom freedom-practical-postulate-not-theoretical-object`),
        a("nature-20-transaction", "杜威", "经验是心里的一幅画，还是人与环境的活动？", "杜威把经验放在有机体与环境的交互中。困难的处境引发探究，提出的判断要经过操作、后果和公共检验。因此，自然、行动与共同学习可以相接，但自然事实并不会自动给出应当采用的社会制度。", "转入社会，检验哪些教育和公共制度能支持共同纠错。", `is-experience-private-inner-content experience-as-organism-environment-transaction problematic-situation-observation inquiry-transforms-problematic-situation must-knowledge-begin-with-certainty warranted-assertibility-through-disciplined-inquiry`),
      ]),
    ], "生命与时间要求辨清解释的范围；行动与环境把自然接到自我和社会。", [{ label: "SEP · 杜威", url: "https://plato.stanford.edu/entries/dewey/" }]),
];
