import type { PhilosopherProfile, PhilosopherSource } from "./philosopher-data";

const russellSource = (chapter: string): PhilosopherSource => ({
  label: `罗素《西方哲学史》${chapter}`,
  kind: "原书",
  url: "https://www.russell-j.com/cool/HWP_1945.pdf",
});

const sepSource = (label: string, slug: string): PhilosopherSource => ({
  label: `Stanford Encyclopedia · ${label}`,
  kind: "补充",
  url: `https://plato.stanford.edu/entries/${slug}/`,
});

export const modernProfiles: PhilosopherProfile[] = [
  {
    id: "machiavelli", order: 54, nameZh: "马基雅维利", nameEn: "Niccolò Machiavelli", greekName: "Niccolò di Bernardo dei Machiavelli", dates: "1469—1527", active: "1498—1527", places: ["佛罗伦萨", "罗马", "意大利城邦"], school: "文艺复兴政治现实主义", figureId: "machiavelli", chapterIds: ["b3-02", "b3-03"],
    thesis: "政治行动必须按权力关系、时机和实际后果来判断；统治者若只遵守私人德性的单一尺度，反而可能毁掉共同体。",
    evidenceCaution: "书信、公职档案和著作使生平较清楚，但《君主论》并非全部政治思想；把“目的证明手段正当”当作他的原句，会遮蔽《论李维》的共和主义维度。",
    lifeSummary: "马基雅维利在佛罗伦萨共和国担任秘书和外交官，亲历法国、西班牙、教皇与意大利城邦的战争。美第奇复辟后他被免职、监禁并退居乡间，转而用历史和外交经验写作。其问题不是教人单纯残酷，而是当旧有统一秩序崩解时，政治如何拥有自己的判断尺度。",
    timeline: [
      { date: "1498—1512", place: "佛罗伦萨", title: "任共和国秘书与外交官", detail: "参与军事、外交和行政工作，多次观察法王、教皇与切萨雷·博吉亚的行动。", certainty: "较可靠" },
      { date: "1512—1513", place: "佛罗伦萨", title: "共和国失败后被捕", detail: "美第奇家族复辟，他因涉嫌阴谋被监禁和刑讯，获释后退出公职。", certainty: "较可靠" },
      { date: "1513 以后", place: "圣卡夏诺", title: "写作《君主论》与《论李维》", detail: "两部作品分别聚焦新君主的生存难题与共和制度的自由和冲突。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "德能", en: "virtù", definition: "掌握局势、组织力量并塑造时机的行动能力，不等于通常意义的道德美德。" },
      { zh: "命运", en: "fortuna", definition: "行动者无法控制的偶然条件；政治能力可以限制其破坏，却不能彻底消除它。" },
      { zh: "国家理由", en: "reason of state", definition: "为保存政治共同体而形成的特殊判断领域；该术语后来才定型，不能直接当作马基雅维利原话。" },
    ],
    lineage: { inherited: "承接古罗马史学、共和政治经验和意大利人文主义的古典文本训练。", school: "文艺复兴政治思想中现实主义与共和主义交叉的关键人物。", influenced: "影响霍布斯以后关于国家、权力与政治自主性的讨论，也成为现代现实主义反复重构的起点。", parallel: "与莫尔同样批判现实制度；马基雅维利从冲突中的行动能力出发，莫尔则用虚构制度形成规范性镜像。" },
    comparisons: [
      { target: "莫尔", relation: "同题比较", shared: "都在文艺复兴政治危机中追问良好秩序。", difference: "马基雅维利研究现实力量和制度冲突；莫尔借乌托邦反讽财产与惩罚制度。" },
      { target: "霍布斯", relation: "影响后继", shared: "政治秩序不能只依赖传统德性，必须分析恐惧、力量与稳定。", difference: "马基雅维利依历史案例讨论多种政体；霍布斯从自然状态演绎统一主权。" },
      { target: "卢梭", relation: "后世重构", shared: "共和国需要不依赖私人利益的公共能力。", difference: "卢梭把他重读为向人民揭露君主技术的共和作者，并以公意重建合法性。" },
    ],
    stars: 5, culturalNotes: [{ kind: "生活印象", title: "白天与农人相处，夜里同古人交谈", text: "流亡乡间时，他在书信中写自己换上体面衣服进入书房，阅读古代作者，仿佛同他们交谈。这一场景把政治失败转化为思想工作的起点。" }],
    russellView: "罗素把马基雅维利视为近代政治哲学真正的开端：他不再从神学或理想德性推导政治，而从权力效果和可观察经验出发。罗素反对其某些残酷结论，却赞赏其诚实与不伪善。",
    modernCorrection: "“马基雅维利主义”等于不择手段过于简单。他同时重视共和国、法治、民众自由和制度化冲突；《君主论》的危机语境也不能代表全部著作。",
    sources: [russellSource("第三卷第二至三章"), sepSource("Niccolò Machiavelli", "machiavelli")],
  },
  {
    id: "erasmus", order: 55, nameZh: "伊拉斯谟", nameEn: "Desiderius Erasmus", greekName: "Desiderius Erasmus Roterodamus", dates: "约 1466—1536", active: "1490 年代—1536", places: ["鹿特丹", "巴黎", "巴塞尔", "英格兰"], school: "北方文艺复兴人文主义", figureId: "erasmus", chapterIds: ["b3-04", "b3-05"],
    thesis: "宗教更新首先需要回到原文、改进教育并校正风俗；温和批评和自由讨论比强制性的教义阵营更接近基督教精神。",
    evidenceCaution: "著作与书信极丰富，生平可靠；但他在宗教改革中的中间位置常被双方漫画化，既不能写成路德的隐蔽盟友，也不能写成只求安稳的旁观者。",
    lifeSummary: "伊拉斯谟借印刷网络成为第一个真正全欧洲性的学者名人。他校勘希腊文《新约》、编订教父、写教育与讽刺作品，力图以语文学和道德改革更新教会。路德争论爆发后，他拒绝把改革交给不可调和的教义阵营，并围绕自由意志公开与路德交锋。",
    timeline: [
      { date: "1490 年代", place: "巴黎／低地国家", title: "进入欧洲人文主义网络", detail: "离开修院束缚，以教学、赞助与出版维持独立学者生活。", certainty: "较可靠" },
      { date: "1511", place: "巴黎", title: "出版《愚人颂》", detail: "以讽刺揭露教士、学者和统治者的自满，也把批评指向人文主义者自身。", certainty: "较可靠" },
      { date: "1516", place: "巴塞尔", title: "出版希腊文《新约》", detail: "提供希腊文本、拉丁新译和注释，推动欧洲经文校勘。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "回到源头", en: "ad fontes", definition: "回到希腊、拉丁及早期基督教文本，用原文比较校正后世累积。" },
      { zh: "基督教哲学", en: "philosophia Christi", definition: "以基督的生活与伦理为中心的实践智慧，反对把信仰缩成繁琐争论。" },
      { zh: "自由选择", en: "free choice", definition: "人在恩典帮助下仍具有可回应的选择能力，是他与路德争论的核心。" },
    ],
    lineage: { inherited: "承接意大利人文主义语文学、教父传统和共同生活弟兄会的教育理想。", school: "北方基督教人文主义的中心人物。", influenced: "影响圣经语文学、欧洲教育和宽容思想，也为宗教改革各方提供文本工具。", parallel: "与莫尔共享古典教育、讽刺和改革友谊；与路德同批教会弊端，却在自由意志、权威和论战方式上分裂。" },
    comparisons: [
      { target: "莫尔", relation: "影响后继", shared: "古典教育、基督教改革和以讽刺批评现实。", difference: "伊拉斯谟以跨国学术网络和文本校勘为主；莫尔更深入法律、国家与乌托邦制度。" },
      { target: "路德", relation: "批评关系", shared: "都要求纠正教会腐败并回到经文。", difference: "伊拉斯谟维护有限自由选择和温和改革；路德强调意志受罪束缚及信仰的断裂性。" },
      { target: "洛克", relation: "影响后继", shared: "反对无益教条争执并为宗教宽容留下空间。", difference: "洛克以权利和政府权限论证宽容，伊拉斯谟主要诉诸教育、和平与基督徒德性。" },
    ],
    stars: 4, culturalNotes: [{ kind: "名言", title: "“和平即使不公，也胜过最公正的战争”", text: "这句常用来概括伊拉斯谟对战争、民族荣耀和教义动员的持续怀疑；其和平主义来自对现实苦难的优先关注。" }],
    russellView: "罗素把伊拉斯谟写成学识广博、温和、机智却缺少殉道式勇气的人文主义者，赞赏其《愚人颂》和反战态度，同时把他与路德的猛烈确定性对照。",
    modernCorrection: "把温和等同怯懦会低估他的独立立场。他在教派化压力下坚持文本批判、教育改革和不确定性伦理，这本身是一种有代价的政治选择。",
    sources: [russellSource("第三卷第四至五章"), sepSource("Desiderius Erasmus", "erasmus")],
  },
  {
    id: "thomas-more", order: 56, nameZh: "莫尔", nameEn: "Thomas More", greekName: "Thomas Morus", dates: "1478—1535", active: "1504—1535", places: ["伦敦", "安特卫普", "英格兰"], school: "基督教人文主义／乌托邦思想", figureId: "thomas-more", chapterIds: ["b3-04", "b3-05"],
    thesis: "虚构一个制度完全不同的社会，可以让财产、惩罚、战争与宗教宽容这些习以为常的安排重新变成可争论的问题。",
    evidenceCaution: "公职和审判材料较清楚，但《乌托邦》的讽刺、对话和拉丁语双关使作者立场不能逐句直取；莫尔本人迫害异端的行为也必须与书中宽容设计并置。",
    lifeSummary: "莫尔是律师、人文主义者、议员和亨利八世的大法官，也是伊拉斯谟的密友。《乌托邦》以旅行叙事比较欧洲制度与虚构岛屿，既提出共同财产、教育和宗教宽容，也故意保留矛盾。拒绝承认国王为英格兰教会最高首领后，他被处决。",
    timeline: [
      { date: "1516", place: "鲁汶", title: "出版《乌托邦》", detail: "借虚构旅行者之口讨论圈地、死刑、财产、劳动和宗教制度。", certainty: "较可靠" },
      { date: "1529—1532", place: "伦敦", title: "任大法官后辞职", detail: "在王权与罗马教廷冲突中逐渐退场，同时参与压制异端。", certainty: "较可靠" },
      { date: "1535", place: "伦敦塔", title: "因拒绝宣誓被处决", detail: "拒绝明确承认王权的宗教最高地位，最终以叛国罪定罪。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "乌托邦", en: "Utopia / no-place", definition: "既是‘无处’又暗示‘好地方’的虚构社会，用制度差异反照现实。" },
      { zh: "共同财产", en: "common property", definition: "取消私人积累以减轻贫困和支配的制度实验，文本同时保留反对意见。" },
      { zh: "制度性贫困", en: "institutional poverty", definition: "贫困不是单纯个人懒惰，而与圈地、失业、刑罚和财产结构共同生成。" },
    ],
    lineage: { inherited: "承接柏拉图政治想象、修道共同生活和文艺复兴对话体。", school: "基督教人文主义中的乌托邦与法律思想。", influenced: "开创近代乌托邦文学和制度批判传统，后世社会主义、共和主义和文学实验都反复重读。", parallel: "与马基雅维利同处国家重组期，却分别从虚构规范与现实力量两端测试政治。" },
    comparisons: [
      { target: "柏拉图", relation: "后世重构", shared: "用整体制度安排追问正义、教育和财产。", difference: "莫尔以人文主义对话和讽刺保留距离，没有直接复制哲学王与固定等级。" },
      { target: "马基雅维利", relation: "同题比较", shared: "都让政治制度脱离经院抽象而面对现实危机。", difference: "莫尔以理想化比较审判现实；马基雅维利从现实行动与冲突检验制度。" },
      { target: "马克思", relation: "后世重构", shared: "私人财产、劳动组织和贫困结构可以被根本改变。", difference: "马克思拒绝仅靠想象方案，以生产关系和阶级斗争解释变革。" },
    ],
    stars: 4, culturalNotes: [{ kind: "生活印象", title: "书中的宽容与任内的迫害", text: "莫尔让乌托邦居民容许多种宗教，却在公职中参与压制新教徒。这个强烈反差提醒我们，思想文本不能替现实责任作无罪证明。" }],
    russellView: "罗素赞赏《乌托邦》对圈地、贫困和财产制度的批判，也注意到其中共同财产、宽容与战争观的现代性；同时强调莫尔现实政治中的不宽容。",
    modernCorrection: "《乌托邦》不是可直接实施的社会主义蓝图，书名、叙事者和结尾都制造解释不确定性。现代研究更重视其修辞游戏、法律经验与殖民想象。",
    sources: [russellSource("第三卷第四章〈伊拉斯谟与莫尔〉"), sepSource("Thomas More", "thomas-more")],
  },
  {
    id: "luther", order: 57, nameZh: "路德", aliases: ["马丁·路德"], nameEn: "Martin Luther", greekName: "Martin Luther", dates: "1483—1546", active: "1517—1546", places: ["维滕贝格", "沃尔姆斯", "德意志诸邦"], school: "宗教改革神学", figureId: "luther", chapterIds: ["b3-05"],
    thesis: "人的得救不由功德、教会交易或自主意志控制，而取决于上帝恩典中被信心接受的应许；经文因此必须高于腐败的制度权威。",
    evidenceCaution: "著作和政治事件材料丰富，但著名言辞常经后世润色；他的良心抗争、反犹言论、农民战争立场和依赖诸侯保护必须同时呈现。",
    lifeSummary: "路德从奥古斯丁会修士和神学教授成为宗教改革中心人物。他反对赎罪券，逐步挑战教皇权威、功德体系和圣礼结构，并在翻译、讲道与印刷中建立新的公共宗教语言。改革释放解释权，也依赖领邦权力并制造新的教派强制。",
    timeline: [
      { date: "1517", place: "维滕贝格", title: "发表反赎罪券论题", detail: "九十五条论题迅速进入印刷传播，争论由牧灵问题升级为权威冲突。", certainty: "较可靠" },
      { date: "1521", place: "沃尔姆斯", title: "帝国会议拒绝撤回", detail: "其立场和审讯可靠，流行的完整宣言措辞则未必逐字可信。", certainty: "较可靠" },
      { date: "1522—1534", place: "维滕贝格", title: "翻译德文《圣经》", detail: "以原文和通俗德语推动识字、礼拜与宗派文化形成。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "因信称义", en: "justification by faith", definition: "人因信接受基督的应许而被称义，不以功德交换恩典。" },
      { zh: "唯独圣经", en: "sola scriptura", definition: "“唯独圣经”是后世概括宗教改革立场的公式：圣经是教义的最高规范，而非声称解释可以脱离语言、讲道、信条和共同体。不能把这句拉丁口号当作路德在所有时期使用的固定术语。" },
      { zh: "意志受缚", en: "bondage of the will", definition: "人在得救问题上不能靠自主选择先行转向上帝，是他反驳伊拉斯谟的核心。" },
    ],
    lineage: { inherited: "承接奥古斯丁恩典论、晚期中世纪经文研究与个人牧灵危机。", school: "新教宗教改革和路德宗神学的奠基人物。", influenced: "改变欧洲教会、教育、政治和语言，也推动良心、权威和个人判断成为近代问题。", parallel: "与伊拉斯谟都反对教会弊端；路德追求救赎确定性，伊拉斯谟则维护解释谨慎和有限自由。" },
    comparisons: [
      { target: "奥古斯丁", relation: "后世重构", shared: "罪、恩典和意志不能由人的功德体系解决。", difference: "路德在印刷、大学和教派国家环境中将恩典论转成对教皇与圣礼制度的断裂。" },
      { target: "伊拉斯谟", relation: "批评关系", shared: "教会需要经文与教育改革。", difference: "路德主张意志受缚并接受尖锐断裂；伊拉斯谟保留自由选择与制度内温和改革。" },
      { target: "洛克", relation: "影响后继", shared: "宗教强制与个人良心之间存在不可消除的边界。", difference: "洛克将问题改写为公民权利与政府权限，而路德本人并未建立普遍宗教宽容。" },
    ],
    stars: 5, culturalNotes: [{ kind: "名言", title: "“我站在这里”", text: "这句话浓缩了个人良心面对帝国与教会权威的形象，因此成为宗教改革最有辨识度的场景。", caveat: "沃尔姆斯会议上拒绝撤回可靠，但这句完整名言未见最早记录。" }],
    russellView: "罗素把宗教改革解释为北方个人主义、民族国家和反罗马情绪的结合，认为路德以信仰与经文摧毁教会统一，却在政治上支持诸侯并反对农民。",
    modernCorrection: "不能把宗教改革只写成现代自由的诞生。它既扩展识字与判断，也形成宗派纪律、国家教会和暴力；路德神学首先是一套救赎论，而非自由主义宣言。",
    sources: [russellSource("第三卷第五章〈宗教改革与反宗教改革〉"), sepSource("Martin Luther", "luther")],
  },
  {
    id: "copernicus", order: 58, nameZh: "哥白尼", nameEn: "Nicolaus Copernicus", greekName: "Mikołaj Kopernik / Nicolaus Copernicus", dates: "1473—1543", active: "1510 年代—1543", places: ["托伦", "弗龙堡", "克拉科夫", "意大利"], school: "科学革命／日心天文学", figureId: "copernicus", chapterIds: ["b3-06"],
    thesis: "把地球设为运动的行星、太阳置于行星次序中心，可以用更统一的几何结构解释逆行与行星排列。",
    evidenceCaution: "著作和行政记录较清楚；“因害怕教会而临终出版”过于单线。其体系仍使用圆周与本轮，也保留古代宇宙论价值，不等于现代物理学突然完成。",
    lifeSummary: "哥白尼受教会俸禄支持，兼任教士、行政者和天文学研究者。他长期修改《天球运行论》，以地球自转和绕日运动重排行星系统。模型最初主要是数学天文学的重构，真正改变的是地球不再拥有静止中心特权。",
    timeline: [
      { date: "1491—1503", place: "克拉科夫／意大利", title: "学习天文、法律与医学", detail: "接触古典天文学与人文主义文本，同时取得教会法训练。", certainty: "较可靠" },
      { date: "约 1514", place: "弗龙堡", title: "传播《短论》", detail: "向少数同行概述地动和日心排列的基本假设。", certainty: "较可靠" },
      { date: "1543", place: "纽伦堡／弗龙堡", title: "出版《天球运行论》", detail: "作品在其去世之年出版，匿名序言把体系描述为计算假设。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "日心体系", en: "heliocentric system", definition: "以太阳附近为行星运动中心、地球作为行星的天文排列。" },
      { zh: "地球运动", en: "motion of the Earth", definition: "地球自转并绕日公转，使天空周日运动和部分行星现象成为视运动。" },
      { zh: "相对运动解释", en: "relative-motion explanation", definition: "观察者自身运动能够制造天体后退等表象，是模型解释力的关键。" },
    ],
    lineage: { inherited: "承接托勒密数学天文学、古代地动假说和文艺复兴语文学。", school: "科学革命早期的数学天文学。", influenced: "直接设置开普勒、伽利略和牛顿必须解决的新问题，并长期改变人类在宇宙中的位置。", parallel: "与弗朗西斯·培根都反对无效权威，却分别走数学模型和经验归纳两条方法路线。" },
    comparisons: [
      { target: "开普勒", relation: "影响后继", shared: "地球是行星，日心次序提供统一天文学。", difference: "开普勒放弃匀速圆周，以椭圆和面积定律提高物理与预测精度。" },
      { target: "伽利略", relation: "影响后继", shared: "地球运动和太阳系新结构。", difference: "伽利略加入望远镜证据、运动学和公开论战，却未采用开普勒椭圆。" },
      { target: "亚里士多德", relation: "批评关系", shared: "都要给出宇宙中地球与天体的整体位置。", difference: "日心模型取消地球的静止中心地位，也削弱天地两套物理的结构。" },
    ],
    stars: 5, culturalNotes: [{ kind: "生活印象", title: "一场“哥白尼式革命”", text: "后来人把任何彻底改变观察中心的理论称为“哥白尼式革命”。这个比喻说明他的影响超出天文学，也提醒我们革命在出版后经过几代人才完成。" }],
    russellView: "罗素把哥白尼置于科学兴起的决定性起点：理论不一定比托勒密立刻更简洁，却通过取消地球中心地位改变了人的宇宙自尊。",
    modernCorrection: "不能用一场理性对宗教的单次胜利概括。哥白尼在教会制度内工作，模型也深受古代圆周理想支配；科学革命是数学、观测、仪器和制度逐步重组。",
    sources: [russellSource("第三卷第六章〈科学的兴起〉"), sepSource("Nicolaus Copernicus", "copernicus")],
  },
  {
    id: "kepler", order: 59, nameZh: "开普勒", nameEn: "Johannes Kepler", greekName: "Johannes Kepler", dates: "1571—1630", active: "1596—1630", places: ["维尔斯塔特", "布拉格", "格拉茨", "林茨"], school: "科学革命／数学天文学", figureId: "kepler", chapterIds: ["b3-06"],
    thesis: "行星轨道不是匀速圆周，而是以太阳为焦点的椭圆；数学和精密观测必须共同约束宇宙结构。",
    evidenceCaution: "著作和第谷观测资料可靠；把他写成摆脱神秘主义的纯现代科学家会失真。几何和谐、神学宇宙观与技术计算在其工作中相互支撑。",
    lifeSummary: "开普勒最初试图用正多面体解释行星间距，后在布拉格使用第谷·布拉赫的高精度火星数据。持续误差迫使他放弃圆周和匀速的古老理想，形成椭圆轨道、面积定律与周期定律。他代表一种重要科学德性：宁可修改美丽模型，也不忽略顽固数据。",
    timeline: [
      { date: "1600—1601", place: "布拉格", title: "与第谷·布拉赫合作", detail: "获得长期精密观测，并在第谷去世后成为帝国数学家。", certainty: "较可靠" },
      { date: "1609", place: "布拉格", title: "发表前两条行星定律", detail: "在《新天文学》中以椭圆与面积定律解释火星运动。", certainty: "较可靠" },
      { date: "1619", place: "林茨", title: "提出周期定律", detail: "把行星周期平方与轨道尺度立方联系起来。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "椭圆轨道", en: "elliptical orbit", definition: "行星沿以太阳为一焦点的椭圆运动，取消完美圆周的传统特权。" },
      { zh: "面积定律", en: "law of areas", definition: "行星与太阳连线在相等时间扫过相等面积，表示速度随距离改变。" },
      { zh: "调和定律", en: "harmonic law", definition: "公转周期平方与轨道半长轴立方成比例，把各行星纳入单一数量关系。" },
    ],
    lineage: { inherited: "承接哥白尼日心体系、第谷精密观测与毕达哥拉斯式数学和谐理想。", school: "科学革命中的数学—物理天文学。", influenced: "为牛顿万有引力提供必须解释的经验定律，也示范模型接受精密数据检验。", parallel: "与伽利略都数学化自然；开普勒更依赖长期天文数据，伽利略更突出实验、运动与仪器观察。" },
    comparisons: [
      { target: "哥白尼", relation: "承接前人", shared: "以日心次序统一行星系统。", difference: "开普勒放弃匀速圆周，并赋予太阳更强物理作用。" },
      { target: "伽利略", relation: "同题比较", shared: "数学结构与观测共同推翻传统宇宙论。", difference: "伽利略没有采纳椭圆，开普勒则缺少同等影响力的地面运动实验纲领。" },
      { target: "莱布尼茨", relation: "影响后继", shared: "世界秩序可由普遍数量规律表达。", difference: "莱布尼茨把这种可理解性扩展为充足理由和形而上学体系。" },
    ],
    stars: 4, culturalNotes: [{ kind: "例子", title: "不能被抹掉的八分角", text: "火星位置只有八分角的偏差，却足以让开普勒放弃延续千年的圆周理想。它成为数据怎样迫使理论更新的经典例子。" }],
    russellView: "罗素高度评价开普勒三定律，尤其强调他虽带有神秘和谐信念，却能在观测压力下放弃圆周偏见，使真正的科学方法胜过先入美学。",
    modernCorrection: "神秘主义与科学在他身上不是可以简单切开的早期缺陷和现代成就。几何、神学和物理原因共同引导问题选择，关键在于最终让计算与数据约束模型。",
    sources: [russellSource("第三卷第六章〈科学的兴起〉"), sepSource("Johannes Kepler", "kepler")],
  },
  {
    id: "galileo", order: 60, nameZh: "伽利略", nameEn: "Galileo Galilei", greekName: "Galileo di Vincenzo Bonaiuti de' Galilei", dates: "1564—1642", active: "1589—1642", places: ["比萨", "帕多瓦", "佛罗伦萨", "罗马"], school: "科学革命／数学实验传统", figureId: "galileo", chapterIds: ["b3-06"],
    thesis: "自然运动应由可测数量、理想化模型和实验论证表达；仪器观察能够产生传统肉眼和权威文本没有的新证据。",
    evidenceCaution: "著作、审判和观测记录丰富；比萨斜塔实验及“地球仍在转”多属后世故事。教会冲突涉及经文解释、赞助政治和证据强度，不宜压成科学与宗教永恒对决。",
    lifeSummary: "伽利略在帕多瓦研究运动和机械，望远镜使他看到月面、木星卫星、金星相位和太阳黑子。他用对话、实验与数学挑战亚里士多德物理，并公开支持地动说。1633 年受审后软禁，但仍完成关于落体和抛射运动的重要著作。",
    timeline: [
      { date: "1609—1610", place: "帕多瓦／威尼斯", title: "改进望远镜并发表天文发现", detail: "木星卫星和月面不平支持天界并非围绕地球的完美领域。", certainty: "较可靠" },
      { date: "1632—1633", place: "佛罗伦萨／罗马", title: "《关于两大世界体系的对话》与审判", detail: "作品被判违反禁令，他撤回立场并被终身软禁。", certainty: "较可靠" },
      { date: "1638", place: "阿尔切特里／莱顿", title: "出版《两门新科学》", detail: "系统处理材料强度、落体、惯性倾向与抛射运动。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "数学化自然", en: "mathematization of nature", definition: "用形状、数量、速度和比例表达可检验的自然规律。" },
      { zh: "理想化", en: "idealization", definition: "有意识忽略摩擦等因素，以揭示在现实中被干扰的结构关系。" },
      { zh: "惯性倾向", en: "inertial tendency", definition: "伽利略以运动的相对性、斜面和理想化思想实验说明：共同运动可以保存，物体不因缺少持续推动便立即静止。这为后来直线惯性定律铺路，但不能直接等同牛顿式完整表述。" },
      { zh: "伽利略相对性", en: "Galilean relativity", definition: "在匀速运动的封闭系统内，局部机械现象不能单凭自身判断系统是否整体运动。" },
    ],
    lineage: { inherited: "承接阿基米德数学物理、哥白尼地动体系和文艺复兴工程实践。", school: "科学革命中的数学实验与仪器观察传统。", influenced: "运动研究进入笛卡尔和牛顿物理；审判也成为知识权威边界的长期象征。", parallel: "与弗朗西斯·培根都反对空洞权威；伽利略通过理想化与数学实验，培根提出系统归纳和协作研究纲领。" },
    comparisons: [
      { target: "哥白尼", relation: "承接前人", shared: "地球运动和日心系统。", difference: "伽利略提供新仪器证据与运动学辩护，但潮汐证明并不成功。" },
      { target: "开普勒", relation: "同题比较", shared: "新天文学必须由数学和观测重建。", difference: "开普勒接受椭圆并研究行星定律；伽利略坚持圆周并集中地面运动与望远镜证据。" },
      { target: "笛卡尔", relation: "影响后继", shared: "自然应由几何、运动和机械过程解释。", difference: "笛卡尔追求从第一原则演绎整体物理，伽利略更聚焦可测局部问题。" },
    ],
    stars: 5, culturalNotes: [{ kind: "名言", title: "“然而它仍在转动”", text: "传说伽利略在撤回地动说后低声坚持地球仍在运动，成为证据不因权威命令而改变的象征。", caveat: "这句名言缺少同期证据，应作为后世文化记忆而非审判实录。" }],
    russellView: "罗素把伽利略写成实验科学与自由探究的英雄，强调落体研究、相对运动和教会审判，并用这场冲突说明新知识不能再服从传统权威。",
    modernCorrection: "英雄叙事不能遮蔽其修辞策略、赞助网络和若干错误论证，也不能把所有神学家视为反科学。审判确属权力压制，但争议的制度和证据语境更复杂；他的实验也常由思想实验、装置测量与数学推导共同组成，并非只靠肉眼观察。",
    sources: [russellSource("第三卷第六章〈科学的兴起〉"), sepSource("Galileo Galilei", "galileo")],
  },
  {
    id: "francis-bacon", order: 61, nameZh: "弗朗西斯·培根", nameEn: "Francis Bacon", greekName: "Francis Bacon, Viscount St Alban", dates: "1561—1626", active: "1584—1626", places: ["伦敦", "剑桥", "英格兰"], school: "经验方法与知识改革", figureId: "francis-bacon", chapterIds: ["b3-06", "b3-07"],
    thesis: "知识必须通过有组织的观察、排除和协作逐步建立；方法的目标不是赢得争论，而是发现能改变生活的因果与操作。",
    evidenceCaution: "政治生涯与著作资料充分；流行“培根发明现代科学方法”夸大其直接作用。他少用数学，也没有给出今天的单一归纳算法。",
    lifeSummary: "培根既是律师、议员和大法官，也是宏大知识改革的设计者。因受贿案失势后，他更集中写作《新工具》和《新大西岛》。他批判经院争论与仓促概括，设想由协作机构积累实验、技术和自然史，使知识成为公共事业。",
    timeline: [
      { date: "1605", place: "伦敦", title: "出版《学术的进展》", detail: "系统评估知识缺口，并把研究与国家、教育和公共用途连接。", certainty: "较可靠" },
      { date: "1620", place: "伦敦", title: "出版《新工具》", detail: "以偶像论、自然史和排除表提出知识改革纲领。", certainty: "较可靠" },
      { date: "1621", place: "伦敦", title: "因受贿案失去公职", detail: "承认收受礼物但否认裁判受影响，政治责任不能由哲学成就抵消。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "四类偶像", en: "four idols", definition: "种族、洞穴、市场和剧场四类认知偏差，分别来自人性、个人习惯、语言与体系权威。" },
      { zh: "排除归纳", en: "eliminative induction", definition: "通过比较正反实例排除不相关性质，逐步缩小因果解释。" },
      { zh: "知识就是力量", en: "knowledge and power", definition: "真正知道因果意味着能够产生效果；知识价值与公共操作能力相连。" },
    ],
    lineage: { inherited: "承接文艺复兴自然史、工艺知识和对经院权威的批评。", school: "近代经验方法与科研制度的纲领性思想家。", influenced: "影响皇家学会式协作理想、经验主义自我理解和科学服务公共改善的观念。", parallel: "与笛卡尔都寻找新方法；培根从集体经验和排除出发，笛卡尔从个体理性的清楚原则演绎。" },
    comparisons: [
      { target: "罗杰·培根", relation: "后世重构", shared: "都强调观察、实验和知识的实际作用。", difference: "两人相隔数百年，所处制度也不同；弗朗西斯·培根并未从罗杰·培根那里直接继承一套成熟的实验方法。" },
      { target: "笛卡尔", relation: "同题比较", shared: "传统学问需要由明确方法重建。", difference: "培根强调自然史、协作与排除归纳；笛卡尔强调直观起点和演绎次序。" },
      { target: "洛克", relation: "影响后继", shared: "限制先入体系，让知识对经验来源负责。", difference: "洛克转向观念如何产生和知识边界，培根主要设计发现自然因果的研究程序。" },
    ],
    stars: 5, culturalNotes: [{ kind: "例子", title: "所罗门宫：想象中的研究院", text: "《新大西岛》用所罗门宫想象分工协作、采集资料和服务公共生活的研究机构，后来常被视为科学院的文学预演。" }],
    russellView: "罗素认为培根在哲学上不如伽利略重要，归纳理论也有缺陷，却高度评价其作为科学组织者和新精神宣传者的历史作用。",
    modernCorrection: "科学并非只靠无偏见事实积累，假说、数学、仪器和理论传统同样构成观察。培根的价值更多在研究制度、偏差诊断和排除思路，而非一套万能方法。",
    sources: [russellSource("第三卷第七章〈弗朗西斯·培根〉"), sepSource("Francis Bacon", "francis-bacon")],
  },
  {
    id: "hobbes", order: 62, nameZh: "霍布斯", nameEn: "Thomas Hobbes", greekName: "Thomas Hobbes of Malmesbury", dates: "1588—1679", active: "1620 年代—1679", places: ["英格兰", "巴黎", "伦敦"], school: "机械论政治哲学", figureId: "hobbes", chapterIds: ["b3-08", "b3-12"],
    thesis: "在没有共同裁判者的条件下，平等而相互不信任的个人会陷入战争风险；理性因此要求共同授权一个足以维持和平的主权。",
    evidenceCaution: "文本与生平充分；“自然状态”是分析模型，不是断言所有人类曾实际独居混战。把霍布斯简单称为极权主义者也会遗漏授权、保护义务和臣民自由。",
    lifeSummary: "霍布斯经历英国内战并长期往返英法，受几何学和机械论自然哲学影响。《利维坦》从身体、语言和欲望开始，逐步推导契约、人格代表和国家。其体系以个人为起点却通向强主权，成为近代政治哲学最有张力的结构之一。",
    timeline: [
      { date: "1640—1651", place: "巴黎", title: "流亡并完成主要政治体系", detail: "内战风险促使他依次发表《论公民》和《利维坦》。", certainty: "较可靠" },
      { date: "1651", place: "伦敦", title: "出版《利维坦》", detail: "以契约、代表与主权重新解释政治共同体。", certainty: "较可靠" },
      { date: "1666", place: "伦敦", title: "面临无神论调查压力", detail: "议会审查导致他不再公开出版争议性宗教与政治论述。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "自然状态", en: "state of nature", definition: "没有共同强制权时人与人关系的分析条件，其核心是结构性不安全。" },
      { zh: "自然律", en: "laws of nature", definition: "理性发现的和平规则，如寻求和平、履行契约；没有执行权时不足以稳定行为。此译名也便于同阿奎那的自然法传统保持区分。" },
      { zh: "授权与代表", en: "authorization and representation", definition: "多数人把统一行动资格归给主权者，使国家成为他们共同承认的人工人格。" },
    ],
    lineage: { inherited: "承接马基雅维利的政治自主性、古代唯物论和伽利略式机械运动理想。", school: "近代社会契约论与机械论政治哲学。", influenced: "迫使洛克、卢梭及后来的自由主义说明为何主权必须受限，也奠定现代代表与国家分析的语言。", parallel: "与斯宾诺莎都从欲望和自保自然化政治；霍布斯更集中统一主权，斯宾诺莎更重思想自由和民主稳定。" },
    comparisons: [
      { target: "马基雅维利", relation: "承接前人", shared: "政治必须面对力量、冲突和国家生存。", difference: "霍布斯用自然状态与契约演绎合法秩序，马基雅维利依历史案例研究行动能力。" },
      { target: "洛克", relation: "影响后继", shared: "从自由平等个人和契约解释政治权力。", difference: "洛克保留自然法执行、财产权与反抗权，拒绝不可分割绝对主权。" },
      { target: "卢梭", relation: "影响后继", shared: "政治共同体须由个人共同授权，而非自然等级。", difference: "卢梭要求公意使人仍服从自己制定的法律，不接受代表者永久吸收主权。" },
    ],
    stars: 5, culturalNotes: [{ kind: "生活印象", title: "“恐惧与我一同出生”", text: "霍布斯把自己早产同西班牙无敌舰队威胁联系起来。无论是否精确，它都成为理解其政治哲学为何从恐惧与安全出发的记忆入口。" }],
    russellView: "罗素赞赏霍布斯清楚、世俗和不诉诸自然权利的政治推理，也认同安全的重要性；但他批评主权几乎不受限制，并认为个人自保仍能支持更多反抗空间。",
    modernCorrection: "霍布斯不是单纯为专制辩护：主权来自被授权的和平功能，臣民在国家不能保护生命时保留自保自由。其宗教批评和人格代表理论也不应被《自然状态》独占。",
    sources: [russellSource("第三卷第八章〈霍布斯的《利维坦》〉"), sepSource("Hobbes's Moral and Political Philosophy", "hobbes-moral")],
  },
  {
    id: "descartes", order: 63, nameZh: "笛卡尔", nameEn: "René Descartes", greekName: "Renatus Cartesius", dates: "1596—1650", active: "1619—1650", places: ["法国", "荷兰共和国", "斯德哥尔摩"], school: "大陆理性主义", figureId: "descartes", chapterIds: ["b3-09"],
    thesis: "把一切可怀疑之物暂时撤去后，正在思考的活动仍不可被怀疑；知识必须从这个确定点按清楚、可检验的次序重建。",
    evidenceCaution: "作品、书信和知识网络清楚；“我思故我在”不是从大前提演绎出的三段论。梦、恶魔和蜡块都是方法性装置，不代表他永久怀疑外部世界。",
    lifeSummary: "笛卡尔在军旅、旅行与荷兰隐居中发展数学、自然哲学和形而上学。他以方法怀疑将主体的思考活动设为知识起点，再试图通过上帝与清楚分明观念重建外部世界。解析几何和机械论自然观使其方法不只是怀疑，而是一套新的科学野心。",
    timeline: [
      { date: "1619", place: "德意志地区", title: "形成统一方法的计划", detail: "著名梦境由本人后来叙述，具体意义仍有解释争议。", certainty: "传统记载" },
      { date: "1637", place: "莱顿", title: "出版《方法谈》及科学论文", detail: "以法文展示方法、解析几何、光学和气象学成果。", certainty: "较可靠" },
      { date: "1641", place: "巴黎／荷兰", title: "出版《第一哲学沉思》", detail: "连同反驳与答辩公开测试怀疑、我思、上帝与心物区分。", certainty: "较可靠" },
      { date: "1649—1650", place: "斯德哥尔摩", title: "赴瑞典宫廷并去世", detail: "接受克里斯蒂娜女王邀请讲学，数月后患病去世；具体病因仍有争论。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "方法怀疑", en: "methodic doubt", definition: "为寻找确定基础而主动暂停可疑信念，不是以永远不信为目标。" },
      { zh: "我思", en: "cogito", definition: "只要正在思考，就不能否认此时作为思考者的存在。" },
      { zh: "心物二元论", en: "mind-body dualism", definition: "思维实体与广延实体具有不同本质，由此产生二者如何互动的问题。" },
      { zh: "清楚分明的知觉", en: "clear and distinct perception", definition: "心灵把握内容时清晰呈现且与其他内容严格区分；它承担真理标准，但其可靠性仍需论证。" },
      { zh: "广延", en: "extension", definition: "占有空间、可分割并具有形状和运动，是笛卡尔赋予物质实体的本质属性。" },
      { zh: "天赋观念", en: "innate ideas", definition: "不等于出生时已有完整句子，而指某些观念及其形成能力不能由感官图像充分解释。" },
      { zh: "心身联合", en: "mind-body union", definition: "人把疼痛、饥饿和行动体验为一个统一生命，而不只是纯心灵观察一台身体机器；这一事实使严格二元划分更难处理。" },
    ],
    lineage: { inherited: "承接奥古斯丁式内省、经院形而上学和新数学—机械科学。", school: "近代大陆理性主义与主体哲学的起点。", influenced: "直接塑造斯宾诺莎、莱布尼茨和整个心物问题，也迫使经验主义与康德重新界定主体。", parallel: "与弗朗西斯·培根都反传统方法；笛卡尔从个体确定性和演绎出发，培根从协作经验与排除出发。" },
    comparisons: [
      { target: "奥古斯丁", relation: "后世重构", shared: "即使受欺骗，内在思考的发生仍指向存在。", difference: "笛卡尔把内省放进普遍怀疑和科学奠基工程，功能不同于奥古斯丁的神学自知。" },
      { target: "斯宾诺莎", relation: "影响后继", shared: "用定义、实体和演绎追求整体可理解性。", difference: "斯宾诺莎拒绝两个实体，把心与身视为唯一实体的两种属性。" },
      { target: "洛克", relation: "批评关系", shared: "都要说明心灵如何获得观念和知识。", difference: "洛克拒绝天赋内容，从经验追踪观念来源；笛卡尔保留理性可把握的先天结构。" },
      { target: "伽利略", relation: "承接前人", shared: "自然现象应通过数学、运动与机械过程解释，而不是只引述古代权威。", difference: "伽利略从受控现象和局部定律推进；笛卡尔更大胆地由形而上学原则演绎整体自然体系。" },
      { target: "康德", relation: "影响后继", shared: "主体并非被动接收材料，认识结构参与对象如何被经验。", difference: "康德拒绝由我思直接证明灵魂实体，也限制纯理性对上帝和世界整体的知识要求。" },
      { target: "弗朗西斯·培根", relation: "同题比较", shared: "传统权威不能代替有步骤、可复查的方法，知识应帮助形成新的自然科学。", difference: "培根用协作观察和排除法逐步上升；笛卡尔由直观清楚的简单原则向复杂问题演绎，并更信任数学结构。" },
    ],
    stars: 5, culturalNotes: [{ kind: "名言", title: "“我思故我在”", text: "这句话的力量不在于它很短，而在于每次试图否定它都必须实际进行思考，于是怀疑反而执行了它要推翻的条件。" }],
    russellView: "罗素把笛卡尔视为现代哲学之父：主体取代权威成为起点，数学方法支配体系。他赞赏怀疑和我思，却认为上帝证明与由此恢复外部世界的步骤并不成功。",
    modernCorrection: "不能把笛卡尔只缩成孤立心灵。他同时是数学家、物理学家和通信网络中的研究者；方法怀疑服务于建立自然知识，而非把世界永久封闭在意识里。伊丽莎白公主对心身互动的追问也表明，体系是在真实反驳中调整的。",
    sources: [russellSource("第三卷第九章〈笛卡尔〉"), sepSource("René Descartes", "descartes")],
  },
  {
    id: "spinoza", order: 64, nameZh: "斯宾诺莎", nameEn: "Baruch Spinoza", greekName: "Bento de Espinosa / Benedictus de Spinoza", dates: "1632—1677", active: "1656—1677", places: ["阿姆斯特丹", "莱顿", "海牙"], school: "大陆理性主义／激进启蒙", figureId: "spinoza", chapterIds: ["b3-10"],
    thesis: "上帝或自然是唯一实体，一切事物都按其必然性发生；自由不是逃离因果，而是由更充分的理解转向主动生活。",
    evidenceCaution: "著作、书信和逐出文书可靠，但磨镜片致死、贫穷圣人等形象常被道德化。‘上帝即自然’也不能直接等同无神论或简单泛神论。",
    lifeSummary: "斯宾诺莎出生于阿姆斯特丹塞法迪犹太社群，1656 年被逐出会堂后以拉丁文写作并参与共和国知识网络。他拒绝大学职位，生前匿名出版《神学政治论》，死后由友人刊行《伦理学》。他的几何式体系把形而上学、情绪分析、伦理和政治自由放在同一因果结构中。",
    timeline: [
      { date: "1656", place: "阿姆斯特丹", title: "被犹太社群逐出", detail: "逐出文书仍存，具体争议言论和此前思想发展无法完全重建。", certainty: "较可靠" },
      { date: "1670", place: "阿姆斯特丹", title: "匿名出版《神学政治论》", detail: "以历史解释经文，主张思想自由有助国家和平。", certainty: "较可靠" },
      { date: "1677", place: "海牙", title: "去世并由友人出版遗著", detail: "《伦理学》等作品在其死后迅速刊行。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "上帝或自然", en: "Deus sive Natura", definition: "唯一无限实体的两种称呼；自然不是人格之外的受造物。" },
      { zh: "属性与样态", en: "attributes and modes", definition: "属性表达实体本质，具体事物则是实体在确定方式中的样态。" },
      { zh: "努力", en: "conatus", definition: "每一事物保存并增强自身存在的倾向，是情绪和德性的自然基础。" },
      { zh: "充分观念", en: "adequate idea", definition: "就观念自身考察，具有真观念的一切内在性质；在人类有限心灵中，一个观念若可由该心灵中的充分原因完整说明，就是充分的。它不等于任何关于“共同原因”的概括。" },
      { zh: "被动情绪", en: "passive affects", definition: "当人只是某种情绪或行动的部分原因，不能单凭自身本性充分说明它时，这一情绪是被动的；增加充分认识可提高主动性，但不是简单压抑感受。" },
    ],
    lineage: { inherited: "承接笛卡尔的实体、机械自然和几何方法，也回应犹太经文解释与荷兰共和政治。", school: "大陆理性主义和激进启蒙的独特一元论路线。", influenced: "影响德国观念论、圣经批判、自然主义伦理和当代情绪哲学。", parallel: "与霍布斯都把人放回因果自然；斯宾诺莎反对用恐惧维系统治，并更重思想自由与民主。" },
    comparisons: [
      { target: "笛卡尔", relation: "承接前人", shared: "从实体、属性与清楚观念建立理性体系。", difference: "斯宾诺莎取消心物两个实体和超越自然的创造者，只保留唯一实体。" },
      { target: "霍布斯", relation: "同题比较", shared: "欲望、自保和因果自然构成政治分析起点。", difference: "霍布斯集中绝对主权；斯宾诺莎认为思想自由和更广参与能增强国家。" },
      { target: "黑格尔", relation: "影响后继", shared: "有限事物只能在整体关系中被理解。", difference: "黑格尔把整体写成历史性精神发展，斯宾诺莎体系不以辩证历史为中心。" },
    ],
    stars: 5, culturalNotes: [{ kind: "生活印象", title: "拒绝海德堡教席", text: "斯宾诺莎担心官方职位附带的思想边界，婉拒海德堡大学邀请。这个选择强化了他把哲学自由落实为生活方式的形象。" }],
    russellView: "罗素把斯宾诺莎视为伟大哲学家中人格最高尚者，赞赏其以理解必然性克服恐惧、仇恨和死亡焦虑；同时认为实体体系在逻辑上难以成立。",
    modernCorrection: "不能把斯宾诺莎只读成安静宿命论者。他的自由概念与身体能力、共同制度和思想表达紧密相连；经文批判与政治著作也是体系核心。",
    sources: [russellSource("第三卷第十章〈斯宾诺莎〉"), sepSource("Baruch Spinoza", "spinoza")],
  },
  {
    id: "leibniz", order: 65, nameZh: "莱布尼茨", nameEn: "Gottfried Wilhelm Leibniz", greekName: "Gottfried Wilhelm Leibniz", dates: "1646—1716", active: "1666—1716", places: ["莱比锡", "巴黎", "汉诺威", "柏林"], school: "大陆理性主义", figureId: "leibniz", chapterIds: ["b3-11"],
    thesis: "现实由具有内在表象活动的单子构成；每一事实都应有充足理由，而世界秩序来自彼此不作用却协调对应的多重视角。",
    evidenceCaution: "手稿和书信极多，且大量未在生前发表；后世“莱布尼茨体系”由不同时期、不同对象的文本重建。与牛顿争夺微积分优先权也不能替代其哲学评价。",
    lifeSummary: "莱布尼茨横跨法律、外交、数学、工程、历史和哲学，长期为汉诺威宫廷服务并在欧洲通信网络中组织知识。他独立发展微积分，设计计算机和科学院计划，又以单子、充足理由和可能世界说明个体与整体。其公开著作很少，思想更像不断调整的研究网络。",
    timeline: [
      { date: "1672—1676", place: "巴黎／伦敦", title: "发展微积分并进入科学网络", detail: "与惠更斯等人交流，形成微分记号并展示计算机。", certainty: "较可靠" },
      { date: "1686", place: "汉诺威", title: "写作《形而上学谈》", detail: "压缩个体实体、充足理由和上帝选择世界的核心结构。", certainty: "较可靠" },
      { date: "1714", place: "维也纳／汉诺威", title: "完成《单子论》", detail: "以短条目概述单子、知觉、等级和预定和谐。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "单子", en: "monad", definition: "无物理部分、由内在知觉和欲求活动构成的简单实体。" },
      { zh: "充足理由原则", en: "principle of sufficient reason", definition: "任何事实为何如此而非彼样，都必须存在足够理由，即使有限者未必知道。" },
      { zh: "预定和谐", en: "pre-established harmony", definition: "各实体依自身法则展开，却由世界整体安排保持对应，不需直接因果输入。" },
      { zh: "可能世界", en: "possible worlds", definition: "由彼此共可能的个体及相应自然法则构成的完整可能秩序；不同可能世界之间常含不相容选择。现实世界被解释为上帝依其智慧与善选择实现的一项。" },
      { zh: "不可分辨者同一原则", en: "identity of indiscernibles", definition: "若两个对象在一切性质上都无差别，就没有充分理由把它们视为两个不同个体。" },
    ],
    lineage: { inherited: "承接笛卡尔理性主义、经院个体实体问题和新数学科学。", school: "大陆理性主义中多元、逻辑与可能性路线。", influenced: "影响德国哲学、现代逻辑、模态形而上学和计算思想。", parallel: "与斯宾诺莎都追求全体可理解性；斯宾诺莎只有一个实体，莱布尼茨则保留无限多个个体中心。" },
    comparisons: [
      { target: "笛卡尔", relation: "承接前人", shared: "用理性原则和数学理想解释自然与心灵。", difference: "莱布尼茨拒绝物质纯粹是被动广延，并以连续知觉和单子替代心物二分。" },
      { target: "斯宾诺莎", relation: "批评关系", shared: "每一事实都属于一个必然可理解的整体。", difference: "莱布尼茨用可能世界与上帝选择保存偶然性和个体，反对单一实体。" },
      { target: "康德", relation: "影响后继", shared: "理性原则超越经验事实并组织形而上学问题。", difference: "康德限制充足理由和纯理性对世界整体的认识资格。" },
    ],
    stars: 5, culturalNotes: [{ kind: "例子", title: "为什么有某物而不是一无所有？", text: "莱布尼茨把这一问作为充足理由原则的最高表达：即使列出世界内部全部原因，仍可追问为什么是这个世界。" }],
    russellView: "罗素区分莱布尼茨公开的乐观正统体系与未发表手稿中更严格的逻辑哲学，赞赏其逻辑天才，却批评单子和最佳世界受宫廷、神学妥协影响。",
    modernCorrection: "“真正莱布尼茨藏在手稿里”也可能过度二分。外交、神学与技术项目不是哲学外部妥协，而是其普遍协调理想的实践场域。",
    sources: [russellSource("第三卷第十一章〈莱布尼茨〉"), sepSource("Gottfried Wilhelm Leibniz", "leibniz")],
  },
  {
    id: "locke", order: 66, nameZh: "洛克", nameEn: "John Locke", greekName: "John Locke", dates: "1632—1704", active: "1660 年代—1704", places: ["牛津", "伦敦", "荷兰共和国", "埃塞克斯"], school: "英国经验主义／自由主义", figureId: "locke", chapterIds: ["b3-12", "b3-13", "b3-14", "b3-15"],
    thesis: "知识必须说明观念的经验来源和把握范围；政治权力则是个人为保护生命、自由和财产而设立的有限委托。",
    evidenceCaution: "著作和政治网络充分，但《政府论》不是光荣革命后的即兴辩护。自然权利与其殖民投资、卡罗来纳宪法工作和财产理论间的冲突必须保留。",
    lifeSummary: "洛克受医学和自然哲学训练，作为沙夫茨伯里伯爵的医生、顾问和政治盟友进入反王权网络，流亡荷兰后回到英格兰。他在《人类理解论》中限制知识边界，在《政府论》和《论宽容》中用同意、权利和政府权限重建政治。温和文风背后是一套同时改变认识论与自由主义的高连接方案。",
    timeline: [
      { date: "1667", place: "伦敦", title: "进入沙夫茨伯里家庭", detail: "兼任医生、秘书和政治顾问，接触殖民、贸易与反王权政治。", certainty: "较可靠" },
      { date: "1683—1689", place: "荷兰共和国", title: "流亡并整理主要著作", detail: "在政治压力下离开英格兰，参与跨国异议者网络。", certainty: "较可靠" },
      { date: "1689—1690", place: "伦敦", title: "发表认识论、政治与宽容著作", detail: "多部长期写作几乎同时进入公共讨论。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "白板", en: "tabula rasa", definition: "心灵没有预装的命题内容，观念材料来自感觉和对自身活动的反省。" },
      { zh: "第一与第二性质", en: "primary and secondary qualities", definition: "形状、运动等被视为物体本身性质；颜色等则是物体引起感受的能力。" },
      { zh: "政府委托", en: "fiduciary government", definition: "政府权力为保护权利而受托，违反目的时人民可撤回或反抗。" },
    ],
    lineage: { inherited: "承接培根经验纲领、笛卡尔观念问题、自然法传统和英国内战后的宪政争论。", school: "英国经验主义与近代自由主义的共同奠基人物。", influenced: "直接影响贝克莱、休谟、启蒙政治、美国革命语言和后世宽容理论。", parallel: "与霍布斯都从个人和契约出发，洛克却保留先于国家的权利与反抗资格。" },
    comparisons: [
      { target: "霍布斯", relation: "批评关系", shared: "政治权力由平等个人的协议而非自然等级产生。", difference: "洛克的自然状态有自然法和权利，政府是可撤回委托；霍布斯以安全支持不可分主权。" },
      { target: "贝克莱", relation: "影响后继", shared: "观念是认识论分析的直接材料。", difference: "贝克莱认为物质基质无经验内容，进一步取消物质实体。" },
      { target: "休谟", relation: "影响后继", shared: "复杂观念必须接受经验来源审查。", difference: "休谟更彻底地把因果、实体和自我降为知觉关系与习惯。" },
    ],
    stars: 5, culturalNotes: [{ kind: "例子", title: "忒修斯之船式的人格同一", text: "洛克用王子与鞋匠的思想实验说明，人格同一依赖意识能够把过去行动归为自己，而不只是同一个身体或灵魂实体。" }],
    russellView: "罗素把洛克赞为自由、温和、反独断的哲学典型，强调其认识论和政治哲学共同反对天赋权威；同时指出物质实体和观念表象仍留下难题。",
    modernCorrection: "自由主义肖像必须连同殖民、奴隶制和财产扩张语境审视。认识论也不只是被动白板：反省、抽象和判断显示心灵具有积极组织功能。",
    sources: [russellSource("第三卷第十二至十五章"), sepSource("John Locke", "locke")],
  },
  {
    id: "berkeley", order: 67, nameZh: "贝克莱", nameEn: "George Berkeley", greekName: "George Berkeley", dates: "1685—1753", active: "1709—1752", places: ["爱尔兰", "伦敦", "罗得岛", "克洛因"], school: "英国经验主义／非物质主义", figureId: "berkeley", chapterIds: ["b3-16"],
    thesis: "我们经验到的只有观念及其秩序；把物质实体设为观念背后不可经验的支撑，并不能增加解释，存在应由被感知和感知活动说明。",
    evidenceCaution: "文本清楚；“存在就是被感知”只适用于感性对象，不能推出无人看见时世界消失。贝克莱保留有限心灵、上帝和稳定自然规律。",
    lifeSummary: "贝克莱在都柏林三一学院形成非物质主义，试图用经验主义自身的原则反击怀疑论和无神论。他后来推动百慕大神学院计划、旅居美洲，并任克洛因主教。其理论并非说世界是私人幻觉，而是说感性世界就是按规律被给予的观念网络。",
    timeline: [
      { date: "1709—1713", place: "都柏林／伦敦", title: "发表视觉论和非物质主义著作", detail: "依次出版《视觉新论》《人类知识原理》和《海拉斯与斐洛诺斯》。", certainty: "较可靠" },
      { date: "1728—1731", place: "罗得岛", title: "等待百慕大教育计划资助", detail: "购买农场并在新港生活，计划因政府资金未到而放弃。", certainty: "较可靠" },
      { date: "1734", place: "克洛因", title: "任主教", detail: "继续写作数学、医学和宗教作品。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "存在就是被感知", en: "esse est percipi", definition: "感性对象的存在方式是被感知，并非所有存在都只是被动观念。" },
      { zh: "非物质主义", en: "immaterialism", definition: "否认物质实体这种独立于心灵、作为性质基底的存在者；贝克莱并不否认苹果、树木等普通对象，而把它们解释为有秩序的观念集合。" },
      { zh: "观念与精神", en: "ideas and spirits", definition: "观念是被感知的被动内容，精神则是感知、意愿和行动的主体。" },
    ],
    lineage: { inherited: "承接洛克的观念论和第一／第二性质区分，也回应笛卡尔外部世界问题。", school: "英国经验主义内部的非物质主义。", influenced: "迫使休谟更彻底审查实体、自我和因果，也长期刺激知觉哲学和观念论。", parallel: "与斯宾诺莎都拒绝传统物质概念，却分别保留心灵—观念结构与唯一实体的一元自然。" },
    comparisons: [
      { target: "洛克", relation: "承接前人", shared: "直接认识的是观念，性质需要分析其经验条件。", difference: "贝克莱拒绝物质基质，并把第一性质也纳入感知依赖。" },
      { target: "休谟", relation: "影响后继", shared: "不可经验实体不能承担解释工作。", difference: "休谟也不接受贝克莱用上帝和精神实体稳定世界。" },
      { target: "笛卡尔", relation: "批评关系", shared: "外部世界如何超出心灵表象而被认识。", difference: "贝克莱取消物质实体鸿沟，笛卡尔则试图证明与心灵不同的广延世界。" },
    ],
    stars: 4, culturalNotes: [{ kind: "轶事", title: "踢石头并没有反驳贝克莱", text: "约翰逊据说踢一块石头说“我如此反驳他”。疼痛和阻力当然真实，但贝克莱从未否认经验世界，只是否认其背后必须有物质基质。" }],
    russellView: "罗素承认贝克莱论证敏锐：若坚持经验主义，物质实体很难获得内容；但他认为贝克莱对观念和被感知的处理依赖语言混淆，上帝补丁也缺乏证明。",
    modernCorrection: "把理论称为主观唯心主义容易误导，因为世界并不由个人想象制造。其目标是保存常识对象和自然规律，同时消除哲学家虚构的物质抽象物。",
    sources: [russellSource("第三卷第十六章〈贝克莱〉"), sepSource("George Berkeley", "berkeley")],
  },
  {
    id: "hume", order: 68, nameZh: "休谟", aliases: ["大卫·休谟"], nameEn: "David Hume", greekName: "David Hume", dates: "1711—1776", active: "1734—1776", places: ["爱丁堡", "法国", "伦敦"], school: "英国经验主义／怀疑主义", figureId: "hume", chapterIds: ["b3-17"],
    thesis: "经验只给予知觉及其规律联结；因果必然、自我实体和归纳正当性不能由理性证明，却通过习惯、情感与社会实践支撑生活。",
    evidenceCaution: "著作和书信充分；《人性论》“从印刷机上夭折”是修辞性自述。休谟的缓和怀疑不是放弃知识，而是限制哲学断言并解释实践信念。",
    lifeSummary: "休谟年轻时在法国写成《人性论》，其后以论文、历史著作和外交工作获得名声。他把心灵研究当作经验科学，从印象与观念分析因果、自我、道德和宗教。怀疑论的终点不是沉默，而是承认自然习惯和共同生活先于哲学证明。",
    timeline: [
      { date: "1734—1737", place: "拉弗莱什", title: "写作《人性论》", detail: "在法国集中形成知觉、因果、情感与道德体系。", certainty: "较可靠" },
      { date: "1748／1751", place: "伦敦／爱丁堡", title: "重写认识论与道德哲学", detail: "以两部《研究》更清楚地发表核心论证。", certainty: "较可靠" },
      { date: "1763—1766", place: "巴黎", title: "任外交秘书并成为启蒙名人", detail: "与法国思想界广泛交往，后与卢梭发生公开冲突。", certainty: "较可靠" },
      { date: "1776／1779", place: "爱丁堡／伦敦", title: "去世与宗教著作身后出版", detail: "休谟安然面对死亡的公开形象引发争论；《自然宗教对话录》依其安排在身后刊行。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "印象与观念", en: "impressions and ideas", definition: "鲜明直接的知觉与较弱的思维表象；简单观念通常可追溯到相应印象。" },
      { zh: "恒常结合", en: "constant conjunction", definition: "相似事件反复相随，使心灵形成由一项期待另一项的习惯。" },
      { zh: "知觉束", en: "bundle of perceptions", definition: "内省只发现不断变化的知觉序列，而非独立、恒常的自我实体。" },
      { zh: "观念关系与事实问题", en: "relations of ideas and matters of fact", definition: "前者凭概念关系获得确定性，后者依赖经验且其反面仍可设想。" },
      { zh: "习惯", en: "custom / habit", definition: "重复经验使心灵自然产生预期，是因果信念和日常行动的实际基础，而不是逻辑证明。" },
      { zh: "是与应当", en: "is and ought", definition: "从事实陈述转到规范结论需要说明新的评价关系，不能悄然把‘应当’塞入描述。" },
      { zh: "同情", en: "sympathy", definition: "他人的情绪和福祉能够影响我们的心理机制，是社会性道德判断的重要基础。" },
      { zh: "信念的活力", en: "vivacity of belief", definition: "信念不是另添一个观念，而是某个观念因当前印象、记忆或习惯联结而以更有力量的方式被把握。" },
    ],
    lineage: { inherited: "承接洛克、贝克莱的观念分析和古代怀疑主义，也吸收牛顿式经验科学理想。", school: "英国经验主义的怀疑性完成与自然主义转向。", influenced: "唤醒康德的批判计划，塑造现代因果、归纳、道德情感和宗教批判。", parallel: "与威廉·詹姆斯都承认信念扎根于实践与心理生活；詹姆斯更积极讨论选择和真理如何在经验中形成。" },
    comparisons: [
      { target: "洛克", relation: "承接前人", shared: "观念须追溯经验，知识要服从能力边界。", difference: "休谟取消实体支撑和必然因果，把大量理性信念解释为习惯。" },
      { target: "贝克莱", relation: "承接前人", shared: "不可经验的物质实体没有说明资格。", difference: "休谟同样怀疑精神实体和神学保证，不以非物质主义封闭体系。" },
      { target: "康德", relation: "影响后继", shared: "经验无法单独提供因果必然与科学普遍性。", difference: "康德把因果解释为经验可能性的先天范畴，而非纯粹习惯。" },
      { target: "约翰·斯图亚特·密尔", relation: "影响后继", shared: "道德与制度应由人的感受、习惯和可观察后果解释。", difference: "密尔把功利原则发展为规范与改革纲领；休谟更重描述道德评价如何在人性和社会中形成。" },
      { target: "罗素", relation: "影响后继", shared: "传统形而上学和宗教主张必须接受证据与逻辑审查，归纳问题不能靠习惯性措辞掩盖。", difference: "罗素借现代逻辑和科学哲学寻找更明确的结构，同时承认归纳并未获得演绎式证明。" },
    ],
    stars: 5, culturalNotes: [{ kind: "例子", title: "台球碰撞", text: "看见一球撞上另一球，我们观察到的是运动前后相继，而不是眼睛直接看到“必然性”。这个普通场景压缩了休谟最深的因果问题。" }],
    russellView: "罗素把休谟视为经验主义的逻辑终点：一旦接受其前提，科学、神学和自我都失去传统理性基础。罗素赞赏其诚实，却认为现代哲学必须重新回应归纳及科学推理的可靠程度。",
    modernCorrection: "休谟不是只会摧毁的怀疑论者。他用习惯、情感、规则和社会约定解释稳定生活，形成一种自然主义；缓和的怀疑要求把断言限制在证据和人的能力之内，而不是停止研究，也不是否认科学实践。其种族主义文字应纳入历史责任，而非由哲学地位遮蔽。",
    sources: [russellSource("第三卷第十七章〈休谟〉"), sepSource("David Hume", "hume")],
  },
  {
    id: "rousseau", order: 69, nameZh: "卢梭", nameEn: "Jean-Jacques Rousseau", greekName: "Jean-Jacques Rousseau", dates: "1712—1778", active: "1749—1778", places: ["日内瓦", "巴黎", "蒙莫朗西", "英格兰"], school: "启蒙批判／浪漫主义先声", figureId: "rousseau", chapterIds: ["b3-18", "b3-19"],
    thesis: "文明进步可以扩大依赖、不平等和虚荣；正当政治必须让每个人服从自己作为公民共同制定的法律。",
    evidenceCaution: "自传材料丰富却高度自我塑造；“高贵野蛮人”不是他的固定概念。公意不等于多数意见，但其强制自由公式确有整体主义风险。",
    lifeSummary: "卢梭从日内瓦手工业家庭出走，在巴黎启蒙圈成名，又以文明批判同百科全书派分裂。他把音乐、教育、小说、自传与政治哲学连接起来，追问社会怎样制造不平等又如何恢复自由。作品屡遭查禁，晚年在孤立和被迫害感中继续写作。",
    timeline: [
      { date: "1750", place: "巴黎", title: "《论科学与艺术》获奖", detail: "以文明进步腐蚀德性这一逆向命题进入公共思想界。", certainty: "较可靠" },
      { date: "1762", place: "阿姆斯特丹／巴黎", title: "出版《社会契约论》与《爱弥儿》", detail: "政治与教育著作同时受查禁，他离开法国。", certainty: "较可靠" },
      { date: "1766—1767", place: "英格兰", title: "接受休谟帮助后公开决裂", detail: "冲突由真实误解、名誉焦虑与心理危机共同造成。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "公意", en: "general will", definition: "公民作为共同体成员指向公共利益的意志，不等于所有私人偏好的简单多数。" },
      { zh: "可完善性", en: "perfectibility", definition: "人能学习和改变的开放能力，既使文明、自由可能，也使比较、虚荣和不平等扩张。" },
      { zh: "自然自爱与社会性自爱", en: "amour de soi / amour-propre", definition: "卢梭区分自然的自爱（amour de soi）与依赖比较和他人评价的社会性自爱（amour-propre）；后者可造成虚荣和竞争，却不能在所有语境中直接等同“虚荣”。" },
    ],
    lineage: { inherited: "承接社会契约论、古代共和德性和启蒙自然状态问题。", school: "启蒙内部的文明批判，也是浪漫主义与民主理论的共同来源。", influenced: "深刻影响康德、法国革命、浪漫主义、民主与民族政治。", parallel: "与洛克都从自由个人出发；卢梭更担心财产依赖和代表制度使公民失去共同立法。" },
    comparisons: [
      { target: "洛克", relation: "批评关系", shared: "合法政治来自自由平等个人的同意。", difference: "洛克把财产权和有限政府置于中心；卢梭认为既有财产结构本身制造依赖。" },
      { target: "霍布斯", relation: "承接前人", shared: "政治共同体由契约而非自然等级形成。", difference: "卢梭拒绝把主权让渡给代表，要求人民作为公意主体持续拥有主权。" },
      { target: "康德", relation: "影响后继", shared: "自由不是任意欲望，而是服从自己认可的普遍法则。", difference: "康德把自律严格化为实践理性原则，不依赖小型共和国的公民共同体。" },
    ],
    stars: 5, culturalNotes: [{ kind: "名言", title: "“人生而自由，却无往不在枷锁之中”", text: "开篇名句不是要求回到孤独自然状态，而是提出制度难题：怎样把不可避免的社会关系改造成非支配的共同规则。" }],
    russellView: "罗素认为卢梭以情感、自然和公意开启浪漫主义，并影响法国革命和现代整体国家。他承认其历史力量，却对反理性、强迫自由和人格自我戏剧化评价严厉。",
    modernCorrection: "罗素把从卢梭到极权政治的路线画得过直。公意也可被解释为反私人支配、要求普遍法律的共和原则；但性别排除、弃养子女和强制风险不能回避。",
    sources: [russellSource("第三卷第十八至十九章"), sepSource("Jean-Jacques Rousseau", "rousseau")],
  },
  {
    id: "kant", order: 70, nameZh: "康德", nameEn: "Immanuel Kant", greekName: "Immanuel Kant", dates: "1724—1804", active: "1755—1804", places: ["柯尼斯堡", "普鲁士"], school: "批判哲学／德国观念论起点", figureId: "kant", chapterIds: ["b3-20"],
    thesis: "心灵不是被动接收世界，而以空间、时间和范畴组织经验；知识限于可能经验，道德自由则表现为理性为自己制定普遍法则。",
    evidenceCaution: "著作、讲稿和生平记录充分；“从未离开故乡”“生活像钟表”都是夸张。其普遍主义与著作中的种族等级、性别偏见必须并置。",
    lifeSummary: "康德终身以柯尼斯堡大学为中心，早期研究自然科学和理性形而上学，休谟问题促使他重建知识条件。三部批判分别处理认识、实践和审美目的论，试图让牛顿科学、自由与宗教在被限定的边界内共存。其“哥白尼式转向”改变了哲学提问方式：先问对象怎样可能被我们经验。",
    timeline: [
      { date: "1755", place: "柯尼斯堡", title: "取得教职资格并写宇宙生成论", detail: "早期自然哲学已尝试用机械过程解释太阳系形成。", certainty: "较可靠" },
      { date: "1781／1787", place: "里加", title: "出版两版《纯粹理性批判》", detail: "研究数学、自然科学和形而上学判断何以可能。", certainty: "较可靠" },
      { date: "1788—1790", place: "柯尼斯堡", title: "完成实践与判断力批判", detail: "把自由、道德、审美和目的判断纳入批判体系。", certainty: "较可靠" },
      { date: "1793—1794", place: "柯尼斯堡／柏林", title: "宗教论引发审查", detail: "《单纯理性限度内的宗教》与普鲁士审查制度发生冲突，显示启蒙公开运用理性的现实边界。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "先验", en: "transcendental", definition: "研究经验知识何以可能的条件，不等于超自然或脱离经验。" },
      { zh: "现象与物自身", en: "appearances and things in themselves", definition: "可由认识形式组织的对象与不依赖这种关系的对象之间的边界区分。" },
      { zh: "绝对命令", en: "categorical imperative", definition: "不依赖特定欲望而要求行动准则能够成为普遍法则的道德原则。" },
      { zh: "综合先天判断", en: "synthetic a priori judgment", definition: "扩展知识却不以具体经验归纳为根据的判断，是康德解释数学和基础自然科学的关键问题。" },
      { zh: "范畴", en: "categories", definition: "知性统一经验判断的基本概念，如实体与因果；其效力限于可能经验。" },
      { zh: "自律", en: "autonomy", definition: "理性者把自己视为普遍法则的共同制定者，而不是只受欲望、奖惩或外在命令推动。" },
      { zh: "目的王国", en: "kingdom of ends", definition: "每个人都被当作目的并共同服从可普遍立法原则的道德共同体理想。" },
      { zh: "先验唯心论", en: "transcendental idealism", definition: "空间、时间和范畴规定对象如何成为我们的经验对象；它不等于否认外部世界或把现实说成个人想象。" },
    ],
    lineage: { inherited: "综合理性主义、休谟经验主义挑战、牛顿科学和卢梭自由伦理。", school: "批判哲学并开启德国观念论。", influenced: "直接塑造黑格尔、叔本华、分析与大陆哲学，也持续支配认识论和伦理学。", parallel: "与休谟共享对传统形而上学的限制；康德以先验条件重建必然性，休谟以习惯解释信念。" },
    comparisons: [
      { target: "休谟", relation: "承接前人", shared: "经验本身不能呈现因果必然或自我实体。", difference: "康德把因果与统一解释为经验可能性的先天条件，而非心理习惯。" },
      { target: "卢梭", relation: "承接前人", shared: "自由不是随欲望行动，而是服从可普遍认可的法则。", difference: "康德将公民自律转化为每个理性者的道德立法。" },
      { target: "黑格尔", relation: "影响后继", shared: "主体结构参与对象性，自由需要超越任意选择。", difference: "黑格尔拒绝把物自身保留在认识之外，并把理性放入历史制度发展。" },
      { target: "莱布尼茨", relation: "批评关系", shared: "理性寻求充足理由、普遍原则和不依赖感觉偶然性的知识。", difference: "康德认为纯理性不能仅凭概念建立灵魂、世界整体和上帝的对象知识。" },
      { target: "罗素", relation: "影响后继", shared: "数学、逻辑和经验知识为何具有客观性，是哲学必须正面处理的问题。", difference: "罗素反对先验唯心论，以现代逻辑和关系分析重写数学基础，并批评康德受旧逻辑限制。" },
    ],
    stars: 5, culturalNotes: [{ kind: "生活印象", title: "准时散步的哲学家", text: "后世说邻居可凭康德散步校时。无论细节是否夸张，这一形象让严格规律与他研究的自由问题形成有趣反差。", caveat: "其作息有规律可靠，但“只有一次因读卢梭误时”等细节多为传记塑形。" }],
    russellView: "罗素承认康德提出休谟之后不可回避的问题，也赞赏空间、时间与范畴的结构分析；但反对把经验秩序过多归于主体，并认为物自身和先验论证产生混乱。",
    modernCorrection: "康德不是简单说心灵创造世界，而是分析对象能够成为经验对象的条件。现代阅读也必须正视其人类学中的种族主义与普遍道德原则之间的矛盾。",
    sources: [russellSource("第三卷第二十章〈康德〉"), sepSource("Immanuel Kant", "kant")],
  },
  {
    id: "hegel", order: 71, nameZh: "黑格尔", nameEn: "G. W. F. Hegel", greekName: "Georg Wilhelm Friedrich Hegel", dates: "1770—1831", active: "1801—1831", places: ["斯图加特", "耶拿", "海德堡", "柏林"], school: "德国观念论", figureId: "hegel", chapterIds: ["b3-21", "b3-22"],
    thesis: "概念、主体与制度都通过内在矛盾和关系发展；自由不是脱离社会，而是在能够被理性承认的制度中成为现实。",
    evidenceCaution: "著作与讲稿丰富但层次复杂，后世编订讲稿不等同亲定文本。“正反合”不是其通用固定公式，称赞现实也不等于任何现存国家都合理。",
    lifeSummary: "黑格尔与荷尔德林、谢林同受神学院教育，在法国革命和拿破仑战争背景中形成历史哲学。《精神现象学》追踪意识形态如何在自身失败中推进，柏林时期的逻辑、法哲学和历史讲演则把自由放进家庭、市民社会与国家制度。其体系既提供关系和历史工具，也容易被整体权威吸收。",
    timeline: [
      { date: "1806—1807", place: "耶拿", title: "战争中完成《精神现象学》", detail: "拿破仑军队进入耶拿之际交付手稿，革命时代成为体系背景。", certainty: "较可靠" },
      { date: "1812—1816", place: "纽伦堡", title: "出版《逻辑学》", detail: "研究概念规定如何因内在矛盾转化，而非列出形式规则。", certainty: "较可靠" },
      { date: "1818—1831", place: "柏林", title: "执教并形成制度哲学影响", detail: "讲授历史、宗教、美学与法哲学，成为普鲁士学术中心人物。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "辩证法", en: "dialectic", definition: "概念或生活形态因自身规定产生矛盾，经过否定与保存进入更充分关系。" },
      { zh: "扬弃", en: "Aufhebung / sublation", definition: "同时取消、保存并提升先前规定，不是把反方简单删除。" },
      { zh: "承认", en: "recognition", definition: "自我只有在与其他自我相互确认的关系中形成稳定自由和身份。" },
      { zh: "客观精神", en: "objective spirit", definition: "自由在法律、道德、家庭、市民社会和国家等制度形式中的实现层次，不是某种飘浮的集体心灵。" },
    ],
    lineage: { inherited: "承接康德与德国观念论、卢梭自由问题、法国革命和古希腊伦理共同体。", school: "德国观念论的系统与历史性高峰。", influenced: "分化出马克思主义、存在主义、历史主义、批判理论和多种承认理论。", parallel: "与尼采都把价值放入生成和冲突；黑格尔寻求可理解的整体调解，尼采怀疑这种和解遮蔽生命差异。" },
    comparisons: [
      { target: "康德", relation: "承接前人", shared: "自由和对象性不能由经验材料直接给出。", difference: "黑格尔拒绝不可知物自身和固定范畴，把理性结构写成历史发展。" },
      { target: "马克思", relation: "影响后继", shared: "社会形式通过内在冲突和历史过程变化。", difference: "马克思将重点转向劳动、生产关系和物质实践，批评理念自我运动。" },
      { target: "罗素", relation: "批评关系", shared: "哲学必须揭示命题和对象之间的结构关系。", difference: "罗素以逻辑分析反对整体主义和内在关系，认为黑格尔由概念跳到政治权威。" },
    ],
    stars: 5, culturalNotes: [{ kind: "生活印象", title: "“骑在马背上的世界精神”", text: "黑格尔看见拿破仑经过耶拿时，用这一形象表达革命原则如何以个人和军队进入现实历史。", caveat: "原信确有类似表述，但不意味着他赞同拿破仑全部政策。" }],
    russellView: "罗素承认黑格尔影响巨大，却猛烈批评整体论、内在关系和国家哲学，认为其晦涩逻辑把普鲁士国家包装成理性终点，并成为政治专断的思想资源。",
    modernCorrection: "罗素的批判抓住整体吞没个体的风险，却把黑格尔逻辑和国家论压得过平。现代研究区分合理制度与任何现实国家，也重视承认、市民社会和社会自由。",
    sources: [russellSource("第三卷第二十一至二十二章"), sepSource("Georg Wilhelm Friedrich Hegel", "hegel")],
  },
  {
    id: "byron", order: 72, nameZh: "拜伦", nameEn: "Lord Byron", greekName: "George Gordon Byron", dates: "1788—1824", active: "1809—1824", places: ["伦敦", "日内瓦", "意大利", "希腊"], school: "浪漫主义／拜伦式英雄", figureId: "byron", chapterIds: ["b3-18", "b3-23"],
    thesis: "反叛、激情与自我创造可以成为对社会虚伪和顺从规范的抗议；但若个人力量不受共同尺度约束，也会滑向支配与毁灭。",
    evidenceCaution: "作品、书信和公共生活材料丰富；“拜伦式英雄”是跨作品和接受史形成的类型，不等于作者本人，也不是一套严密哲学体系。",
    lifeSummary: "拜伦以贵族身份、诗歌名声、丑闻和自我流亡成为欧洲浪漫主义偶像。《恰尔德·哈罗尔德游记》《唐璜》和戏剧人物把骄傲、孤独、反习俗与政治反抗连接起来。他参与意大利自由派网络并赴希腊独立战争，在迈索隆吉翁病逝，使文学人格进一步政治神话化。",
    timeline: [
      { date: "1812", place: "伦敦", title: "凭《恰尔德·哈罗尔德》成名", detail: "诗人与作品中的忧郁旅行者迅速在公众想象中重叠。", certainty: "较可靠" },
      { date: "1816", place: "日内瓦／意大利", title: "永久离开英格兰", detail: "婚姻破裂和舆论丑闻促成自我流亡，并进入欧洲自由派圈。", certainty: "较可靠" },
      { date: "1824", place: "迈索隆吉翁", title: "参与希腊独立事业时去世", detail: "尚未投入战斗便因病去世，迅速成为泛欧洲自由象征。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "拜伦式英雄", en: "Byronic hero", definition: "骄傲、孤独、带罪感且反抗社会的魅力人物类型。" },
      { zh: "浪漫反叛", en: "Romantic revolt", definition: "以激情、想象和个性对抗抽象理性、礼俗和制度顺从。" },
      { zh: "自我神话", en: "self-mythologizing", definition: "作者生活、公共形象和作品角色相互塑造，使人格本身成为文化文本。" },
    ],
    lineage: { inherited: "承接卢梭的文明批判、浪漫主义自然与情感崇尚，以及革命时代的自由政治。", school: "浪漫主义文学中的反叛个人主义类型。", influenced: "影响欧洲文学、民族自由运动，以及尼采式价值创造的文化想象。", parallel: "与叔本华都拒绝理性乐观；拜伦把欲望写成行动人格，叔本华把欲望诊断为普遍痛苦。" },
    comparisons: [
      { target: "卢梭", relation: "承接前人", shared: "社会文明可能扭曲真实情感和个人自由。", difference: "拜伦以诗性人格和反叛表演展开，卢梭仍设计公意和教育制度。" },
      { target: "叔本华", relation: "同题比较", shared: "欲望与理性秩序的冲突构成人的深层处境。", difference: "拜伦赞颂危险行动和个性；叔本华以否定意志寻求解脱。" },
      { target: "尼采", relation: "影响后继", shared: "反习俗、贵族性格和个体自我塑造。", difference: "尼采用谱系批判和价值重估将文学类型改造成哲学诊断。" },
    ],
    stars: 4, culturalNotes: [{ kind: "生活印象", title: "诗人走进希腊独立战争", text: "拜伦不是只写反叛英雄；他投入金钱、组织和生命参与希腊独立，使文学姿态与政治行动罕见地重合。" }],
    russellView: "罗素专章讨论拜伦，不因其是系统哲学家，而因拜伦式反叛人格影响欧洲政治和思想。他欣赏自由热情，却警惕贵族英雄崇拜、暴力和蔑视普通幸福。",
    modernCorrection: "把拜伦直线连接到法西斯主义会过度简化。其讽刺、自我怀疑、自由派政治和跨国声援同样重要；人物类型不应被当成稳定教义。",
    sources: [russellSource("第三卷第二十三章〈拜伦〉"), { label: "Poetry Foundation · Lord Byron", kind: "补充", url: "https://www.poetryfoundation.org/poets/lord-byron" }],
  },
  {
    id: "schopenhauer", order: 73, nameZh: "叔本华", nameEn: "Arthur Schopenhauer", greekName: "Arthur Schopenhauer", dates: "1788—1860", active: "1818—1860", places: ["但泽", "柏林", "法兰克福"], school: "意志哲学／悲观主义", figureId: "schopenhauer", chapterIds: ["b3-24"],
    thesis: "作为表象的世界受主体认识形式组织，其内在本性却是无目的的意志；欲望不断再生产匮乏，审美、同情和禁欲只能暂时或逐步削弱它。",
    evidenceCaution: "著作和生平充分；其印度思想理解经由当时欧洲译介，不能当作忠实代表佛教或吠檀多。悲观主义也不是简单个人坏脾气的投射。",
    lifeSummary: "叔本华出身商人家庭，反抗父亲预设的商业道路，受康德、柏拉图和早期印度文本译介影响。1818 年出版《作为意志和表象的世界》，长期少人问津；与黑格尔同时开课失败后离开大学，晚年才获得名声。他把身体经验作为从表象通往意志的线索，并以同情对抗自我中心。",
    timeline: [
      { date: "1818／1819", place: "德累斯顿", title: "出版《作为意志和表象的世界》", detail: "第一版反响有限，却已包含体系核心。", certainty: "较可靠" },
      { date: "1820", place: "柏林", title: "与黑格尔同时开课", detail: "学生极少，大学计划失败；后世常把它戏剧化为两种哲学的对决。", certainty: "较可靠" },
      { date: "1851", place: "法兰克福", title: "《附录与补遗》带来晚年名声", detail: "短论和随笔使其思想进入更广读者。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "作为表象的世界", en: "world as representation", definition: "世界作为表象，首先意味着对象总是相对于认识主体而成为对象；感知中的个别对象由空间、时间与因果性组织，抽象概念则不能简单说成占据空间。" },
      { zh: "意志", en: "will", definition: "不依赖理性目的、在身体与自然中表现的盲目冲动，是世界内在本性。" },
      { zh: "同情", en: "compassion", definition: "越过个体化表象直接感受他者痛苦，是道德行动的非利己基础。" },
    ],
    lineage: { inherited: "承接康德现象／物自身区分、柏拉图审美和欧洲所理解的印度思想。", school: "后康德意志形而上学与哲学悲观主义。", influenced: "深刻影响尼采、弗洛伊德、文学现代主义和生命哲学。", parallel: "与佛教传统都诊断欲望—痛苦联系，但其形而上学、无我与解脱路径不能简单等同。" },
    comparisons: [
      { target: "康德", relation: "承接前人", shared: "经验世界由主体形式组织，物自身不直接成为对象。", difference: "叔本华大胆把身体体验中的意志认作物自身线索，康德拒绝这种知识越界。" },
      { target: "黑格尔", relation: "批评关系", shared: "都要解释表面个体背后的整体结构。", difference: "叔本华拒绝历史理性和国家和解，以盲目意志取代精神发展。" },
      { target: "尼采", relation: "影响后继", shared: "理性不是人的根本动力，价值与生命冲动相连。", difference: "尼采反对否定意志和普遍悲观，转向肯定、创造与力量差异。" },
    ],
    stars: 5, culturalNotes: [{ kind: "生活印象", title: "与黑格尔同时开课的空教室", text: "叔本华故意把课程排在黑格尔同一时间，结果几乎无人听课。这场失败后来成为一个思想家长期不被时代承认的象征。" }],
    russellView: "罗素欣赏叔本华文体、心理洞察和非基督教资源，却认为其悲观主义与个人生活不一致，也反对把意志设为世界本体及把解脱理解为否定生命。",
    modernCorrection: "用性格攻击不能反驳论证。现代研究更重视身体、自我、同情和动机理论，也应校正其对亚洲传统的选择性吸收与性别偏见。",
    sources: [russellSource("第三卷第二十四章〈叔本华〉"), sepSource("Arthur Schopenhauer", "schopenhauer")],
  },
  {
    id: "nietzsche", order: 74, nameZh: "尼采", nameEn: "Friedrich Nietzsche", greekName: "Friedrich Wilhelm Nietzsche", dates: "1844—1900", active: "1869—1889", places: ["巴塞尔", "锡尔斯-玛丽亚", "都灵", "魏玛"], school: "谱系学／价值批判", figureId: "nietzsche", chapterIds: ["b3-25"],
    thesis: "价值不是超历史命令，而是生命形式、情感训练和权力关系的产物；虚无主义要求重新评价价值，而非用旧真理的空壳继续生活。",
    evidenceCaution: "出版作品、笔记和书信丰富；《权力意志》是身后编选而非本人定稿，纳粹式解读受妹妹编辑和政治挪用影响。精神崩溃不能倒推全部哲学。",
    lifeSummary: "尼采以古典语文学者身份早年获巴塞尔教席，健康恶化后辞职，在瑞士、意大利和法国独居写作。他由悲剧与文化批评转向道德谱系、视角主义和虚无主义诊断，采用格言、诗、心理分析和虚构先知等多种形式。1889 年崩溃后失去写作能力，作品由家人和编辑塑造接受史。",
    timeline: [
      { date: "1869", place: "巴塞尔", title: "二十四岁任古典语文学教授", detail: "尚未完成通常博士程序即获教席，早期与瓦格纳关系密切。", certainty: "较可靠" },
      { date: "1879—1888", place: "瑞士／意大利", title: "辞职后完成成熟著作", detail: "在迁徙与疾病中写作《查拉图斯特拉》《善恶的彼岸》《道德谱系》等。", certainty: "较可靠" },
      { date: "1889", place: "都灵", title: "精神崩溃", detail: "著名抱马故事只有间接证据；此后由母亲和妹妹照料。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "谱系学", en: "genealogy", definition: "通过历史、语言和心理机制追踪价值如何形成及取得权威。" },
      { zh: "权力意志", en: "will to power", definition: "生命解释、组织和扩展能力的多义概念，不是单纯政治统治欲。" },
      { zh: "永恒轮回", en: "eternal recurrence", definition: "设想同一生命的一切细节永远重复。它可作为检验生命肯定程度的实践思想实验，也有宇宙论解释；不能把前一种读法写成无争议的唯一含义。" },
    ],
    lineage: { inherited: "承接叔本华的非理性动力诊断、希腊悲剧研究和法国道德心理学。", school: "谱系学、生命哲学和价值批判的核心人物。", influenced: "影响存在主义、精神分析、谱系批判、文学和后结构主义，也被多种政治运动争夺。", parallel: "与马克思都揭示观念背后的历史力量；马克思强调生产与阶级，尼采强调情感、身体和价值类型。" },
    comparisons: [
      { target: "叔本华", relation: "承接前人", shared: "理性背后有更根本的生命冲动，痛苦不可由乐观进步抹去。", difference: "尼采反对否定意志和同情普遍化，转向对痛苦和创造的肯定。" },
      { target: "马克思", relation: "同题比较", shared: "价值与观念需要由其历史生成和支配关系解释。", difference: "马克思以生产方式和阶级为主轴；尼采拒绝单一经济基础并聚焦道德心理。" },
      { target: "拜伦", relation: "后世重构", shared: "反习俗、贵族人格和危险的自我创造。", difference: "尼采把浪漫英雄类型改造成对文化健康与价值来源的哲学诊断。" },
    ],
    stars: 5, culturalNotes: [{ kind: "名言", title: "“上帝死了”", text: "这不是关于神发生生物学死亡的断言，而是说最高价值的旧基础已失去可信力，欧洲却还未理解由此产生的虚无主义。" }],
    russellView: "罗素承认尼采才智、心理洞察和对虚伪道德的揭露，却强烈反对贵族主义、残酷审美、反平等与英雄崇拜，并将其置于通向法西斯主义的危险路线。",
    modernCorrection: "尼采与纳粹不能简单等同：他反民族主义、反反犹主义，文本也遭妹妹选择性编辑。但其等级、残酷和反民主表达确有问题，不能只用误读替他免责。",
    sources: [russellSource("第三卷第二十五章〈尼采〉"), sepSource("Friedrich Nietzsche", "nietzsche")],
  },
  {
    id: "bentham", order: 75, nameZh: "边沁", nameEn: "Jeremy Bentham", greekName: "Jeremy Bentham", dates: "1748—1832", active: "1776—1832", places: ["伦敦", "威斯敏斯特"], school: "古典功利主义", figureId: "bentham", chapterIds: ["b3-26"],
    thesis: "法律与制度应按它们给所有相关者造成的快乐和痛苦来评价；传统、身份和自然权利口号都不能免除后果检验。",
    evidenceCaution: "著作和改革活动材料庞大，但许多手稿由编辑整理；“快乐计算”不是一台可直接输入数字的机器。对圆形监狱的评价也须结合实际监禁制度与其未实现状态。",
    lifeSummary: "边沁受法律训练，却因英国法的混乱和特权结构转向全面改革。他以功利原则分析刑罚、证据、行政、贫困和代表制度，组织门徒网络并推动法典化。圆形监狱计划使可见性和监督进入制度设计，也成为后世批判的焦点。",
    timeline: [
      { date: "1776", place: "伦敦", title: "出版《政府片论》", detail: "批评布莱克斯通以传统和自然权利为英国制度辩护。", certainty: "较可靠" },
      { date: "1789", place: "伦敦", title: "出版《道德与立法原理导论》", detail: "系统提出功利原则、快乐维度和刑罚限度。", certainty: "较可靠" },
      { date: "1790 年代—1810 年代", place: "伦敦", title: "推动圆形监狱计划", detail: "多年游说政府但未建成，项目成为其制度工程雄心和失败的缩影。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "功利原则", en: "principle of utility", definition: "按行动或制度增减相关者幸福的倾向来赞成或反对。" },
      { zh: "快乐计算", en: "felicific calculus", definition: "用强度、持续、确定、远近、繁殖、纯度和范围等维度系统比较后果。" },
      { zh: "圆形监狱", en: "Panopticon", definition: "以中央可见性组织监督的监狱设计，兼具改革效率理想与持续控制风险。" },
    ],
    lineage: { inherited: "承接休谟的情感与效用分析、启蒙改革和法律实证主义。", school: "古典功利主义与制度改革运动的奠基者。", influenced: "直接影响詹姆斯·密尔、约翰·斯图亚特·密尔、法律改革和现代公共政策分析。", parallel: "与康德都追求普遍公共标准；边沁比较结果，康德要求行动准则和人格尊重不依赖结果。" },
    comparisons: [
      { target: "休谟", relation: "承接前人", shared: "道德判断与人类情感、社会效用相连，而非纯理性实体。", difference: "边沁把效用系统化为立法和制度改革的单一公共标准。" },
      { target: "约翰·斯图亚特·密尔", relation: "影响后继", shared: "幸福后果是伦理和制度评价核心。", difference: "密尔加入快乐质量、个性、自由和少数保护，修正简单数量图景。" },
      { target: "康德", relation: "同题比较", shared: "伦理原则应能从私人偏好上升为公共标准。", difference: "边沁聚合幸福后果；康德拒绝把人格只当作总体福利的投入项。" },
    ],
    stars: 5, culturalNotes: [{ kind: "生活印象", title: "至今仍“出席”会议的自动圣像", text: "边沁遗体按遗愿制成“自动圣像”，保存在伦敦大学学院。这个奇特安排延续了他希望制度与教育在身后继续发挥公共作用的形象。" }],
    russellView: "罗素把边沁写成缺少诗意却极有公共用途的改革者，赞赏其清楚、反迷信和对刑法制度的实际影响，同时承认简单快乐计算会低估复杂价值。",
    modernCorrection: "功利主义并非只问短期多数满意。边沁重视每人计为一人、动物痛苦和制度激励；但幸福可比较性、少数权利和监督技术仍是根本难题。",
    sources: [russellSource("第三卷第二十六章〈功利主义者〉"), sepSource("Jeremy Bentham", "bentham")],
  },
  {
    id: "mill", order: 76, nameZh: "约翰·斯图亚特·密尔", aliases: ["穆勒"], nameEn: "John Stuart Mill", greekName: "John Stuart Mill", dates: "1806—1873", active: "1820 年代—1873", places: ["伦敦", "阿维尼翁", "英国议会"], school: "功利主义／自由主义", figureId: "mill", chapterIds: ["b3-26"],
    thesis: "幸福不能只按感受数量比较；个性、思想实验和较高能力需要免受社会强制，除非一个人的行动伤害他人。",
    evidenceCaution: "自传和著作丰富，但童年教育与精神危机由成年后的自我叙述组织。哈丽雅特·泰勒对作品的贡献真实且重要，具体共同写作范围仍有争论。",
    lifeSummary: "密尔在父亲詹姆斯·密尔和边沁圈的严格计划中接受早熟教育，二十岁左右经历精神危机，转向诗歌、情感与个性发展。他在东印度公司、公共论战和议会中工作，与哈丽雅特·泰勒形成长期思想伙伴关系。《论自由》《功利主义》和《妇女的屈从》把改革、幸福和反多数压迫连接起来。",
    timeline: [
      { date: "约 1826", place: "伦敦", title: "经历精神危机", detail: "自传记述机械改革目标失去意义，华兹华斯诗歌帮助恢复情感。", certainty: "较可靠" },
      { date: "1859—1863", place: "伦敦", title: "发表自由与功利主义代表作", detail: "将个性、实验和快乐质量纳入功利框架。", certainty: "较可靠" },
      { date: "1865—1868", place: "英国议会", title: "任议员并支持妇女选举权", detail: "提出以“person”替代选举法中的“man”等修正。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "伤害原则", en: "harm principle", definition: "《论自由》主张：对共同体中具有成熟能力的成员施加强制，正当目的在于防止伤害他人，而非只为使本人更好。密尔原文还带有如今不能接受的文明等级限制，应用时须与核心原则区分。" },
      { zh: "较高快乐", en: "higher pleasures", definition: "运用智力、情感和道德能力的满足具有质量差异，不能只按强度求和。" },
      { zh: "生活实验", en: "experiments in living", definition: "多样生活方式让个人发展，也为社会发现错误和新可能。" },
    ],
    lineage: { inherited: "承接边沁功利主义、詹姆斯·密尔联想心理学、浪漫主义个性和哈丽雅特·泰勒的平等思想。", school: "修正功利主义、自由主义和早期女性平等论。", influenced: "塑造现代言论自由、少数权利、女性主义和社会自由主义。", parallel: "与托克维尔共同诊断多数暴政；密尔更集中论证思想和生活方式的实验价值。" },
    comparisons: [
      { target: "边沁", relation: "承接前人", shared: "行动和制度必须对所有人的幸福后果负责。", difference: "密尔拒绝纯数量快乐观，以个性、能力发展和自由保护补充功利主义。" },
      { target: "卢梭", relation: "同题比较", shared: "个人自由可能被社会依赖和舆论结构侵蚀。", difference: "密尔保护差异和少数实验，卢梭寻求公意下的共同公民自律。" },
      { target: "罗素", relation: "影响后继", shared: "自由讨论、经验改革和个人幸福应抵抗教条权威。", difference: "罗素以逻辑分析和二十世纪政治经验扩展自由主义，且不接受密尔归纳逻辑的全部框架。" },
    ],
    stars: 5, culturalNotes: [{ kind: "例子", title: "即使全人类反对一个人", text: "密尔说，即使全人类只有一个异议者，多数也没有比异议者压制全人类更多的正当性。这个极端比例凸显言论自由不是人数奖励。" }],
    russellView: "罗素尊敬密尔的自由主义、理性诚实和改革精神，也讨论其童年教育与思想发展；但认为功利主义证明、快乐质量和归纳逻辑仍不够坚实。",
    modernCorrection: "伤害与自涉的边界并非自动清楚，结构性依赖和公共风险会使分类困难。密尔的自由论也应与殖民帝国职务和所谓未开化者例外并置。",
    sources: [russellSource("第三卷第二十六章〈功利主义者〉"), sepSource("John Stuart Mill", "mill")],
  },
  {
    id: "marx", order: 77, nameZh: "马克思", nameEn: "Karl Marx", greekName: "Karl Heinrich Marx", dates: "1818—1883", active: "1842—1883", places: ["特里尔", "巴黎", "布鲁塞尔", "伦敦"], school: "历史唯物主义／资本主义批判", figureId: "marx", chapterIds: ["b3-21", "b3-27"],
    thesis: "社会观念和政治制度必须放回生产关系、阶级冲突与实践中解释；资本主义自由交换的表面形式建立在劳动能力被商品化的结构上。",
    evidenceCaution: "著作、书信和经济手稿丰富但未完成，马克思与恩格斯文本须区分。后世国家的“马克思主义”不能全部倒归本人，反之也不能免除其决定论表达和政治排斥。",
    lifeSummary: "马克思从青年黑格尔派哲学批评转向政治经济学，在审查和流亡中先后居于巴黎、布鲁塞尔和伦敦。他与恩格斯长期合作，参与共产主义者同盟和第一国际，并在大英博物馆研究资本主义。其核心工作不是预言日期，而是揭示商品、工资与利润形式怎样遮蔽社会关系。",
    timeline: [
      { date: "1844—1848", place: "巴黎／布鲁塞尔", title: "转向政治经济学并形成历史唯物主义", detail: "与恩格斯合作，写作经济哲学手稿、《德意志意识形态》和《共产党宣言》。", certainty: "较可靠" },
      { date: "1849", place: "伦敦", title: "开始长期流亡", detail: "在贫困、疾病和家庭损失中持续研究与政治组织。", certainty: "较可靠" },
      { date: "1867", place: "汉堡", title: "出版《资本论》第一卷", detail: "第二、三卷由恩格斯依据手稿身后编辑。", certainty: "较可靠" },
      { date: "1871", place: "伦敦／巴黎", title: "评述巴黎公社", detail: "在《法兰西内战》中把短暂公社视为工人政治的新实验，其判断也深受事件当时的信息限制。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "历史唯物主义", en: "historical materialism", definition: "从生产方式、社会关系与实践解释制度和观念变化，不是经济因素机械单因决定一切。" },
      { zh: "异化", en: "alienation", definition: "劳动者的产品、活动、共同能力和人与人关系以外在力量反过来支配劳动者。" },
      { zh: "剩余价值", en: "surplus value", definition: "劳动者在工作日中创造的价值超过劳动力自身的价值，差额被资本占有并构成利润等收入的基础。劳动力的价值与维持和再生产劳动力所需资料相关，但不等同实际工资。" },
      { zh: "生产方式", en: "mode of production", definition: "生产力与生产关系的历史组合，包括劳动组织、技术、财产和支配结构。" },
      { zh: "商品拜物教", en: "commodity fetishism", definition: "生产者之间的社会关系在市场中表现为商品仿佛天然具有的价值关系；不是单指消费崇拜。" },
      { zh: "意识形态", en: "ideology", definition: "观念怎样在特定社会关系中形成并使其显得自然；它不等于任何错误思想或简单谎言。" },
      { zh: "阶级斗争", en: "class struggle", definition: "在生产、财产和权力位置不同的群体之间形成的结构性冲突，其政治形态并非自动给定。" },
    ],
    lineage: { inherited: "承接黑格尔辩证历史、费尔巴哈批判、英国政治经济学和法国社会主义。", school: "历史唯物主义与资本主义批判传统。", influenced: "塑造全球社会主义、社会科学、劳动运动和批判理论，也被党国制度多次正统化。", parallel: "与尼采都揭露意识表面下的历史力量；马克思以阶级与生产为主轴，尼采以道德情感和权力类型为主轴。" },
    comparisons: [
      { target: "黑格尔", relation: "后世重构", shared: "社会形式通过矛盾和历史过程改变，个体嵌在整体关系中。", difference: "马克思把辩证法转向劳动、财产和物质实践，拒绝理念自我运动。" },
      { target: "莫尔", relation: "后世重构", shared: "私人财产和劳动制度并非自然不变。", difference: "马克思批评乌托邦蓝图，要求由现实生产关系和阶级力量解释转型。" },
      { target: "罗素", relation: "批评关系", shared: "资本主义不平等需要制度改革，思想不能脱离社会权力。", difference: "罗素拒绝历史必然论、阶级独占真理和革命专政，支持自由社会主义。" },
      { target: "约翰·斯图亚特·密尔", relation: "同题比较", shared: "工业社会的贫困、劳动条件和权力集中要求制度改变。", difference: "密尔以自由、教育、合作社和渐进改革修正市场社会；马克思把工资劳动和资本关系本身作为批判对象。" },
      { target: "卢梭", relation: "后世重构", shared: "形式自由可以与依赖、不平等和由财产造成的支配同时存在。", difference: "卢梭从公民立法和道德心理诊断不平等；马克思转向生产关系、阶级形成与资本积累。" },
    ],
    stars: 5, culturalNotes: [{ kind: "名言", title: "“哲学家们只是用不同方式解释世界”", text: "《关于费尔巴哈的提纲》最后一句把哲学的任务转向改变世界；但改变若没有准确解释，也会失去方向。" }],
    russellView: "罗素承认马克思以经济结构解释思想和制度极具力量，也同情其反贫困目标；但批评黑格尔式历史必然、阶级斗争单线化和由此为政治专断留下的空间。",
    modernCorrection: "马克思没有一套简单经济决定论，文本中存在偶然、政治组织与多重历史路径，也没有留下可直接照图施工的共产社会制度蓝图。但欧洲中心表达、殖民判断及后世权威化必须接受具体批判。",
    sources: [russellSource("第三卷第二十七章〈卡尔·马克思〉"), sepSource("Karl Marx", "marx")],
  },
  {
    id: "bergson", order: 78, nameZh: "柏格森", nameEn: "Henri Bergson", greekName: "Henri-Louis Bergson", dates: "1859—1941", active: "1889—1939", places: ["巴黎", "法兰西公学院", "伦敦"], school: "生命哲学／直觉主义", figureId: "bergson", chapterIds: ["b3-28"],
    thesis: "活着的时间不是钟表上的同质单位，而是过去渗入现在的质性绵延；分析会把流动空间化，直觉则尝试从内部把握生成。",
    evidenceCaution: "著作和公共生涯充分；“直觉”不是反证据的灵感，也不应把柏格森写成单纯反科学。他批评的是把科学抽象无界限地当作生命经验本身。",
    lifeSummary: "柏格森在法国教育体系内成为国际知名哲学家，以《时间与自由意志》《物质与记忆》《创造进化》讨论时间、意识、身体和生命。他的公开讲座吸引大众，也参与国际知识合作。二战占领期间，他拒绝利用例外免除犹太人登记，1941 年去世。",
    timeline: [
      { date: "1889", place: "巴黎", title: "发表《时间与自由意志》", detail: "以绵延批评把心理状态当作可并列数量。", certainty: "较可靠" },
      { date: "1900—1921", place: "法兰西公学院", title: "公开讲学并形成国际影响", detail: "课程吸引学者和普通听众，哲学成为重要公共事件。", certainty: "较可靠" },
      { date: "1927", place: "斯德哥尔摩", title: "获诺贝尔文学奖", detail: "以思想活力和表达艺术获得文学奖。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "绵延", en: "durée / duration", definition: "质性状态相互渗透、过去持续进入现在的生活时间。" },
      { zh: "直觉", en: "intuition", definition: "进入对象独特生成过程的反思方法，不是放弃概念和论证的瞬间感觉。" },
      { zh: "生命冲力", en: "élan vital / vital impetus", definition: "生命演化的创造性分叉倾向，不是一种可直接测量的神秘物质。" },
    ],
    lineage: { inherited: "回应斯宾塞进化论、心理学、康德自由问题和法国生命科学。", school: "生命哲学和现代时间哲学的核心人物。", influenced: "影响威廉·詹姆斯、现象学、过程哲学、文学现代主义和电影理论。", parallel: "与爱因斯坦都讨论时间，却分别研究生活绵延与物理测量结构；二者不能由一次公开争论简单裁决。" },
    comparisons: [
      { target: "叔本华", relation: "后世重构", shared: "抽象理性不能穷尽生命内在动力。", difference: "柏格森强调创造和分叉，不把生命冲动定义为永恒重复痛苦的盲意志。" },
      { target: "威廉·詹姆斯", relation: "同题比较", shared: "经验是连续流动、多样且不能被静态概念完全替代。", difference: "詹姆斯强调实用后果和信念，柏格森集中绵延、记忆与生命创造。" },
      { target: "罗素", relation: "批评关系", shared: "哲学必须说明时间和变化而不受语言表面误导。", difference: "罗素认为直觉削弱可检验分析；柏格森认为分析把流动空间化。" },
    ],
    stars: 4, culturalNotes: [{ kind: "例子", title: "旋律不是一串孤立音符", text: "听旋律时，前一个音并未消失，而是留在当前音中形成整体。这个经验让“绵延”比抽象定义更容易被识别。" }],
    russellView: "罗素承认柏格森文体和对空间化时间的吸引力，却猛烈反对直觉主义、生命冲力和反智倾向，认为其论证依赖比喻并削弱科学分析。",
    modernCorrection: "罗素低估了柏格森对心理时间、记忆和行动的细致分析。直觉不是任意感觉；但生命冲力的解释资格和物理时间批评确实需要严格限制。",
    sources: [russellSource("第三卷第二十八章〈柏格森〉"), sepSource("Henri Bergson", "bergson")],
  },
  {
    id: "william-james", order: 79, nameZh: "威廉·詹姆斯", nameEn: "William James", greekName: "William James", dates: "1842—1910", active: "1870 年代—1910", places: ["纽约", "剑桥（马萨诸塞）", "哈佛大学"], school: "实用主义／彻底经验主义", figureId: "william-james", chapterIds: ["b3-29"],
    thesis: "观念的意义要由它在经验和行动中造成的差异说明；当证据不能先行决定而选择又不可避免时，信念可以承担实践风险。",
    evidenceCaution: "著作、讲稿和心理学材料充分；“真理就是有用”是过度压缩。詹姆斯要求观念在经验中得到兑现，并不允许任何令人舒服的信念自动成真。",
    lifeSummary: "詹姆斯在跨大西洋艺术、医学和科学教育中成长，经历健康与意志危机后在哈佛建立心理学教学。他的《心理学原理》研究意识流、习惯和注意，后来以实用主义、宗教经验和彻底经验主义连接事实与生活选择。其哲学不是反科学，而是反对科学被误写成封闭的单一世界图景。",
    timeline: [
      { date: "1875", place: "哈佛大学", title: "建立实验心理学教学空间", detail: "常被称为美国早期心理实验室之一，实际功能首先是教学。", certainty: "较可靠" },
      { date: "1890", place: "纽约", title: "出版《心理学原理》", detail: "十二年写成，系统讨论意识流、习惯、注意和自我。", certainty: "较可靠" },
      { date: "1907", place: "纽约", title: "出版《实用主义》", detail: "把皮尔士方法扩展为面向公众的意义与真理理论。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "实用主义准则", en: "pragmatic maxim", definition: "通过一个观念可能造成的具体经验与行动差异澄清其意义。" },
      { zh: "意识流", en: "stream of consciousness", definition: "意识持续变化、带有边缘和选择，不是彼此孤立状态的机械串联。" },
      { zh: "信念意志", en: "will to believe", definition: "当一个选项对当事人是切实的、不可回避的且重大的，而理智证据又不能预先裁决时，詹姆斯允许情感本性参与承诺；这不是任意相信任何有用主张的许可证。" },
    ],
    lineage: { inherited: "承接皮尔士实用方法、休谟经验自然主义、达尔文进化和心理学。", school: "美国实用主义与彻底经验主义的主要代表。", influenced: "影响杜威、宗教哲学、心理学、过程思想和多元主义。", parallel: "与柏格森互相欣赏，都反对静态智性压平经验；詹姆斯更强调选择、验证与多元世界。" },
    comparisons: [
      { target: "休谟", relation: "后世重构", shared: "信念扎根于习惯、情感和生活实践，而非纯演绎证明。", difference: "詹姆斯更积极说明选择如何参与生成可验证的关系。" },
      { target: "柏格森", relation: "同题比较", shared: "经验是流动连续体，概念服务行动却不能穷尽现实。", difference: "柏格森诉诸绵延直觉，詹姆斯以实用后果和彻底经验关系展开。" },
      { target: "约翰·杜威", relation: "影响后继", shared: "思想是环境中解决问题、可由后果修正的活动。", difference: "杜威更系统地转向公共探究、教育和制度民主。" },
    ],
    stars: 5, culturalNotes: [{ kind: "例子", title: "先相信友谊，友谊才可能发生", text: "如果双方都等待对方先证明友善，关系可能永不开始。詹姆斯用这类情境说明某些事实需要信念参与才能成为现实。" }],
    russellView: "罗素尊重詹姆斯的开放、多元和心理洞察，却批评实用主义真理论似乎把“相信有好处”混同“命题为真”，尤其反对以宗教安慰替代证据。",
    modernCorrection: "詹姆斯并非说任意有用信念都真；真理需要在经验、他人和后续后果中持续兑现。罗素的批评更适合某些粗糙口号，而非全部彻底经验主义。",
    sources: [russellSource("第三卷第二十九章〈威廉·詹姆斯〉"), sepSource("William James", "james")],
  },
  {
    id: "dewey", order: 80, nameZh: "约翰·杜威", aliases: ["杜威"], nameEn: "John Dewey", greekName: "John Dewey", dates: "1859—1952", active: "1884—1952", places: ["芝加哥", "纽约", "哥伦比亚大学", "中国"], school: "实用主义／工具主义", figureId: "dewey", chapterIds: ["b3-30"],
    thesis: "认识不是旁观者复制既成世界，而是有机体和共同体在不确定处境中提出问题、试验方案并重组经验的探究。",
    evidenceCaution: "著作与公共活动丰富；“做中学”并非其固定口号，也不意味着取消知识传授。工具主义不是只问短期效率，而要求后果进入更长公共探究。",
    lifeSummary: "杜威从黑格尔主义转向以达尔文、心理学和社会改革为背景的实用主义。在芝加哥实验学校测试课程与民主共同生活，后在哥伦比亚大学长期写作并参与教育、工会、反战和公共调查。他把民主理解为共同经验与沟通方式，而不只是投票制度。",
    timeline: [
      { date: "1894—1904", place: "芝加哥", title: "建立实验学校", detail: "把课程、手工活动、社会合作与心理发展放入同一教育实验。", certainty: "较可靠" },
      { date: "1919—1921", place: "中国", title: "在华讲学", detail: "五四时期广泛讲授教育、民主和社会哲学，形成重要中国接受史。", certainty: "较可靠" },
      { date: "1927", place: "纽约", title: "出版《公众及其问题》", detail: "回应技术社会中公众如何识别共同后果并重新组织民主。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "探究", en: "inquiry", definition: "把不确定处境转化为结构更清楚、能够继续行动的受控过程。" },
      { zh: "工具主义", en: "instrumentalism", definition: "概念和理论是组织行动与预见后果的工具，其价值需由探究表现检验。" },
      { zh: "民主生活方式", en: "democracy as a way of life", definition: "通过沟通、共同经验和可修正制度处理共同后果，不限于选举程序。" },
    ],
    lineage: { inherited: "承接威廉·詹姆斯、皮尔士、黑格尔有机关系和达尔文适应思想。", school: "美国实用主义、工具主义与民主教育。", influenced: "影响教育学、公共哲学、设计研究和参与式民主，也引发进步教育争论。", parallel: "与马克思都反对脱离实践的思想；杜威依赖渐进实验和多元公众，马克思集中结构矛盾与阶级变革。" },
    comparisons: [
      { target: "威廉·詹姆斯", relation: "承接前人", shared: "观念意义和真理必须在经验后果中得到说明。", difference: "杜威把个体选择扩展为问题情境、公共探究与教育制度。" },
      { target: "黑格尔", relation: "后世重构", shared: "个体能力在社会关系和制度中形成。", difference: "杜威拒绝封闭的历史整体，以实验和可修正性替代必然辩证终点。" },
      { target: "罗素", relation: "同题比较", shared: "教育与公共理性应抵抗教条，并服务民主。", difference: "罗素更信形式分析与独立命题真理，杜威更强调探究情境和行动重组。" },
    ],
    stars: 4, culturalNotes: [{ kind: "例子", title: "学校不是社会的准备班，而是社会生活", text: "实验学校让儿童围绕烹饪、制作和合作学习科学与历史，重点不是取消课程，而是让知识重新进入共同问题。" }],
    russellView: "罗素认为杜威哲学具有美国式实践、民主和适应精神，赞赏其教育目标，却担心把真理过度依赖问题解决会削弱独立于人类目的的事实。",
    modernCorrection: "杜威不是把真理降为眼前有用，也不是无结构的儿童中心教育。他强调长期后果、公共验证和教师设计环境；其民主理想仍面临权力不平等问题。",
    sources: [russellSource("第三卷第三十章〈约翰·杜威〉"), sepSource("John Dewey", "dewey")],
  },
  {
    id: "frege", order: 81, nameZh: "弗雷格", nameEn: "Gottlob Frege", greekName: "Friedrich Ludwig Gottlob Frege", dates: "1848—1925", active: "1879—1918", places: ["维斯马", "耶拿大学"], school: "现代逻辑／分析哲学起点", figureId: "frege", chapterIds: ["b3-31"],
    thesis: "逻辑不能再由主词—谓词和心理联想承担；用函数、变量与量词分析命题，可以揭示推理结构并重新追问数学基础。",
    evidenceCaution: "著作和学术生涯可靠；其影响多数在罗素等人发现后扩大。晚年日记中的反民主与反犹内容必须记录，不能由逻辑贡献遮蔽。",
    lifeSummary: "弗雷格长期在耶拿任教，1879 年《概念文字》建立现代谓词逻辑的关键框架。他试图把算术还原为逻辑，并在语言哲学中区分意义与指称。罗素悖论击中《算术基本规律》体系时，他公开承认基础动摇；这个失败也迫使后人重新检查集合、定义和证明的边界。",
    timeline: [
      { date: "1879", place: "哈勒／耶拿", title: "出版《概念文字》", detail: "以二维记号表达量词、条件和函数结构，初期影响有限。", certainty: "较可靠" },
      { date: "1892", place: "耶拿", title: "发表《论意义与指称》", detail: "用晨星／昏星等例子解释同一指称为何具有不同认知价值。", certainty: "较可靠" },
      { date: "1902—1903", place: "耶拿", title: "收到罗素悖论并承认体系危机", detail: "在第二卷附录中坦率记录基础被动摇。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "概念文字", en: "Begriffsschrift / concept-script", definition: "为纯思想设计的形式语言，是现代谓词逻辑的重要起点。" },
      { zh: "意义与指称", en: "sense and reference", definition: "意义是表达式呈现其所指的方式，指称是表达式所指向的对象；二者解释同一性陈述的认知差异。表达式可以有意义而缺少指称，间接语境中的指称也会变化。" },
      { zh: "逻辑主义", en: "logicism", definition: "算术真理可由纯逻辑定义和原则推出的计划。" },
    ],
    lineage: { inherited: "承接莱布尼茨普遍语言理想、十九世纪数学严格化与函数概念。", school: "现代逻辑和分析哲学的奠基人物。", influenced: "直接影响罗素、维特根斯坦、卡尔纳普以及现代语言哲学和数学基础。", parallel: "与黑格尔都试图揭示思想结构；弗雷格以可检查的形式分析反对从含混整体运动推出结论。" },
    comparisons: [
      { target: "莱布尼茨", relation: "后世重构", shared: "希望以普遍符号和逻辑原则澄清推理与数学。", difference: "弗雷格建立量词逻辑的技术系统，并严格区分心理过程与客观思想。" },
      { target: "罗素", relation: "影响后继", shared: "逻辑可揭示语言表面之下的命题结构，并服务数学基础。", difference: "罗素以类型论和摹状词分析回应悖论，改写弗雷格体系。" },
      { target: "黑格尔", relation: "批评关系", shared: "逻辑被赋予超出教科书推理规则的哲学任务。", difference: "弗雷格要求形式明确与真值保存，分析传统由此反对黑格尔式辩证整体。" },
    ],
    stars: 5, culturalNotes: [{ kind: "例子", title: "晨星就是昏星", text: "两个名称都指金星，但发现二者同一仍有知识价值。意义与指称的区分由此进入日常可见的天文例子。" }],
    russellView: "罗素在逻辑分析章把弗雷格视为现代逻辑的决定性先驱，承认自己许多方向受其启发；同时以悖论说明不受限制的逻辑主义基础无法成立。",
    modernCorrection: "弗雷格不仅是罗素的前奏，其语义学和反心理主义具有独立持续影响。评价也必须纳入晚年政治日记所显示的反犹与反民主立场。",
    sources: [russellSource("第三卷第三十一章〈逻辑分析哲学〉"), sepSource("Gottlob Frege", "frege")],
  },
  {
    id: "russell", order: 82, nameZh: "罗素", nameEn: "Bertrand Russell", greekName: "Bertrand Arthur William Russell", dates: "1872—1970", active: "1890 年代—1970", places: ["剑桥", "伦敦", "美国", "威尔士"], school: "逻辑分析哲学／自由主义", figureId: "russell", chapterIds: ["b3-31"],
    thesis: "哲学应利用逻辑分析拆解语言造成的虚假实体和问题，同时以可错、公开和反权威的理性支持科学与个人自由。",
    evidenceCaution: "著作、生平和公共活动极丰富；本站所依原书本身就是罗素在特定战争年代的选择性叙事，他对前人的判断必须与其哲学立场和政治经验共同阅读。",
    lifeSummary: "罗素出身英国贵族家庭，在剑桥与怀特海合作数学基础，因悖论和类型论成为现代逻辑中心人物。他以摹状词理论和逻辑原子主义推动分析哲学，同时长期参与反战、核裁军、教育与自由主义公共论战。哲学精确与政治介入在他身上不是两条无关生涯，而是共同反对不可审查的整体权威。",
    timeline: [
      { date: "1901", place: "剑桥", title: "发现罗素悖论", detail: "不受限制地把性质组成集合会产生自相矛盾，迫使逻辑主义重新规定层级。", certainty: "较可靠" },
      { date: "1903—1913", place: "剑桥", title: "重构数学基础", detail: "发表《数学原则》，与怀特海完成《数学原理》三卷。", certainty: "较可靠" },
      { date: "1918", place: "伦敦", title: "因反战活动入狱", detail: "在狱中写作《数理哲学导论》，展示公共立场的现实代价。", certainty: "较可靠" },
      { date: "1945", place: "英国", title: "出版《西方哲学史》", detail: "战时讲座发展成面向公众的思想史；叙事鲜明、影响巨大，也带有作者自己的哲学和政治判断。", certainty: "较可靠" },
      { date: "1950／1955", place: "斯德哥尔摩／伦敦", title: "获诺贝尔文学奖并推动反核宣言", detail: "以公共写作获奖，后与爱因斯坦等发布反核武器宣言。", certainty: "较可靠" },
    ],
    concepts: [
      { zh: "摹状词理论", en: "theory of descriptions", definition: "把“这个／那个唯一的某物”分析为存在、唯一性和谓述条件。" },
      { zh: "逻辑原子主义", en: "logical atomism", definition: "尝试把复杂事实和命题分析为更简单、逻辑独立的组成。" },
      { zh: "类型论", en: "theory of types", definition: "通过限制表达式可作用的层级避免集合和自指悖论。" },
      { zh: "亲知与描述知识", en: "knowledge by acquaintance and description", definition: "区分直接呈现的对象与通过性质、关系和推论被认识的对象。" },
      { zh: "外在关系", en: "external relations", definition: "关系不必由对象各自的内在性质完全决定；这一立场支撑罗素对观念论整体主义的反驳。" },
      { zh: "逻辑构造", en: "logical construction", definition: "用较清楚、可检验的关系结构替代未经说明的推定实体，而不是另造一种隐藏对象。" },
      { zh: "可错论", en: "fallibilism", definition: "本站用“可错论”概括罗素长期强调的认识态度：经验信念应按证据保留可修正性，而逻辑和数学命题另需区分讨论。它不是罗素在全部时期以同一方式建立的单一学说。" },
    ],
    lineage: { inherited: "承接弗雷格逻辑、皮亚诺符号、英国经验主义和摩尔反观念论。", school: "二十世纪逻辑分析哲学的重要奠基者，也是自由社会主义公共知识分子。", influenced: "影响维特根斯坦、逻辑实证主义、语言分析、数学哲学和现代公共理性。", parallel: "与杜威都支持教育、民主和反教条；罗素更坚持独立事实与形式逻辑，杜威更强调问题情境和探究过程。" },
    comparisons: [
      { target: "弗雷格", relation: "承接前人", shared: "现代逻辑能够澄清数学基础和语言的真实结构。", difference: "罗素以悖论、类型论和摹状词改造弗雷格逻辑主义。" },
      { target: "黑格尔", relation: "批评关系", shared: "哲学要说明部分与整体、关系与对象的结构。", difference: "罗素拒绝内在关系和整体先于部分，以分析和外在关系反对观念论。" },
      { target: "马克思", relation: "批评关系", shared: "经济权力和阶级不平等需要社会变革。", difference: "罗素反对历史必然、革命专政与正统思想，主张自由社会主义和权力分散。" },
      { target: "休谟", relation: "后世重构", shared: "经验知识需要说明从直接经验到因果、对象和未来预期的推论资格。", difference: "罗素借关系逻辑和科学结构重写经验主义，不把一切联结都交给心理习惯。" },
      { target: "约翰·杜威", relation: "同题比较", shared: "知识应公开检验并保持可修正，民主需要教育和反教条习惯。", difference: "罗素从独立事实和逻辑形式理解客观性；杜威从问题情境、行动后果和共同探究理解知识。" },
    ],
    stars: 5, culturalNotes: [{ kind: "轶事", title: "“现任法国国王是秃头”", text: "这个看似荒唐的句子成了分析哲学名场面：问题不在法国有没有国王，而在语法怎样诱使我们假设一个对象。" }],
    russellView: "第三十一章最接近罗素对自身方法的定位：现代逻辑打破亚里士多德主谓框架，关系和形式分析能够消除旧形而上学的许多伪问题；哲学仍保留探索未知可能性的任务。",
    modernCorrection: "逻辑分析不是哲学唯一合法方法，罗素本人的理论也多次修订。《西方哲学史》的自由主义主线、人物褒贬和欧洲中心范围都需作为有立场的二十世纪叙事审查。",
    sources: [russellSource("第三卷第三十一章〈逻辑分析哲学〉"), sepSource("Bertrand Russell", "russell")],
  },
];
