import type { PhilosopherProfile, PhilosopherSource } from "./philosopher-data";

const russellSource = (chapter: string): PhilosopherSource => ({
  label: `罗素《西方哲学史》${chapter}`,
  kind: "原书",
  url: "https://www.russell-j.com/cool/HWP_1945.pdf",
});

const sepSource = (label: string, slug: string): PhilosopherSource => ({
  label: `Stanford Encyclopedia · ${label}`,
  kind: "补充",
  url: `https://plato.stanford.edu/entries/${slug}/`,
});

export const medievalProfiles: PhilosopherProfile[] = [
  {
    id: "philo-alexandria", order: 30, nameZh: "亚历山大的斐洛", nameEn: "Philo of Alexandria", greekName: "Φίλων ὁ Ἀλεξανδρεύς", dates: "约前 20—约 50", active: "公元 1 世纪前半叶", places: ["亚历山大里亚", "罗马"], school: "希腊化犹太哲学", figureId: "philo-alexandria", chapterIds: ["b2-01"],
    thesis: "用寓意解释把《摩西五经》与柏拉图主义、斯多葛主义相接：超越的上帝通过逻各斯与诸能力同可理解世界发生关系。",
    evidenceCaution: "斐洛有大量希腊文著作传世，思想证据相对充足；生平却主要只由其作品与约瑟夫斯重建，年代和私人经历多为推定。",
    lifeSummary: "斐洛出身亚历山大里亚富裕犹太家庭，既接受希腊教育，也把犹太经文视为最高权威。约 38—41 年，他参加赴罗马使团，向卡利古拉申诉亚历山大里亚犹太人的处境。他不是后来意义的基督教思想家，却为‘经文怎样与希腊哲学共存’提供了影响深远的解释模型。",
    timeline: [
      { date: "约前 20", place: "亚历山大里亚", title: "出生", detail: "出生年代由其公元 40 年左右自称年长者反推。", certainty: "推定" },
      { date: "约 38—41", place: "罗马", title: "参加申诉使团", detail: "代表亚历山大里亚犹太社群面见卡利古拉，后在《致盖乌斯使团》中记述事件。", certainty: "较可靠" },
      { date: "1 世纪中叶", place: "亚历山大里亚", title: "完成主要释经著作", detail: "以希腊文写作经文注释、哲学论文和历史记述。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "经文与哲学", question: "摩西经文与希腊哲学看似冲突时，如何同时保存启示权威与理性解释？", start: "经文用人格化叙事谈论上帝，哲学却要求不变、非物质的第一原则。", steps: ["区分经文字面层与寓意层", "把人物和事件解释为灵魂能力与德性过程", "以逻各斯说明超越者与世界之间的中介", "将希腊哲学视为对摩西智慧的部分发现"], conclusion: "经文的哲学意义可通过寓意解释显现；上帝保持超越，而逻各斯、理念和能力说明创造与认识。" }],
    concepts: [
      { zh: "逻各斯", en: "Logos", definition: "上帝的理性、话语与创造范型；斐洛的用法并不总是一致，不能简单等同于后来基督教的第二位格。" },
      { zh: "寓意解释", en: "allegorical interpretation", definition: "在不取消字面叙事的前提下，把经文人物与事件读作灵魂、德性和宇宙结构。" },
      { zh: "神圣能力", en: "divine powers", definition: "上帝作用于世界的可理解方式，如创造与治理；用于维护神的超越性。" },
    ],
    lineage: { inherited: "继承犹太经文传统，也吸收柏拉图的可知范型、斯多葛的逻各斯和希腊寓意释经。", school: "希腊化犹太哲学的代表，在一神经文与希腊形而上学之间建立系统接口。", influenced: "其语言和释经方法进入奥利金、教父传统与中世纪负神学，但具体传递路径并非处处可证。", parallel: "与新约《约翰福音》都使用逻各斯语言，但二者关系与直接影响仍有争论。" },
    comparisons: [
      { target: "柏拉图", relation: "承接前人", shared: "可理解范型高于感官世界。", difference: "斐洛把范型置入独一上帝的创造活动，并以摩西经文统摄哲学。" },
      { target: "奥利金", relation: "影响后继", shared: "用希腊哲学和寓意解释阅读经文。", difference: "奥利金在基督论、三位一体与救赎框架中重新组织这套方法。" },
      { target: "迈蒙尼德", relation: "同题比较", shared: "都调和犹太启示与哲学理性，并警惕把上帝人格化。", difference: "斐洛以中期柏拉图主义为主；迈蒙尼德主要面对亚里士多德主义与伊斯兰哲学。" },
    ],
    stars: 3, culturalNotes: [{ kind: "生活印象", title: "一位真正参加过政治使团的哲学解释者", text: "斐洛并非只在书斋里调和传统。他曾作为犹太代表赴罗马申诉，使其关于共同体、律法与帝国的思考带有直接政治经验。" }],
    russellView: "罗素把斐洛称为希腊思想影响犹太人的最佳例证，着重介绍他对创世、逻各斯和柏拉图理念的调和，并把他置于基督教神学形成的前史。",
    modernCorrection: "斐洛不是把两套现成体系机械拼合；现代研究更重视他的犹太身份、释经实践和著作体裁差异。‘逻各斯’在不同文本中承担多种功能，不宜压成单一教义。",
    sources: [russellSource("第二卷第一章〈犹太人的宗教发展〉"), sepSource("Philo of Alexandria", "philo")],
  },
  {
    id: "origen", order: 31, nameZh: "奥利金", nameEn: "Origen of Alexandria", greekName: "Ὠριγένης", dates: "约 185—约 253", active: "3 世纪前半叶", places: ["亚历山大里亚", "凯撒利亚", "罗马"], school: "亚历山大里亚教父哲学", figureId: "origen", chapterIds: ["b2-02"],
    thesis: "基督教信仰需要系统的理性阐释：经文具有多层意义，受造理性灵魂凭自由转向或远离上帝，整个宇宙史因此成为教育与复归过程。",
    evidenceCaution: "著作数量巨大但大量只存拉丁译本，且译者有时为避争议而改写；后世定罪也使‘奥利金本人’与‘奥利金主义’必须区分。",
    lifeSummary: "奥利金成长于亚历山大里亚的基督教家庭，父亲在迫害中殉道。他从教学、文本校勘和释经出发，后来迁居凯撒利亚建立教学与藏书中心。《论首要原理》是早期基督教最雄心勃勃的系统神学之一，《驳塞尔苏斯》则正面回应异教哲学批评。",
    timeline: [
      { date: "约 202", place: "亚历山大里亚", title: "父亲殉道", detail: "塞普蒂米乌斯·塞维鲁时期迫害塑造了其禁欲与护教生活。", certainty: "较可靠" },
      { date: "约 230 年代", place: "凯撒利亚", title: "迁居并任教", detail: "与亚历山大主教冲突后在凯撒利亚讲学、释经并受任圣职。", certainty: "较可靠" },
      { date: "约 249—253", place: "凯撒利亚／推罗", title: "受迫害与去世", detail: "德西乌斯迫害中受刑，数年后去世；具体地点和年份略有分歧。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "启示的理性结构", question: "经文中的矛盾、拟人叙事与哲学难题，能否被理解为同一救赎秩序？", start: "若上帝良善而理性，经文与宇宙就不应只是任意命令和字面冲突。", steps: ["区分经文的身体、灵魂与精神意义", "以自由意志解释理性受造物的差异", "把物质世界理解为教育与医治场域", "在基督—逻各斯中说明知识与复归"], conclusion: "哲学推理可以服务于信仰，但必须接受经文和教会规则约束；救赎是理性受造物重新面向上帝的过程。" }],
    concepts: [
      { zh: "三重经义", en: "threefold sense of scripture", definition: "经文具有身体、灵魂、精神层次；困难文本会迫使读者越过字面寻找更深意义。" },
      { zh: "自由意志", en: "free choice", definition: "灵魂差异不是上帝偏私造成，而源于受造理性者的不同选择；这是神义论与教育宇宙论的支点。" },
      { zh: "复归", en: "restoration / apokatastasis", definition: "受造秩序最终复归上帝的强烈希望；是否意味着所有理性存在必然得救，文本与解释传统都有争议。" },
    ],
    lineage: { inherited: "承接斐洛式寓意释经、柏拉图主义灵魂论与早期教会的信仰规则。", school: "亚历山大里亚基督教哲学，把释经、形而上学、自由意志和护教组织成体系。", influenced: "影响卡帕多西亚教父、拉丁教父和中世纪释经，也因后世奥利金主义争论而被选择性接受。", parallel: "与普罗提诺同处三世纪柏拉图主义环境，却在创造、人格自由、基督与复活上走向不同体系。" },
    comparisons: [
      { target: "亚历山大的斐洛", relation: "承接前人", shared: "以寓意解释连接经文与希腊哲学。", difference: "奥利金把方法置于基督教的基督论、教会与救赎史中。" },
      { target: "普罗提诺", relation: "同题比较", shared: "灵魂下降、多层实在与向最高者复归。", difference: "奥利金坚持创造、自由受造物和基督事件；普罗提诺以流溢和观照解释秩序。" },
      { target: "奥古斯丁", relation: "影响后继", shared: "借柏拉图主义处理基督教的恶、灵魂和解释问题。", difference: "奥古斯丁对原罪、恩典与历史共同体的强调更强，也不接受奥利金的一些宇宙论推测。" },
    ],
    stars: 4, culturalNotes: [{ kind: "轶事", title: "把一生变成注释工程", text: "古代传记把奥利金写成几乎不停口授、校勘和讲课的人。《六文本合参》把多种希伯来经文与希腊译本并排列出，是早期文本批判的惊人项目。", caveat: "关于其极端禁欲行为的著名传说来源较晚，现代学者并不一致采信。" }],
    russellView: "罗素把奥利金视为早期教会中最重要、最有哲学头脑的人物之一，强调他借希腊哲学形成系统神学，也指出其灵魂先存和普遍复归等观点后来被判为异端。",
    modernCorrection: "不能只用后世定罪倒推奥利金。他的许多大胆命题是探索性假设，且传世拉丁译本可能被修订；现代研究也更强调其经文校勘、讲道与教会实践。",
    sources: [russellSource("第二卷第二章〈基督教最初的四个世纪〉"), sepSource("Origen", "origen")],
  },
  {
    id: "ambrose", order: 32, nameZh: "米兰的安布罗斯", nameEn: "Ambrose of Milan", greekName: "Aurelius Ambrosius", dates: "约 339—397", active: "374—397", places: ["特里尔", "米兰"], school: "拉丁教父／教会政治思想", figureId: "ambrose", chapterIds: ["b2-03"],
    thesis: "皇帝属于教会而非凌驾于教会；主教可以用礼仪纪律和道德权威限制基督教皇权。",
    evidenceCaution: "书信、讲道和同代记载较丰富，但著名冲突常由安布罗斯一方叙述；其意义主要是教会—国家关系与拉丁神学，不应误写成完整形而上学体系。",
    lifeSummary: "安布罗斯原是罗马帝国官员，尚未受洗便在米兰主教选举冲突中被拥立，随即受洗、受任。他与皇后尤斯蒂娜及皇帝狄奥多西的冲突，让主教权威第一次以高度戏剧化方式约束宫廷；他的讲道也促成奥古斯丁重新理解基督教经文。",
    timeline: [
      { date: "374", place: "米兰", title: "由总督成为主教", detail: "介入教派冲突时被群众推举，短期内完成受洗与受任。", certainty: "较可靠" },
      { date: "386", place: "米兰", title: "抵抗宫廷索取教堂", detail: "拒绝把教堂交给阿里乌派宫廷使用，以群众礼拜维护主教管辖。", certainty: "较可靠" },
      { date: "390", place: "米兰", title: "要求狄奥多西悔罪", detail: "帖撒罗尼迦屠杀后拒绝照常举行圣礼，事件细节仍需结合书信谨慎重建。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "教会与皇权", question: "信奉基督教的皇帝犯下公共罪行时，谁能对他作道德审判？", start: "皇帝掌握法律与军队，但圣礼与教会纪律不应成为宫廷工具。", steps: ["区分政治统治与圣礼管辖", "主张皇帝作为信徒也受教会纪律约束", "用拒绝共融迫使权力回应公共罪责"], conclusion: "皇帝在教会之内，不在教会之上；政治权力不能自动取得宗教与道德上的无责地位。" }],
    concepts: [
      { zh: "教会自主", en: "ecclesial autonomy", definition: "圣所、教义与圣礼纪律不由皇帝随意处分。" },
      { zh: "主教劝诫", en: "episcopal admonition", definition: "主教以公共教导和圣礼纪律纠正统治者，而非直接取代行政权。" },
      { zh: "皇帝在教会内", en: "the emperor within the Church", definition: "基督教皇帝仍是受规范的信徒；这一公式深刻影响西方政教权力想象。" },
    ],
    lineage: { inherited: "继承尼西亚正统、罗马公共职位经验和西塞罗式德性语言。", school: "拉丁教父传统中的教会政治思想家与讲道者。", influenced: "影响奥古斯丁的皈依与释经，也为中世纪教皇和主教限制世俗权力提供经典先例。", parallel: "与大格列高利都把主教职位塑造成公共治理角色，但安布罗斯面对仍强大的晚期罗马皇权。" },
    comparisons: [
      { target: "奥古斯丁", relation: "影响后继", shared: "拉丁基督教、寓意释经与公共教会。", difference: "安布罗斯主要以讲道和主教行动示范权威；奥古斯丁把意志、恩典与历史写成更完整理论。" },
      { target: "大格列高利", relation: "影响后继", shared: "主教承担教义、礼仪与公共治理责任。", difference: "格列高利在西罗马帝国崩解后更直接承担行政与救济。" },
      { target: "帕多瓦的马西略", relation: "同题比较", shared: "都处理宗教权威与政治权力的边界。", difference: "安布罗斯以主教纪律约束皇帝；马西略反对教皇强制权并把政治立法权归于公民共同体。" },
    ],
    stars: 2, culturalNotes: [{ kind: "轶事", title: "让皇帝站到忏悔者的位置", text: "安布罗斯要求狄奥多西为帖撒罗尼迦屠杀公开悔罪，成为西方历史中宗教权威约束君主最常被讲述的场景之一。", caveat: "后世艺术常把事件画成主教在教堂门口挡驾，实际过程可能主要通过书信与礼仪协商完成。" }],
    russellView: "罗素把安布罗斯视为三位教会博士中最具政治重要性者，认为他所确立的教会独立与主教约束皇帝原则具有革命性。",
    modernCorrection: "这一关系不是现代意义的政教分离。安布罗斯既需要帝国支持正统，也以教会权威介入公共事务；‘教会胜过国家’不足以概括复杂互动。",
    sources: [russellSource("第二卷第三章〈三位教会博士〉"), { label: "Britannica · Saint Ambrose", kind: "补充", url: "https://www.britannica.com/biography/Saint-Ambrose" }],
  },
  {
    id: "jerome", order: 33, nameZh: "哲罗姆", nameEn: "Jerome", greekName: "Eusebius Sophronius Hieronymus", dates: "约 347—420", active: "4 世纪末至 5 世纪初", places: ["斯特里顿", "罗马", "伯利恒"], school: "拉丁教父／经文翻译", figureId: "jerome", chapterIds: ["b2-03"],
    thesis: "拉丁基督教必须尽可能回到经文语言与文本差异本身；翻译、语言学习和禁欲生活共同构成解释权威。",
    evidenceCaution: "书信与著作很多，但其论战文风强烈、对手形象常被夸张。武加大译本也不是一人一次完成的统一文本，后世修订层累复杂。",
    lifeSummary: "哲罗姆受过古典修辞教育，先在罗马从事教会工作，后定居伯利恒主持修院和翻译。他学习希伯来语，以希伯来文本重译旧约，并修订拉丁福音书。其工作塑造了西方教会千余年的圣经语言，也制造了‘古典文学是否妨碍基督徒生活’的持续张力。",
    timeline: [
      { date: "约 382—385", place: "罗马", title: "为达玛苏教皇工作", detail: "修订福音书拉丁文本，并参与罗马禁欲社群。", certainty: "较可靠" },
      { date: "386", place: "伯利恒", title: "定居修院", detail: "在保拉资助下建立修院、旅舍与学习中心。", certainty: "较可靠" },
      { date: "约 390—405", place: "伯利恒", title: "由希伯来文翻译旧约", detail: "逐步形成后来武加大传统的核心部分。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "翻译与权威", question: "当希腊、希伯来和旧拉丁文本不一致时，基督徒应以什么校正文义？", start: "教会通行译本彼此有差异，字面错误会改变解释与争论。", steps: ["比较多种语言文本", "把希伯来文本视为旧约的重要校准依据", "保留教会用语同时重译难句", "以注释解释译法和历史语境"], conclusion: "翻译不是透明抄写，而是需要语言学、文本批判与共同体判断的解释工作。" }],
    concepts: [
      { zh: "希伯来真本", en: "Hebraica veritas", definition: "用希伯来文本校准旧约拉丁译文的原则，并不意味着哲罗姆拥有现代文本批判方法。" },
      { zh: "武加大译本", en: "Vulgate", definition: "以哲罗姆翻译和修订为核心、后世逐步定型的拉丁圣经传统。" },
      { zh: "禁欲学术", en: "ascetic scholarship", definition: "把语言学习、抄写、注释和修院纪律视为同一种基督徒实践。" },
    ],
    lineage: { inherited: "继承古典语文学、奥利金的经文校勘传统与东方修道生活。", school: "拉丁教父中的翻译家、注释家和禁欲论战者。", influenced: "武加大成为西欧神学、礼仪和文学的基础文本；其修院学术理想也长期延续。", parallel: "与罗杰·培根都强调原文语言对知识纠错的重要性，但所处学术制度和目标不同。" },
    comparisons: [
      { target: "奥利金", relation: "承接前人", shared: "以多语文本比较与注释处理经文。", difference: "哲罗姆一面依赖奥利金，一面又在奥利金主义争论中与其遗产保持距离。" },
      { target: "奥古斯丁", relation: "同题比较", shared: "都维护拉丁教会的经文解释与禁欲伦理。", difference: "哲罗姆优先语言和文本；奥古斯丁更强调符号、爱与教会阅读规则，并曾质疑重译造成的礼仪冲突。" },
      { target: "罗杰·培根", relation: "影响后继", shared: "错误翻译会系统性损害知识。", difference: "培根把语言改革扩展到大学哲学、科学与传教计划。" },
    ],
    stars: 2, culturalNotes: [{ kind: "轶事", title: "书房里的狮子", text: "西方艺术常把哲罗姆画成在书房工作的老人，脚边伏着一头狮子；狮子拔刺报恩的故事强化了他既严厉又隐居的公共形象。", caveat: "这个故事原本属于另一位圣人，后来才移植到哲罗姆传说。" }],
    russellView: "罗素认为哲罗姆的历史重要性主要在武加大译本和修道运动，而不是原创哲学；他也用哲罗姆对古典文学的矛盾态度呈现基督教与古代文化的张力。",
    modernCorrection: "‘武加大是哲罗姆独自完成的一本书’是过度简化。不同卷的翻译来源和修订历史不同；他的希伯来文能力很重要，但仍受当时犹太教师和希腊传统帮助。",
    sources: [russellSource("第二卷第三章〈三位教会博士〉"), { label: "Britannica · St. Jerome", kind: "补充", url: "https://www.britannica.com/biography/Saint-Jerome" }],
  },
  {
    id: "augustine", order: 34, nameZh: "奥古斯丁", nameEn: "Augustine of Hippo", greekName: "Aurelius Augustinus", dates: "354—430", active: "386—430", places: ["塔加斯特", "迦太基", "米兰", "希波"], school: "拉丁教父／基督教柏拉图主义", figureId: "augustine", chapterIds: ["b2-03", "b2-04"],
    thesis: "确定性从正在怀疑和记忆的内在主体展开；恶不是实体而是善的缺失，人的意志却因错误之爱受缚，必须在恩典和历史共同体中重新定向。",
    evidenceCaution: "著作与书信极丰富，但《忏悔录》是神学自传而非中性履历；其思想跨五十年变化明显，不能把晚期恩典论无差别投射到早期作品。",
    lifeSummary: "奥古斯丁出生于北非，经历摩尼教、怀疑主义和新柏拉图主义，386 年在米兰皈依，后成为希波主教。他在罗马帝国西部危机中处理个人意志、时间、记忆、恶、恩典、教会与政治秩序，成为拉丁中世纪最强大的共同语言之一。",
    timeline: [
      { date: "354", place: "塔加斯特", title: "出生", detail: "成长于拉丁化北非家庭，母亲莫妮卡是基督徒。", certainty: "较可靠" },
      { date: "386—387", place: "米兰", title: "皈依并受洗", detail: "在安布罗斯讲道、新柏拉图著作和个人危机共同作用下改变生活。", certainty: "较可靠" },
      { date: "395/396", place: "希波", title: "成为主教", detail: "此后参与多纳徒派、伯拉纠派等长期争论。", certainty: "较可靠" },
      { date: "430", place: "希波", title: "围城中去世", detail: "汪达尔人围攻希波期间去世。", certainty: "较可靠" },
    ],
    inquiries: [
      { object: "时间与意识", question: "过去已不在、未来尚未来，时间怎样仍能被测量？", start: "日常说长短时间，却无法把过去未来当作现成物体观察。", steps: ["把过去定位为现在的记忆", "把未来定位为现在的期待", "把当下过程定位为注意", "用心灵的延展解释时间经验"], conclusion: "被测量的是心灵中记忆、注意与期待的延展；时间问题由宇宙对象转入意识结构。" },
      { object: "恶与意志", question: "若上帝全善且创造万物，恶从哪里来？", start: "把恶当作独立实体会限制上帝，把一切归给上帝又似乎取消责任。", steps: ["把存在本身理解为善", "将恶解释为秩序和善的缺失", "追踪意志由较高善转向较低善", "以恩典说明受缚意志的医治"], conclusion: "恶没有独立本体，却通过意志失序产生真实损害；自由、习惯、原罪和恩典构成张力。" },
    ],
    concepts: [
      { zh: "内在确定性", en: "inner certainty", definition: "即使受骗或怀疑，正在思考、生活和记忆的主体仍不能同时被取消。" },
      { zh: "恶是善的缺失", en: "privation of good", definition: "恶不是与善对等的实体，而是受造物应有秩序、形式或善的败坏。" },
      { zh: "爱的秩序", en: "order of love", definition: "伦理的核心不是有没有爱，而是爱什么、以何种次序爱；失序之爱形成支配欲。" },
      { zh: "两个城", en: "two cities", definition: "由两种爱组织的历史共同体：爱上帝至忘我，与爱自己至蔑视上帝；不等同于可见教会和国家。" },
    ],
    lineage: { inherited: "承接保罗、安布罗斯与新柏拉图主义，并把古典修辞和怀疑论问题带入基督教。", school: "拉丁基督教哲学的核心人物，连接古代内在性、教父神学和中世纪争论。", influenced: "决定安瑟伦、波那文图拉、宗教改革乃至近代内在性讨论的基本问题表。", parallel: "与阿奎那都系统处理信仰与理性，但奥古斯丁更从内在照明、意志和历史经验展开。" },
    comparisons: [
      { target: "普罗提诺", relation: "承接前人", shared: "由内在上升至非物质实在，并把恶理解为缺失。", difference: "奥古斯丁坚持创造、人格上帝、历史启示和意志责任，拒绝把救赎化约为纯粹观照。" },
      { target: "坎特伯雷的安瑟伦", relation: "影响后继", shared: "信仰寻求理解，理性在信仰内部工作。", difference: "安瑟伦以更紧缩的必然性论证重写上帝存在与救赎问题。" },
      { target: "托马斯·阿奎那", relation: "影响后继", shared: "基督教创造论、恶的缺失和恩典伦理。", difference: "阿奎那以亚里士多德的形式—质料、能力—实现和自然目的论重构体系。" },
    ],
    stars: 5, culturalNotes: [{ kind: "名言", title: "“给我贞洁和节制——但不要现在”", text: "《忏悔录》用这句自嘲概括意志分裂：人可能清楚知道何为更好的生活，却仍希望改变再晚一点发生。" }],
    russellView: "罗素把奥古斯丁视为柏拉图与十三世纪之间最伟大的基督教哲学家，尤其重视其时间理论、历史哲学与教会政治影响，同时严厉批评其原罪、预定和宗教强制观。",
    modernCorrection: "罗素常以自由主义尺度压缩奥古斯丁的牧灵、释经和论战语境。现代研究强调其思想阶段差异，也提醒‘两个城’不是教会与国家的简单二分。",
    sources: [russellSource("第二卷第三至四章〈三位教会博士〉／〈圣奥古斯丁的哲学与神学〉"), sepSource("Saint Augustine", "augustine")],
  },
  {
    id: "boethius", order: 35, nameZh: "波爱修斯", nameEn: "Boethius", greekName: "Anicius Manlius Severinus Boethius", dates: "约 477—524", active: "6 世纪初", places: ["罗马", "拉文纳", "帕维亚"], school: "晚期古代拉丁哲学", figureId: "boethius", chapterIds: ["b2-05"],
    thesis: "幸福不能依赖命运可夺走的外物；天意在永恒当下中认识一切，而受造者仍按自身方式自由行动。",
    evidenceCaution: "著作和公职记录较可靠，但监禁、审判与死亡细节来自立场不同的材料。《哲学的慰藉》刻意少用基督教语言，不足以证明作者放弃信仰。",
    lifeSummary: "波爱修斯出身罗马元老贵族，在东哥特王狄奥多里克统治下任高官。他计划把柏拉图、亚里士多德的作品与解释传统译成拉丁文，虽未完成，却把逻辑、音乐与数论术语送入中世纪。因政治指控入狱后，他写成哲学对话体《哲学的慰藉》。",
    timeline: [
      { date: "约 510", place: "罗马／拉文纳", title: "出任执政官", detail: "进入东哥特王国最高行政层，同时持续翻译和注释。", certainty: "较可靠" },
      { date: "522", place: "拉文纳", title: "两个儿子同任执政官", detail: "家族政治地位达到高峰。", certainty: "较可靠" },
      { date: "523—524", place: "帕维亚附近", title: "监禁、写作与处决", detail: "被控叛国和魔法等罪名；审判是否公正长期有争议。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "先知与自由", question: "若上帝无误地知道未来，人还可能不那样行动吗？", start: "无误知识似乎把未来变成必然事实。", steps: ["区分事物自身的单纯必然与条件必然", "区分时间中的预见与永恒中的同时观看", "让知识方式取决于认识者而非对象被强迫", "保留行动由理性主体产生的自愿性"], conclusion: "上帝不是提前猜中未来，而在永恒当下认识时间全体；被认识不等于被知识强迫。" }],
    concepts: [
      { zh: "命运之轮", en: "wheel of Fortune", definition: "外在地位、财富和权力不断翻转；把幸福系于轮缘就必然不稳。" },
      { zh: "永恒", en: "eternity", definition: "对无限生命的完整、同时占有，不只是持续无限长时间。" },
      { zh: "共相问题", en: "problem of universals", definition: "其波菲利导论译注把种属究竟独立存在、存在于事物或只在思想中的问题传给拉丁中世纪。" },
    ],
    lineage: { inherited: "继承柏拉图主义、亚里士多德逻辑和晚期古代自由技艺教育。", school: "晚期古代向拉丁中世纪的关键中介，兼具哲学翻译、逻辑和基督教神学。", influenced: "其逻辑教材和《慰藉》长期成为中世纪学校核心文本，并启动共相与先知自由争论。", parallel: "与奥古斯丁都从时间与永恒处理神知，但波爱修斯用更技术化的模态区分。" },
    comparisons: [
      { target: "亚里士多德", relation: "承接前人", shared: "逻辑范畴、命题与论证是哲学教育基础。", difference: "波爱修斯通过翻译注释把部分亚里士多德转入拉丁基督教世界。" },
      { target: "彼得·阿伯拉尔", relation: "影响后继", shared: "共相、语言与逻辑推理问题。", difference: "阿伯拉尔在十二世纪扩展语义与辩证法，拥有更丰富的拉丁逻辑材料。" },
      { target: "奥卡姆的威廉", relation: "影响后继", shared: "逻辑语言和共相问题。", difference: "奥卡姆把唯名论与心灵语言理论推进到远超波爱修斯导论的问题规模。" },
    ],
    stars: 4, culturalNotes: [{ kind: "生活印象", title: "牢房里由“哲学女士”来访", text: "《哲学的慰藉》开篇让一位威严的哲学女士赶走诗歌缪斯，与被判死刑的作者对话。抽象论证因此具有戏剧和自我治疗的形式。" }],
    russellView: "罗素把波爱修斯称为从古代世界通向中世纪的桥梁，认为《慰藉》的柏拉图气质和翻译事业使他在之后数百年拥有异常大的影响。",
    modernCorrection: "把波爱修斯简单称为‘最后的罗马人’会遮蔽东哥特意大利的文化连续性；《慰藉》不点名基督并不等于其神学著作不真或临终改宗。",
    sources: [russellSource("第二卷第五章〈第五和第六世纪〉"), sepSource("Anicius Manlius Severinus Boethius", "boethius")],
  },
  {
    id: "benedict", order: 36, nameZh: "努西亚的本尼狄克", nameEn: "Benedict of Nursia", greekName: "Benedictus Nursiae", dates: "约 480—约 547", active: "6 世纪前半叶", places: ["努西亚", "苏比亚科", "卡西诺山"], school: "西方修道制度", figureId: "benedict", chapterIds: ["b2-06"],
    thesis: "稳定共同生活以节制、服从、祈祷、阅读和劳动组织日常，使德性不依赖英雄式瞬间，而由可持续制度养成。",
    evidenceCaution: "唯一连续生平主要来自大格列高利约半世纪后写的圣人传，奇迹很多；《圣本尼狄克规程》文本可靠，但作者生平与早期传播仍有争论。",
    lifeSummary: "本尼狄克不是以论证著称的哲学家，而是通过一部短规程塑造生活形式。他先在苏比亚科隐修，后在卡西诺山建立团体。《规程》以院长、共同财产、固定作息、诵读、接待与劳动，把晚期古代禁欲理想转为可复制制度。",
    timeline: [
      { date: "约 500", place: "苏比亚科", title: "隐修与形成团体", detail: "具体故事主要见于大格列高利《对话录》，年代为推定。", certainty: "传统记载" },
      { date: "约 529", place: "卡西诺山", title: "建立修院", detail: "传统纪年广泛采用，但没有同期文件可精确确认。", certainty: "传统记载" },
      { date: "6 世纪中叶", place: "卡西诺山", title: "形成《规程》", detail: "文本吸收更早《师傅规程》等传统，后来逐渐成为西欧修院标准。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "共同生活", question: "普通人怎样在长年共同生活中持续训练欲望，而不是依赖少数极端苦行者？", start: "孤独苦行可能过度，松散团体又容易受财产、权力和情绪破坏。", steps: ["要求稳定居所和共同规程", "让院长权威受规程、咨询与责任约束", "以固定祈祷和阅读划分时间", "根据年龄、健康和季节调节劳动与饮食"], conclusion: "德性成为日复一日的制度实践；克制并非最大痛苦，而是可持续、共同且有尺度的生活。" }],
    concepts: [
      { zh: "稳定", en: "stabilitas", definition: "承诺留在具体共同体，不以不断迁徙逃避关系和纪律。" },
      { zh: "服从", en: "obedientia", definition: "通过倾听规程、院长与共同体训练自我意志，同时要求权威对灵魂负责。" },
      { zh: "有尺度的规程", en: "discretio", definition: "规程按体力与处境调节要求，避免把极端苦行当作普遍标准。" },
    ],
    lineage: { inherited: "继承埃及、叙利亚与高卢修道传统以及《师傅规程》。", school: "西方共同修道制度的代表，影响主要通过生活规则而非抽象体系。", influenced: "数世纪后在加洛林改革中成为西欧主导规程，保存阅读、抄写和教育制度。", parallel: "与斯多葛生活训练都用日常操练重塑欲望，但本尼狄克以礼仪共同体、服从和恩典为中心。" },
    comparisons: [
      { target: "哲罗姆", relation: "承接前人", shared: "禁欲生活、阅读与共同体纪律。", difference: "哲罗姆以翻译和论战著称；本尼狄克把修道经验压缩为可复制规程。" },
      { target: "大格列高利", relation: "影响后继", shared: "修道生活与教会治理相互支持。", difference: "格列高利通过传记、教皇行政和传教把本尼狄克形象推向整个西欧。" },
      { target: "爱比克泰德", relation: "同题比较", shared: "自由需要持续训练欲望、判断和行为。", difference: "本尼狄克把训练放入共同礼仪与服从；爱比克泰德以个体理性角色和可控判断为核心。" },
    ],
    stars: 2, culturalNotes: [{ kind: "生活印象", title: "“祈祷与工作”背后的规程生活", text: "人们常用“祈祷并工作”概括本笃会生活。准确地说，这句口号成形较晚，但确实抓住规程把礼仪、阅读、手工劳动和接待客人织成一天的方式。", caveat: "这句拉丁口号并非《圣本尼狄克规程》原句。" }],
    russellView: "罗素重视本尼狄克并非因为原创哲学，而因其规程把修道运动变成稳定制度，在战争和行政崩解中保存了纪律、学习与跨地区组织。",
    modernCorrection: "‘修道院独自保存文明’过于浪漫化，也忽略拜占庭、伊斯兰世界、城市与家庭网络。规程在本尼狄克死后数百年才取得西欧主导地位。",
    sources: [russellSource("第二卷第六章〈圣本尼狄克与大格列高利〉"), { label: "Britannica · St. Benedict", kind: "补充", url: "https://www.britannica.com/biography/Saint-Benedict-of-Nursia" }],
  },
  {
    id: "gregory-great", order: 37, nameZh: "大格列高利", nameEn: "Gregory the Great", greekName: "Gregorius Magnus", dates: "约 540—604", active: "590—604", places: ["罗马", "君士坦丁堡"], school: "拉丁教父／教牧政治", figureId: "gregory-great", chapterIds: ["b2-06"],
    thesis: "治理的正当性表现为照料灵魂与脆弱者的负担；理想领导者必须在默观与行动、谦卑与纠正之间维持张力。",
    evidenceCaution: "书信和著作保存丰富，行政行动也可考；但《对话录》奇迹叙事的作者、体裁与史实价值长期有争论。",
    lifeSummary: "格列高利出身罗马元老家庭，做过城市长官，后把家宅改为修院。590 年成为教皇时，罗马面临伦巴第战争、饥荒和帝国行政衰弱。他谈判、救济、管理地产、改革教牧并派遣奥古斯丁赴英格兰，其思想主要体现为‘如何承担一个无法退出的公共职位’。",
    timeline: [
      { date: "约 573", place: "罗马", title: "任罗马城市长官", detail: "显示其受过行政与法律训练，具体任期材料有限。", certainty: "较可靠" },
      { date: "590", place: "罗马", title: "成为教皇", detail: "在瘟疫、战争和救济压力中接任。", certainty: "较可靠" },
      { date: "597", place: "罗马—肯特", title: "派遣英格兰传教团", detail: "坎特伯雷的奥古斯丁率团抵达肯特。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "治理与灵魂", question: "公共领导怎样避免变成权力欲，又不以追求纯洁为由逃避责任？", start: "默观生活有吸引力，危机中的共同体却需要行政、纠正和照料。", steps: ["把职位理解为重担而非荣耀", "要求牧者先检查自身动机", "按不同性格与处境调整劝诫", "让行动返回默观，让默观承担邻人需要"], conclusion: "真正的治理是‘牧灵照管’：权威越大，对具体人的责任越重，也越需要自我怀疑和谦卑。" }],
    concepts: [
      { zh: "牧灵规则", en: "pastoral rule", definition: "按人的处境施教、纠正和照顾的治理艺术，也是中世纪主教与君主反复阅读的领导手册。" },
      { zh: "众仆之仆", en: "servant of the servants of God", definition: "教皇自称，表达权威作为服务的规范；现实政治并不因此失去权力竞争。" },
      { zh: "行动与默观", en: "active and contemplative lives", definition: "领导者不能把二者割裂：默观校正行动动机，行动回应邻人需要。" },
    ],
    lineage: { inherited: "继承奥古斯丁神学、本尼狄克式修道纪律和罗马行政经验。", school: "晚期拉丁教父与早期中世纪教皇治理传统。", influenced: "《牧灵规则》影响中世纪教士教育，传教和行政行动重塑西欧教会网络。", parallel: "与安布罗斯都以主教权威处理公共危机，但格列高利面对帝国治理缺席更为严重的罗马。" },
    comparisons: [
      { target: "努西亚的本尼狄克", relation: "承接前人", shared: "纪律、谦卑与共同体生活塑造治理者。", difference: "格列高利把修道训练带入教皇行政，并以传记塑造本尼狄克的后世形象。" },
      { target: "奥古斯丁", relation: "承接前人", shared: "恩典、欲望秩序和基督教历史共同体。", difference: "格列高利少做系统形而上学，更关心讲道、灵魂分类和危机治理。" },
      { target: "米兰的安布罗斯", relation: "同题比较", shared: "教会领袖必须对公共权力和城市生活负责。", difference: "安布罗斯主要限制强皇权；格列高利常在弱行政环境中补位。" },
    ],
    stars: 2, culturalNotes: [{ kind: "轶事", title: "“不是盎格鲁人，而是天使”", text: "传说格列高利在罗马市场见到来自英格兰的浅发奴隶，以 Angli 与 angeli 的双关引出传教愿望。", caveat: "故事见于较晚的比德，适合当作传教记忆，不是可核实现场记录。" }],
    russellView: "罗素把大格列高利写成古罗马与中世纪教皇制之间的关键人物：有行政能力、修道热情和迷信气质，其现实成就比抽象哲学更重要。",
    modernCorrection: "罗素‘文明衰落／轻信奇迹’的框架容易低估格列高利书信网络、经济治理和适应性政治。奇迹文本也应按牧灵和文学体裁分析，而不只当作理性退步。",
    sources: [russellSource("第二卷第六章〈圣本尼狄克与大格列高利〉"), { label: "Britannica · St. Gregory the Great", kind: "补充", url: "https://www.britannica.com/biography/St-Gregory-the-Great" }],
  },
  {
    id: "eriugena", order: 38, nameZh: "约翰·司各脱·爱留根纳", nameEn: "John Scottus Eriugena", greekName: "Iohannes Scottus Eriugena", dates: "约 800—约 877", active: "9 世纪中叶", places: ["爱尔兰", "西法兰克宫廷"], school: "加洛林新柏拉图主义", figureId: "eriugena", chapterIds: ["b2-08"],
    thesis: "自然包括一切存在与非存在，并可按创造与被创造的关系分为四类；万物由上帝显现、通过理性层级展开，并最终复归不可说的源头。",
    evidenceCaution: "著作保存良好但生平极少；后来在英格兰被学生杀死等故事不可靠。其‘泛神论’标签也可能混淆神显论与上帝—世界同一。",
    lifeSummary: "爱留根纳可能来自爱尔兰，因罕见的希腊文能力进入秃头查理宫廷。他翻译伪狄奥尼修、忏悔者马克西穆斯等希腊神学，写成对话体《论自然的区分》。这使拉丁西欧重新接上东方基督教的新柏拉图传统。",
    timeline: [
      { date: "约 850", place: "西法兰克宫廷", title: "参与预定论争", detail: "《论神圣预定》因强调理性与恶的非存在引发争议。", certainty: "较可靠" },
      { date: "约 860 年代", place: "宫廷学术圈", title: "翻译希腊教父", detail: "翻译伪狄奥尼修等作品，为拉丁世界建立术语。", certainty: "较可靠" },
      { date: "约 862—866", place: "西法兰克", title: "写作《论自然的区分》", detail: "以师生对话组织创造、认识与复归。", certainty: "推定" },
    ],
    inquiries: [{ object: "自然与神显", question: "超越一切范畴的上帝，怎样既不可说又在万物中显现？", start: "若上帝是一种最高的‘东西’，便仍落入受造范畴；若完全不可知，创造又无法显示神。", steps: ["把自然定义为存在与非存在的一切", "区分创造而不受造、受造且创造、受造不创造、不创造也不受造", "把理念与万物理解为神显", "让分析过程返回超越一切断言的上帝"], conclusion: "创造是上帝的显现而非对外部材料加工；理性可追踪显现，却必须以否定神学承认源头超越存在。" }],
    concepts: [
      { zh: "自然四分", en: "four divisions of nature", definition: "按创造／受造关系组织上帝、理念、具体世界与终极复归的辩证结构。" },
      { zh: "神显", en: "theophany", definition: "受造物是不可见上帝以有限方式呈现自身，不意味着每个有限物就是神的全部。" },
      { zh: "否定神学", en: "negative theology", definition: "上帝超越‘善、存在、智慧’等范畴；肯定之后必须以否定和超越修正。" },
    ],
    lineage: { inherited: "承接奥古斯丁，也通过翻译吸收伪狄奥尼修和希腊教父新柏拉图主义。", school: "加洛林宫廷哲学中最具系统性的基督教新柏拉图主义。", influenced: "影响十二世纪自然哲学、神秘主义和德意志思想，著作也因涉嫌泛神论而多次受禁。", parallel: "与普罗提诺都描述由一到多再复归，但爱留根纳用创造、经文和三位一体重写结构。" },
    comparisons: [
      { target: "普罗提诺", relation: "后世重构", shared: "实在由最高统一者展开并向源头复归。", difference: "爱留根纳经由基督教希腊作者接受新柏拉图主义，并坚持创造与基督教启示语言。" },
      { target: "奥古斯丁", relation: "承接前人", shared: "理性从受造秩序和内在心灵上升至上帝。", difference: "爱留根纳的自然四分与希腊否定神学更大胆地模糊存在和非存在边界。" },
      { target: "坎特伯雷的安瑟伦", relation: "影响后继", shared: "理性并非信仰的敌人，而在信仰内部追求理解。", difference: "安瑟伦偏向紧缩论证；爱留根纳构造百科式宇宙复归体系。" },
    ],
    stars: 3, culturalNotes: [{ kind: "轶事", title: "“桌子把爱尔兰人与醉汉分开”", text: "一则宫廷双关故事说，国王问‘醉汉与爱尔兰人相隔什么’，爱留根纳答‘一张桌子’。它塑造了机敏、敢于顶撞宫廷的学者形象。", caveat: "故事来源较晚，不能当作逐字实录。" }],
    russellView: "罗素把爱留根纳视为黑暗时代少见的原创哲学家，赞赏其希腊学养和体系勇气，并把《论自然》概括为带有泛神论危险的新柏拉图主义。",
    modernCorrection: "‘泛神论者’标签过于粗糙。其神显语言同时坚持上帝超越存在；现代研究也更重视其翻译活动、语义分析和加洛林争论语境。",
    sources: [russellSource("第二卷第八章〈约翰·司各脱〉"), sepSource("John Scottus Eriugena", "scottus-eriugena")],
  },
  {
    id: "anselm", order: 43, nameZh: "坎特伯雷的安瑟伦", nameEn: "Anselm of Canterbury", greekName: "Anselmus Cantuariensis", dates: "1033/34—1109", active: "11 世纪末至 12 世纪初", places: ["奥斯塔", "贝克修道院", "坎特伯雷"], school: "早期经院哲学／奥古斯丁主义", figureId: "anselm", chapterIds: ["b2-11"],
    thesis: "信仰寻求理解；从‘无法设想有比它更伟大者’这一概念出发，理性试图说明上帝不能只存在于思想中。",
    evidenceCaution: "著作、书信和同时代传记丰富；但所谓‘本体论证明’是后世命名，《独白》《宣讲》中的论证与祈祷语境不可割裂。",
    lifeSummary: "安瑟伦离开奥斯塔后进入诺曼底贝克修道院，在教育与默想中写成《独白》和《宣讲》。1093 年出任坎特伯雷大主教，因授职权和教会财产与两任英王冲突、两度流亡。他把严密推理、祈祷和教会政治责任结合在一生中。",
    timeline: [
      { date: "1060", place: "贝克修道院", title: "入院", detail: "师从兰弗朗克，后来成为院长。", certainty: "较可靠" },
      { date: "1070 年代", place: "贝克", title: "写作《独白》《宣讲》", detail: "探索不单依靠经文权威的理性论证。", certainty: "较可靠" },
      { date: "1093—1109", place: "坎特伯雷／流亡地", title: "大主教与王权冲突", detail: "围绕授职、效忠与教会自主多次谈判。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "上帝存在", question: "理解‘无法设想有比它更伟大者’是否已经要求它不只存在于思想？", start: "即使否认者也能理解这个表达，概念因而存在于心中。", steps: ["设定不可设想更伟大者", "区分只在理解中与也在现实中存在", "指出现实存在似乎比仅在思想中更伟大", "推出该对象若只在思想中便可设想更伟大者，形成矛盾"], conclusion: "上帝不能只作为概念存在；但论证是否偷渡存在谓词、定义能否保证实例，成为持续千年的争论。" }],
    concepts: [
      { zh: "信仰寻求理解", en: "faith seeking understanding", definition: "理性不是先悬置信仰再中立证明，而是信者希望理解已相信内容的内在必然性。" },
      { zh: "本体论论证", en: "ontological argument", definition: "由上帝概念及其不可超越性推向现实存在的一类先验论证，名称由后世赋予。" },
      { zh: "合宜与必然", en: "fittingness and necessity", definition: "安瑟伦在救赎论中追问道成肉身为何不仅合宜，而且在给定神圣目的下具有理由上的必然。" },
    ],
    lineage: { inherited: "继承奥古斯丁的内在上升、神圣真理与信仰理解关系，也吸收修院辩证训练。", school: "早期经院哲学与修院神学之间的枢纽。", influenced: "本体论论证经笛卡尔、莱布尼茨到现代模态版本不断重构；其救赎论也深刻影响拉丁神学。", parallel: "与阿奎那都论证上帝存在，但安瑟伦从概念必然性展开，阿奎那坚持从可经验的因果和变化出发。" },
    comparisons: [
      { target: "奥古斯丁", relation: "承接前人", shared: "由信仰进入理性理解，并从心灵中的真理上升。", difference: "安瑟伦把论证压缩为更明确的概念反证结构。" },
      { target: "托马斯·阿奎那", relation: "影响后继", shared: "理性能够讨论上帝存在与属性。", difference: "阿奎那拒绝人能直接掌握上帝本质的定义，改用从效果到原因的五路。" },
      { target: "罗瑟林", relation: "批评关系", shared: "都在逻辑语言与三位一体之间寻找可论证表达。", difference: "安瑟伦认为罗瑟林的唯名论会把三位一体拆成三个实体，专文反驳。" },
    ],
    stars: 4, culturalNotes: [{ kind: "例子", title: "一座“无法想象更伟大”的岛？", text: "同代修士高尼罗用完美海岛反驳：仅从概念似乎不能让对象出现。安瑟伦回答，上帝这种必然、不可超越对象不同于任何偶然岛屿。" }],
    russellView: "罗素高度重视本体论证明的历史生命力：即使他本人不接受，也承认它从安瑟伦经笛卡尔、莱布尼茨和黑格尔反复出现，是哲学史上少见的纯粹论证发明。",
    modernCorrection: "把论证只写成四行形式逻辑会失去《宣讲》的祈祷、理解与‘必然存在’语境。高尼罗、阿奎那和康德的反驳也针对不同版本，不能合并成一次终结。",
    sources: [russellSource("第二卷第十一章〈十二世纪〉"), sepSource("Saint Anselm", "anselm")],
  },
  {
    id: "roscelin", order: 44, nameZh: "罗瑟林", nameEn: "Roscelin of Compiègne", greekName: "Roscelinus Compendiensis", dates: "约 1050—约 1125", active: "11 世纪末", places: ["贡比涅", "苏瓦松", "洛什"], school: "早期唯名论", figureId: "roscelin", chapterIds: ["b2-11"],
    thesis: "共相并非独立事物，而与语词或声音密切相关；这一语义立场进入三位一体时，会立刻产生‘共同名称是否对应共同实体’的神学风险。",
    evidenceCaution: "几乎没有可确认的哲学作品传世，其观点主要由安瑟伦、阿伯拉尔等对手转述。‘共相只是气息之声’的著名公式未必是其原话。",
    lifeSummary: "罗瑟林是法国教士和逻辑教师，因三位一体解释在 1092 年苏瓦松会议受谴责。他的重要性不在保存完整体系，而在共相问题第一次与语言、个体和神学正统发生高强度碰撞；对手的反驳反而保存了他的历史位置。",
    timeline: [
      { date: "约 1090", place: "法国", title: "教授逻辑", detail: "阿伯拉尔曾短期从学；具体学校与年代不完全确定。", certainty: "推定" },
      { date: "1092", place: "苏瓦松", title: "三位一体观点受谴责", detail: "在压力下撤回；会议材料主要由后世来源重建。", certainty: "较可靠" },
      { date: "约 1120", place: "法国", title: "晚年仍参与论争", detail: "与阿伯拉尔的敌对书信显示其尚在活动。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "共相", question: "‘人’‘动物’等共同名称，除许多个体之外还对应一个共同实在吗？", start: "感官中只有苏格拉底、柏拉图等个体，语言却能用一个词谈论许多人。", steps: ["拒绝把种属当作独立实体", "把普遍性定位到共同语词或发声功能", "以个体为实际存在的首要单位", "检验这一立场用于三位一体时的后果"], conclusion: "共同名称不必对应一个额外实体；但罗瑟林究竟持声音论、语词论还是更细的语义理论，证据不足。" }],
    concepts: [
      { zh: "唯名论", en: "nominalism", definition: "否认共相作为独立普遍实体存在；在罗瑟林处只能依据敌对材料谨慎使用。" },
      { zh: "气息之声", en: "flatus vocis", definition: "后世归给他的公式，意指共相接近发出的声音；是否准确概括其观点有争议。" },
      { zh: "三神论指控", en: "charge of tritheism", definition: "若三个‘位格’各是独立个体，共同神性是否只剩名称？安瑟伦据此攻击其立场。" },
    ],
    lineage: { inherited: "承接波爱修斯传入的波菲利共相问题与十一世纪语法—逻辑教学。", school: "早期唯名论的象征人物，但可重建教义远少于后来的奥卡姆。", influenced: "刺激安瑟伦和阿伯拉尔澄清共相、部分整体与神学语言。", parallel: "与奥卡姆都拒绝额外的普遍实体，但奥卡姆有完整心灵语言、指代理论与大量原作。" },
    comparisons: [
      { target: "波爱修斯", relation: "承接前人", shared: "种和属究竟怎样存在的共相问题。", difference: "罗瑟林被理解为把存在优先权更激进地交给个体与名称。" },
      { target: "彼得·阿伯拉尔", relation: "影响后继", shared: "共相必须通过语言和个体关系解释。", difference: "阿伯拉尔批评把共相缩成物理声音，改谈语词的意义功能和个体相似状态。" },
      { target: "奥卡姆的威廉", relation: "影响后继", shared: "不承认个体之外另有共同实体。", difference: "两者相隔两百年且无简单直线师承；奥卡姆的理论资料和逻辑工具远为丰富。" },
    ],
    stars: 2, culturalNotes: [{ kind: "生活印象", title: "一个主要活在反驳中的哲学家", text: "罗瑟林提醒我们：哲学史有时由对手保存。今天熟悉的几句观点，多半来自安瑟伦和阿伯拉尔想证明他错在哪里。" }],
    russellView: "罗素把罗瑟林作为中世纪唯名论争的开端，强调其‘共相只是声音’以及由此引出的三神论争议。",
    modernCorrection: "现代研究对这一简明画像非常谨慎：敌对转述可能把技术立场漫画化，‘唯名论’也涵盖多种不相同理论。页面因此保留问题，不补造完整体系。",
    sources: [russellSource("第二卷第十一章〈十二世纪〉"), { label: "Internet Encyclopedia of Philosophy · Medieval Theories of Universals", kind: "补充", url: "https://iep.utm.edu/universa/" }],
  },
  {
    id: "abelard", order: 45, nameZh: "彼得·阿伯拉尔", nameEn: "Peter Abelard", greekName: "Petrus Abaelardus", dates: "1079—1142", active: "12 世纪前半叶", places: ["布列塔尼", "巴黎", "埃卢瓦尔修院", "克吕尼"], school: "十二世纪辩证哲学", figureId: "abelard", chapterIds: ["b2-11"],
    thesis: "共相不是共同实体，也不只是声音，而是语词基于个体的共同状态所承担的谓述功能；伦理责任主要取决于意图与同意。",
    evidenceCaution: "作品和书信丰富，但最著名爱情叙事同时来自自传性辩护与后世整理的书信集；哲学立场跨时期变化，不能只用‘概念论’一词概括。",
    lifeSummary: "阿伯拉尔从布列塔尼到巴黎挑战名师，以逻辑讲授成名。他与爱洛依丝的关系、秘密婚姻和遭阉割把私人生活推入公共传奇，此后两人分别进入宗教生活。他的《是与否》并非制造怀疑，而是把权威文本的表面冲突变成需要辨义、语境和推理解决的课堂问题。",
    timeline: [
      { date: "约 1100—1115", place: "巴黎", title: "以辩证教学成名", detail: "先后与香波的威廉等教师论争。", certainty: "较可靠" },
      { date: "约 1116—1118", place: "巴黎", title: "与爱洛依丝的关系及阉割事件", detail: "基本事件较可信，动机和书信传承仍有争议。", certainty: "较可靠" },
      { date: "1121／1140", place: "苏瓦松／桑斯", title: "两次受谴责", detail: "神学命题先后遭会议处理，晚年赴克吕尼。", certainty: "较可靠" },
    ],
    inquiries: [
      { object: "共相与语言", question: "同一个谓词如何真实地述说许多个体，而不假定一个共同物体？", start: "一个实体不能完整地同时存在于多个彼此分离的个体中，纯声音本身又没有可共同理解的内容。", steps: ["区分声音、语词意义与所指个体", "拒绝共同实体", "考察个体因某种状态而相似", "把普遍性归于语词可谓述多个对象的功能"], conclusion: "共相主要是有意义语词的语义地位；共同述说有客观根据，却不要求额外普遍物。" },
      { object: "伦理意图", question: "外在行为相同，为什么道德责任可能不同？", start: "误行、强迫、欲望与有意同意不能得到同一评价。", steps: ["区分倾向或诱惑与同意", "把罪定位为明知违背所信的神圣要求", "用意图解释行为的道德性质", "保留无知本身可能有责的复杂情况"], conclusion: "伦理判断应穿过外在结果考察主体同意和意图，但这不等于现代主观主义。" },
    ],
    concepts: [
      { zh: "是与否", en: "Sic et Non", definition: "并列教父权威的表面矛盾，训练学生通过词义、作者、语境和证据层级解决冲突。" },
      { zh: "状态", en: "status", definition: "个体得以被共同谓述的客观根据，不是一件可与个体分离的普遍实体。" },
      { zh: "意图伦理", en: "ethics of intention", definition: "罪与功德不能只按外在行为分类，关键在理性主体是否同意自己认为不应做之事。" },
    ],
    lineage: { inherited: "从罗瑟林、香波的威廉和波爱修斯逻辑传统继承共相问题。", school: "十二世纪巴黎辩证教学的标志人物，连接逻辑、神学方法与伦理。", influenced: "推动经院争辩法、问题体裁和语义分析，也因与伯尔纳的冲突呈现修院神学与学校辩证法张力。", parallel: "与奥卡姆都重视语言和个体，但阿伯拉尔的语义框架不是十四世纪心灵语言理论的缩小版。" },
    comparisons: [
      { target: "罗瑟林", relation: "承接前人", shared: "拒绝把共相当作独立共同实体。", difference: "阿伯拉尔反对把普遍性归于物理声音，转向语词意义和谓述功能。" },
      { target: "克莱尔沃的伯尔纳", relation: "批评关系", shared: "都要维护基督教真理和灵魂转化。", difference: "阿伯拉尔信任辩证分析澄清权威；伯尔纳担心技术好奇和自信破坏信仰谦卑。" },
      { target: "奥卡姆的威廉", relation: "影响后继", shared: "共相问题应通过语言、概念与个体说明。", difference: "奥卡姆以心灵语言、指代和简约原则建立另一套成熟理论。" },
    ],
    stars: 4, culturalNotes: [{ kind: "轶事", title: "阿伯拉尔与爱洛依丝", text: "两人的爱情、秘密婚姻、暴力报复与修院书信使阿伯拉尔成为少数具有大众辨识度的经院哲学家。爱洛依丝本人也是敏锐的伦理与制度思考者，不应只作爱情故事配角。" }],
    russellView: "罗素欣赏阿伯拉尔的聪明、独立和辩证精神，也用他与伯尔纳的冲突象征理性探究同教会权威之间的紧张。",
    modernCorrection: "《是与否》不是反宗教怀疑主义宣言，而是学校训练工具；阿伯拉尔也不是简单‘以理性反信仰’。爱情书信的编辑历史和爱洛依丝的独立声音需单独尊重。",
    sources: [russellSource("第二卷第十一章〈十二世纪〉"), sepSource("Peter Abelard", "abelard")],
  },
  {
    id: "bernard-clairvaux", order: 46, nameZh: "克莱尔沃的伯尔纳", nameEn: "Bernard of Clairvaux", greekName: "Bernardus Claraevallensis", dates: "1090—1153", active: "12 世纪前半叶", places: ["勃艮第", "克莱尔沃", "法国与意大利教会会议"], school: "修院神学／神秘主义", figureId: "bernard-clairvaux", chapterIds: ["b2-11"],
    thesis: "知识的最高目标不是展示聪明，而是通过谦卑与爱使意志转化；当辩证法脱离灵性生活，它会把神圣奥秘变成自我夸耀的对象。",
    evidenceCaution: "书信、讲道和政治活动材料丰富，但圣人传与后世虔敬传统强化了传奇色彩；他反对阿伯拉尔不等于反对所有理性或学习。",
    lifeSummary: "伯尔纳加入改革中的熙笃会，在克莱尔沃建立修院后成为欧洲最有影响力的教会顾问之一。他介入教皇分裂、异端审判与第二次十字军，也写下关于爱、谦卑和《雅歌》的精细灵修文本。他的权威同时具有道德说服、网络政治和争议性的动员力量。",
    timeline: [
      { date: "1112/1113", place: "熙笃", title: "加入修道团体", detail: "带领亲友共同入院的细节带有传记塑造。", certainty: "较可靠" },
      { date: "1115", place: "克莱尔沃", title: "建立修院", detail: "成为院长并形成广泛书信与修院网络。", certainty: "较可靠" },
      { date: "1140", place: "桑斯", title: "推动审查阿伯拉尔", detail: "将若干神学命题提交谴责，双方程序与动机仍有争论。", certainty: "较可靠" },
      { date: "1146—1149", place: "法国／德意志", title: "鼓动第二次十字军", detail: "远征失败使其声誉与神学解释承受压力。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "知识与爱", question: "知道上帝的命题，与真正认识上帝有什么差别？", start: "技术论证可以增加信息和名声，却不必改变骄傲的欲望。", steps: ["以自知和谦卑拆除自我夸耀", "区分为好奇、功利、教导和爱而求知", "让默想从自身贫乏转向神圣恩典", "把爱理解为意志与最高善的日益一致"], conclusion: "完整认识包含爱与人格转化；理性有位置，但不能把奥秘只变成可操纵的论题。" }],
    concepts: [
      { zh: "爱的四阶段", en: "four degrees of love", definition: "由为自己爱自己、为自己爱上帝，走向为上帝爱上帝，并在罕见时刻为上帝而爱自己。" },
      { zh: "谦卑", en: "humility", definition: "如实认识自身有限与依赖，是默观和正确求知的条件，不只是降低自我评价。" },
      { zh: "修院神学", en: "monastic theology", definition: "以礼仪、经文默想、讲道和生活转化为知识环境，与学校问题辩论侧重不同。" },
    ],
    lineage: { inherited: "继承奥古斯丁爱的秩序、本尼狄克规程与早期修院《雅歌》解释。", school: "十二世纪修院神学和熙笃改革的代表。", influenced: "影响中世纪神秘主义、虔敬传统和教会政治，也成为批评学校理性自负的经典声音。", parallel: "与波那文图拉都把知识完成于爱与心灵上升，但后者更系统吸收大学经院论证。" },
    comparisons: [
      { target: "彼得·阿伯拉尔", relation: "批评关系", shared: "基督教真理应当被理解并塑造生活。", difference: "伯尔纳以谦卑、传统和默观检验理性；阿伯拉尔更相信辩证冲突能澄清命题。" },
      { target: "奥古斯丁", relation: "承接前人", shared: "爱的秩序决定灵魂方向，知识不能脱离意志。", difference: "伯尔纳以修院讲道和亲密灵修语言展开，较少构造历史与形而上学体系。" },
      { target: "波那文图拉", relation: "影响后继", shared: "由谦卑、爱和默观走向上帝。", difference: "波那文图拉在十三世纪大学环境中把这一路径与经院分类结合。" },
    ],
    stars: 3, culturalNotes: [{ kind: "轶事", title: "一次声望巨大的失败动员", text: "伯尔纳的讲道帮助点燃第二次十字军热情，但远征惨败。他后来把失败解释为基督徒的罪，这段经历也暴露精神权威介入大规模政治暴力的危险。" }],
    russellView: "罗素把伯尔纳写成十二世纪强大的修院神秘主义者和阿伯拉尔的敌手：圣洁、政治影响与反智倾向在他笔下同时存在。",
    modernCorrection: "将伯尔纳称为简单反理性会遗漏其严密的欲望分析和修辞策略；但也不应因灵修著作而淡化他推动谴责、迫害与十字军动员的责任。",
    sources: [russellSource("第二卷第十一章〈十二世纪〉"), { label: "Britannica · St. Bernard of Clairvaux", kind: "补充", url: "https://www.britannica.com/biography/Saint-Bernard-of-Clairvaux" }],
  },
  {
    id: "avicenna", order: 39, nameZh: "阿维森纳", nameEn: "Avicenna (Ibn Sina)", greekName: "ابن سينا", dates: "约 980—1037", active: "11 世纪前期", places: ["布哈拉", "古尔甘杰", "雷伊", "哈马丹", "伊斯法罕"], school: "伊斯兰逍遥学派", figureId: "avicenna", chapterIds: ["b2-10"],
    thesis: "存在本身不包含在普通事物的本质中；一切自身可能的存在者需要原因，因果链最终依赖一个本质即存在的必然存在者。",
    evidenceCaution: "著作与弟子传记较丰富，但作品卷帙大、版本和译名复杂；拉丁‘阿维森纳’的接受史与伊本·西那原本的阿拉伯语体系不能完全等同。",
    lifeSummary: "伊本·西那成长于中亚萨曼王朝文化圈，少年时期已学习医学、逻辑与形而上学。此后在政权更替中担任医生、行政官和学者，频繁迁徙，仍完成《医典》《治愈之书》等百科体系。他把亚里士多德、新柏拉图主义与伊斯兰神学问题重组为高度原创的存在论和心灵哲学。",
    timeline: [
      { date: "约 997", place: "布哈拉", title: "进入宫廷藏书与医疗实践", detail: "据自传，他治愈统治者后获准使用王室图书馆。", certainty: "传统记载" },
      { date: "约 1015—1024", place: "哈马丹", title: "任医师与维齐尔", detail: "政治任职、监禁和写作交织。", certainty: "较可靠" },
      { date: "1024—1037", place: "伊斯法罕／哈马丹", title: "完成晚期著作并去世", detail: "在阿拉乌丁宫廷继续写作，行军途中病逝。", certainty: "较可靠" },
    ],
    inquiries: [
      { object: "本质与存在", question: "理解一件事是什么，是否已说明它现实存在？", start: "我们能理解马、三角形或凤凰的本质，却不能只凭定义知道它们是否存在。", steps: ["在概念上区分本质与存在", "把普通事物归为自身可能存在", "要求其现实存在由原因说明", "拒绝可能原因无限倒退，归结为必然存在者"], conclusion: "受造物的存在是被赋予的，必然存在者则不从别处取得存在；这一结构深刻改变拉丁经院形而上学。" },
      { object: "自我意识", question: "不依赖身体感觉时，人是否仍直接把握自己的存在？", start: "设想一个突然完整受造、悬浮空中且无任何感官接触的人。", steps: ["移除对身体和外物的感觉", "检验他是否仍肯定‘我存在’", "区分自我觉知与身体表象", "由此讨论灵魂的非物质性"], conclusion: "‘悬浮人’会意识到自身存在而不意识到身体；它是思想实验，不是经验实验或笛卡尔怀疑的原样前身。" },
    ],
    concepts: [
      { zh: "本质与存在", en: "essence and existence", definition: "事物是什么与它是否现实存在在可能者中可概念区分。" },
      { zh: "必然存在者", en: "Necessary Existent", definition: "不可能不存在、且是其他一切可能存在者的最终原因。" },
      { zh: "悬浮人", en: "Flying Man", definition: "隔离所有感觉的自我意识思想实验，用于论证灵魂对自身的直接把握。" },
      { zh: "意向", en: "intention / maʿnā", definition: "感官不仅接收形式，也把握羊对狼的敌意等不直接等同于颜色形状的意义。" },
    ],
    lineage: { inherited: "承接亚里士多德逻辑、自然哲学与形而上学，也吸收新柏拉图式因果层级和伊斯兰一神论问题。", school: "伊斯兰东方逍遥学派的体系高峰。", influenced: "影响安萨里、苏赫拉瓦迪、伊斯兰神学，也经拉丁译本深刻塑造大阿尔伯特和阿奎那。", parallel: "与迈蒙尼德都在亚伯拉罕一神论中吸收亚里士多德，但阿维森纳的必然存在与宇宙因果结构更具体系自主性。" },
    comparisons: [
      { target: "亚里士多德", relation: "后世重构", shared: "以因、形式、灵魂能力和证明组织哲学。", difference: "阿维森纳以本质—存在和必然存在重写形而上学，并融合新柏拉图因果论。" },
      { target: "安萨里", relation: "影响后继", shared: "哲学论证必须回应创造、神知和灵魂命运。", difference: "安萨里系统批评哲学家的永恒世界、因果必然等主张。" },
      { target: "托马斯·阿奎那", relation: "影响后继", shared: "本质—存在、可能—必然和理性灵魂是核心问题。", difference: "阿奎那吸收这些区分，却拒绝某些流溢结构与灵魂认知理论。" },
    ],
    stars: 5, culturalNotes: [{ kind: "例子", title: "“悬浮人”思想实验", text: "想象一个人出生即悬浮空中，四肢互不接触，也没有任何感官输入。阿维森纳问：他仍会不会肯定自己存在？这是中世纪最有辨识度的思想实验之一。" }],
    russellView: "罗素把阿维森纳与阿威罗伊列为伊斯兰哲学中必须特别说明的两人，强调其亚里士多德主义、医学声望与经拉丁翻译进入西欧的影响。",
    modernCorrection: "阿维森纳不是亚里士多德的阿拉伯语注释员，而是建立了独立、长期主导的阿维森纳主义。其伊斯兰语境和波斯—中亚政治生活也不应只作为把希腊思想‘送回欧洲’的中转站。",
    sources: [russellSource("第二卷第十章〈伊斯兰文化与哲学〉"), sepSource("Ibn Sina [Avicenna]", "ibn-sina")],
  },
  {
    id: "al-ghazali", order: 40, nameZh: "安萨里", nameEn: "al-Ghazali", greekName: "أبو حامد الغزالي", dates: "约 1058—1111", active: "11 世纪末至 12 世纪初", places: ["图斯", "巴格达", "大马士革", "耶路撒冷"], school: "伊斯兰神学／苏非思想", figureId: "al-ghazali", chapterIds: ["b2-10"],
    thesis: "哲学家的证明必须逐项接受检验；自然规律描述稳定次序，却不能把受造事件变成脱离上帝意志的必然联系。",
    evidenceCaution: "自传与大量著作传世，但精神危机叙述具有教导目的；他批评特定形而上学结论，并不拒绝逻辑、数学、医学或全部哲学。",
    lifeSummary: "安萨里在内沙布尔学习，后任巴格达尼扎米亚学院教授。1095 年经历信仰与动机危机，离开显赫职位游历并过苏非生活，晚年回到图斯。他在《哲学家的宗旨》中准确陈述哲学，在《哲学家的不一致》中批评二十项命题，再以《宗教学科的复兴》重建知识、实践和内在德性。",
    timeline: [
      { date: "1091", place: "巴格达", title: "任尼扎米亚学院教授", detail: "成为塞尔柱世界最显赫的教法与神学教师之一。", certainty: "较可靠" },
      { date: "1095", place: "巴格达", title: "精神危机并离职", detail: "自述失语、无法进食，最终放弃职位；动机兼有宗教与政治环境。", certainty: "较可靠" },
      { date: "约 1106", place: "内沙布尔／图斯", title: "短暂复教并退居", detail: "完成自传与晚期教学，1111 年去世。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "因果性", question: "火接触棉花后燃烧，是逻辑必然，还是上帝通常创造的稳定并行？", start: "经验显示火与燃烧恒常相随，却没有直接观察到一个不可分离的必然纽带。", steps: ["区分事件相继与逻辑必然", "保留上帝在每一事件中的自由创造", "承认稳定习惯使科学预测可能", "用可能例外为奇迹留下空间"], conclusion: "自然因果不拥有独立强制上帝的必然性；但安萨里是否完全否认受造因，现代解释仍有分歧。" }],
    concepts: [
      { zh: "哲学家的不一致", en: "Incoherence of the Philosophers", definition: "针对法拉比—阿维森纳传统二十项形而上学主张的技术批评，不是反对一切理性学科。" },
      { zh: "偶因论问题", en: "occasionalism", definition: "事件联系是否完全由上帝每次直接创造；安萨里文本也容纳二级因解释，标签需谨慎。" },
      { zh: "确定性危机", en: "crisis of certainty", definition: "自传中对感官、理性、权威和内在动机的层层审查，最终把知识与灵性实践联系。" },
    ],
    lineage: { inherited: "受艾什尔里神学、伊斯兰法学、阿维森纳哲学与苏非实践共同塑造。", school: "逊尼派神学与苏非伦理综合的核心人物。", influenced: "改变伊斯兰哲学的论题和证明标准，并促使阿威罗伊写《不一致的不一致》回应。", parallel: "常与休谟比较因果批判，但安萨里以神圣全能、创造和奇迹为中心，休谟则分析经验推断习惯。" },
    comparisons: [
      { target: "阿维森纳", relation: "批评关系", shared: "逻辑证明可以检验形而上学主张。", difference: "安萨里拒绝世界永恒、神只知普遍者等结论，并削弱自然因果的独立必然性。" },
      { target: "阿威罗伊", relation: "批评关系", shared: "哲学与启示的关系需要精确论证。", difference: "阿威罗伊反驳安萨里，维护亚里士多德因果与哲学证明的合法性。" },
      { target: "大卫·休谟", relation: "同题比较", shared: "从经验相继本身不能读出必然联系。", difference: "安萨里诉诸上帝自由和习惯秩序；休谟诉诸人的心理习惯并悬置神学解释。" },
    ],
    stars: 4, culturalNotes: [{ kind: "例子", title: "火真的“必须”烧棉花吗？", text: "安萨里用火与棉花追问：我们看到的是接触后燃烧，还是看到火自身具有不可违背的力量？这个普通场景成为哲学史最著名的因果例子之一。" }],
    russellView: "罗素称安萨里为敌视哲学的神学家，并以他攻击自然必然性说明伊斯兰正统对哲学的反击。",
    modernCorrection: "‘反哲学’过于简单。安萨里熟练使用逻辑，准确重述哲学家体系，只判定其中少数命题触犯信仰；其批评本身是高水平哲学论证，也没有让伊斯兰哲学就此终止。",
    sources: [russellSource("第二卷第十章〈伊斯兰文化与哲学〉"), sepSource("al-Ghazali", "al-ghazali")],
  },
  {
    id: "averroes", order: 41, nameZh: "阿威罗伊", nameEn: "Averroes (Ibn Rushd)", greekName: "ابن رشد", dates: "1126—1198", active: "12 世纪后半叶", places: ["科尔多瓦", "塞维利亚", "马拉喀什"], school: "安达卢西亚亚里士多德主义", figureId: "averroes", chapterIds: ["b2-10"],
    thesis: "示范性证明与经文真理不可能真正冲突；合格者在字面产生矛盾时应作解释，而不同认识能力的人需要不同论证方式。",
    evidenceCaution: "阿拉伯原作部分失传，许多只存希伯来文或拉丁文；拉丁‘阿威罗伊主义’的单一理智、双重真理论未必准确代表伊本·鲁世德本人。",
    lifeSummary: "伊本·鲁世德出生于科尔多瓦法官家庭，兼任法官、宫廷医师和哲学家。他为亚里士多德写短、中、长三类注释，回应安萨里，并在《决定性论述》中论证哲学研究对有能力者是宗教法要求。晚年一度失宠、著作受限，随后部分复职。",
    timeline: [
      { date: "1169", place: "塞维利亚", title: "任法官并开始系统注释", detail: "受伊本·图斐利引荐进入穆瓦希德宫廷学术圈。", certainty: "较可靠" },
      { date: "1182", place: "马拉喀什", title: "任宫廷医师", detail: "继承伊本·图斐利职位，并继续司法任职。", certainty: "较可靠" },
      { date: "1195—1198", place: "卢塞纳／马拉喀什", title: "失宠、复职与去世", detail: "政治与宗教原因交织，不能只解释为单纯‘哲学受迫害’。", certainty: "较可靠" },
    ],
    inquiries: [
      { object: "哲学与经文", question: "严格证明若与经文字面意义不同，信徒必须放弃哪一方？", start: "真理不可能反对真理，但经文面向不同理解能力的共同体。", steps: ["由经文要求思考受造物推出哲学研究的合法性", "区分示范、辩证和修辞论证", "仅在证明成立时解释表面冲突的经文", "限制高难解释向不具训练者传播"], conclusion: "哲学和启示在真理上统一，在表达与受众上分层；这不是两个互相矛盾的真理。" },
      { object: "理智", question: "抽象普遍知识如何既具有共同有效性，又被具体个人思考？", start: "若理智完全是个体身体形式，普遍对象似乎随个体化；若完全共同，个人认识又难解释。", steps: ["区分质料理智、能动理智与想象表象", "把可理解形式从个体表象中抽象", "让共同理智保证知识普遍性", "以个人想象和认知活动解释‘我的思考’"], conclusion: "理智统一论试图兼顾普遍知识与个人活动，却引发拉丁世界关于个人不朽和责任的巨大争论。" },
    ],
    concepts: [
      { zh: "决定性论述", en: "Decisive Treatise", definition: "以伊斯兰法学方式论证哲学研究的宗教合法性及解释经文的条件。" },
      { zh: "注释者", en: "the Commentator", definition: "拉丁中世纪对阿威罗伊的称号，反映其亚里士多德长篇注释的权威。" },
      { zh: "理智统一", en: "unity of the intellect", definition: "人类共享分离的质料理智的解释；其确切版本及个人认识机制仍有争议。" },
    ],
    lineage: { inherited: "继承亚里士多德、亚历山大注释传统和安达卢西亚哲学，也直接回应安萨里。", school: "安达卢西亚伊斯兰逍遥学派及拉丁阿威罗伊主义的源头。", influenced: "经希伯来文、拉丁文译本影响大阿尔伯特、阿奎那、拉丁激进亚里士多德主义和文艺复兴。", parallel: "与迈蒙尼德同在科尔多瓦文化背景并处理哲学—律法，但各自在伊斯兰与犹太法传统内工作。" },
    comparisons: [
      { target: "安萨里", relation: "批评关系", shared: "哲学命题必须接受严密证明和神学检验。", difference: "阿威罗伊捍卫自然因果和哲学证明，写《不一致的不一致》逐项回应。" },
      { target: "托马斯·阿奎那", relation: "影响后继", shared: "亚里士多德是自然与形而上学的核心资源。", difference: "阿奎那大量吸收注释，却反驳人类只有一个理智。" },
      { target: "迈蒙尼德", relation: "同题比较", shared: "哲学真理与宗教律法不能最终冲突，困难文本需要解释。", difference: "阿威罗伊更明确捍卫亚里士多德证明；迈蒙尼德以写作隐微性与负神学处理共同体风险。" },
    ],
    stars: 5, culturalNotes: [{ kind: "生活印象", title: "欧洲人眼中的“注释者”", text: "中世纪拉丁作者常只写“哲学家”指亚里士多德，写“注释者”便指阿威罗伊。一个十二世纪科尔多瓦人的阅读，长期决定欧洲大学怎样理解希腊哲学。" }],
    russellView: "罗素把阿威罗伊视为比阿维森纳更严格的亚里士多德主义者，强调理智统一、哲学解释经文与其在基督教欧洲远大于伊斯兰世界的后续影响。",
    modernCorrection: "‘双重真理’通常是拉丁对手给激进亚里士多德主义者的标签，不是阿威罗伊本人主张两套矛盾真理。其法官、医师与穆瓦希德政治语境也应进入解释。",
    sources: [russellSource("第二卷第十章〈伊斯兰文化与哲学〉"), sepSource("Ibn Rushd [Averroes]", "ibn-rushd")],
  },
  {
    id: "maimonides", order: 42, nameZh: "迈蒙尼德", nameEn: "Maimonides", greekName: "משה בן מימון", dates: "1138—1204", active: "12 世纪后半叶", places: ["科尔多瓦", "非斯", "福斯塔特", "开罗"], school: "犹太亚里士多德主义", figureId: "maimonides", chapterIds: ["b2-01", "b2-10"],
    thesis: "上帝不属于受造物的分类，肯定属性容易把神变成复合对象；人更可靠地知道上帝不是什么，并以律法、哲学与审慎解释引导不同能力的读者。",
    evidenceCaution: "法律、哲学、医学著作和书信丰富，但《迷途指津》有意采用隐微写法；不能假定每一处表面矛盾都只是疏忽，也不能自信破解唯一秘密教义。",
    lifeSummary: "迈蒙尼德出生于安达卢西亚犹太家庭，因穆瓦希德统治迁往北非和埃及，最终在福斯塔特担任社群领袖与宫廷医师。他以《密西拿托拉》系统整理犹太律法，以阿拉伯语《迷途指津》帮助受哲学教育却受经文字面困扰的读者。",
    timeline: [
      { date: "1148 以后", place: "安达卢西亚—北非", title: "家族迁徙", detail: "穆瓦希德扩张迫使家庭离开科尔多瓦，具体宗教处境仍有争论。", certainty: "较可靠" },
      { date: "1168", place: "福斯塔特", title: "完成《密西拿托拉》前期工作", detail: "逐渐成为埃及犹太社群的法律权威。", certainty: "较可靠" },
      { date: "约 1190", place: "福斯塔特", title: "完成《迷途指津》", detail: "以阿拉伯语写给受哲学困惑的学生约瑟夫。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "神圣属性", question: "说上帝‘智慧、强大、良善’，会不会把多个性质加到绝对统一者身上？", start: "普通肯定谓词把主词归入共同类别，似乎令上帝与受造物共享性质。", steps: ["拒绝把属性当作上帝内部附加成分", "把部分肯定语句解释为行动属性", "以否定逐步排除身体、有限和缺陷", "承认认识增长常表现为知道哪些说法不适用"], conclusion: "关于神本质，否定语言比同义肯定更安全；人的最高知识包含对自身认识限度的认识。" }],
    concepts: [
      { zh: "否定属性", en: "negative attributes", definition: "通过否认缺陷和受造分类谈论上帝，避免把共同谓词当作神人同义。" },
      { zh: "迷途者", en: "the perplexed", definition: "既忠于律法又接受哲学证明，因二者表面冲突而困惑的受教育读者。" },
      { zh: "隐微写作", en: "esoteric writing", definition: "按读者能力控制困难真理的表达，以矛盾、暗示和章节次序保护共同体与学习过程。" },
    ],
    lineage: { inherited: "继承犹太经文、拉比法学、阿拉伯语哲学和亚里士多德传统。", school: "中世纪犹太哲学与法律思想的核心人物。", influenced: "影响犹太哲学、基督教经院哲学和后世负神学，也引发长期反迈蒙尼德争论。", parallel: "与阿威罗伊同样生活在安达卢西亚哲学世界，但迈蒙尼德的社群法律工程和写作策略更突出。" },
    comparisons: [
      { target: "亚历山大的斐洛", relation: "后世重构", shared: "调和犹太经文与希腊哲学，反对粗糙神人同形论。", difference: "迈蒙尼德以亚里士多德和阿拉伯哲学为框架，法律系统化的地位也更核心。" },
      { target: "阿威罗伊", relation: "同题比较", shared: "律法面向共同体，哲学证明面向受训练者，真理不应最终冲突。", difference: "迈蒙尼德对创世证明保持审慎，并以负神学和隐微写作处理不确定性。" },
      { target: "托马斯·阿奎那", relation: "影响后继", shared: "神圣单纯性、属性类比和理性讨论律法。", difference: "阿奎那发展肯定性的类比语言；迈蒙尼德对本质属性的否定更严格。" },
    ],
    stars: 5, culturalNotes: [{ kind: "生活印象", title: "白天行医，夜晚回信", text: "迈蒙尼德在书信中描述自己白天为宫廷和病人诊疗，回家后仍被求医者包围，常到夜间才有时间处理社群与学术事务。哲学、法律和照护在他身上不是分开的职业。" }],
    russellView: "罗素把迈蒙尼德列为犹太哲学中最重要的人物，强调其亚里士多德主义、负神学、创世问题和《迷途指津》对阿奎那的影响。",
    modernCorrection: "不能只把迈蒙尼德当作希腊哲学传向基督教欧洲的桥。他首先在犹太法律、社群治理和阿拉伯语思想世界中工作；其哲学立场也因隐微写法存在多种竞争解释。",
    sources: [russellSource("第二卷第一、十章"), sepSource("Maimonides", "maimonides")],
  },
  {
    id: "albert-great", order: 47, nameZh: "大阿尔伯特", nameEn: "Albert the Great", greekName: "Albertus Magnus", dates: "约 1200—1280", active: "13 世纪中叶", places: ["帕多瓦", "巴黎", "科隆", "雷根斯堡"], school: "多明我会经院哲学", figureId: "albert-great", chapterIds: ["b2-12", "b2-13"],
    thesis: "新进入拉丁世界的亚里士多德自然与形而上学必须被完整理解、分类和检验，而不能仅凭权威接受或因异教来源拒绝。",
    evidenceCaution: "著作很多且归属复杂，科学观察与传说常被混合；‘发明机器人’和魔法师形象是后世传奇。",
    lifeSummary: "阿尔伯特加入多明我会，在巴黎和科隆教学，托马斯·阿奎那是其学生。他撰写覆盖逻辑、自然学、生物学、心理学、伦理与神学的释义，帮助拉丁学界第一次系统消化完整亚里士多德及阿拉伯注释传统，并保持对植物、动物和矿物的经验兴趣。",
    timeline: [
      { date: "约 1245", place: "巴黎", title: "任神学硕士", detail: "在大学环境中讲授并开始大规模亚里士多德释义。", certainty: "较可靠" },
      { date: "1248", place: "科隆", title: "建立多明我会学术中心", detail: "阿奎那随行学习。", certainty: "较可靠" },
      { date: "1260—1262", place: "雷根斯堡", title: "任主教后辞职", detail: "短期承担教区治理，之后重返教学与调解。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "自然哲学的自主性", question: "基督教学者应怎样面对来自异教和伊斯兰传统、却带有强大解释力的自然知识？", start: "简单禁止会失去论证工具，照单全收又可能与创造和灵魂教义冲突。", steps: ["先按学科完整陈述亚里士多德", "区分哲学证明与神学启示的方法", "比较阿维森纳、阿威罗伊等注释", "以观察和论证修正具体自然主张"], conclusion: "哲学各学科有相对自主的方法，神学仍提供更高目的与不能由自然理性独立获得的真理。" }],
    concepts: [
      { zh: "亚里士多德释义", en: "Aristotelian paraphrase", definition: "不只逐句注释，而是按拉丁读者需要重述学科整体并加入阿拉伯材料与本人判断。" },
      { zh: "学科区分", en: "distinction of sciences", definition: "自然学、形而上学与神学按对象和证明原则区分，避免每个问题直接诉诸经文。" },
      { zh: "经验自然研究", en: "empirical natural inquiry", definition: "在植物、动物与矿物著作中重视亲见和报告，但仍处在亚里士多德框架内。" },
    ],
    lineage: { inherited: "通过拉丁译本承接亚里士多德、阿维森纳、阿威罗伊，也受多明我会神学训练。", school: "十三世纪多明我会亚里士多德主义的开拓者。", influenced: "直接培养阿奎那，并为大学接受自然哲学与形而上学建立百科基础。", parallel: "与罗杰·培根都重视自然和语言知识；阿尔伯特偏百科释义，培根更强调实验、数学与改革计划。" },
    comparisons: [
      { target: "阿维森纳", relation: "承接前人", shared: "自然、灵魂与形而上学形成系统科学。", difference: "阿尔伯特在拉丁基督教大学中评估并重组阿维森纳体系。" },
      { target: "阿威罗伊", relation: "承接前人", shared: "亚里士多德注释是哲学研究核心。", difference: "阿尔伯特拒绝某些理智统一和宇宙永恒解释。" },
      { target: "托马斯·阿奎那", relation: "影响后继", shared: "区分哲学与神学方法并广泛吸收亚里士多德。", difference: "阿奎那把材料压缩成更统一的存在、因果和自然法体系。" },
    ],
    stars: 3, culturalNotes: [{ kind: "轶事", title: "会说话的铜头传说", text: "后世传说阿尔伯特制造了会回答问题的机械铜头，甚至被阿奎那砸毁。这更像大众对其百科知识和‘自然魔法’想象的投影。", caveat: "没有可靠同期证据。" }],
    russellView: "罗素把大阿尔伯特与阿奎那并列为把亚里士多德完整纳入天主教思想的关键人物，但认为学生的体系与历史影响更大。",
    modernCorrection: "阿尔伯特不是阿奎那的预备草稿。他有独立的自然哲学、神秘主义和学科观；‘经验科学先驱’也不应直接等同于近代实验科学。",
    sources: [russellSource("第二卷第十二至十三章"), sepSource("Albert the Great", "albert-great")],
  },
  {
    id: "aquinas", order: 48, nameZh: "托马斯·阿奎那", nameEn: "Thomas Aquinas", greekName: "Thomas Aquinas", dates: "约 1225—1274", active: "13 世纪中叶", places: ["罗卡塞卡", "巴黎", "科隆", "那不勒斯", "奥尔维耶托"], school: "多明我会经院哲学", figureId: "aquinas", chapterIds: ["b2-12", "b2-13"],
    thesis: "恩典不摧毁自然而使其完成；理性可从受造效果认识上帝存在与部分属性，启示则给予超出自然证明的三位一体与救赎真理。",
    evidenceCaution: "作品、审判材料和早期传记丰富，但‘一次神秘体验后认为作品如稻草’的含义不可确定；托马斯主义也有多个后世版本。",
    lifeSummary: "阿奎那出身意大利贵族家庭，不顾家族反对加入新兴多明我会，师从大阿尔伯特，在巴黎和意大利教学。他以问题、反对、回应和答辩的格式处理神学全体，在《反异教大全》《神学大全》中把亚里士多德哲学、教父传统与基督教教义组织成影响最持久的经院体系。",
    timeline: [
      { date: "约 1244", place: "那不勒斯／罗马", title: "加入多明我会", detail: "家族曾将他扣留，希望阻止选择托钵修会。", certainty: "较可靠" },
      { date: "1252—1259", place: "巴黎", title: "首度执教", detail: "卷入托钵修会在大学的地位争论。", certainty: "较可靠" },
      { date: "1265—1273", place: "罗马／巴黎／那不勒斯", title: "写作《神学大全》", detail: "作品未完成，于 1273 年底停止写作。", certainty: "较可靠" },
      { date: "1274", place: "福萨诺瓦", title: "赴里昂会议途中去世", detail: "享年约四十九岁。", certainty: "较可靠" },
    ],
    inquiries: [
      { object: "从运动到第一原因", question: "世界中的变化是否要求一个不以同样方式被推动的第一根源？", start: "变化是潜能在已实现者作用下成为现实，同一事物不能在同一方面同时以同一方式既潜在又现实。", steps: ["从实际变化而非抽象定义出发", "分析推动者与被推动者的依赖", "拒绝此刻依赖的本质序列无限后退", "指向不受推动的第一推动者"], conclusion: "五路不是五种竞争神话，而是由不同依赖结构指向第一原因；从第一原因到基督教上帝仍需后续论证。" },
      { object: "自然法", question: "普遍善怎样进入具体人的实践判断？", start: "人具有共同倾向，却在可变情境中行动。", steps: ["以‘行善避恶’为实践理性的首要原则", "从生命、家庭、真理与社会倾向展开一般规范", "用审慎把一般原则应用于个别处境", "承认人为法需服务共同善并受更高法衡量"], conclusion: "自然法是理性受造者参与永恒法，不是一张无需判断即可机械执行的规则表。" },
    ],
    concepts: [
      { zh: "五路", en: "Five Ways", definition: "从运动、有效因、可能与必然、程度和目的秩序出发的五种后验论证。" },
      { zh: "存在之实现", en: "act of being / esse", definition: "事物不仅有本质形式，还实际存在；阿奎那用存在活动说明受造参与和神圣根源。" },
      { zh: "类比语言", en: "analogical predication", definition: "‘善、智慧、存在’用于神和受造物时既非完全同义也非毫无关系。" },
      { zh: "自然法", en: "natural law", definition: "实践理性对共同善秩序的参与，需要德性和审慎完成具体判断。" },
    ],
    lineage: { inherited: "承接亚里士多德、大阿尔伯特、奥古斯丁、阿维森纳、阿威罗伊与迈蒙尼德。", school: "十三世纪多明我会经院哲学和托马斯主义的中心。", influenced: "影响天主教神学、自然法、德性伦理与当代分析托马斯主义，也长期受到方济各会和唯名论批评。", parallel: "与波那文图拉都在巴黎处理信仰和理性，但阿奎那更信任亚里士多德自然知识的稳定自主性。" },
    comparisons: [
      { target: "大阿尔伯特", relation: "承接前人", shared: "完整吸收亚里士多德和阿拉伯注释传统。", difference: "阿奎那建立更紧密的存在论、自然法与神学综合。" },
      { target: "阿威罗伊", relation: "批评关系", shared: "亚里士多德理智论需要与知识普遍性协调。", difference: "阿奎那坚持每个人有自己的理智灵魂，反驳单一共同理智。" },
      { target: "邓斯·司各脱", relation: "影响后继", shared: "经院问题体系、创造论和德性伦理。", difference: "司各脱批评存在类比与个体化解释，强调存在单义和意志自由。" },
    ],
    stars: 5, culturalNotes: [{ kind: "轶事", title: "“沉默的牛”", text: "同学因托马斯身材魁梧而沉默，称他“西西里的哑牛”。传说大阿尔伯特预言，这头牛的吼声终将传遍世界。", caveat: "来自早期传记传统，适合表现后世形象，不是课堂录音式史实。" }],
    russellView: "罗素称阿奎那为最伟大的经院哲学家，承认其体系清晰、完整且成功调和亚里士多德与天主教，却批评其结论预先由正统规定，因而不具完全自由的哲学冒险。",
    modernCorrection: "罗素的‘先有答案再找论据’低估了阿奎那对权威冲突、自然知识和反对意见的真实开放，也容易忽略其存在论原创性；但制度正统确实规定了不可放弃的教义边界。",
    sources: [russellSource("第二卷第十三章〈圣托马斯·阿奎那〉"), sepSource("Saint Thomas Aquinas", "aquinas")],
  },
  {
    id: "roger-bacon", order: 49, nameZh: "罗杰·培根", nameEn: "Roger Bacon", greekName: "Rogerus Bacon", dates: "约 1214—约 1292", active: "13 世纪中后期", places: ["牛津", "巴黎"], school: "方济各会自然哲学", figureId: "roger-bacon", chapterIds: ["b2-14"],
    thesis: "权威、习惯与译本错误会累积知识障碍；数学、语言和实验经验应共同校正哲学、神学与实际技术。",
    evidenceCaution: "生平、监禁时间与原因并不完全确定；他并未发明现代实验方法，也不能把火药、望远镜等所有预言都当作亲自制造。",
    lifeSummary: "罗杰·培根在牛津、巴黎学习并教授亚里士多德自然哲学，后来加入方济各会。应教皇克莱孟四世要求，他秘密而迅速地写成《大著作》《小著作》《第三著作》，提出语言、数学、光学、实验科学和道德哲学协同改革知识与教会。",
    timeline: [
      { date: "1240 年代", place: "巴黎／牛津", title: "学习与讲授自然哲学", detail: "接触新译亚里士多德、阿拉伯光学与数学材料。", certainty: "较可靠" },
      { date: "1266—1268", place: "巴黎", title: "为教皇写三部改革著作", detail: "在修会限制下完成庞大知识计划。", certainty: "较可靠" },
      { date: "1270—1280 年代", place: "方济各会机构", title: "争议与可能监禁", detail: "确有纪律处分线索，但‘因科学被囚十年’过于简化。", certainty: "推定" },
    ],
    inquiries: [{ object: "知识纠错", question: "学术传统为何会在人人引用权威时持续积累错误？", start: "劣质翻译、盲从习惯、公众偏见和假装知道会彼此强化。", steps: ["识别权威、习惯、偏见、伪知识四类障碍", "学习希伯来语、希腊语和阿拉伯语核对文本", "以数学保证数量和光学推理", "以经验确认、制造和纠正论证"], conclusion: "知识改革不是一句‘做实验’，而是语言、数学、仪器、观察与道德目的协同。" }],
    concepts: [
      { zh: "经验科学", en: "scientia experimentalis", definition: "验证其他科学结论、发现仅凭推理未知之事并制造实际效果的知识。" },
      { zh: "知识四障碍", en: "four causes of error", definition: "脆弱权威、长期习惯、无知大众意见与用智慧外表掩盖无知。" },
      { zh: "语言改革", en: "linguistic reform", definition: "直接学习原文语言，以减少圣经、哲学和科学翻译链造成的系统错误。" },
    ],
    lineage: { inherited: "承接格罗斯泰斯特的光学与数学传统、阿拉伯光学、亚里士多德自然哲学和方济各会改革关怀。", school: "十三世纪方济各会自然哲学与知识改革计划。", influenced: "后世常把他塑造成现代科学先驱；更准确的影响在光学、语言学习和中世纪科学史自我反思。", parallel: "与大阿尔伯特都扩大自然研究，罗杰更集中批评翻译、数学不足和缺乏经验验证。" },
    comparisons: [
      { target: "大阿尔伯特", relation: "同题比较", shared: "自然知识需要广泛吸收亚里士多德与阿拉伯材料。", difference: "阿尔伯特以百科释义和观察见长；罗杰把语言、数学和实验编成改革方案。" },
      { target: "哲罗姆", relation: "后世重构", shared: "原文语言是校正传统错误的必要条件。", difference: "罗杰将其扩展到大学课程、科学、传教和教会改革。" },
      { target: "奥卡姆的威廉", relation: "同题比较", shared: "同属方济各会并批评知识体系中的多余假设。", difference: "罗杰重实验、数学与语言；奥卡姆重逻辑语义、认识限度和政治权威。" },
    ],
    stars: 4, culturalNotes: [{ kind: "轶事", title: "“罗杰修士的铜头”", text: "英国传说把罗杰·培根写成制造会说话铜头的魔法师。真实的培根确实讨论光学、火药和机械可能性，但传奇把知识改革者改造成巫师。", caveat: "铜头故事没有可靠历史证据。" }],
    russellView: "罗素把罗杰·培根写成少见重实验、数学和原文语言的中世纪思想家，赞赏其科学精神，也突出他因独立和神秘声誉与修会冲突。",
    modernCorrection: "把他称为孤独的现代科学家穿越到中世纪会误读其目标：实验服务于神学、历法、传教和教会改革。他依赖权威传统，只是要求更好地校验权威。",
    sources: [russellSource("第二卷第十四章〈方济各会经院哲学家〉"), sepSource("Roger Bacon", "roger-bacon")],
  },
  {
    id: "bonaventure", order: 50, nameZh: "波那文图拉", nameEn: "Bonaventure", greekName: "Bonaventura", dates: "约 1217—1274", active: "13 世纪中叶", places: ["巴尼奥雷焦", "巴黎", "里昂"], school: "方济各会奥古斯丁主义", figureId: "bonaventure", chapterIds: ["b2-14"],
    thesis: "世界、心灵与经文都是通向上帝的痕迹；哲学知识必须在照明、爱和心灵超越自身的旅程中完成，而不是封闭为自足体系。",
    evidenceCaution: "著作与行政记录较丰富；‘反亚里士多德’标签过强，他广泛使用亚里士多德逻辑与自然概念，主要拒绝哲学的自足和世界永恒。",
    lifeSummary: "波那文图拉加入方济各会，在巴黎与阿奎那大致同时教学，后来任修会总会长，调和内部贫穷实践争论。他的《心灵通向上帝的旅程》以感官世界、内在心灵和超越观照构成六阶段上升，把经院分类与方济各灵性生活结合。",
    timeline: [
      { date: "约 1243", place: "巴黎", title: "加入方济各会并学习神学", detail: "师从哈勒斯的亚历山大传统。", certainty: "较可靠" },
      { date: "1257", place: "巴黎", title: "获神学教席并任总会长", detail: "与阿奎那一同得到大学承认。", certainty: "较可靠" },
      { date: "1274", place: "里昂", title: "参加大公会议并去世", detail: "此前被任命为枢机。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "心灵上升", question: "有限心灵如何由世界中的多样事物走向不可把握的上帝？", start: "受造物既不是上帝，又在秩序、美和能力中留下源头痕迹。", steps: ["在外部世界阅读神的痕迹", "进入感官与心灵能力的映像", "在记忆、理解、意志中辨认三一结构", "超越概念，在爱与黑暗中安息"], conclusion: "哲学知识是旅程中的必要阶段，却只有在爱和自我超越中完成。" }],
    concepts: [
      { zh: "痕迹与形象", en: "vestige and image", definition: "万物以因果秩序留下上帝痕迹，理性心灵则以记忆、理解、意志更直接地成为形象。" },
      { zh: "神圣照明", en: "divine illumination", definition: "确定真理依赖心灵参与不变的神圣规则，不只是自然抽象。" },
      { zh: "心灵旅程", en: "journey of the mind", definition: "由世界、内在心灵到超越上帝的认识—爱之路径。" },
    ],
    lineage: { inherited: "继承奥古斯丁照明论、伪狄奥尼修上升结构、伯尔纳修院灵修和方济各贫穷理想。", school: "十三世纪方济各会经院哲学的系统代表。", influenced: "影响方济各会神学、神秘主义与后来关于知识照明和创造范型的争论。", parallel: "与阿奎那同时把大学哲学纳入神学，但对亚里士多德自足性与照明需要评价不同。" },
    comparisons: [
      { target: "奥古斯丁", relation: "承接前人", shared: "从受造痕迹和心灵内在结构上升，以照明确保真理。", difference: "波那文图拉把路径编成方济各式六阶段旅程。" },
      { target: "克莱尔沃的伯尔纳", relation: "承接前人", shared: "知识完成于爱、谦卑和默观。", difference: "波那文图拉在巴黎大学语境中给予逻辑和学科分类更明确位置。" },
      { target: "托马斯·阿奎那", relation: "同题比较", shared: "哲学与神学可协同，但启示超越自然理性。", difference: "波那文图拉更强调照明、范型和历史回归，警惕永恒世界的亚里士多德主义。" },
    ],
    stars: 4, culturalNotes: [{ kind: "生活印象", title: "把世界当成一本可阅读的书", text: "在波那文图拉那里，石头、光、记忆和欲望都不只是对象，也像指向作者的字迹。‘阅读世界’因此同时是一种知识方法和精神练习。" }],
    russellView: "罗素把波那文图拉归为方济各会较保守、较奥古斯丁主义的一翼，强调其神秘倾向及对亚里士多德世界永恒论的敌意。",
    modernCorrection: "他不是以神秘主义替代论证，而是把逻辑、自然知识和形而上学安放在一条有终点的道路上。与阿奎那的差别也不能简化为柏拉图对亚里士多德。",
    sources: [russellSource("第二卷第十四章〈方济各会经院哲学家〉"), sepSource("Saint Bonaventure", "bonaventure")],
  },
  {
    id: "duns-scotus", order: 51, nameZh: "邓斯·司各脱", nameEn: "John Duns Scotus", greekName: "Ioannes Duns Scotus", dates: "约 1265/66—1308", active: "13 世纪末至 14 世纪初", places: ["苏格兰", "牛津", "巴黎", "科隆"], school: "方济各会经院哲学", figureId: "duns-scotus", chapterIds: ["b2-14"],
    thesis: "形而上学若要证明关于上帝的结论，‘存在’必须以某种单义核心适用于有限者与无限者；个体之所以是这个个体，还需不可还原的此性。",
    evidenceCaution: "著作文本史复杂，许多讲义由学生整理，旧版还混入伪作；其精微论证常被‘意志主义者’‘反托马斯’等标签压扁。",
    lifeSummary: "司各脱是方济各会神学家，在牛津、巴黎和科隆短暂而高强度地教学。1303 年因拒绝支持法王反对教皇而离开巴黎，后复返取得教席，1308 年在科隆早逝。他围绕存在、个体化、认识、自由和圣母始胎无染原罪提出精密区分。",
    timeline: [
      { date: "约 1290 年代", place: "牛津", title: "讲授《命题集》", detail: "形成《牛津著作》的多层修订文本。", certainty: "较可靠" },
      { date: "1303", place: "巴黎", title: "因政治忠诚离开", detail: "拒绝签署支持腓力四世反教皇立场，后获准返回。", certainty: "较可靠" },
      { date: "1307—1308", place: "科隆", title: "教学并去世", detail: "死因不明，活埋传说没有可靠依据。", certainty: "较可靠" },
    ],
    inquiries: [
      { object: "个体化", question: "两个同属一种的人为何不只是同一形式的可互换副本？", start: "共同人性说明相似，却不说明这个苏格拉底为何就是不可重复的这个人。", steps: ["拒绝以共同本性自身说明个体", "承认共同本性在自身不普遍也不个别", "加入收缩本性的最终个体差异", "把它称为此性而非可分离的另一物"], conclusion: "此性使共同本性成为这个不可重复个体；个体性具有正面形而上学地位。" },
      { object: "自由意志", question: "自由是否只是在已判断为最好的选项面前自动行动？", start: "若理智判断必然决定选择，意志就只是认知结果的执行器。", steps: ["区分自然倾向与意志能力", "主张意志可对相反方案保持同步可能", "让理智提供对象而不完全决定选择", "以自我决定解释责任和偶然性"], conclusion: "自由包含当下选择相反项的真实能力，意志不是理智判断的被动终点。" },
    ],
    concepts: [
      { zh: "存在的单义性", en: "univocity of being", definition: "至少一个共同概念核心可同样用于神与受造物，使形而上学推理不在中途换义。" },
      { zh: "此性", en: "haecceity", definition: "使共同本性收缩为这个不可重复个体的最终个体差异。" },
      { zh: "形式区别", en: "formal distinction", definition: "同一实体内不同形式内容的区别，强于纯概念区分、弱于两个可分离事物。" },
      { zh: "同步偶然性", en: "synchronic contingency", definition: "行动发生的同一时刻，意志仍具有选择相反项的能力。" },
    ],
    lineage: { inherited: "承接方济各会奥古斯丁主义、阿维森纳本质论和阿奎那经院问题体系。", school: "晚期十三世纪方济各会经院哲学与司各脱主义的源头。", influenced: "影响奥卡姆、苏亚雷斯、近代模态与个体性讨论，也形成长期司各脱主义学派。", parallel: "与阿奎那在许多问题共享框架，差异集中于存在语言、个体化、神知与意志自由。" },
    comparisons: [
      { target: "托马斯·阿奎那", relation: "批评关系", shared: "存在、个体、自由与神学语言需要统一形而上学。", difference: "司各脱以存在单义、此性和更强意志偶然性修正托马斯式类比与个体化。" },
      { target: "阿维森纳", relation: "承接前人", shared: "共同本性在自身不因概念定义而现实存在。", difference: "司各脱以形式区别和此性重构本性怎样成为具体个体。" },
      { target: "奥卡姆的威廉", relation: "影响后继", shared: "重视个体、意志自由与逻辑精确。", difference: "奥卡姆拒绝司各脱许多形式区别和共同本性装置，采取更激进的本体简约。" },
    ],
    stars: 4, culturalNotes: [{ kind: "生活印象", title: "“笨蛋帽”原本来自一位“精微博士”", text: "司各脱的追随者因维护繁复经院论证，在近代人文主义者笔下变成 dunce（笨蛋）的词源；讽刺的是，他本人在中世纪称号正是“精微博士”。" }],
    russellView: "罗素强调司各脱是方济各会中反托马斯的一方，重视意志优先、个体化和关于上帝存在的论证，也把他的精微视为经院哲学晚期特征。",
    modernCorrection: "司各脱不是走向衰败的繁琐过渡。他关于单义、模态、此性和同步自由的论证在当代形而上学中仍具可讨论性；‘意志主义’也不能意味着任性。",
    sources: [russellSource("第二卷第十四章〈方济各会经院哲学家〉"), sepSource("John Duns Scotus", "duns-scotus")],
  },
  {
    id: "ockham", order: 52, nameZh: "奥卡姆的威廉", nameEn: "William of Ockham", greekName: "Guillelmus de Ockham", dates: "约 1287—1347", active: "14 世纪前半叶", places: ["牛津", "阿维尼翁", "比萨", "慕尼黑"], school: "唯名论／方济各会经院哲学", figureId: "ockham", chapterIds: ["b2-14", "b2-15"],
    thesis: "解释不应无必要地增加实体；只有个体在世界中存在，共相是心灵符号的自然指称功能，而非个体之外的共同物。",
    evidenceCaution: "‘如无必要，勿增实体’不是其作品中固定出现的原句；剃刀是多种中世纪简约原则的后世名称。其被逐出教会的确切法律状态也有技术争议。",
    lifeSummary: "奥卡姆是英国方济各会士，在牛津讲授但未完成神学硕士程序。被召到阿维尼翁审查神学观点时，他卷入方济各会绝对贫穷与教皇权力争论，1328 年逃离并投靠皇帝路易四世，在慕尼黑写作政治论著。其逻辑、认识论和政治思想共同限制不必要权威。",
    timeline: [
      { date: "约 1317—1324", place: "牛津／伦敦", title: "讲授与写作逻辑神学", detail: "形成《逻辑大全》和《命题集注释》等核心材料。", certainty: "较可靠" },
      { date: "1324", place: "阿维尼翁", title: "接受教义审查", detail: "多个命题被委员会调查，程序持续多年。", certainty: "较可靠" },
      { date: "1328", place: "阿维尼翁—比萨", title: "逃离教廷", detail: "与方济各会总会长同行，转而寻求皇帝保护。", certainty: "较可靠" },
      { date: "约 1347", place: "慕尼黑", title: "去世", detail: "可能死于黑死病前后，年份仍有小幅争议。", certainty: "推定" },
    ],
    inquiries: [
      { object: "共相与符号", question: "一个概念怎样代表许多个体，却不需要共同实体？", start: "若假设现实共相，会增加难以说明的实体和个体化问题。", steps: ["只承认苏格拉底等个体在世界中存在", "把概念理解为心灵语言中的自然符号", "用指代理论说明同一概念可站在多个对象位置", "按解释需要拒绝多余的种属实体"], conclusion: "普遍性属于符号的可指称方式，而不属于一个额外的普遍物；逻辑分析替代本体增殖。" },
      { object: "政治权威", question: "教皇是否拥有不受限制的属灵与世俗权力？", start: "绝对权力会威胁福音自由、财产权争论中的良心和世俗共同体秩序。", steps: ["区分正常管辖与紧急权力主张", "允许教皇可能陷入异端和错误", "让教会共同体、会议或世俗权威在危机中纠正", "以信徒自由限制纯粹专断"], conclusion: "教皇权威不是无限的；异端与暴政情况下存在纠正和抵抗空间。" },
    ],
    concepts: [
      { zh: "奥卡姆剃刀", en: "Ockham's razor", definition: "在解释充分时不无必要增加实体或假设；是方法约束，不保证最简单理论必真。" },
      { zh: "心灵语言", en: "mental language", definition: "先于约定口语的概念符号系统，其项自然指称世界中的个体。" },
      { zh: "直观认识", en: "intuitive cognition", definition: "使主体能判断对象是否存在及其偶然事实的认识方式，与抽象认识相区分。" },
      { zh: "唯名论", en: "nominalism", definition: "拒绝现实共相并用符号功能说明普遍谓述；不等于认为分类全是任意名字。" },
    ],
    lineage: { inherited: "承接阿伯拉尔以来语言分析、司各脱的个体与自由问题以及方济各会贫穷争论。", school: "十四世纪唯名论、逻辑与方济各会政治思想的中心人物。", influenced: "影响晚期中世纪逻辑、自然哲学、教会政治和后世简约方法论，但近代科学并非由一把剃刀直接产生。", parallel: "与马西略都限制教皇权力；奥卡姆从信徒权利和异端纠正出发，马西略从政治共同体和立法权出发。" },
    comparisons: [
      { target: "邓斯·司各脱", relation: "承接前人", shared: "个体优先、意志自由和精密模态分析。", difference: "奥卡姆拒绝共同本性、此性与形式区别等实体性装置。" },
      { target: "彼得·阿伯拉尔", relation: "后世重构", shared: "用语言与概念功能解决共相问题。", difference: "奥卡姆拥有成熟的心灵语言、指代和推论理论。" },
      { target: "帕多瓦的马西略", relation: "同题比较", shared: "教皇不拥有无限世俗强制权。", difference: "奥卡姆保留较强教会制度并强调权利与纠错；马西略把强制立法权归于公民整体。" },
    ],
    stars: 5, culturalNotes: [{ kind: "名言", title: "“如无必要，勿增实体”", text: "这句常用来解释奥卡姆剃刀：能用较少假设说明时，不要平白增加看不见的东西。", caveat: "流行拉丁公式不是奥卡姆作品中的固定原句，也不是‘最简单答案必然正确’。" }],
    russellView: "罗素把奥卡姆视为经院综合解体和近代精神出现的标志：唯名论削弱神学证明，政治著作反对教皇绝对权力，哲学重新获得相对独立。",
    modernCorrection: "‘最后的经院哲学家／第一个现代人’是有力但线性的叙事。奥卡姆仍深处方济各神学与中世纪逻辑，其简约原则也不是经验科学的万能口号。",
    sources: [russellSource("第二卷第十四至十五章"), sepSource("William of Ockham", "ockham")],
  },
  {
    id: "marsilius-padua", order: 53, nameZh: "帕多瓦的马西略", nameEn: "Marsilius of Padua", greekName: "Marsilius Patavinus", dates: "约 1275/80—约 1342", active: "14 世纪前半叶", places: ["帕多瓦", "巴黎", "纽伦堡", "慕尼黑"], school: "中世纪政治哲学", figureId: "marsilius-padua", chapterIds: ["b2-14", "b2-15"],
    thesis: "政治法律的有效强制权来自公民整体或其较有分量部分；教士可教导与施行圣礼，却不因神职自动拥有独立强制管辖。",
    evidenceCaution: "《和平保卫者》文本明确，但‘人民主权’‘民主主义’都是现代近似词；其公民整体、较有分量部分与皇帝角色不等同于普选民主。",
    lifeSummary: "马西略受过医学训练，曾任巴黎大学校长。他与让丹的约翰合写或合作形成《和平保卫者》，在教皇约翰二十二世与皇帝路易四世冲突中逃往帝国宫廷。著作把教会权力争论转成法律来源、共同善与社会和平的制度分析。",
    timeline: [
      { date: "1313", place: "巴黎", title: "任巴黎大学校长", detail: "显示其位于医学、自然哲学与政治网络交点。", certainty: "较可靠" },
      { date: "1324", place: "巴黎", title: "完成《和平保卫者》", detail: "著作匿名流传，很快被认定具有激进反教皇含义。", certainty: "较可靠" },
      { date: "1326", place: "巴黎—纽伦堡", title: "逃往路易四世宫廷", detail: "与让丹的约翰一同遭教皇谴责。", certainty: "较可靠" },
      { date: "1328", place: "罗马", title: "参与皇帝意大利行动", detail: "在废立教皇的政治实验中承担宣传与教会安排角色。", certainty: "较可靠" },
    ],
    inquiries: [{ object: "法律与和平", question: "谁有权制定可强制执行的政治法律，才能避免相互竞争的最高权威破坏和平？", start: "教皇若主张独立且最高的强制权，便与城市、王国和帝国法律产生双重主权冲突。", steps: ["把共同体自足生活与和平设为政治目的", "将立法者定义为公民整体或其较有分量部分", "让政府执行由立法者授权的法律", "把教士职能限制为教导、圣礼和无强制裁判"], conclusion: "世俗政治共同体是强制法的来源；教会争议应由代表信徒的普遍会议处理。" }],
    concepts: [
      { zh: "人类立法者", en: "human legislator", definition: "公民整体或其较有分量部分，是政治强制法的直接有效原因。" },
      { zh: "和平", en: "peace / tranquillity", definition: "各社会部分按其职能协调运作的秩序，是政治共同体充分生活的条件。" },
      { zh: "教会无强制权", en: "non-coercive priesthood", definition: "教士以教导和圣礼服务灵魂，今世强制惩罚需由政治立法者授权。" },
      { zh: "大公会议主义", en: "conciliarism", definition: "普遍会议代表信徒共同体，可在教义和治理危机中高于单个教皇。" },
    ],
    lineage: { inherited: "继承亚里士多德政治共同体分析、巴黎自然哲学与帝国—教皇冲突经验。", school: "十四世纪世俗与会议主义政治哲学。", influenced: "影响后期会议主义、反教皇论争与近代国家思想的某些资源，但不存在直线通往民主国家。", parallel: "与奥卡姆共同投靠路易四世并反对教皇绝对权力，论证基础和教会观却不相同。" },
    comparisons: [
      { target: "亚里士多德", relation: "后世重构", shared: "城邦是为充分生活形成的部分秩序，共同善需要法律。", difference: "马西略在拉丁基督教双重权威冲突中重写立法者与强制权。" },
      { target: "奥卡姆的威廉", relation: "同题比较", shared: "教皇权力可犯错且不应吞并世俗政治。", difference: "马西略更彻底取消教士独立强制权，强调公民立法者和会议。" },
      { target: "米兰的安布罗斯", relation: "同题比较", shared: "教会与政治权力的边界决定公共秩序。", difference: "安布罗斯以主教纪律约束皇帝；马西略反向限制教士强制权。" },
    ],
    stars: 4, culturalNotes: [{ kind: "生活印象", title: "一位从大学校长变成政治流亡者的医生", text: "马西略受医学训练、做过巴黎大学校长，最终因一本政治书逃到皇帝宫廷。他把社会失调写得像身体各部分争夺功能造成的疾病。" }],
    russellView: "罗素把马西略视为远超时代的政治思想家，赞赏其人民立法、会议高于教皇和教会不应有强制权等主张，并把他纳入教皇制衰落叙事。",
    modernCorrection: "‘民主先驱’需要限制：其公民共同体排除范围很大，‘较有分量部分’可能容纳精英结构，对路易四世的支持也不是现代世俗共和国方案。",
    sources: [russellSource("第二卷第十四至十五章"), sepSource("Marsilius of Padua", "marsilius-padua")],
  },
];
