export type ProblemNodeKind = "观察" | "问题" | "答案";
export type ProblemAnswerRole = "提出" | "区分" | "反驳" | "修复" | "转向" | "综合";
export type ProblemRelationKind = "提出问题" | "回应问题" | "产生问题";
export type ProblemConnectionKind = "原书线索" | "历史回应" | "同题并列" | "本站推演" | "后世重构";
export type ProblemObservationDomain = "自然经验" | "个体体验" | "社会与制度" | "历史变化" | "知识实践";

export type ProblemHistoryLink = {
  stageId: string;
  responseId?: string;
  eventId?: string;
  label: string;
  note: string;
};

export type ProblemObservationContext = {
  domain: ProblemObservationDomain;
  note: string;
  historyLinks?: ProblemHistoryLink[];
};

export type ProblemParticipant = {
  name: string;
  philosopherId?: string;
  role: string;
};

export type ProblemGraphPosition = {
  row: number;
  lane: number;
};

export type ProblemNode = {
  id: string;
  kind: ProblemNodeKind;
  answerRole?: ProblemAnswerRole;
  observation?: ProblemObservationContext;
  title: string;
  summary: string;
  pressure: string;
  consequence: string;
  participants: ProblemParticipant[];
  chapterIds: string[];
  graph: ProblemGraphPosition;
};

export type ProblemEdge = {
  id: string;
  from: string;
  to: string;
  relation: ProblemRelationKind;
  label: string;
  connection: ProblemConnectionKind;
};

export type ProblemPhase = {
  id: string;
  order: number;
  label: string;
  title: string;
  question: string;
  transition: string;
  nodes: ProblemNode[];
};

export type ProblemMapSource = {
  label: string;
  url: string;
  note: string;
};

export type ProblemMap = {
  id: string;
  title: string;
  english: string;
  period: string;
  thesis: string;
  scopeNote: string;
  phases: ProblemPhase[];
  edges: ProblemEdge[];
  sources: ProblemMapSource[];
};

export const problemConnectionNotes: Record<ProblemConnectionKind, string> = {
  原书线索: "罗素原书的章节安排或评价提供了这一步的叙述线索。",
  历史回应: "有较强理由把它理解为对既有困难的历史性回应。",
  同题并列: "思想家处理的是相近问题，但不据此主张直接影响。",
  本站推演: "为降低理解成本而建立的逻辑连接，不冒充思想家本人的明确论证。",
  后世重构: "使用后来的概念重新看见早期问题，须防止把术语倒灌给古人。",
};

export const problemRelationNotes: Record<ProblemRelationKind, string> = {
  提出问题: "观察使一个尚未由既有答案产生的困难变得可追问。",
  回应问题: "答案尝试回应问题；同一问题可以有多个并列答案。",
  产生问题: "答案解决部分困难，同时留下限制、矛盾或新的解释负担。",
};

export const ancientDifferenceProblemMap: ProblemMap = {
  id: "difference-change-knowledge",
  title: "从多样与变化到启示、恩典与两座城",
  english: "OBSERVATION → QUESTION → ANSWER → NEW QUESTION",
  period: "第一卷至第二卷第四章 · 泰勒斯至奥古斯丁",
  thesis: "从自然中的多样、变化和秩序出发，经由知识、实体、因果与好生活，继续追踪城邦瓦解、帝国角色、精神内向化和经文共同体怎样重新提出自由、创造、恶、恩典与历史的问题。",
  scopeNote: "这不是一条被古代与教父作者共同承认的师承路线，也不是把原书改写成单线进步史。图中只有观察、问题和答案三类节点；人物作为参与者附着其上。历史变化只在确实改变问题条件时进入观察层，连线同时说明逻辑作用与证据性质。当前向前推进一个完整阶段，止于第二卷第四章奥古斯丁。",
  phases: [
    {
      id: "encounter-difference",
      order: 1,
      label: "经验起点",
      title: "把并存的多样与时间中的变化拆开",
      question: "多样的来源、变化的过程与同一、持续秩序，分别要求怎样的解释？",
      transition: "入口把并存多样、状态变化、条件关联、周期重复和过程持续拆成五个观察维度；它们可以相互重叠，但分别施加不同的解释压力。",
      nodes: [
        {
          id: "difference-as-observation",
          kind: "观察",
          observation: {
            domain: "自然经验",
            note: "记录同一时刻并存的事物与性质差异，不预先指定它们是否同源。",
            historyLinks: [{
              stageId: "origins",
              responseId: "milesians",
              eventId: "ionian-network",
              label: "爱奥尼亚海上网络与跨地域知识接触",
              note: "进入历史概览查看航海、贸易、历法和跨文化比较怎样使自然差异成为可持续讨论的对象。",
            }],
          },
          title: "同一时刻，世界包含彼此不同的事物与性质",
          summary: "石头、植物、火焰和水彼此不同；同一环境中也同时出现冷与热、干与湿、轻与重等性质。这里首先记录并存的多样性，不预设它来自一种还是多种本原。",
          pressure: "仅仅列举差异，不能说明这些差异是否共享来源、怎样组成同一个世界。",
          consequence: "观察提出多样的来源问题，也让“多个事物是否真正可能”成为后续压力。",
          participants: [],
          chapterIds: ["b1-01", "b1-02", "b1-03", "b1-04"],
          graph: { row: 0, lane: 0 },
        },
        {
          id: "change-over-time-observation",
          kind: "观察",
          observation: {
            domain: "自然经验",
            note: "只记录同一对象的前后状态差异；变化条件、周期与持续同一分别作为相邻观察展开。",
          },
          title: "同一事物会在时间中呈现不同状态",
          summary: "种子长成植物，水受热改变状态，人从清醒进入睡眠。这里先记录前后状态不同，不把变化机制、触发条件或周期秩序提前写入观察。",
          pressure: "描述两个状态还不足以说明变化怎样发生，也不能自动证明改变前后属于同一对象。",
          consequence: "观察提出变化中的同一与运动是否可能等问题，并与条件关联、周期重复及过程持续的观察共同形成解释压力。",
          participants: [],
          chapterIds: ["b1-02", "b1-04", "b1-05", "b1-06", "b1-09"],
          graph: { row: 0, lane: 1 },
        },
        {
          id: "conditional-change-observation",
          kind: "观察",
          observation: {
            domain: "自然经验",
            note: "记录条件与结果的可重复关联，不预先把它提升为现代因果律。",
          },
          title: "相似条件经常伴随相似变化",
          summary: "水受热后趋向沸腾，材料受压、受冷或混合时也常出现可预期的结果。人能够主动制造条件并重复观察变化，但这还不是一套成熟因果理论。",
          pressure: "事件相继出现不等于已经说明作用怎样传递，也不能保证所有相似次序都具有同一种原因。",
          consequence: "观察要求解释变化机制，也要求说明为什么世界呈现可重复而非任意的次序。",
          participants: [],
          chapterIds: ["b1-02", "b1-06", "b1-09"],
          graph: { row: 0, lane: 2 },
        },
        {
          id: "recurring-change-observation",
          kind: "观察",
          observation: {
            domain: "自然经验",
            note: "记录持续、往复与周期变化；它可能没有一个可单独指出的首次触发事件。",
          },
          title: "有些变化持续、往复或周期性重复",
          summary: "昼夜、季节、天体运动、火焰和生命过程不是一次变化后便停止，而呈现持续、往复或周期性的次序。",
          pressure: "如果找不到一次性的外部触发，仍需说明过程为什么继续、为什么保持尺度，又为什么能够重复。",
          consequence: "观察把动力问题与秩序问题连接起来，为时间平衡、比例与逻各斯等答案提供经验压力。",
          participants: [],
          chapterIds: ["b1-02", "b1-03", "b1-04", "b1-06"],
          graph: { row: 0, lane: 3 },
        },
        {
          id: "persistent-process-observation",
          kind: "观察",
          observation: {
            domain: "自然经验",
            note: "记录构成不断替换时仍被识别为同一整体的经验，不预先决定同一来自材料、形式还是关系。",
          },
          title: "构成持续更替的过程仍可能被认作同一",
          summary: "河流的水、火焰的燃料和生命体的材料不断更替，但人仍会把它们识别为同一条河、同一团火或同一个生命过程。",
          pressure: "若材料相同才保证同一，这些持续过程便难以理解；若关系或活动保证同一，又要说明它怎样保持。",
          consequence: "观察使变化机制与同一标准不能分开处理，并为赫拉克利特式过程答案提供经验入口。",
          participants: [],
          chapterIds: ["b1-04", "b1-13"],
          graph: { row: 0, lane: 4 },
        },
        {
          id: "difference-derived-or-original",
          kind: "问题",
          title: "多样来自共同来源，还是原本就有多个要素？",
          summary: "如果许多事物来自同一来源，就要说明统一来源怎样产生差异；如果差异原本就有多个要素，又要说明多个要素为什么形成一个世界。",
          pressure: "给本原命名只能提出候选来源，不能独自解释多样怎样出现并保持。",
          consequence: "问题向一种基础来源、从无定者分出对立、由气连续变形三种米利都答案开放；比例和逻各斯则主要回答秩序问题。",
          participants: [],
          chapterIds: ["b1-02", "b1-03", "b1-04", "b1-06"],
          graph: { row: 1, lane: 0.5 },
        },
        {
          id: "identity-through-change",
          kind: "问题",
          title: "变化通过什么过程发生，又如何保留同一？",
          summary: "变化要求前后状态不同，识别变化又要求把这些状态归给同一对象。问题因此同时追问：改变以什么过程发生，材料、结构、关系或持续活动中又有什么使前后仍可联系。",
          pressure: "若只有触发事件而没有变化机制，就不能说明作用怎样成为结果；若不说明同一性的根据，“某物改变”又可能退化为一个事物消失、另一个出现。",
          consequence: "问题向连续程度变化与以持续过程维持同一两种主要答案开放。",
          participants: [],
          chapterIds: ["b1-02", "b1-04", "b1-05"],
          graph: { row: 1, lane: 2 },
        },
        {
          id: "order-not-arbitrary-agency",
          kind: "问题",
          title: "为什么变化呈现稳定次序，而不是任意发生？",
          summary: "早期自然哲学没有简单排除神圣，却开始把季节、天体和生成消灭理解成世界内部可以说明的次序，而不只诉诸一次性的行动者。",
          pressure: "重复与周期不等于现代意义的“自然规律”；它们首先要求说明次序、尺度和可理解性从何而来。",
          consequence: "问题可以获得时间平衡、连续机制、数与比例、逻各斯与对立秩序等不同答案。",
          participants: [],
          chapterIds: ["b1-02", "b1-03", "b1-04"],
          graph: { row: 1, lane: 3.5 },
        },
      ],
    },
    {
      id: "generate-difference",
      order: 2,
      label: "自然解释",
      title: "用世界内部的来源、过程与秩序回答",
      question: "多样与变化能否由自然自身得到说明？",
      transition: "这些答案回应多个上游问题，彼此不是一条单线演进；同一答案也可能同时说明来源、动力和秩序。",
      nodes: [
        {
          id: "one-source-many-states",
          kind: "答案",
          answerRole: "提出",
          title: "以一种基础来源统一自然的多样",
          summary: "关于泰勒斯的可靠材料极少；亚里士多德把水解释为他的第一原理。可以谨慎地说，这一路线尝试让自然现象由自然内部的一种基础来源得到统一。",
          pressure: "它首先回答“多样是否同源”，但不能据现存材料替泰勒斯补出成熟的状态转换理论。",
          consequence: "一种来源怎样真正形成多种事物，仍成为生成问题。",
          participants: [{ name: "泰勒斯", philosopherId: "thales", role: "以水作为自然统一来源的传统起点" }],
          chapterIds: ["b1-02"],
          graph: { row: 2, lane: 0 },
        },
        {
          id: "opposites-and-process",
          kind: "答案",
          answerRole: "提出",
          title: "对立从无定者中分出，并按时间恢复平衡",
          summary: "阿那克西曼德让热与冷等对立力量从无定者中分出；事物依时间秩序彼此补偿，季节、天体运行和生成消灭因此构成世界内部的循环系统。",
          pressure: "它不只给出来源，还试图说明多样、变化和反复次序怎样属于同一个自然过程。",
          consequence: "分出与复归仍留下生成在逻辑上能否成立的问题。",
          participants: [{ name: "阿那克西曼德", philosopherId: "anaximander", role: "以无定者、对立力量和时间秩序组织自然" }],
          chapterIds: ["b1-02"],
          graph: { row: 2, lane: 1 },
        },
        {
          id: "rarefaction-condensation",
          kind: "答案",
          answerRole: "提出",
          title: "气通过稀薄与凝聚连续变形",
          summary: "阿那克西美尼以气为基础来源，并用稀薄和凝聚说明火、风、云、水、土与石的连续序列；冷热也与这一过程联系。",
          pressure: "它把“来自同一来源”推进为一个可以用程度差异理解的变化机制。",
          consequence: "连续机制说明了怎样变化，却仍要面对生成、同一与存在之间的逻辑压力。",
          participants: [{ name: "阿那克西美尼", philosopherId: "anaximenes", role: "以稀薄和凝聚说明连续变化" }],
          chapterIds: ["b1-02"],
          graph: { row: 2, lane: 2 },
        },
        {
          id: "difference-as-ratio",
          kind: "答案",
          answerRole: "提出",
          title: "数与比例使差异和秩序可以理解",
          summary: "毕达哥拉斯传统从音程与数的关系发展出数学秩序的方向；完整的数学宇宙论主要属于后来的毕达哥拉斯学派，不能无保留地归给毕达哥拉斯本人。",
          pressure: "只列举材料不能解释音程、结构和天体次序为何可以通过比例理解。",
          consequence: "“由什么构成”之外，出现了“按什么关系组织”以及这种结构如何成为知识对象的问题。",
          participants: [{ name: "毕达哥拉斯", philosopherId: "pythagoras", role: "代表数、比例与宇宙秩序的传统起点" }],
          chapterIds: ["b1-03", "b1-13", "b1-24"],
          graph: { row: 2, lane: 3 },
        },
        {
          id: "change-as-order",
          kind: "答案",
          answerRole: "区分",
          title: "对立转换本身构成持续的世界秩序",
          summary: "赫拉克利特把对立状态、持续转换与逻各斯联系起来。河流、火焰和生命显示：某些事物不是排除变化才保持，而是在有次序的变化中持续。",
          pressure: "它同时回应变化中的同一、动力与秩序，但不能被简化成“任何事物在任何方面都不断变化”。",
          consequence: "变化成为秩序的一部分，也使生成、存在和同一能否同时成立更加尖锐。",
          participants: [{ name: "赫拉克利特", philosopherId: "heraclitus", role: "以逻各斯和对立连接变化与秩序" }],
          chapterIds: ["b1-04", "b1-13"],
          graph: { row: 2, lane: 4 },
        },
      ],
    },
    {
      id: "eleatic-pressure",
      order: 3,
      label: "逻辑压力",
      title: "变化在逻辑上是否可能",
      question: "生成、运动与多个事物会不会要求我们谈论不存在？",
      transition: "埃利亚路线不是补充另一种自然机制，而是检查此前答案所使用的“生成”和“运动”是否说得通。",
      nodes: [
        {
          id: "being-from-nonbeing",
          kind: "问题",
          title: "生成是否意味着存在从不存在中出现？",
          summary: "若某物真的成为它原本不是的东西，新的存在从哪里来？谈论和思考一个完全不存在的起点是否可能？",
          pressure: "此前答案描述了变化过程，却没有先说明产生和消灭在逻辑上是否成立。",
          consequence: "问题要求一种不依赖从无到有的存在说明。",
          participants: [],
          chapterIds: ["b1-05"],
          graph: { row: 3, lane: 1 },
        },
        {
          id: "motion-and-plurality-possible",
          kind: "问题",
          title: "运动和多个事物在概念上可能吗？",
          summary: "经验似乎直接给出运动和多个对象，但连续、分割和路径一旦被严格分析，常识是否仍然自洽？",
          pressure: "“我们明明看见运动”不能独自回答无限分割和多个对象如何成立。",
          consequence: "问题同时获得巴门尼德式否定和芝诺式压力测试。",
          participants: [],
          chapterIds: ["b1-05"],
          graph: { row: 3, lane: 3 },
        },
        {
          id: "stable-being",
          kind: "答案",
          answerRole: "提出",
          title: "真正的存在必须保持同一",
          summary: "在严格解释中，真正存在不生不灭、不分割、不运动；日常经验中的多样和变化不能未经检验地充当最终实在。",
          pressure: "它保存了存在的可思与同一，却扩大了理性与经验之间的裂缝。",
          consequence: "若基本存在不变，可见变化必须被重新解释。",
          participants: [{ name: "巴门尼德", philosopherId: "parmenides", role: "把自然问题改写为存在条件问题" }],
          chapterIds: ["b1-05", "b1-15", "b1-18"],
          graph: { row: 4, lane: 1 },
        },
        {
          id: "test-motion-and-plurality",
          kind: "答案",
          answerRole: "反驳",
          title: "以悖论检验运动与多样",
          summary: "埃利亚的芝诺用悖论迫使对手说明连续、分割、多个对象和运动怎样同时成立，而不是把常识当作无需论证的答案。",
          pressure: "悖论没有提供一套完整自然理论，却提高了任何变化理论必须承受的概念精度。",
          consequence: "保存变化的答案必须让基本存在稳定，同时重写可见生成。",
          participants: [{ name: "埃利亚的芝诺", role: "以悖论检验运动与多样" }],
          chapterIds: ["b1-05"],
          graph: { row: 4, lane: 3 },
        },
      ],
    },
    {
      id: "preserve-and-recombine",
      order: 4,
      label: "多元修复",
      title: "保存存在，重写变化",
      question: "如果基本存在不生成也不消灭，可见世界还能怎样变化？",
      transition: "同一个新问题产生三种并列答案：基本构成保持不变，变化转由结合、分离、位置或比例承担。",
      nodes: [
        {
          id: "change-as-reconfiguration",
          kind: "问题",
          title: "不变的构成怎样形成变化的世界？",
          summary: "如果接受基本存在不能从无到有，就要说明原有构成怎样形成新整体，又怎样在整体解体时继续存在。",
          pressure: "它必须同时保住埃利亚的存在约束和经验中无法否认的变化。",
          consequence: "问题向四根与爱争、混合与努斯、原子与虚空三种答案开放。",
          participants: [],
          chapterIds: ["b1-06", "b1-08", "b1-09"],
          graph: { row: 5, lane: 2 },
        },
        {
          id: "roots-love-strife",
          kind: "答案",
          answerRole: "修复",
          title: "四根不变，爱与争改变比例",
          summary: "火、气、水、土不产生也不消灭；爱使它们结合，争使它们分离。可见事物来自混合比例，宇宙循环来自两种力量轮流占优。",
          pressure: "它用多种稳定材料与动力原则共同解释整体形成。",
          consequence: "自然过程也延伸到感觉：外物与身体怎样相遇成为新问题。",
          participants: [{ name: "恩培多克勒", philosopherId: "empedocles", role: "以根和力量重写生成" }],
          chapterIds: ["b1-06"],
          graph: { row: 6, lane: 0.5 },
        },
        {
          id: "mixture-nous-separation",
          kind: "答案",
          answerRole: "修复",
          title: "成分原已在场，努斯启动分离",
          summary: "所谓产生，是原本混合的成分在旋转和分离中取得优势并显现；努斯启动宇宙运动，具体世界仍通过自然过程展开。",
          pressure: "若后来出现的性质原先完全不存在，就会重新落入从不存在产生存在的困难。",
          consequence: "连续性得到保存，却留下努斯究竟解释启动、秩序还是目的的问题。",
          participants: [{ name: "阿那克萨哥拉", philosopherId: "anaxagoras", role: "以努斯和分离组织混合物" }],
          chapterIds: ["b1-08", "b1-13"],
          graph: { row: 6, lane: 2 },
        },
        {
          id: "atoms-void-arrangement",
          kind: "答案",
          answerRole: "修复",
          title: "原子不变，排列产生现象差异",
          summary: "留基伯和德谟克利特以不可分原子与虚空保存运动；事物的形成和性质差异由原子的组合、位置与排列解释。",
          pressure: "运动需要空处，性质变化又要在不改变基本单位的前提下得到解释。",
          consequence: "颜色、味道和痛苦是在原子中，还是发生于对象与感觉者的相遇中？",
          participants: [
            { name: "留基伯", philosopherId: "leucippus", role: "建立原子论框架" },
            { name: "德谟克利特", philosopherId: "democritus", role: "扩展自然与知觉解释" },
          ],
          chapterIds: ["b1-09"],
          graph: { row: 6, lane: 3.5 },
        },
        {
          id: "what-does-nous-explain",
          kind: "问题",
          title: "努斯解释的是启动、秩序还是目的？",
          summary: "阿那克萨哥拉以努斯启动宇宙旋转，却让此后的分离过程主要依照自然机制展开。努斯究竟只是第一推动，还是也解释世界的秩序与目的？",
          pressure: "若努斯只在开端出现，它与其他机械原因有何不同；若它持续安排世界，又需要说明安排的范围和方式。",
          consequence: "这条支线在本谱系暂时开放，并将在目的解释与机械解释的后续谱系中重新出现。",
          participants: [{ name: "阿那克萨哥拉", philosopherId: "anaxagoras", role: "留下努斯的解释范围问题" }],
          chapterIds: ["b1-08", "b1-13"],
          graph: { row: 7, lane: 2 },
        },
      ],
    },
    {
      id: "from-perception-to-knowledge",
      order: 5,
      label: "认识转向",
      title: "体验到变化，等于认识真实么",
      question: "感觉呈现外物、相遇关系还是感觉者状态；共同知识又需要什么尺度？",
      transition: "关于世界构成的答案反过来改变知识问题：观察者不再站在变化之外。",
      nodes: [
        {
          id: "same-thing-different-appearance",
          kind: "观察",
          observation: {
            domain: "个体体验",
            note: "记录感觉内容随感觉者处境而异；它不直接判定外物性质是否真实。",
          },
          title: "同一事物对不同的人显现不同",
          summary: "同一阵风对一人显冷，对另一人却不冷。感觉确实发生，但感觉内容并不总能直接成为所有人共享的对象性质。",
          pressure: "差异不能只归给外物，也不能只归给感觉者而不作说明。",
          consequence: "观察与早期感觉理论共同提出“感觉究竟呈现什么”的问题。",
          participants: [],
          chapterIds: ["b1-10", "b1-18"],
          graph: { row: 8, lane: 0 },
        },
        {
          id: "public-disagreement-observation",
          kind: "观察",
          observation: {
            domain: "社会与制度",
            note: "雅典的民主法庭、公共演说和职业教育使互相冲突的判断在同一公共空间中竞争，真理与说服的差别因而具有制度后果。",
            historyLinks: [
              {
                stageId: "athens",
                responseId: "sophists",
                eventId: "athenian-democracy",
                label: "民主、帝国与公共辩论扩张",
                note: "进入历史概览查看公共判断、智者教育与知识标准为何在雅典成为紧迫问题。",
              },
            ],
          },
          title: "公共生活让相互冲突的判断同时争夺有效性",
          summary: "同一案件可以由双方演说者提出相反论证，多数决定又会产生真实政治后果。能说服公众与知道何为正义，不再能被默认成同一件事。",
          pressure: "如果公共判断只剩修辞胜负，城邦如何区分较好的意见、知识和权势？",
          consequence: "这一历史处境与感觉差异共同提出：不同显现和意见之间是否存在可以共同辩护的尺度？",
          participants: [],
          chapterIds: ["b1-07", "b1-10", "b1-11", "b1-18"],
          graph: { row: 8, lane: 4 },
        },
        {
          id: "what-does-perception-reveal",
          kind: "问题",
          title: "感觉呈现的是外物、关系还是自身状态？",
          summary: "如果感觉本身也是身体发生的变化，它可以真实发生，却仍可能不足以独自确定外部原因。",
          pressure: "自然哲学已经说明外物与身体都在过程中，观察者不能继续被放在变化之外。",
          consequence: "问题获得自然化的感觉说明和以感觉者为尺度的两种相关答案。",
          participants: [],
          chapterIds: ["b1-06", "b1-09", "b1-10", "b1-18"],
          graph: { row: 9, lane: 2 },
        },
        {
          id: "perception-as-event",
          kind: "答案",
          answerRole: "区分",
          title: "体验是对象与感觉者之间的事件",
          summary: "外物作用于身体，身体发生改变，颜色、声音、冷热或痛苦才成为显现。“我确实感到痛”与“我知道痛由什么造成”不是同一个判断。",
          pressure: "它区分体验发生、对象判断和原因解释。",
          consequence: "感觉的真实性仍不能独自提供共同判断标准。",
          participants: [
            { name: "恩培多克勒", philosopherId: "empedocles", role: "尝试自然化感觉过程" },
            { name: "德谟克利特", philosopherId: "democritus", role: "区分基本构成与感官性质" },
          ],
          chapterIds: ["b1-06", "b1-09", "b1-18"],
          graph: { row: 10, lane: 1.2 },
        },
        {
          id: "appearance-relative-to-perceiver",
          kind: "答案",
          answerRole: "提出",
          title: "显现以感觉者的处境为尺度",
          summary: "普罗泰戈拉的尺度命题把显现、感觉者处境和判断联系起来，但其确切范围主要通过柏拉图等后世材料传达。",
          pressure: "它认真保存每个人当下显现的地位。",
          consequence: "如果不同显现都成立，共同判断真假的尺度在哪里？",
          participants: [{ name: "普罗泰戈拉", philosopherId: "protagoras", role: "把人的显现置于尺度位置" }],
          chapterIds: ["b1-10", "b1-18"],
          graph: { row: 10, lane: 3.4 },
        },
        {
          id: "common-standard-of-judgment",
          kind: "问题",
          title: "不同显现之间有没有共同判断尺度？",
          summary: "如果同一事物可以对不同人呈现不同性质，我们凭什么区分当下显现、关于对象的判断和可以共同辩护的知识？",
          pressure: "感觉事件和尺度答案都说明差异，却没有充分说明公共判断如何可能。",
          consequence: "问题从报告经验转向追问定义、理由与共同对象。",
          participants: [],
          chapterIds: ["b1-10", "b1-11", "b1-18"],
          graph: { row: 11, lane: 2.7 },
        },
        {
          id: "definition-beyond-instance",
          kind: "答案",
          answerRole: "转向",
          title: "从个别实例追问共同定义",
          summary: "苏格拉底式问答要求从许多个案返回定义，并检验信念是否相互一致。列举快乐、痛苦或勇敢行为，不等于知道快乐、勇敢和善是什么。",
          pressure: "它把共同尺度放在可说明、可检验的定义，而不只是感觉报告中。",
          consequence: "定义又要求说明：知识究竟把握怎样稳定的对象？",
          participants: [{ name: "苏格拉底", philosopherId: "socrates", role: "以反诘追问共同定义" }],
          chapterIds: ["b1-11", "b1-13"],
          graph: { row: 12, lane: 2.2 },
        },
        {
          id: "how-order-soul-and-polis",
          kind: "问题",
          title: "共同尺度若存在，灵魂与城邦应怎样按它组织？",
          summary: "知识标准不只评价命题，也会评价欲望、教育、分工和统治资格。柏拉图把个人内部冲突与城邦政治失序看作可以相互照见的结构问题。",
          pressure: "把政治秩序类比为灵魂秩序可能揭示功能关系，也可能把社会等级过快自然化。",
          consequence: "正义被回答为各部分在整体中履行适当功能。",
          participants: [],
          chapterIds: ["b1-12", "b1-13", "b1-14"],
          graph: { row: 12, lane: 4 },
        },
        {
          id: "justice-as-ordered-whole",
          kind: "答案",
          answerRole: "综合",
          title: "正义是灵魂与城邦各部分在整体中形成秩序",
          summary: "《理想国》把理性、意气和欲望的关系，与治理、护卫和生产功能相互映照；哲学教育的任务是让善的知识成为整体尺度。",
          pressure: "这一模型以知识资格限制政治参与，并可能把统一压过差异、自由和现实制度经验。",
          consequence: "若理性灵魂能够把握稳定形式，它与可朽身体的关系又是什么？",
          participants: [{ name: "柏拉图", philosopherId: "plato", role: "以灵魂—城邦类比连接知识、德性与政治秩序" }],
          chapterIds: ["b1-12", "b1-14"],
          graph: { row: 13, lane: 4 },
        },
        {
          id: "can-soul-survive-body",
          kind: "问题",
          title: "把握不变形式的灵魂是否能独立于身体延续？",
          summary: "若知识要求灵魂转离不断变化的感觉，死亡可能被理解为灵魂与身体的分离；但认识活动在现实生活中又明显依赖感官与身体。",
          pressure: "从知识对象稳定直接推出灵魂不朽并不充分，回忆、相似、生命原则等论证各有额外前提。",
          consequence: "柏拉图以多组论证和神话把哲学生活连接到灵魂净化与不朽。",
          participants: [],
          chapterIds: ["b1-16"],
          graph: { row: 14, lane: 4 },
        },
        {
          id: "immortal-rational-soul",
          kind: "答案",
          answerRole: "提出",
          title: "理性灵魂通过净化与观照趋向不变真实",
          summary: "柏拉图的不同对话以回忆、对立生成、灵魂与生命的关联及神话叙事支持灵魂不随身体一同消灭；哲学由此成为学习死亡与重新定向欲望。",
          pressure: "这些论证并非一个无争议的单一证明，灵魂各部分、个人身份与死后状态也存在文本差异。",
          consequence: "灵魂若能趋向可知秩序，可见宇宙本身是否也按形式和善得到组织？",
          participants: [{ name: "柏拉图", philosopherId: "plato", role: "把知识、哲学生活与灵魂不朽的多种论证连接" }],
          chapterIds: ["b1-16"],
          graph: { row: 15, lane: 4 },
        },
        {
          id: "how-can-cosmos-reflect-good",
          kind: "问题",
          title: "变化的宇宙怎样仍能呈现形式、比例与善的秩序？",
          summary: "感性世界不断生成，却也呈现数学结构、周期和生命秩序。若它只是混乱摹本，稳定规律难以解释；若它完全等同形式，变化和缺陷又失去位置。",
          pressure: "需要一种让形式成为宇宙尺度、又不取消材料限制和生成过程的说明。",
          consequence: "《蒂迈欧篇》以工匠、范型、必然与世界灵魂组织宇宙生成叙事。",
          participants: [],
          chapterIds: ["b1-17", "b1-24"],
          graph: { row: 16, lane: 4 },
        },
        {
          id: "cosmos-shaped-by-form-and-good",
          kind: "答案",
          answerRole: "综合",
          title: "宇宙依可知范型获得比例秩序，却受生成材料限制",
          summary: "柏拉图以善的工匠面向永恒范型整理无序运动，并用世界灵魂与数学比例连接可知和可见层次。这是哲学宇宙论的模型，不是现代物理过程报告。",
          pressure: "工匠、范型和必然之间的关系仍留下形式怎样进入具体世界、目的说明能解释到何种程度的问题。",
          consequence: "宇宙秩序支线与理念分有支线共同进入亚里士多德的实体、原因和科学说明。",
          participants: [{ name: "柏拉图", philosopherId: "plato", role: "以范型、善、比例和世界灵魂组织宇宙生成" }],
          chapterIds: ["b1-17", "b1-24"],
          graph: { row: 17, lane: 4 },
        },
        {
          id: "what-stabilizes-knowledge",
          kind: "问题",
          title: "知识需要怎样稳定的共同对象？",
          summary: "流变显现、数学结构、不变存在和共同定义分别提供了知识条件的一部分；这些要求能否由同一种对象统一承担？",
          pressure: "若知识只等于当下感觉，记忆、判断、共同标准和关于“是什么”的说明都难以获得位置。",
          consequence: "柏拉图将多条答案重新组织为关于可知形式的综合方案。",
          participants: [],
          chapterIds: ["b1-13", "b1-15", "b1-18"],
          graph: { row: 13, lane: 2.3 },
        },
        {
          id: "stable-object-of-knowledge",
          kind: "答案",
          answerRole: "综合",
          title: "可知形式为知识提供稳定对象",
          summary: "柏拉图把赫拉克利特式流变、巴门尼德式稳定、毕达哥拉斯式数学秩序和苏格拉底式定义重新组织起来：感觉面对变化的个别事物，理性追问使多个实例可理解的形式。",
          pressure: "它让存在、知识和共同定义在同一方案中获得位置。",
          consequence: "理念与具体事物怎样关联，成为新的解释负担。",
          participants: [{ name: "柏拉图", philosopherId: "plato", role: "把存在、知识与形式问题合并" }],
          chapterIds: ["b1-13", "b1-15", "b1-18"],
          graph: { row: 14, lane: 2.3 },
        },
        {
          id: "forms-and-particulars",
          kind: "问题",
          title: "稳定形式怎样进入变化的具体世界？",
          summary: "如果理念与个别事物分离，参与、模仿或分有究竟说明了什么？如果形式就在具体事物中，又怎样保持知识需要的普遍性？",
          pressure: "设置两个层次会把“变化如何可能”改写成“两个层次如何关联”，并未彻底消除困难。",
          consequence: "问题通向亚里士多德：形式、质料、实体、潜能与现实将重新解释变化和同一。",
          participants: [
            { name: "柏拉图", philosopherId: "plato", role: "留下理念与个别物关系问题" },
            { name: "亚里士多德", philosopherId: "aristotle", role: "下一阶段的系统修复者" },
          ],
          chapterIds: ["b1-15", "b1-19", "b1-23"],
          graph: { row: 15, lane: 2.3 },
        },
      ],
    },
    {
      id: "aristotelian-reconstruction",
      order: 6,
      label: "实体与解释",
      title: "让形式回到具体事物之中",
      question: "怎样既保存普遍形式，又解释具体事物的变化、功能与原因？",
      transition: "柏拉图留下的分有困难被改写为具体实体内部的结构问题；形式、质料、潜能、现实与原因因此进入同一解释框架。",
      nodes: [
        {
          id: "immanent-form-matter",
          kind: "答案",
          answerRole: "修复",
          title: "形式内在于质料，具体复合体是首要实体",
          summary: "亚里士多德不再让形式作为个别事物之外的平行对象存在。质料说明某物由什么构成，形式说明它成为何种事物并能进行何种活动；具体实体由两者共同构成。",
          pressure: "它缩短了理念与个别物之间的距离，却必须进一步说明同一实体怎样从一种状态成为另一种状态。",
          consequence: "分有问题被转写成潜能如何实现、结构如何组织材料的变化问题。",
          participants: [{ name: "亚里士多德", philosopherId: "aristotle", role: "以质料—形式复合体修复分离理念的解释负担" }],
          chapterIds: ["b1-19"],
          graph: { row: 16, lane: 2.3 },
        },
        {
          id: "organized-life-observation",
          kind: "观察",
          observation: {
            domain: "知识实践",
            note: "动物器官、生长、繁殖和活动显示：相同材料因组织方式不同而具有不同能力；分类与比较使功能差异成为可系统研究的对象。",
          },
          title: "生命材料相近，组织方式与活动能力却不同",
          summary: "骨、肉和液体本身不足以说明眼为何能看、鳍为何能游、种子为何趋向成熟。对生物的持续比较让‘结构做什么’成为不能被材料清单取代的问题。",
          pressure: "若解释只列出组成成分和外部推动，就难以说明器官、成长与物种活动的相对稳定性。",
          consequence: "观察提出何种原因才能构成完整解释的问题。",
          participants: [{ name: "亚里士多德", philosopherId: "aristotle", role: "把比较观察、分类和功能说明组织成研究计划" }],
          chapterIds: ["b1-19", "b1-23", "b1-24"],
          graph: { row: 16, lane: 0 },
        },
        {
          id: "change-as-actualization-question",
          kind: "问题",
          title: "变化怎样真实发生，又不是从绝对无中生成？",
          summary: "若一个事物只能是已经现实存在的东西，生成仍会遭遇巴门尼德式困难；若未来状态完全不存在，又难以说明变化为何具有方向和能力边界。",
          pressure: "需要区分‘尚未现实’与‘绝对不存在’，并说明变化主体在过程中怎样保持连续。",
          consequence: "潜能与现实为变化提供新的逻辑词汇。",
          participants: [],
          chapterIds: ["b1-05", "b1-19", "b1-23"],
          graph: { row: 17, lane: 2.8 },
        },
        {
          id: "what-makes-explanation-complete",
          kind: "问题",
          title: "材料和推动是否足以构成完整解释？",
          summary: "说明青铜、碰撞或热量，可以回答部分‘怎样发生’，却未必回答结构是什么、过程为何趋向某种完成状态。不同对象可能要求不同层次的原因。",
          pressure: "若目的说明只是把人的意图投射给自然，它会过度；若一概排除功能与完成，又会漏掉生命组织的重要特征。",
          consequence: "问题要求区分多种‘为什么’，而不是寻找一种万能原因。",
          participants: [],
          chapterIds: ["b1-19", "b1-23"],
          graph: { row: 17, lane: 0.8 },
        },
        {
          id: "potentiality-actuality",
          kind: "答案",
          answerRole: "区分",
          title: "以潜能实现为变化保留连续主体",
          summary: "种子并非现实的成树，却具有在合适条件下成为树的能力。变化是已有能力转为现实活动，而非任何事物都能任意成为任何事物。",
          pressure: "区分潜能与现实保存了生成，也使现实形式成为理解能力和过程方向的标准。",
          consequence: "变化获得结构后，还需要说明哪些原因共同使潜能实现。",
          participants: [{ name: "亚里士多德", philosopherId: "aristotle", role: "以潜能—现实区分重新说明生成和运动" }],
          chapterIds: ["b1-19", "b1-23"],
          graph: { row: 18, lane: 3.4 },
        },
        {
          id: "four-causes-teleology",
          kind: "答案",
          answerRole: "综合",
          title: "材料、形式、动力与目的回答不同的为什么",
          summary: "充分解释可以分别说明构成材料、可理解结构、变化来源和过程所趋向的完成。目的因不必表示人格设计者，也可以指器官活动或生长过程实现的功能。",
          pressure: "四因避免把所有解释压缩成碰撞，但也可能让观察到的秩序过快被写成固定目的。",
          consequence: "若原因有不同类型，知识就必须说明哪些推论真正揭示对象的原因。",
          participants: [{ name: "亚里士多德", philosopherId: "aristotle", role: "把多种解释要求编入四因框架" }],
          chapterIds: ["b1-19", "b1-23"],
          graph: { row: 18, lane: 0.8 },
        },
        {
          id: "how-can-causes-be-known",
          kind: "问题",
          title: "怎样从经验材料得到关于原因的可靠知识？",
          summary: "观察提供个别事实，争论提供公认意见；科学说明却要求结论不仅碰巧为真，还要由真实起点展示为何如此。",
          pressure: "无限要求每个前提再被证明会使知识无法开始；仅凭习惯分类又不能保证因果结构。",
          consequence: "逻辑、分类、归纳和科学证明被组织成相互配合的知识工具。",
          participants: [],
          chapterIds: ["b1-19", "b1-22", "b1-24"],
          graph: { row: 19, lane: 2.1 },
        },
        {
          id: "demonstration-classification",
          kind: "答案",
          answerRole: "综合",
          title: "由观察与分类寻找起点，再用论证展示原因",
          summary: "亚里士多德把收集现象、公认意见、分类和辩证困难放在发现过程，把三段论与科学证明放在检验推论和说明原因的位置；逻辑不是观察的替代品。",
          pressure: "证明依赖首要原理，而首要原理不能由同一种证明无限倒推。",
          consequence: "知识结构把问题带回人的活动：如果事物具有功能，人的卓越活动和好生活是什么？",
          participants: [{ name: "亚里士多德", philosopherId: "aristotle", role: "建立词项逻辑、科学证明与分类研究的系统关系" }],
          chapterIds: ["b1-22", "b1-24"],
          graph: { row: 20, lane: 2.1 },
        },
      ],
    },
    {
      id: "flourishing-and-polis",
      order: 7,
      label: "幸福与共同体",
      title: "从事物的功能转向人的好生活",
      question: "人的卓越活动是什么，它能否脱离习惯、友谊、制度和外部条件独自完成？",
      transition: "自然与知识的功能语言进入伦理和政治；随后城邦自主性的瓦解又暴露这种好生活对公共条件的依赖。",
      nodes: [
        {
          id: "actions-aim-goods-observation",
          kind: "观察",
          observation: {
            domain: "个体体验",
            note: "行动、技艺和选择通常以某种被认为值得追求的结果为目标，但短期欲望、社会成功与完整生活可能彼此冲突。",
          },
          title: "人不断追求具体目标，却仍会追问一生是否过得好",
          summary: "赢得一次争论、获得财富或感受快乐都可以是目标，但它们不能自动说明一个人的整个生活是否值得选择。局部成功需要被放入更完整的尺度。",
          pressure: "若没有最高层的生活标准，不同目标只能相互争夺；若标准太抽象，又无法指导具体选择。",
          consequence: "观察提出幸福究竟是感受、占有还是持续活动的问题。",
          participants: [],
          chapterIds: ["b1-20"],
          graph: { row: 21, lane: 0 },
        },
        {
          id: "constitutions-shape-character-observation",
          kind: "观察",
          observation: {
            domain: "社会与制度",
            note: "法律、教育、财产安排和公民资格不仅限制行动，也长期培养人认为可敬、可耻、可能或不可能的生活方式。",
            historyLinks: [{
              stageId: "athens",
              responseId: "aristotle",
              eventId: "macedonian-rise",
              label: "学园建立、政体比较与马其顿接管",
              note: "进入历史概览查看哲学研究制度化与城邦政治空间收缩如何同时发生。",
            }],
          },
          title: "不同制度会培养不同习惯、角色与善的想象",
          summary: "在民主、寡头或君主制下，谁能参与、何者受奖励、怎样接受教育都不同。伦理选择因此不是与制度无关的私人瞬间。",
          pressure: "若德性只能靠个人意志，法律教育为何重要；若制度完全决定人格，个人判断又在哪里？",
          consequence: "观察提出好生活能否离开共同体条件的问题。",
          participants: [{ name: "亚里士多德", philosopherId: "aristotle", role: "以政体比较研究制度如何塑造公民生活" }],
          chapterIds: ["b1-20", "b1-21"],
          graph: { row: 21, lane: 4 },
        },
        {
          id: "what-is-human-flourishing",
          kind: "问题",
          title: "幸福是短暂感受、外在成功，还是一种生活活动？",
          summary: "人会追求快乐、荣誉、财富、友谊和理解，但这些目标可能分离。需要一个能评价整段生命而非单一时刻的尺度。",
          pressure: "只看感受会忽略行动品质，只看德性又可能低估疾病、贫困和关系断裂的真实影响。",
          consequence: "人的功能与德性活动成为亚里士多德的回答起点。",
          participants: [],
          chapterIds: ["b1-20"],
          graph: { row: 22, lane: 1 },
        },
        {
          id: "can-good-life-be-private",
          kind: "问题",
          title: "个人能否脱离共同体独自完成好生活？",
          summary: "语言、正义判断、友谊、教育和法律都在共同生活中形成；但政治参与也会让幸福暴露于战争、放逐和权力竞争。",
          pressure: "把人完全交给城邦会压缩个体，把幸福完全私有化又无法解释制度怎样塑造行动能力。",
          consequence: "实践智慧、友谊、法律教育和政体比较被放进同一伦理政治结构。",
          participants: [],
          chapterIds: ["b1-20", "b1-21"],
          graph: { row: 22, lane: 3 },
        },
        {
          id: "virtue-as-rational-activity",
          kind: "答案",
          answerRole: "区分",
          title: "幸福是一生中依德性实现理性能力的活动",
          summary: "亚里士多德不把幸福等同于一阵愉快，而理解为持续活动：通过习惯形成品格，以实践智慧在具体情境中选择，并让理性能力得到卓越实现。",
          pressure: "幸福需要时间、友谊和一定外部条件，因此不能被压缩成任何处境都不受损的纯内心状态。",
          consequence: "好生活对共同体和运气的依赖成为后世学派要重新处理的脆弱点。",
          participants: [{ name: "亚里士多德", philosopherId: "aristotle", role: "以功能、德性活动和实践智慧界定幸福" }],
          chapterIds: ["b1-20"],
          graph: { row: 23, lane: 1 },
        },
        {
          id: "polis-practical-wisdom",
          kind: "答案",
          answerRole: "综合",
          title: "城邦以法律教育支持德性，实践智慧处理具体差异",
          summary: "人作为政治动物，在共同体中学习语言、正义与角色。良好制度不能替每个人完成德性，却能提供习惯、友谊和行动条件；政治研究因此要比较现实政体而非只画理想模型。",
          pressure: "这一回答仍以城邦能够相对自主、持续教育公民为背景。",
          consequence: "当城邦被大帝国取代，个人怎样获得不依赖政治掌控的安全与自由便变得尖锐。",
          participants: [{ name: "亚里士多德", philosopherId: "aristotle", role: "连接伦理活动、法律教育与政体经验" }],
          chapterIds: ["b1-20", "b1-21"],
          graph: { row: 23, lane: 3 },
        },
        {
          id: "polis-autonomy-collapse",
          kind: "观察",
          observation: {
            domain: "历史变化",
            note: "马其顿征服与继业者王国使许多人从小型城邦的参与者变为广大君主国中的臣民、移民或城市居民，公共决策与个人生活之间的距离增大。",
            historyLinks: [{
              stageId: "hellenistic",
              responseId: "cynics",
              eventId: "alexander",
              label: "亚历山大征服与城邦政治边界瓦解",
              note: "进入历史概览比较城邦公民如何转成帝国世界中的个人。",
            }],
          },
          title: "城邦仍存在，但已不再是个人能够共同掌控的最高世界",
          summary: "征服、迁移和君主国行政扩大了生活空间，也降低普通人影响最高政治秩序的可能。哲学共同体与个人训练因而承担更多安全和身份功能。",
          pressure: "如果幸福依赖可治理的共同体和稳定外物，帝国世界会使好生活过度暴露于运气。",
          consequence: "历史变化重新提出：无法控制公共世界时，人怎样获得自由与宁静？",
          participants: [],
          chapterIds: ["b1-25"],
          graph: { row: 24, lane: 4 },
        },
        {
          id: "how-live-uncontrollable-world",
          kind: "问题",
          title: "无法控制公共世界时，人怎样获得自由、宁静与好生活？",
          summary: "战争、流动、财富损失、身份变化和政治无力，使幸福若依赖外物便持续不稳。问题不再只是什么是真的，也是什么样的需要和判断不会被命运轻易夺走。",
          pressure: "完全退出会失去公共责任，完全投入会让幸福依赖权力；减少知识承诺又可能削弱行动依据。",
          consequence: "犬儒、怀疑、伊壁鸠鲁和斯多葛路线从共同压力给出不同生活方案。",
          participants: [],
          chapterIds: ["b1-25", "b1-26", "b1-27", "b1-28"],
          graph: { row: 25, lane: 2 },
        },
      ],
    },
    {
      id: "hellenistic-therapies",
      order: 8,
      label: "哲学治疗",
      title: "用生活结构回应不可控制的世界",
      question: "减少需要、悬置判断、理解自然或顺应秩序，哪一种最能降低脆弱性？",
      transition: "四条路线共享治疗目标，却对知识、自然、公共责任和自由的位置给出竞争答案。",
      nodes: [
        {
          id: "cynic-low-dependence",
          kind: "答案",
          answerRole: "反驳",
          title: "减少需要，以公开反习俗降低外部支配",
          summary: "犬儒主义把财富、名望、礼俗和权力视为制造依赖的装置。主动简化生活、训练身体并坦率发言，使统治者更少拥有交换服从的筹码。",
          pressure: "低依赖确实增加自主，却可能把必须共同解决的制度问题转换成个人退出。",
          consequence: "犬儒答案留下自由应靠退出角色还是改造角色的问题。",
          participants: [{ name: "第欧根尼", philosopherId: "diogenes", role: "以可见生活和反习俗行动证明低依赖自由" }],
          chapterIds: ["b1-26"],
          graph: { row: 26, lane: 0 },
        },
        {
          id: "skeptical-suspension",
          kind: "答案",
          answerRole: "转向",
          title: "相反理由势均时悬置断言，让扰动失去抓手",
          summary: "皮浪式怀疑不急于为世界增加新体系，而在无法决定时停止把显现批准为事物本性。安宁被理解为放松教条执着后的实践结果。",
          pressure: "不轻率断言可以降低焦虑，却必须说明人如何行动，也要面对印象是否可能提供可靠标准的争论。",
          consequence: "怀疑路线同时提出知识是否必要、表象能否自证和无确定性如何行动的问题。",
          participants: [{ name: "皮浪", philosopherId: "pyrrho", role: "把悬置与不受扰动的生活联系起来" }],
          chapterIds: ["b1-26"],
          graph: { row: 26, lane: 1.3 },
        },
        {
          id: "epicurean-natural-therapy",
          kind: "答案",
          answerRole: "综合",
          title: "用自然解释、欲望分类与友谊解除恐惧",
          summary: "伊壁鸠鲁保留原子和虚空，以非神罚的自然说明消解恐惧；快乐不是刺激最大化，而是无痛、宁静、审慎选择和可靠友谊构成的低扰动生活。",
          pressure: "这一方案需要某些自然知识，却不追求统治公共世界；其契约正义也要说明共同体范围。",
          consequence: "它提出宁静究竟需要多少知识、自然解释能否提供完整意义的问题。",
          participants: [
            { name: "伊壁鸠鲁", philosopherId: "epicurus", role: "把原子论、欲望管理和友谊组织成治疗系统" },
            { name: "卢克莱修", philosopherId: "lucretius", role: "以诗性自然说明把治疗带入罗马世界" },
          ],
          chapterIds: ["b1-27"],
          graph: { row: 26, lane: 2.7 },
        },
        {
          id: "stoic-virtue-in-order",
          kind: "答案",
          answerRole: "综合",
          title: "把善放在德性与同意，使自由进入因果秩序内部",
          summary: "斯多葛主义把世界理解为理性因果整体。外部事件并非完全由个人支配，真正的善却可以限定在判断、选择和德性；自由因此不是脱离自然，而是在自然中成为行动的内在原因。",
          pressure: "决定论、天意、责任和恶必须同时得到说明；认知印象也要能支持理性同意。",
          consequence: "这一答案产生自由是否等于内在同意，以及印象能否保证真理的争论。",
          participants: [
            { name: "季蒂昂的芝诺", philosopherId: "zeno", role: "建立逻辑—物理—伦理相互支持的纲领" },
            { name: "克里安西斯", philosopherId: "cleanthes", role: "以宇宙自然和自愿同行强化宗教伦理" },
            { name: "克律西波斯", philosopherId: "chrysippus", role: "系统化逻辑、决定论、同意与责任" },
          ],
          chapterIds: ["b1-28"],
          graph: { row: 26, lane: 4 },
        },
        {
          id: "freedom-withdrawal-or-role",
          kind: "问题",
          title: "自由来自退出脆弱角色，还是在角色中改变判断？",
          summary: "犬儒主义通过减少需要拒绝社会筹码，斯多葛主义则允许承担家庭和公共角色，同时把价值核心安放在无法直接被强迫的判断与意志。",
          pressure: "退出可能忽视他人和制度，留在角色中又可能把服从包装成自由。",
          consequence: "罗马斯多葛主义将用恰当行动、日常操练和控制区分继续回答。",
          participants: [],
          chapterIds: ["b1-26", "b1-28", "b1-29"],
          graph: { row: 27, lane: 0.7 },
        },
        {
          id: "tranquility-needs-knowledge",
          kind: "问题",
          title: "宁静需要理解自然，还是减少知识承诺？",
          summary: "伊壁鸠鲁认为理解神、死亡和自然事件才能解除恐惧；怀疑派则担心对不可确定之本性的强行承诺正是扰动来源。",
          pressure: "知识可能治疗恐惧，也可能制造教条竞争；不承诺可以减压，也可能失去解释和行动标准。",
          consequence: "自然治疗与怀疑论证将分别细化两条路线。",
          participants: [],
          chapterIds: ["b1-26", "b1-27"],
          graph: { row: 27, lane: 2.1 },
        },
        {
          id: "can-impression-certify-truth",
          kind: "问题",
          title: "一种印象能否凭自身保证它来自真实对象？",
          summary: "斯多葛派需要可靠印象作为知识与行动起点，学院怀疑派则以梦、幻觉和不可区分对象说明鲜明感受未必携带真理印章。",
          pressure: "若没有可靠标准，知识体系难以开始；若心理确信被当成保证，错误印象便会冒充认识。",
          consequence: "认知印象与悬置同意形成直接争论。",
          participants: [],
          chapterIds: ["b1-26", "b1-28"],
          graph: { row: 27, lane: 3.5 },
        },
      ],
    },
    {
      id: "criteria-freedom-cosmopolis",
      order: 9,
      label: "判断与世界城邦",
      title: "在不确定和必然中保存行动",
      question: "没有绝对控制或无误知识时，行动、责任与更大的共同体怎样仍然可能？",
      transition: "希腊学派的争论进入罗马法律、角色与帝国生活；个人内在训练和普遍共同体因此被同时放大。",
      nodes: [
        {
          id: "role-and-inner-freedom",
          kind: "答案",
          answerRole: "修复",
          title: "履行角色，但把善限定在判断与恰当行动",
          summary: "罗马斯多葛作者把体系转成每日操练：区分事件与判断，审查冲动，在皇帝、奴隶、教师或官员等不同位置完成能够负责的行动。",
          pressure: "内在自由不能自动证明既有角色正义，也不能消除身体、关系和政治暴力的真实损害。",
          consequence: "角色伦理需要说明义务为何能扩展到陌生人与不同民族。",
          participants: [
            { name: "帕奈提奥斯", philosopherId: "panaetius", role: "把伦理转译为普通角色与恰当行动" },
            { name: "塞涅卡", philosopherId: "seneca", role: "在财富、权力与死亡压力中进行每日自省" },
            { name: "爱比克泰德", philosopherId: "epictetus", role: "以可控区分和角色训练压缩实践路径" },
            { name: "马可·奥勒留", philosopherId: "aurelius", role: "在帝国职责中检验整体视角与自我约束" },
          ],
          chapterIds: ["b1-28", "b1-29"],
          graph: { row: 28, lane: 0.6 },
        },
        {
          id: "natural-knowledge-removes-fear",
          kind: "答案",
          answerRole: "修复",
          title: "自然知识不求统治世界，而求解除神罚和死亡恐惧",
          summary: "伊壁鸠鲁和卢克莱修不把物理学当作无限好奇的竞赛，而让原子、灵魂的可朽性和多种自然解释服务于宁静。知识的价值由它消除何种虚假恐惧来衡量。",
          pressure: "治疗性标准可能容许多个远距离现象解释，却仍须避免把有用等同于真实。",
          consequence: "即使自然不由神意治理，人仍要说明友谊、正义和意义怎样成立。",
          participants: [
            { name: "伊壁鸠鲁", philosopherId: "epicurus", role: "把自然知识限定为解除恐惧的治疗工具" },
            { name: "卢克莱修", philosopherId: "lucretius", role: "把不可见自然结构转化为可理解的诗性经验" },
          ],
          chapterIds: ["b1-27"],
          graph: { row: 28, lane: 1.8 },
        },
        {
          id: "suspend-self-certifying-assent",
          kind: "答案",
          answerRole: "反驳",
          title: "没有印象能仅凭自身排除所有虚假对应物",
          summary: "阿尔克西劳攻击斯多葛认知印象：若真假印象可能不可区分，理性就不应把鲜明感受批准为确定知识。悬置不是放弃探究，而是拒绝超出证据。",
          pressure: "严格悬置立即遭遇实践反驳：不确认任何印象，怎样选择、出门或承担责任？",
          consequence: "知识问题转成没有确定性时如何合理行动。",
          participants: [{ name: "阿尔克西劳", philosopherId: "arcesilaus", role: "以不可区分反例把学院转向非独断论证" }],
          chapterIds: ["b1-26"],
          graph: { row: 28, lane: 3 },
        },
        {
          id: "cognitive-impression-and-assent",
          kind: "答案",
          answerRole: "区分",
          title: "区分印象出现与主体同意，以可靠印象建立知识",
          summary: "斯多葛派认为外物造成印象，但判断还需要主体同意；认知印象被设想为由真实对象以不会由假对象产生的方式留下，能够成为把握的基础。",
          pressure: "怀疑派质疑这种内部标记是否真的可辨；决定论又要求说明同意怎样仍属于主体。",
          consequence: "争论推进到一切有原因时责任为何可能。",
          participants: [
            { name: "季蒂昂的芝诺", philosopherId: "zeno", role: "提出认知印象与同意结构" },
            { name: "克律西波斯", philosopherId: "chrysippus", role: "系统辩护印象、同意和因果责任" },
          ],
          chapterIds: ["b1-28"],
          graph: { row: 28, lane: 4 },
        },
        {
          id: "imperial-law-observation",
          kind: "观察",
          observation: {
            domain: "社会与制度",
            note: "帝国道路、城市网络、法律程序与公民身份扩张，使不同民族和角色被置于共同规则下；共同体第一次以远大于城邦的制度尺度日常存在。",
            historyLinks: [{
              stageId: "roman",
              responseId: "roman-stoics",
              eventId: "citizenship-law",
              label: "罗马法与公民身份扩张",
              note: "进入历史概览查看普遍法律、角色义务与共同人性怎样获得制度背景。",
            }],
          },
          title: "不同民族与社会角色开始长期生活在共同法律空间中",
          summary: "帝国并没有消除不平等，却使超越单一城邦的共同规则成为现实经验。哲学必须说明义务为何能越过亲缘、地位与地方习俗。",
          pressure: "共同统治不等于平等共同体；普遍法可能是理性标准，也可能只是帝国权力。",
          consequence: "观察提出谁属于道德共同体、普遍义务依据何在的问题。",
          participants: [],
          chapterIds: ["b1-28", "b1-29"],
          graph: { row: 29, lane: 0 },
        },
        {
          id: "is-natural-explanation-enough",
          kind: "问题",
          title: "没有天意的自然解释能否同时支持正义、友谊与意义？",
          summary: "原子论可以解除神罚恐惧，却不会自动推出应怎样共同生活。个人宁静还需要友谊、可信承诺和避免互害的规则。",
          pressure: "若价值完全由自然事实推出会混淆层次；若价值与自然无关，治疗体系又失去统一。",
          consequence: "伊壁鸠鲁以审慎、友谊与互利契约连接个人快乐和共同规则。",
          participants: [],
          chapterIds: ["b1-27"],
          graph: { row: 29, lane: 1.8 },
        },
        {
          id: "how-act-without-certainty",
          kind: "问题",
          title: "不拥有确定知识时，行动怎样避免任意和瘫痪？",
          summary: "实践不能等待所有怀疑消失。重要选择需要某种可比较、可复查而又不冒充绝对保证的依据。",
          pressure: "只凭当下说服力容易追随偏见，要求无误知识又会使行动永久延期。",
          consequence: "可信印象被发展为分层的实践程序。",
          participants: [],
          chapterIds: ["b1-26"],
          graph: { row: 29, lane: 3 },
        },
        {
          id: "fate-and-responsibility",
          kind: "问题",
          title: "如果每件事都有原因，人的同意为何仍能承担责任？",
          summary: "决定论若被理解成外力单向推动，赞扬、责备和训练都会失去意义；但无原因选择也不像属于一个稳定主体。",
          pressure: "责任需要行动既属于因果世界，又通过行动者自身结构发生。",
          consequence: "克律西波斯以内部原因和共命运说明兼容结构。",
          participants: [],
          chapterIds: ["b1-28"],
          graph: { row: 29, lane: 4 },
        },
        {
          id: "probable-tested-guidance",
          kind: "答案",
          answerRole: "修复",
          title: "按可信度、一致性与检查程度分层行动依据",
          summary: "卡尔内阿德不把可信印象升级为真理印章，而把它作为可修正程序：越重要的行动，越需要检查相关印象、情境和相互一致性。",
          pressure: "程序支持行动，却不能独自说明某项政治规范是否普遍正义。",
          consequence: "怀疑论证把问题推进到法律和正义是否只是强者或地方利益。",
          participants: [{ name: "卡尔内阿德", philosopherId: "carneades", role: "以分级可信印象连接怀疑与实践" }],
          chapterIds: ["b1-26"],
          graph: { row: 30, lane: 3 },
        },
        {
          id: "assent-as-internal-cause",
          kind: "答案",
          answerRole: "修复",
          title: "外因触发印象，行动仍通过主体判断成为自己的行动",
          summary: "克律西波斯承认完整因果链，却用圆柱受推后依自身形状滚动等比喻说明：外部条件不是充分解释，性格、判断和同意也是行动的内部原因。",
          pressure: "兼容论保留责任，却未消除命运中的苦难，也不能保证主体已形成良好判断。",
          consequence: "内在原因使日常训练重要，同时留下内在自由是否足以面对帝国脆弱性的问题。",
          participants: [{ name: "克律西波斯", philosopherId: "chrysippus", role: "以主体结构与共命运反驳消极宿命论" }],
          chapterIds: ["b1-28"],
          graph: { row: 30, lane: 4 },
        },
        {
          id: "friendship-contract-without-providence",
          kind: "答案",
          answerRole: "综合",
          title: "以审慎、友谊与避免互害的契约稳定快乐",
          summary: "伊壁鸠鲁不需要宇宙天意来保证共同生活：正义是避免彼此伤害的互利安排，友谊则成为安全、信任和快乐本身的重要组成。",
          pressure: "小共同体能提供真实照护，却可能缩小对陌生人和宏大制度不正义的责任。",
          consequence: "它与世界城邦形成两种扩大或限制共同体的方案，也都将面对帝国危机中的终极意义问题。",
          participants: [
            { name: "伊壁鸠鲁", philosopherId: "epicurus", role: "以友谊和契约正义补足非天意自然观" },
            { name: "卢克莱修", philosopherId: "lucretius", role: "以文明和契约的自然历史解释社会规则" },
          ],
          chapterIds: ["b1-27"],
          graph: { row: 30, lane: 1.8 },
        },
        {
          id: "who-belongs-moral-community",
          kind: "问题",
          title: "道德共同体止于朋友、城邦，还是扩展到所有人？",
          summary: "帝国共同法律、犬儒世界公民姿态、伊壁鸠鲁友谊共同体和斯多葛共同理性，分别改变传统城邦边界。",
          pressure: "普遍主义可能抽象到忽略具体关系，小共同体又可能把远方他人排除在义务之外。",
          consequence: "斯多葛世界城邦以共同理性和自然法回答范围问题。",
          participants: [],
          chapterIds: ["b1-26", "b1-27", "b1-28", "b1-29"],
          graph: { row: 30, lane: 0.5 },
        },
        {
          id: "cosmopolis-common-reason",
          kind: "答案",
          answerRole: "综合",
          title: "共享理性使所有人属于同一世界城邦",
          summary: "斯多葛主义把宇宙理解为受共同法治理的城市。人的共同理性使正义要求越过地方、身份和距离；中期及罗马作者再把它转译为角色义务和人类亲近关系。",
          pressure: "普遍共同体在奴隶制和帝国等级中仍高度理想化，不能被当作现实平等已经实现。",
          consequence: "外部法律与普遍义务扩大后，仍要问它们能否提供面对死亡、苦难和世界分裂的最终安顿。",
          participants: [
            { name: "季蒂昂的芝诺", philosopherId: "zeno", role: "早期提出超越既有城邦的共同生活理想" },
            { name: "帕奈提奥斯", philosopherId: "panaetius", role: "把共同理性转译到罗马公共义务" },
            { name: "波塞多尼奥斯", philosopherId: "posidonius", role: "连接自然、历史和跨地域人类生活" },
            { name: "马可·奥勒留", philosopherId: "aurelius", role: "以共同理性反复提醒帝国角色的普遍责任" },
          ],
          chapterIds: ["b1-28", "b1-29"],
          graph: { row: 31, lane: 0.5 },
        },
      ],
    },
    {
      id: "roman-inwardness-and-one",
      order: 10,
      label: "内向与超越",
      title: "外部秩序之外，更高真实在哪里",
      question: "内在训练和普遍法律仍不能消除苦难与死亡时，灵魂是否属于一个高于感性世界的秩序？",
      transition: "罗马制度、学派伦理与三世纪危机共同把问题推向灵魂内部；普罗提诺由此把柏拉图的形式重新组织成太一、精神与灵魂的层级。",
      nodes: [
        {
          id: "imperial-vulnerability-observation",
          kind: "观察",
          observation: {
            domain: "历史变化",
            note: "三世纪内战、皇位更替、疾病、边境压力与经济混乱显示：庞大制度可以维持秩序，却无法保证个人安全或提供苦难的终极解释。",
            historyLinks: [{
              stageId: "roman",
              responseId: "plotinus",
              eventId: "third-century-crisis",
              label: "三世纪危机与宗教需求上升",
              note: "进入历史概览查看帝国不稳定如何强化灵魂、超越与救赎问题。",
            }],
          },
          title: "帝国能够统一法律，却不能取消死亡、苦难与意义危机",
          summary: "角色纪律、友谊共同体和世界公民身份都能改善生活，但瘟疫、战争、失序和个人死亡仍可能使外部世界显得不足。",
          pressure: "若全部价值仍依赖感性世界，最稳固的制度也会崩解；若转向更高真实，又须解释它与可见世界的关系。",
          consequence: "观察提出内在自由和自然解释是否足以安顿灵魂的问题。",
          participants: [],
          chapterIds: ["b1-29", "b1-30"],
          graph: { row: 31, lane: 4 },
        },
        {
          id: "is-inner-freedom-enough",
          kind: "问题",
          title: "内在自由、友谊与普遍法律是否已足以回答最高意义？",
          summary: "希腊化和罗马哲学已经大幅降低外物支配，却仍面对世界为何存在、灵魂何以统一以及死亡是否终结全部价值。",
          pressure: "继续只做伦理训练可能回避形而上问题；诉诸超越层级又可能贬低身体、政治和经验研究。",
          consequence: "普罗提诺把好生活问题重新接回柏拉图式最高真实。",
          participants: [],
          chapterIds: ["b1-28", "b1-29", "b1-30"],
          graph: { row: 32, lane: 2.2 },
        },
        {
          id: "one-intellect-soul",
          kind: "答案",
          answerRole: "综合",
          title: "太一、精神与灵魂构成由统一到多样的真实层级",
          summary: "普罗提诺把最高原则理解为超越存在和思维的太一；精神包含可知形式，灵魂使生命与感性宇宙获得秩序。人的内在上升因此也是对真实结构的回归。",
          pressure: "层级说明不同真实程度，却必须解释完全统一的第一原则怎样产生多样而不发生变化或损失。",
          consequence: "问题转向多如何来自一。",
          participants: [{ name: "普罗提诺", philosopherId: "plotinus", role: "重构柏拉图、亚里士多德和斯多葛资源为三重本原" }],
          chapterIds: ["b1-30"],
          graph: { row: 33, lane: 2.2 },
        },
        {
          id: "how-many-from-one",
          kind: "问题",
          title: "绝对统一怎样产生多样，而自身不因此改变？",
          summary: "若太一因缺乏而行动，它便不完满；若它完全自足，多样又为何出现。普通的制造因果会把变化和意图重新带回第一原则。",
          pressure: "需要一种结果依赖原因、原因却不因产生结果而受损的关系。",
          consequence: "流溢与回归把因果改写成完满活动的外向结果。",
          participants: [],
          chapterIds: ["b1-30"],
          graph: { row: 34, lane: 2.2 },
        },
        {
          id: "emanation-without-loss",
          kind: "答案",
          answerRole: "修复",
          title: "完满活动产生依赖结果，结果再通过观照转向来源",
          summary: "普罗提诺以活动的内在完成与外在结果说明通常所谓流溢：较低层依赖较高层，较高层却不因给予而减少；转向和观照使派生者获得自己的确定结构。",
          pressure: "层级依赖容易被误解成时间中的制造，也可能被读成感性世界本身就是恶。",
          consequence: "方案必须说明可见世界是恶、幻象，还是较低却真实的秩序。",
          participants: [{ name: "普罗提诺", philosopherId: "plotinus", role: "以双重活动、流溢和观照解释由一到多" }],
          chapterIds: ["b1-30"],
          graph: { row: 35, lane: 2.2 },
        },
        {
          id: "is-sensible-world-evil",
          kind: "问题",
          title: "感性世界是应逃离的恶，还是依赖更高原则的有限善？",
          summary: "灵魂向更高统一回归，并不自动意味着身体和宇宙由邪恶原则制造。若世界完全恶，它的秩序与美便无法解释。",
          pressure: "过度贬低世界会切断伦理责任，过度肯定世界又可能消除上升与净化的必要。",
          consequence: "普罗提诺以依赖的影像和善的程度差异反对二元造物恶论。",
          participants: [],
          chapterIds: ["b1-30"],
          graph: { row: 36, lane: 2.2 },
        },
        {
          id: "dependent-image-not-evil",
          kind: "答案",
          answerRole: "区分",
          title: "感性宇宙是较低的依赖影像，不是独立邪恶本原",
          summary: "世界的多样、时间和身体限制其完善程度，却仍通过灵魂和形式分享秩序。恶更像善的缺失与远离，而不是与太一对等的实体。",
          pressure: "这一回答为基督教思想提供重要资源，但创造、人格神、罪和恩典并不等同于普罗提诺的流溢结构。",
          consequence: "第一卷在此打开第二卷入口：灵魂回归最高善需要哲学观照，还是还需要启示、创造与神圣援助？",
          participants: [{ name: "普罗提诺", philosopherId: "plotinus", role: "维护宇宙秩序并把恶解释为善的缺失" }],
          chapterIds: ["b1-30"],
          graph: { row: 37, lane: 2.2 },
        },
        {
          id: "reason-or-divine-aid",
          kind: "问题",
          title: "灵魂回归最高善，只靠哲学观照，还是需要启示与神圣援助？",
          summary: "古代哲学已经把自然、知识、德性、共同体和灵魂组织成多种自我修正的路径；基督教则会把最高原则重新表述为创造者、救赎者和历史中的行动者。",
          pressure: "把后来的信仰问题倒灌给古代哲学会抹平差异，但若不保留这一开放问题，第一卷与第二卷的结构转折便无法显现。",
          consequence: "这是第一卷的终端开放节点，也是进入创造、恶、自由意志、恩典与信仰—理性问题的桥梁。",
          participants: [{ name: "普罗提诺", philosopherId: "plotinus", role: "为后来的教父哲学提供最重要的古代形而上学近邻" }],
          chapterIds: ["b1-30", "b2-02", "b2-04"],
          graph: { row: 38, lane: 2.2 },
        },
      ],
    },
    {
      id: "revelation-grace-history",
      order: 11,
      label: "启示与恩典",
      title: "经文、创造与受医治的意志",
      question: "若最高者在历史中创造、启示并救赎，哲学理性、人的意志与公共权力应怎样重新定位？",
      transition: "这一阶段只推进第二卷前四章：犹太经文传统把最高秩序放入创造与历史，早期基督教将救赎普遍化，教父用希腊概念解释启示；奥古斯丁再把恶、意志、恩典、时间和帝国兴亡组织成同一组问题。",
      nodes: [
        {
          id: "scriptural-history-observation",
          kind: "观察",
          observation: {
            domain: "历史变化",
            note: "观察一个共同体怎样把律法、流亡、复归、预言和苦难保存为与上帝关系的连续历史；这不是在此预先判定启示主张为真。",
            historyLinks: [{
              stageId: "patristic",
              responseId: "paul-john",
              label: "犹太历史伦理进入普世基督教叙事",
              note: "进入历史概览查看民族律法、救赎期待与希腊化语言怎样在早期基督教中被重新组合。",
            }],
          },
          title: "经文共同体把律法、苦难与盼望保存为一段有方向的历史",
          summary: "自然循环之外，犹太经文传统把创造、盟约、流亡、悔改和未来应许连成不可简单重复的历史。群体记忆因此不只说明发生了什么，也追问事件要求人怎样回应。",
          pressure: "若最高秩序只是不变原则，特殊事件为何能够承担普遍意义；若只诉诸特殊事件，又怎样避免把真理缩小为一个民族的私人记忆。",
          consequence: "观察提出超越者能否在时间中行动，以及历史启示怎样具有普遍意义的问题。",
          participants: [],
          chapterIds: ["b2-01", "b2-02"],
          graph: { row: 39, lane: 0.2 },
        },
        {
          id: "does-transcendent-good-act-in-history",
          kind: "问题",
          title: "超越而不变的最高善，能否创造世界并在具体历史中行动？",
          summary: "普罗提诺式最高原则通过依赖层级说明多样，却不是在某个时刻自由决定创造、立约或救赎的人格行动者。经文叙事则把神圣意义放进不可逆的事件。",
          pressure: "若神随事件改变，超越性似乎受损；若神绝不与历史发生真实关系，创造、命令和救赎又容易沦为比喻。",
          consequence: "创造与盟约把宇宙依赖和历史方向放进同一回答。",
          participants: [],
          chapterIds: ["b2-01", "b2-02"],
          graph: { row: 40, lane: 0.8 },
        },
        {
          id: "creator-covenant-salvation-history",
          kind: "答案",
          answerRole: "转向",
          title: "世界依赖自由创造，历史则由盟约、道成肉身与救赎获得方向",
          summary: "犹太—基督教传统不把世界看作最高者自然溢出的必然结果，而把它理解为受造秩序；基督教又把基督事件置于面向所有人的救赎史中心。宇宙论因此转成创造与历史责任。",
          pressure: "创造和救赎以经文叙事表达，却仍须说明这些叙事怎样与哲学关于非物质、统一和因果的要求相容。",
          consequence: "问题转向启示怎样进入理性解释，并由谁约束解释边界。",
          participants: [{ name: "奥利金", philosopherId: "origen", role: "把创造、基督—逻各斯、自由受造物与复归组织成系统神学" }],
          chapterIds: ["b2-01", "b2-02"],
          graph: { row: 41, lane: 0.8 },
        },
        {
          id: "how-can-revelation-enter-reason",
          kind: "问题",
          title: "经文中的人格叙事、命令与矛盾表象，怎样进入哲学理性而不被哲学取代？",
          summary: "若坚持所有字面表达，神可能显得有身体、情绪和变化；若任意寓意化，解释者又可能只把柏拉图或自己的体系写回经文。",
          pressure: "既需要跨语言、跨概念的解释方法，也需要说明理性是启示的裁判、工具还是受教者。",
          consequence: "逻各斯、寓意解释和文本校勘成为连接经文与哲学的互补工具。",
          participants: [],
          chapterIds: ["b2-01", "b2-02", "b2-03"],
          graph: { row: 42, lane: 0.8 },
        },
        {
          id: "logos-layered-exegesis-text",
          kind: "答案",
          answerRole: "综合",
          title: "以逻各斯、多层释义与文本校勘让理性在启示内部工作",
          summary: "斐洛用逻各斯和寓意解释连接摩西经文与希腊哲学；奥利金把经文理解为具有身体、灵魂和精神层次；哲罗姆则让语言差异、译本和原文校勘成为解释责任的一部分。",
          pressure: "解释工具能澄清信仰，也会产生竞争解释；当共同体扩大并进入帝国权力，教义与解释不再只有书斋后果。",
          consequence: "这一路线一方面回答理性与神圣援助如何合作，另一方面产生恶、权威和公共责任的新问题。",
          participants: [
            { name: "亚历山大的斐洛", philosopherId: "philo-alexandria", role: "以寓意解释和逻各斯连接犹太经文与希腊哲学" },
            { name: "奥利金", philosopherId: "origen", role: "以多层经义、文本校勘和哲学推理建立基督教系统释经" },
            { name: "哲罗姆", philosopherId: "jerome", role: "以希伯来文学习、拉丁译本修订和文本差异约束解释" },
          ],
          chapterIds: ["b2-01", "b2-02", "b2-03"],
          graph: { row: 43, lane: 0.8 },
        },
        {
          id: "church-imperial-observation",
          kind: "观察",
          observation: {
            domain: "社会与制度",
            note: "观察基督教从受迫害共同体转成受帝国支持的跨地域组织后，教义判断、礼仪纪律与政治强制怎样获得共同后果。",
            historyLinks: [{
              stageId: "patristic",
              responseId: "augustine",
              eventId: "state-religion",
              label: "基督教成为帝国主导宗教",
              note: "进入历史概览查看帝国资源、主教网络与正统边界结合后，公共权力问题怎样改变。",
            }],
          },
          title: "受迫害共同体成为帝国宗教后，主教、皇帝与信徒进入同一权威冲突",
          summary: "教义分歧、圣礼纪律和公共暴力不再只影响小型团体。皇帝可以召集会议、支持教派或惩罚异端，主教也开始以独立道德权威约束统治者。",
          pressure: "若皇帝支配教会，信仰可能成为行政工具；若教会自称不受政治约束，它又可能把灵魂权威扩张为另一种强制。",
          consequence: "制度变化直接提出谁能判断基督教统治者的问题。",
          participants: [],
          chapterIds: ["b2-02", "b2-03"],
          graph: { row: 43, lane: 3.8 },
        },
        {
          id: "who-judges-christian-power",
          kind: "问题",
          title: "信奉基督教的皇帝犯下公共罪行时，谁有权判断并要求他悔改？",
          summary: "皇帝掌握法律、军队和行政资源，却同时作为信徒进入礼仪共同体。政治最高权力与宗教道德权威不再能够简单重合。",
          pressure: "完全服从皇帝会取消独立道德判断；让主教直接取代行政权，又会抹去两种职责的差异。",
          consequence: "安布罗斯以圣礼纪律而非夺取王位来限定皇权。",
          participants: [],
          chapterIds: ["b2-03"],
          graph: { row: 44, lane: 3.4 },
        },
        {
          id: "emperor-within-church",
          kind: "答案",
          answerRole: "区分",
          title: "皇帝在教会之内而非教会之上，政治统治不取消其道德受责性",
          summary: "安布罗斯区分帝国行政与圣礼管辖：主教不直接统治军队，却可以拒绝把礼仪变成皇权工具，并要求犯下公共罪责的皇帝以信徒身份悔改。",
          pressure: "这一先例既能限制政治无责，也为后世教会权力扩张提供资源；现实教会并不自动等同于正义共同体。",
          consequence: "帝国与教会的相对位置进一步迫使思想区分政治兴亡和救赎历史。",
          participants: [{ name: "米兰的安布罗斯", philosopherId: "ambrose", role: "以主教行动和圣礼纪律建立皇帝仍受道德判断的先例" }],
          chapterIds: ["b2-03"],
          graph: { row: 45, lane: 3.4 },
        },
        {
          id: "if-creator-good-whence-evil",
          kind: "问题",
          title: "若一切存在都由全善创造者而来，恶从哪里来？",
          summary: "把恶设为独立实体会限制创造者的全能；把恶直接归给创造者又破坏其善；只说世界层级较低，也还没有解释人的罪责和真实苦难。",
          pressure: "回答必须同时保存存在的善、恶的现实损害与行动者的责任，而不能引入与上帝对等的恶本原。",
          consequence: "奥古斯丁把新柏拉图主义的缺失结构转入创造与意志问题。",
          participants: [],
          chapterIds: ["b2-04"],
          graph: { row: 44, lane: 0.4 },
        },
        {
          id: "evil-privation-disordered-will",
          kind: "答案",
          answerRole: "修复",
          title: "恶不是独立实体，而是受造善的败坏与意志秩序的偏离",
          summary: "奥古斯丁认为存在本身在其程度上是善；恶是应有形式、秩序或关系的缺失。道德恶发生于意志离开较高善、错误依附较低对象，而不是另一个实体侵入灵魂。",
          pressure: "若意志曾自由转离善，为什么它明知较好者却反复无力选择；把罪归于自己是否意味着也能靠自己恢复。",
          consequence: "恶的本体问题转成受习惯与失序之爱束缚的意志能否自我医治。",
          participants: [{ name: "奥古斯丁", philosopherId: "augustine", role: "在创造论中把恶解释为善的缺失，并将道德恶定位为意志失序" }],
          chapterIds: ["b2-04"],
          graph: { row: 45, lane: 0.4 },
        },
        {
          id: "can-will-heal-itself",
          kind: "问题",
          title: "意志若因自己的选择和习惯而分裂，还能只靠知道善与训练自己恢复吗？",
          summary: "古代伦理治疗通常假定理性训练能够重新排列欲望；奥古斯丁却把反复自愿的选择理解为会沉积成近似必然的习惯，使人同时想改变又想延迟改变。",
          pressure: "若完全不能自救，责任似乎被取消；若总能自行恢复，恩典就只剩外部建议，无法解释深层意志无力。",
          consequence: "恩典被理解为医治并释放意志，而不是替意志行动的外部强迫。",
          participants: [],
          chapterIds: ["b2-04"],
          graph: { row: 46, lane: 0.8 },
        },
        {
          id: "grace-heals-divided-will",
          kind: "答案",
          answerRole: "转向",
          title: "恩典不是取消意志，而是医治分裂之爱，使意志重新能够选择善",
          summary: "奥古斯丁晚期越来越强调：堕落者仍以自己的意志行动，却不能只凭功绩修复意志方向；神圣恩典从内部释放并重新整合意志，使善的选择真正成为可能。",
          pressure: "恩典若决定谁能够转向，便产生预定、责任和公平的持久难题；个人救赎也必须被放入共同历史中理解。",
          consequence: "灵魂上升不再只是认知观照，而成为自由、依赖和历史救赎的张力。",
          participants: [{ name: "奥古斯丁", philosopherId: "augustine", role: "以分裂意志、原罪与恩典重写古代自我训练的能力边界" }],
          chapterIds: ["b2-04"],
          graph: { row: 47, lane: 0.8 },
        },
        {
          id: "how-time-history-relate-eternity",
          kind: "问题",
          title: "永恒的创造者、心灵经验的时间与帝国兴亡，怎样属于同一历史？",
          summary: "若时间随世界被创造，就不能追问创造之前发生了什么；若政治帝国不是终极共同体，它的成功或崩溃也不能直接等同于神圣历史的成败。",
          pressure: "需要同时区分永恒与时间、个人记忆与公共历史、可见制度与救赎共同体，又不能让现实灾难失去道德意义。",
          consequence: "奥古斯丁以心灵的时间经验和两座城重写历史尺度。",
          participants: [],
          chapterIds: ["b2-04"],
          graph: { row: 48, lane: 2.1 },
        },
        {
          id: "created-time-and-two-cities",
          kind: "答案",
          answerRole: "综合",
          title: "时间属于受造心灵的记忆—注意—期待，历史则由两种爱的共同体交织展开",
          summary: "奥古斯丁把过去、现在和未来放进心灵的记忆、注意与期待，避免把永恒理解成无限延长的时间；又以爱上帝与爱支配自身的两种方向区分两座城，使罗马命运不再等于救赎史。",
          pressure: "两座城在现实中交织，不能被简化成教会与国家两种可见机构；恩典与历史终点也仍留下权威、强制和预定问题。",
          consequence: "本阶段在此闭合：古代的最高真实已经转成创造者，伦理自我训练转成受恩典医治的意志，循环宇宙转成有起点与终点的救赎历史。",
          participants: [{ name: "奥古斯丁", philosopherId: "augustine", role: "以时间意识、两座城与爱的秩序连接内在生命和帝国历史" }],
          chapterIds: ["b2-04"],
          graph: { row: 49, lane: 2.1 },
        },
        {
          id: "can-salvation-community-survive-empire",
          kind: "问题",
          title: "当帝国瓦解，承载经文、教育与共同生活的教会怎样保存自身而不等同于帝国？",
          summary: "两座城已经把救赎共同体与罗马命运区分开，但西部行政、学校和城市网络的崩解，会把抽象区分变成制度生存问题。",
          pressure: "若没有稳定规程和跨地域组织，知识与共同生活可能断裂；若保存完全依赖权力和财富，教会又可能复制帝国的支配逻辑。",
          consequence: "这是下一阶段的开放入口：修道规程、教牧治理和教皇网络将把哲学问题进一步变成生活制度问题。",
          participants: [],
          chapterIds: ["b2-04"],
          graph: { row: 50, lane: 2.1 },
        },
      ],
    },
  ],
  edges: [
    { id: "root-01", from: "difference-as-observation", to: "difference-derived-or-original", relation: "提出问题", label: "从并存差异追问来源", connection: "本站推演" },
    { id: "root-02", from: "difference-as-observation", to: "motion-and-plurality-possible", relation: "提出问题", label: "多个对象要求概念说明", connection: "本站推演" },
    { id: "root-03", from: "change-over-time-observation", to: "identity-through-change", relation: "提出问题", label: "前后不同仍被认作同一", connection: "本站推演" },
    { id: "root-05", from: "change-over-time-observation", to: "motion-and-plurality-possible", relation: "提出问题", label: "可见变化要求运动成立", connection: "本站推演" },
    { id: "root-06", from: "conditional-change-observation", to: "identity-through-change", relation: "提出问题", label: "条件关联要求说明作用机制", connection: "本站推演" },
    { id: "root-07", from: "conditional-change-observation", to: "order-not-arbitrary-agency", relation: "提出问题", label: "可重复结果要求解释稳定次序", connection: "本站推演" },
    { id: "root-08", from: "recurring-change-observation", to: "order-not-arbitrary-agency", relation: "提出问题", label: "持续与周期要求内在秩序", connection: "本站推演" },
    { id: "root-09", from: "persistent-process-observation", to: "identity-through-change", relation: "提出问题", label: "构成更替仍保留过程同一", connection: "本站推演" },

    { id: "root-10", from: "difference-derived-or-original", to: "one-source-many-states", relation: "回应问题", label: "以一种来源统一多样", connection: "原书线索" },
    { id: "root-11", from: "difference-derived-or-original", to: "opposites-and-process", relation: "回应问题", label: "以对立分出说明多样", connection: "原书线索" },
    { id: "root-12", from: "difference-derived-or-original", to: "rarefaction-condensation", relation: "回应问题", label: "以程度变化形成多样", connection: "原书线索" },
    { id: "root-15", from: "identity-through-change", to: "rarefaction-condensation", relation: "回应问题", label: "以连续程度保存来源", connection: "同题并列" },
    { id: "root-16", from: "identity-through-change", to: "change-as-order", relation: "回应问题", label: "以持续过程维持同一", connection: "原书线索" },
    { id: "root-20", from: "order-not-arbitrary-agency", to: "opposites-and-process", relation: "回应问题", label: "以时间中的补偿维持次序", connection: "原书线索" },
    { id: "root-22", from: "order-not-arbitrary-agency", to: "difference-as-ratio", relation: "回应问题", label: "以数与比例说明秩序", connection: "同题并列" },
    { id: "root-23", from: "order-not-arbitrary-agency", to: "change-as-order", relation: "回应问题", label: "以逻各斯说明变化秩序", connection: "原书线索" },

    { id: "root-24", from: "one-source-many-states", to: "being-from-nonbeing", relation: "产生问题", label: "一种来源怎样真正生成多样", connection: "历史回应" },
    { id: "root-25", from: "opposites-and-process", to: "being-from-nonbeing", relation: "产生问题", label: "分出与复归是否预设生成", connection: "历史回应" },
    { id: "root-26", from: "rarefaction-condensation", to: "being-from-nonbeing", relation: "产生问题", label: "连续变形是否产生新存在", connection: "历史回应" },
    { id: "root-27", from: "change-as-order", to: "being-from-nonbeing", relation: "产生问题", label: "转换秩序遭遇存在约束", connection: "历史回应" },
    { id: "root-28", from: "being-from-nonbeing", to: "stable-being", relation: "回应问题", label: "拒绝从不存在生成", connection: "原书线索" },
    { id: "root-29", from: "motion-and-plurality-possible", to: "stable-being", relation: "回应问题", label: "把真正存在置于变化之外", connection: "原书线索" },
    { id: "root-30", from: "motion-and-plurality-possible", to: "test-motion-and-plurality", relation: "回应问题", label: "以悖论进行压力测试", connection: "历史回应" },
    { id: "root-31", from: "stable-being", to: "change-as-reconfiguration", relation: "产生问题", label: "不变存在与可见变化冲突", connection: "历史回应" },
    { id: "root-32", from: "test-motion-and-plurality", to: "change-as-reconfiguration", relation: "产生问题", label: "保存变化必须提高精度", connection: "历史回应" },
    { id: "e20", from: "change-as-reconfiguration", to: "roots-love-strife", relation: "回应问题", label: "版本一 · 比例与力量", connection: "历史回应" },
    { id: "e21", from: "change-as-reconfiguration", to: "mixture-nous-separation", relation: "回应问题", label: "版本二 · 混合与分离", connection: "历史回应" },
    { id: "e22", from: "change-as-reconfiguration", to: "atoms-void-arrangement", relation: "回应问题", label: "版本三 · 形状与排列", connection: "历史回应" },
    { id: "e23", from: "same-thing-different-appearance", to: "what-does-perception-reveal", relation: "提出问题", label: "从显现差异追问感觉对象", connection: "原书线索" },
    { id: "e24", from: "roots-love-strife", to: "what-does-perception-reveal", relation: "产生问题", label: "自然过程延伸到感觉", connection: "同题并列" },
    { id: "e25", from: "atoms-void-arrangement", to: "what-does-perception-reveal", relation: "产生问题", label: "原子性质与感官性质分离", connection: "历史回应" },
    { id: "e26", from: "what-does-perception-reveal", to: "perception-as-event", relation: "回应问题", label: "把感觉解释为相遇事件", connection: "同题并列" },
    { id: "e27", from: "what-does-perception-reveal", to: "appearance-relative-to-perceiver", relation: "回应问题", label: "把显现联系到感觉者", connection: "原书线索" },
    { id: "e28", from: "perception-as-event", to: "common-standard-of-judgment", relation: "产生问题", label: "感觉发生不等于原因判断", connection: "本站推演" },
    { id: "e29", from: "appearance-relative-to-perceiver", to: "common-standard-of-judgment", relation: "产生问题", label: "尺度命题留下公共标准", connection: "原书线索" },
    { id: "e29-history", from: "public-disagreement-observation", to: "common-standard-of-judgment", relation: "提出问题", label: "公共论辩使共同尺度具有制度后果", connection: "历史回应" },
    { id: "e30", from: "common-standard-of-judgment", to: "definition-beyond-instance", relation: "回应问题", label: "从实例返回共同定义", connection: "原书线索" },
    { id: "e30-politics", from: "public-disagreement-observation", to: "how-order-soul-and-polis", relation: "提出问题", label: "政治冲突要求组织欲望、教育与统治", connection: "历史回应" },
    { id: "e30-definition", from: "definition-beyond-instance", to: "how-order-soul-and-polis", relation: "产生问题", label: "善与正义的定义进入灵魂和制度", connection: "原书线索" },
    { id: "e30-justice", from: "how-order-soul-and-polis", to: "justice-as-ordered-whole", relation: "回应问题", label: "以部分功能和整体秩序说明正义", connection: "原书线索" },
    { id: "e30-soul-question", from: "justice-as-ordered-whole", to: "can-soul-survive-body", relation: "产生问题", label: "理性灵魂的统治引出身体关系", connection: "本站推演" },
    { id: "e30-soul-answer", from: "can-soul-survive-body", to: "immortal-rational-soul", relation: "回应问题", label: "以回忆、生命与净化论证灵魂延续", connection: "原书线索" },
    { id: "e30-cosmos-question", from: "immortal-rational-soul", to: "how-can-cosmos-reflect-good", relation: "产生问题", label: "灵魂秩序扩展为宇宙秩序问题", connection: "本站推演" },
    { id: "e30-cosmos-answer", from: "how-can-cosmos-reflect-good", to: "cosmos-shaped-by-form-and-good", relation: "回应问题", label: "以范型、比例与善组织宇宙", connection: "原书线索" },
    { id: "e30-cosmos-burden", from: "cosmos-shaped-by-form-and-good", to: "how-can-causes-be-known", relation: "产生问题", label: "宇宙模型要求区分目的、形式与证明", connection: "历史回应" },
    { id: "e31", from: "definition-beyond-instance", to: "what-stabilizes-knowledge", relation: "产生问题", label: "定义要求稳定共同对象", connection: "原书线索" },
    { id: "e32", from: "stable-being", to: "what-stabilizes-knowledge", relation: "产生问题", label: "理性把稳定设为知识条件", connection: "后世重构" },
    { id: "e33", from: "difference-as-ratio", to: "what-stabilizes-knowledge", relation: "产生问题", label: "数学结构提供可知模型", connection: "原书线索" },
    { id: "e34", from: "change-as-order", to: "what-stabilizes-knowledge", relation: "产生问题", label: "流变使稳定知识成为困难", connection: "原书线索" },
    { id: "e35", from: "appearance-relative-to-perceiver", to: "what-stabilizes-knowledge", relation: "产生问题", label: "相对显现迫使知识另寻对象", connection: "后世重构" },
    { id: "e36", from: "what-stabilizes-knowledge", to: "stable-object-of-knowledge", relation: "回应问题", label: "以可知形式统一多条要求", connection: "后世重构" },
    { id: "e37", from: "stable-object-of-knowledge", to: "forms-and-particulars", relation: "产生问题", label: "稳定对象留下分有负担", connection: "本站推演" },
    { id: "e38", from: "mixture-nous-separation", to: "what-does-nous-explain", relation: "产生问题", label: "努斯留下解释范围", connection: "原书线索" },

    { id: "a01", from: "forms-and-particulars", to: "immanent-form-matter", relation: "回应问题", label: "把形式放回具体实体", connection: "历史回应" },
    { id: "a02", from: "immanent-form-matter", to: "change-as-actualization-question", relation: "产生问题", label: "内在形式仍须说明真实生成", connection: "原书线索" },
    { id: "a03", from: "change-as-actualization-question", to: "potentiality-actuality", relation: "回应问题", label: "以能力实现区分尚未现实与绝对无", connection: "原书线索" },
    { id: "a04", from: "organized-life-observation", to: "what-makes-explanation-complete", relation: "提出问题", label: "组织与功能超出材料清单", connection: "原书线索" },
    { id: "a05", from: "what-makes-explanation-complete", to: "four-causes-teleology", relation: "回应问题", label: "以四类为什么补足解释", connection: "原书线索" },
    { id: "a06", from: "potentiality-actuality", to: "how-can-causes-be-known", relation: "产生问题", label: "变化结构需要可证明的原因知识", connection: "本站推演" },
    { id: "a07", from: "four-causes-teleology", to: "how-can-causes-be-known", relation: "产生问题", label: "多层原因要求区分发现与证明", connection: "本站推演" },
    { id: "a08", from: "how-can-causes-be-known", to: "demonstration-classification", relation: "回应问题", label: "观察分类与逻辑证明相互配合", connection: "原书线索" },

    { id: "b01", from: "actions-aim-goods-observation", to: "what-is-human-flourishing", relation: "提出问题", label: "局部目标要求完整生活尺度", connection: "原书线索" },
    { id: "b02", from: "demonstration-classification", to: "what-is-human-flourishing", relation: "产生问题", label: "功能解释转向人的卓越活动", connection: "本站推演" },
    { id: "b03", from: "what-is-human-flourishing", to: "virtue-as-rational-activity", relation: "回应问题", label: "以一生的德性活动界定幸福", connection: "原书线索" },
    { id: "b04", from: "constitutions-shape-character-observation", to: "can-good-life-be-private", relation: "提出问题", label: "制度塑造习惯与行动能力", connection: "历史回应" },
    { id: "b05", from: "virtue-as-rational-activity", to: "can-good-life-be-private", relation: "产生问题", label: "德性活动依赖友谊与外部条件", connection: "原书线索" },
    { id: "b06", from: "can-good-life-be-private", to: "polis-practical-wisdom", relation: "回应问题", label: "以法律教育和实践智慧连接个人与城邦", connection: "原书线索" },
    { id: "b07", from: "polis-practical-wisdom", to: "how-live-uncontrollable-world", relation: "产生问题", label: "城邦条件暴露幸福的政治脆弱性", connection: "本站推演" },
    { id: "b08", from: "polis-autonomy-collapse", to: "how-live-uncontrollable-world", relation: "提出问题", label: "帝国化拉大个人与公共控制距离", connection: "历史回应" },

    { id: "h01", from: "how-live-uncontrollable-world", to: "cynic-low-dependence", relation: "回应问题", label: "以减少需要和反习俗降低支配", connection: "历史回应" },
    { id: "h02", from: "how-live-uncontrollable-world", to: "skeptical-suspension", relation: "回应问题", label: "以悬置断言降低扰动", connection: "历史回应" },
    { id: "h03", from: "how-live-uncontrollable-world", to: "epicurean-natural-therapy", relation: "回应问题", label: "以自然知识和欲望管理获得宁静", connection: "历史回应" },
    { id: "h04", from: "how-live-uncontrollable-world", to: "stoic-virtue-in-order", relation: "回应问题", label: "以德性和同意保存因果世界中的自由", connection: "历史回应" },
    { id: "h05", from: "cynic-low-dependence", to: "freedom-withdrawal-or-role", relation: "产生问题", label: "退出规范是否等于完整自由", connection: "同题并列" },
    { id: "h06", from: "stoic-virtue-in-order", to: "freedom-withdrawal-or-role", relation: "产生问题", label: "内在同意是否能容纳公共角色", connection: "同题并列" },
    { id: "h07", from: "skeptical-suspension", to: "tranquility-needs-knowledge", relation: "产生问题", label: "减少承诺能否替代理解自然", connection: "同题并列" },
    { id: "h08", from: "epicurean-natural-therapy", to: "tranquility-needs-knowledge", relation: "产生问题", label: "治疗需要哪些自然知识", connection: "同题并列" },
    { id: "h09", from: "skeptical-suspension", to: "can-impression-certify-truth", relation: "产生问题", label: "悬置要求检验印象的自证能力", connection: "历史回应" },
    { id: "h10", from: "stoic-virtue-in-order", to: "can-impression-certify-truth", relation: "产生问题", label: "理性同意需要可靠认知起点", connection: "历史回应" },

    { id: "c01", from: "freedom-withdrawal-or-role", to: "role-and-inner-freedom", relation: "回应问题", label: "在角色中限定可负责的判断与行动", connection: "历史回应" },
    { id: "c02", from: "tranquility-needs-knowledge", to: "natural-knowledge-removes-fear", relation: "回应问题", label: "保留以解除恐惧为目标的自然知识", connection: "原书线索" },
    { id: "c03", from: "can-impression-certify-truth", to: "suspend-self-certifying-assent", relation: "回应问题", label: "以不可区分反例拒绝自证印象", connection: "历史回应" },
    { id: "c04", from: "can-impression-certify-truth", to: "cognitive-impression-and-assent", relation: "回应问题", label: "以认知印象和同意建立把握", connection: "历史回应" },
    { id: "c05", from: "suspend-self-certifying-assent", to: "how-act-without-certainty", relation: "产生问题", label: "严格悬置遭遇实践反驳", connection: "历史回应" },
    { id: "c06", from: "how-act-without-certainty", to: "probable-tested-guidance", relation: "回应问题", label: "以分层可信度支持可修正行动", connection: "历史回应" },
    { id: "c07", from: "cognitive-impression-and-assent", to: "fate-and-responsibility", relation: "产生问题", label: "同意进入决定论责任难题", connection: "原书线索" },
    { id: "c08", from: "fate-and-responsibility", to: "assent-as-internal-cause", relation: "回应问题", label: "以主体内部原因保存责任", connection: "历史回应" },
    { id: "c09", from: "natural-knowledge-removes-fear", to: "is-natural-explanation-enough", relation: "产生问题", label: "非天意自然仍需价值与共同生活", connection: "本站推演" },
    { id: "c10", from: "is-natural-explanation-enough", to: "friendship-contract-without-providence", relation: "回应问题", label: "以友谊、审慎和互利契约补足伦理", connection: "原书线索" },
    { id: "c11", from: "imperial-law-observation", to: "who-belongs-moral-community", relation: "提出问题", label: "共同法律扩大共同体尺度", connection: "历史回应" },
    { id: "c12", from: "role-and-inner-freedom", to: "who-belongs-moral-community", relation: "产生问题", label: "角色义务要求说明对谁负责", connection: "历史回应" },
    { id: "c13", from: "probable-tested-guidance", to: "who-belongs-moral-community", relation: "产生问题", label: "政治正反论证追问正义范围", connection: "同题并列" },
    { id: "c14", from: "who-belongs-moral-community", to: "cosmopolis-common-reason", relation: "回应问题", label: "以共同理性和自然法扩展到所有人", connection: "历史回应" },

    { id: "p01", from: "imperial-vulnerability-observation", to: "is-inner-freedom-enough", relation: "提出问题", label: "制度失序重新暴露死亡与意义压力", connection: "历史回应" },
    { id: "p02", from: "role-and-inner-freedom", to: "is-inner-freedom-enough", relation: "产生问题", label: "角色操练仍不能取消苦难与死亡", connection: "本站推演" },
    { id: "p03", from: "assent-as-internal-cause", to: "is-inner-freedom-enough", relation: "产生问题", label: "责任结构未回答最高真实", connection: "本站推演" },
    { id: "p04", from: "friendship-contract-without-providence", to: "is-inner-freedom-enough", relation: "产生问题", label: "小共同体仍面对终极脆弱性", connection: "本站推演" },
    { id: "p05", from: "cosmopolis-common-reason", to: "is-inner-freedom-enough", relation: "产生问题", label: "普遍法仍不能提供最终安顿", connection: "本站推演" },
    { id: "p06", from: "is-inner-freedom-enough", to: "one-intellect-soul", relation: "回应问题", label: "把伦理内向转成真实层级与灵魂回归", connection: "历史回应" },
    { id: "p07", from: "one-intellect-soul", to: "how-many-from-one", relation: "产生问题", label: "三重本原留下由一到多难题", connection: "原书线索" },
    { id: "p08", from: "how-many-from-one", to: "emanation-without-loss", relation: "回应问题", label: "以完满活动的外在结果说明派生", connection: "后世重构" },
    { id: "p09", from: "emanation-without-loss", to: "is-sensible-world-evil", relation: "产生问题", label: "层级依赖可能被误读为世界邪恶", connection: "原书线索" },
    { id: "p10", from: "is-sensible-world-evil", to: "dependent-image-not-evil", relation: "回应问题", label: "以善的程度与依赖影像拒绝二元恶本原", connection: "历史回应" },
    { id: "p11", from: "dependent-image-not-evil", to: "reason-or-divine-aid", relation: "产生问题", label: "哲学回归与基督教救赎在此分叉", connection: "后世重构" },

    { id: "r01", from: "scriptural-history-observation", to: "does-transcendent-good-act-in-history", relation: "提出问题", label: "有方向的共同记忆要求说明神圣行动", connection: "原书线索" },
    { id: "r02", from: "does-transcendent-good-act-in-history", to: "creator-covenant-salvation-history", relation: "回应问题", label: "以创造、盟约与救赎史连接超越和时间", connection: "原书线索" },
    { id: "r03", from: "creator-covenant-salvation-history", to: "how-can-revelation-enter-reason", relation: "产生问题", label: "历史叙事需要跨概念解释", connection: "本站推演" },
    { id: "r04", from: "how-can-revelation-enter-reason", to: "logos-layered-exegesis-text", relation: "回应问题", label: "以逻各斯、释义层次和文本校勘解释", connection: "历史回应" },
    { id: "r05", from: "reason-or-divine-aid", to: "logos-layered-exegesis-text", relation: "回应问题", label: "理性在启示内部工作而非被取消", connection: "后世重构" },
    { id: "r06", from: "church-imperial-observation", to: "who-judges-christian-power", relation: "提出问题", label: "帝国宗教化使权威冲突具有公共后果", connection: "历史回应" },
    { id: "r07", from: "logos-layered-exegesis-text", to: "who-judges-christian-power", relation: "产生问题", label: "解释共同体取得制度权威后必须面对皇权", connection: "本站推演" },
    { id: "r08", from: "who-judges-christian-power", to: "emperor-within-church", relation: "回应问题", label: "以圣礼管辖区分并限制政治最高权力", connection: "历史回应" },
    { id: "r09", from: "creator-covenant-salvation-history", to: "if-creator-good-whence-evil", relation: "产生问题", label: "全善创造使恶成为尖锐解释负担", connection: "原书线索" },
    { id: "r10", from: "dependent-image-not-evil", to: "if-creator-good-whence-evil", relation: "产生问题", label: "善的缺失结构进入创造与罪责问题", connection: "历史回应" },
    { id: "r11", from: "if-creator-good-whence-evil", to: "evil-privation-disordered-will", relation: "回应问题", label: "区分存在之善、缺失与意志偏离", connection: "历史回应" },
    { id: "r12", from: "evil-privation-disordered-will", to: "can-will-heal-itself", relation: "产生问题", label: "意志负责却又被自己的习惯束缚", connection: "原书线索" },
    { id: "r13", from: "can-will-heal-itself", to: "grace-heals-divided-will", relation: "回应问题", label: "以恩典医治而非外部强迫解释恢复", connection: "历史回应" },
    { id: "r14", from: "reason-or-divine-aid", to: "grace-heals-divided-will", relation: "回应问题", label: "把神圣援助落实为意志能力的修复", connection: "后世重构" },
    { id: "r15", from: "creator-covenant-salvation-history", to: "how-time-history-relate-eternity", relation: "产生问题", label: "创造和救赎要求区分永恒与历史", connection: "原书线索" },
    { id: "r16", from: "grace-heals-divided-will", to: "how-time-history-relate-eternity", relation: "产生问题", label: "个人转向进入共同救赎历史", connection: "本站推演" },
    { id: "r17", from: "emperor-within-church", to: "how-time-history-relate-eternity", relation: "产生问题", label: "皇权受限迫使政治帝国与救赎共同体分离", connection: "原书线索" },
    { id: "r18", from: "how-time-history-relate-eternity", to: "created-time-and-two-cities", relation: "回应问题", label: "以心灵时间与两种爱的历史共同体综合", connection: "原书线索" },
    { id: "r19", from: "created-time-and-two-cities", to: "can-salvation-community-survive-empire", relation: "产生问题", label: "可见帝国非终极却仍承载制度条件", connection: "本站推演" },
  ],
  sources: [
    { label: "罗素《西方哲学史》第一卷", url: "", note: "本站主叙述骨架；覆盖希腊文明兴起、前苏格拉底自然哲学、雅典体系、希腊化学派、罗马文化与普罗提诺三十章。" },
    { label: "SEP · Presocratic Philosophy", url: "https://plato.stanford.edu/archives/sum2024/entries/presocratics/", note: "用于校正米利都学派、多元论与原子论之间的关系，以及前苏格拉底材料的证据边界。" },
    { label: "SEP · Heraclitus", url: "https://plato.stanford.edu/entries/heraclitus/", note: "用于避免把赫拉克利特简化成无差别的“万物流变”。" },
    { label: "SEP · Parmenides", url: "https://plato.stanford.edu/entries/parmenides/", note: "用于标示严格一元论只是重要解释之一，并保留其宇宙论部分的解释困难。" },
    { label: "SEP · Protagoras", url: "https://plato.stanford.edu/entries/protagoras/", note: "用于校正“人是万物的尺度”与感觉、显现之间的关系。" },
    { label: "SEP · Plato on Knowledge in the Theaetetus", url: "https://plato.stanford.edu/archives/spr2026/entries/plato-theaetetus/", note: "用于区分柏拉图在对话中检验的立场与可直接归于普罗泰戈拉、赫拉克利特的历史主张。" },
    { label: "SEP · Aristotle's Metaphysics", url: "https://plato.stanford.edu/entries/aristotle-metaphysics/", note: "用于校正实体、质料—形式、潜能—现实及目的说明之间的关系。" },
    { label: "SEP · Ancient Ethical Theory", url: "https://plato.stanford.edu/entries/ethics-ancient/", note: "用于比较亚里士多德、犬儒、伊壁鸠鲁、斯多葛和怀疑路线怎样重新界定幸福与外物。" },
    { label: "SEP · Ancient Skepticism", url: "https://plato.stanford.edu/entries/skepticism-ancient/", note: "用于区分皮浪式传统与学院怀疑主义，并校正悬置、认知印象和实践标准的争论。" },
    { label: "SEP · Stoicism", url: "https://plato.stanford.edu/entries/stoicism/", note: "用于校正逻辑—物理—伦理一体结构、兼容论、世界城邦及罗马实践转译。" },
    { label: "SEP · Plotinus", url: "https://plato.stanford.edu/entries/plotinus/", note: "用于校正太一、精神、灵魂、双重活动与流溢—回归结构。" },
    { label: "罗素《西方哲学史》第二卷第一至四章", url: "", note: "用于从犹太宗教发展、早期基督教、三位教会博士推进到奥古斯丁的时间、恶、意志、恩典与历史问题。" },
    { label: "SEP · Philo of Alexandria", url: "https://plato.stanford.edu/entries/philo/", note: "用于校正斐洛的犹太思想语境、逻各斯多重用法、创造论与哲学作为释经工具的边界。" },
    { label: "SEP · Origen", url: "https://plato.stanford.edu/entries/origen/", note: "用于校正奥利金的多层释经、自由受造物、基督—逻各斯与后世奥利金主义之间的差异。" },
    { label: "SEP · Augustine", url: "https://plato.stanford.edu/entries/augustine/", note: "用于校正恶的缺失、分裂意志、恩典、时间与两个城，并保留奥古斯丁早晚期思想变化。" },
    { label: "SEP · Philosophy and Christian Theology", url: "https://plato.stanford.edu/entries/christiantheology-philosophy/", note: "用于区分哲学概念、教会会议与基督教教义形成的不同作用，避免把教父传统写成单一学派。" },
  ],
};

export const problemMaps = [ancientDifferenceProblemMap];
