import type { ProblemEdge, ProblemMapSource, ProblemPhase } from "./problem-map-data";

export const enlightenmentProblemPhases: ProblemPhase[] = [
  {
    id: "spinoza-one-substance-affects-freedom",
    order: 29,
    label: "唯一实体与能动自由",
    title: "以唯一实体取消心物互动，再从情感因果与共同能力重写自由",
    question: "若思维与广延不是两个独立实体，有限个体、心身关系和自由应怎样重新说明？",
    transition: "斯宾诺莎接受笛卡尔关于属性和清楚理解的部分工具，却拒绝两个受造实体。上帝或自然是唯一无限实体，个体是其样态；心与身表达同一秩序，伦理任务则从无原因选择转成理解并组织造成情感与行动的原因。",
    nodes: [
      {
        id: "one-substance-god-or-nature",
        kind: "答案",
        answerRole: "转向",
        title: "只承认一个自因且无限的实体：上帝或自然",
        summary: "真正实体必须通过自身被设想并拥有自身存在理由；若两个实体共享同一属性，就缺少区分它们的充分根据。有限心物因此不再是独立实体。",
        pressure: "唯一实体若包容一切，仍要说明有限事物如何真实有别，也要避免把上帝或自然误读成具有计划和情绪的人格者。",
        consequence: "问题转向属性与样态：同一无限实在怎样以有限而确定的方式存在。",
        participants: [{ name: "巴鲁赫·斯宾诺莎", philosopherId: "spinoza", role: "以 causa sui 与实体唯一性重写笛卡尔实体体系" }],
        chapterIds: ["b3-10"], graph: { row: 272, lane: 2.8 },
      },
      {
        id: "how-can-finite-things-differ-within-one-substance",
        kind: "问题",
        title: "若只有一个实体，具体身体、心灵和事件凭什么保持差异？",
        summary: "取消实体复数不能把一切压成没有结构的同一物；有限事物仍以确定关系作用、受作用并持续一段时间。",
        pressure: "若样态只是幻象，伦理与因果研究失去对象；若样态又完全独立，实体复数会悄然返回。",
        consequence: "属性表达实体本质，样态则是在属性中被其他样态限定的有限方式。",
        participants: [], chapterIds: ["b3-10"], graph: { row: 273, lane: 2.8 },
      },
      {
        id: "attributes-and-modes-articulate-one-nature",
        kind: "答案",
        answerRole: "区分",
        title: "属性表达同一实体的本质，个体则是相互限定的有限样态",
        summary: "人认识思维与广延两种属性；每个观念与身体都是自然在确定因果关系中的样态，而不是脱离整体自立的东西。",
        pressure: "属性究竟只是认识方式还是实体自身结构存在解释争议；有限个体的统一和持续也仍需关系说明。",
        consequence: "心与身体可被理解为同一有限事物在思维与广延下的两种表达。",
        participants: [{ name: "巴鲁赫·斯宾诺莎", philosopherId: "spinoza", role: "以属性—样态结构保存同一自然内部的有限差异" }],
        chapterIds: ["b3-10"],
        sourceRefs: [{ sourceLabel: "SEP · Baruch Spinoza", locator: "条目关于实体、属性与样态的说明", evidenceNote: "用于区分实体的属性与具体个体的有限样态。" }],
        graph: { row: 274, lane: 2.8 },
      },
      {
        id: "if-mind-and-body-do-not-interact-how-correspond",
        kind: "问题",
        title: "心灵与身体若不跨属性作用，为何观念次序与身体变化仍彼此对应？",
        summary: "疼痛和行动看似需要两种东西交换因果；唯一实体论却不允许思想把运动推入广延，也不允许运动跨入思想。",
        pressure: "只说两条序列同步会留下谁使其同步的问题；解释必须来自两者作为同一因果秩序的身份。",
        consequence: "心身对应被重写为同一事件在不同属性下的平行表达。",
        participants: [], chapterIds: ["b3-10"], graph: { row: 275, lane: 2.2 },
      },
      {
        id: "mind-body-parallel-expression",
        kind: "答案",
        answerRole: "修复",
        title: "观念的次序与事物的次序相同，因为心与身是同一因果秩序的两种表达",
        summary: "心灵是身体的观念，不是坐在身体中的操作者；同一变化在思维属性下是观念关系，在广延属性下是身体关系。",
        pressure: "平行表达避免跨实体碰撞，却使个人控制、责任和第一人称能动性需要新的自然主义说明。",
        consequence: "自由问题不再是意志脱离原因，而是一个有限样态在多大程度上理解并组织自身原因。",
        participants: [{ name: "巴鲁赫·斯宾诺莎", philosopherId: "spinoza", role: "用心身同一与平行表达替代笛卡尔式互动" }],
        chapterIds: ["b3-10"],
        sourceRefs: [{ sourceLabel: "SEP · Baruch Spinoza", locator: "条目关于思维、广延及心身平行的说明", evidenceNote: "用于核对心与身是同一有限事物在不同属性下的表达。" }],
        graph: { row: 276, lane: 2.2 },
      },
      {
        id: "affects-shift-capacity-observation",
        kind: "观察",
        observation: { domain: "个体体验", note: "恐惧、希望、愤怒和喜悦会改变身体可行动的范围，也改变心灵能理解和组合的能力；人常知道欲望却不知道欲望的原因。" },
        title: "情感会扩大或缩小行动能力，人却常只意识到欲望而不知道其原因",
        summary: "同一人可因恐惧变得反应性，也可因理解关系而获得更稳定的行动方向；这使自由呈现为程度差异。",
        pressure: "把情感纳入因果自然容易被误读为取消伦理，但无法解释的被动与可理解的主动仍有实际差别。",
        consequence: "观察提出决定论自然中何种意义的自由仍可能成立。",
        participants: [{ name: "巴鲁赫·斯宾诺莎", philosopherId: "spinoza", role: "把情感当作可因果理解的身心能力变化" }],
        chapterIds: ["b3-10"], graph: { row: 276, lane: 0.5 },
      },
      {
        id: "what-can-freedom-mean-in-necessary-nature",
        kind: "问题",
        title: "若每一欲望和决定都有原因，自由还能意味着什么？",
        summary: "无原因选择既破坏可理解性，也不能说明行动为何真正属于行动者；但完全由不懂的外因推动又显然是一种受制。",
        pressure: "自由若只等于知道自己不自由会失去实践差异；答案必须说明理解怎样真实改变行动能力。",
        consequence: "斯宾诺莎以保存自身的努力和充分原因知识区分被动与主动。",
        participants: [], chapterIds: ["b3-10"], graph: { row: 277, lane: 1.2 },
      },
      {
        id: "conatus-and-adequate-understanding-increase-agency",
        kind: "答案",
        answerRole: "转向",
        title: "自由是由自身可理解本性更充分地行动，而不是逃离因果",
        summary: "每一事物都努力保存并增强自身存在；当观念只记录外因结果时人较被动，当观念把握共同结构与原因时行动更多出自自身能力。",
        pressure: "充分理解不会让有限者控制全部外因，也不能把疾病、压迫或情绪痛苦简单归为认识不足。",
        consequence: "伦理任务变成把被动情感重新组织为更主动、共享且稳定的理解。",
        participants: [{ name: "巴鲁赫·斯宾诺莎", philosopherId: "spinoza", role: "以 conatus、充分观念与主动情感重写自由" }],
        chapterIds: ["b3-10"], graph: { row: 278, lane: 1.2 },
      },
      {
        id: "can-understanding-transform-passions-without-suppressing-them",
        kind: "问题",
        title: "理解情感的原因怎样改变情感，而不只是给它贴上理性标签？",
        summary: "情感是身体能力与观念结构的真实变化，不会因一句命令消失；新的理解必须与更强的共同关系和替代情感结合。",
        pressure: "把理性生活想成冷漠压抑会错过喜悦、友谊和共同能力在体系中的正面作用。",
        consequence: "理性通过共同概念、因果重述与较强主动情感改变欲望组合。",
        participants: [], chapterIds: ["b3-10"], graph: { row: 279, lane: 1.2 },
      },
      {
        id: "active-affects-through-common-causes",
        kind: "答案",
        answerRole: "综合",
        title: "用共同原因和更强的主动情感重组被动激情",
        summary: "把偶然得失放入更广因果秩序，会减弱对单一对象的执著；与他人共同理解和行动又能增加每个人的能力。",
        pressure: "理性治疗仍依赖身体、教育与制度条件，不能只作为孤立哲学家的内在练习。",
        consequence: "个人自由自然地通向思想表达、制度稳定与共同力量的问题。",
        participants: [{ name: "巴鲁赫·斯宾诺莎", philosopherId: "spinoza", role: "把伦理自由连接到共同理解与共同能力" }],
        chapterIds: ["b3-10"], graph: { row: 280, lane: 1.2 },
      },
      {
        id: "confessional-fear-censorship-observation",
        kind: "观察",
        observation: { domain: "历史变化", note: "荷兰共和国的宗派冲突、审查和政治暴力显示，试图以恐惧统一思想可能反而削弱忠诚与和平。", historyLinks: [{ stageId: "early-modern", responseId: "rationalists", label: "共和国中的经文、思想与政治自由", note: "进入历史概览查看宗教战争、新科学和共和政治怎样共同形成自由表达问题。" }] },
        title: "宗派冲突与审查显示，强制统一信念可能制造虚伪、恐惧和更大不稳定",
        summary: "政治权力能够约束行动，却很难直接命令人真诚相信；压制解释争论还可能把宗教权威变成争夺国家的工具。",
        pressure: "思想自由若完全不受公共规则约束也会面对煽动和冲突；关键是区分信念、表达与破坏性行动。",
        consequence: "观察提出自由表达是否能成为国家力量而非国家威胁。",
        participants: [{ name: "巴鲁赫·斯宾诺莎", philosopherId: "spinoza", role: "在《神学政治论》中连接经文批判、思想自由与国家和平" }],
        chapterIds: ["b3-10"], graph: { row: 279, lane: 4.2 },
      },
      {
        id: "can-free-thought-strengthen-common-power",
        kind: "问题",
        title: "让人自由思考和表达，会削弱共同权力还是使它更稳定？",
        summary: "国家若以安全和共同生活为目的，不必取得每个人的心灵；压制无法消除的判断差异可能消耗更多权力。",
        pressure: "斯宾诺莎的思想自由并非今日全部表达权制度，也与国家对宗教和行动的强控制并存。",
        consequence: "答案以思想自由、法治和较广参与扩大共同体的可持续能力。",
        participants: [], chapterIds: ["b3-10"], graph: { row: 280, lane: 4.2 },
      },
      {
        id: "freedom-of-philosophizing-supports-peace",
        kind: "答案",
        answerRole: "修复",
        title: "国家约束公共行动而不强迫内心判断，思想自由可减少虚伪并增强和平",
        summary: "个人自然力量不会在订约后消失；可持续国家应把真实力量组织为共同权利，并允许不破坏公共秩序的哲学表达。",
        pressure: "这一政治自然主义仍需说明个体如何不被唯一实体和集体力量吸收，以及偶然选择是否只是幻象。",
        consequence: "终端问题转向莱布尼茨：能否既保留整体可理解性，又保存真实个体与偶然性。",
        participants: [{ name: "巴鲁赫·斯宾诺莎", philosopherId: "spinoza", role: "把思想自由论证为国家和平与能力的条件" }],
        chapterIds: ["b3-10"], graph: { row: 281, lane: 4.2 },
      },
      {
        id: "can-individuals-and-contingency-survive-complete-intelligibility",
        kind: "问题",
        title: "世界完全可理解时，怎样既保留真正个体，又使事实不是同一实体的必然展开？",
        summary: "斯宾诺莎以唯一实体获得统一，却被批评削弱个体独立和偶然选择；重新引入多个实体又会恢复互动问题。",
        pressure: "答案必须同时说明个体统一、彼此协调、事实理由与自由，而不能仅把困难交给神秘作用。",
        consequence: "第三卷第十一章莱布尼茨将以单子、充足理由、可能世界和预定和谐尝试多元综合。",
        participants: [{ name: "戈特弗里德·威廉·莱布尼茨", philosopherId: "leibniz", role: "将在下一章以多元活动中心回应斯宾诺莎式必然一元论" }],
        chapterIds: ["b3-10", "b3-11"], graph: { row: 282, lane: 2.8 },
      },
    ],
  },
  {
    id: "leibniz-monads-reasons-possible-worlds",
    order: 30,
    label: "单子与充足理由",
    title: "以多重内在视角保存个体，再用充足理由和可能世界组织整体",
    question: "没有外部输入的真正个体怎样共同构成一个有规律、偶然而可理解的世界？",
    transition: "莱布尼茨拒绝把物质只等同被动广延，也拒绝唯一实体吞没个体。简单实体以知觉和欲求从内部变化；充足理由要求说明事实为何如此，可能世界与最佳选择则试图让确定理由不等于逻辑必然。",
    nodes: [
      {
        id: "monads-as-active-perspectival-unities",
        kind: "答案", answerRole: "转向",
        title: "真正实体是无部分、具有知觉与欲求的活动统一体",
        summary: "广延物可以继续分割，不能提供最终统一；单子则从自身原则展开状态，并以不同清晰度表达同一宇宙。",
        pressure: "单子没有窗户且不直接交换状态时，公共世界和身体互动看似变成彼此孤立的私人序列。",
        consequence: "必须解释多个内在历史为何持续对应。",
        participants: [{ name: "戈特弗里德·威廉·莱布尼茨", philosopherId: "leibniz", role: "以单子保存个体统一、活动与视角差异" }],
        chapterIds: ["b3-11"], graph: { row: 283, lane: 2.8 },
      },
      {
        id: "how-can-windowless-monads-share-one-world",
        kind: "问题",
        title: "彼此没有因果窗口的单子，怎样共享同一个身体世界？",
        summary: "若每个实体只按自身概念变化，碰撞、沟通和心身作用都不能是状态从一个实体流入另一个实体。",
        pressure: "偶然同步无法说明稳定自然规律；临时神迹式协调又会让普通因果失去自主结构。",
        consequence: "预定和谐把对应写入各实体的完整发展法则。",
        participants: [], chapterIds: ["b3-11"], graph: { row: 284, lane: 2.1 },
      },
      {
        id: "preestablished-harmony-coordinates-perspectives",
        kind: "答案", answerRole: "修复",
        title: "各单子依自身法则展开，却从创造起就在整体上保持预定和谐",
        summary: "心灵的意愿与身体运动不是跨实体传递，而是两个系列在共同世界设计中的对应；物理因果仍可作为现象层的规律说明。",
        pressure: "预定安排避免持续干预，却把协调负担集中到上帝选择，并使未来似乎已完整写入个体概念。",
        consequence: "问题转为完整理由与真实偶然性是否相容。",
        participants: [{ name: "戈特弗里德·威廉·莱布尼茨", philosopherId: "leibniz", role: "以预定和谐连接实体独立与现象规律" }],
        chapterIds: ["b3-11"], graph: { row: 285, lane: 2.1 },
      },
      {
        id: "does-complete-reason-make-every-truth-necessary",
        kind: "问题",
        title: "若每个事实都有充分理由并包含在个体概念中，一切是否都变成逻辑必然？",
        summary: "‘凯撒渡过卢比孔河’若属于凯撒完整概念，看似不可能不发生；但莱布尼茨仍要区分矛盾必然与被选择世界中的确定事实。",
        pressure: "仅把一种必然称作道德必然不能自动保存相反可能；必须说明其他完整世界如何保持可思。",
        consequence: "真理被分为有限分析可证的理性真理与需要无限分析的事实真理。",
        participants: [], chapterIds: ["b3-11"], graph: { row: 286, lane: 3.2 },
      },
      {
        id: "truths-of-reason-fact-and-possible-worlds",
        kind: "答案", answerRole: "区分",
        title: "理性真理由矛盾律保证，事实真理则在其他可能世界中可以不同",
        summary: "必要真理的否定包含矛盾；偶然事实虽有充分理由，其否定仍可设想在另一组相容可能中成立。",
        pressure: "可能世界不是同时存在的平行宇宙；为何这一完整组合被实现，仍需要选择理由。",
        consequence: "充足理由把问题推进到上帝为何选择这个世界。",
        participants: [{ name: "戈特弗里德·威廉·莱布尼茨", philosopherId: "leibniz", role: "以真理类型和可能世界区分确定性与逻辑必然" }],
        chapterIds: ["b3-11"], graph: { row: 287, lane: 3.2 },
      },
      {
        id: "why-is-this-world-actual-among-possibilities",
        kind: "问题",
        title: "无限可能秩序中，为什么恰好这个世界成为现实？",
        summary: "列出世界内部原因仍可继续追问整个系列为何存在；充分理由不能停在一个任意事实。",
        pressure: "若完满者必然选择唯一最佳世界，自由选择可能再次收缩成必然；若没有最佳项，选择又似乎无充分理由。",
        consequence: "莱布尼茨以最大多样、秩序和整体可相容性的最佳组合回答。",
        participants: [], chapterIds: ["b3-11"], graph: { row: 288, lane: 3.2 },
      },
      {
        id: "best-compossible-world-as-choice-reason",
        kind: "答案", answerRole: "综合",
        title: "现实是上帝在可相容整体中依最佳理由选择的世界",
        summary: "最佳不等于每个局部都无痛苦，而是整体规律、丰富性、自由行动和可实现秩序的组合优于其他完整可能。",
        pressure: "从局部恶到整体更佳的推理超出有限观察，也容易把真实苦难工具化；最佳标准本身需要独立辩护。",
        consequence: "体系必须正面解释恶为何被允许，以及个体区别是否具有充分理由。",
        participants: [{ name: "戈特弗里德·威廉·莱布尼茨", philosopherId: "leibniz", role: "以最佳可相容世界为现实选择提供充分理由" }],
        chapterIds: ["b3-11"], graph: { row: 289, lane: 3.2 },
      },
      {
        id: "can-best-world-justify-evil-and-suffering",
        kind: "问题",
        title: "若现实是最佳可能世界，错误、罪恶和无辜痛苦为何仍存在？",
        summary: "整体比较可以说明某些限制与规律相连，却不能仅凭‘最佳’标签消除每一具体恶的道德压力。",
        pressure: "认识有限不能成为免检答案；神义论需要区分逻辑可能、创造条件与不可被人掌握的整体判断。",
        consequence: "恶被解释为有限世界与更大整体条件中的许可，而非被称为善本身。",
        participants: [], chapterIds: ["b3-11"], graph: { row: 290, lane: 3.8 },
      },
      {
        id: "evil-permitted-not-good-in-itself",
        kind: "答案", answerRole: "区分",
        title: "恶不是自身为善，而是在有限受造秩序中被允许的缺陷或代价",
        summary: "形而上有限、自然痛苦与道德罪恶承担不同解释；莱布尼茨主张上帝允许它们只因没有它们的完整世界整体更差。",
        pressure: "这一比较无法由有限者完整验证，也没有解除受苦者的实践要求；后世讽刺正针对把体系乐观替代具体回应。",
        consequence: "充足理由的野心开始显出人类知识边界，向经验主义的有限性转折。",
        participants: [{ name: "戈特弗里德·威廉·莱布尼茨", philosopherId: "leibniz", role: "区分恶的类型并以整体选择论说明许可" }],
        chapterIds: ["b3-11"], graph: { row: 291, lane: 3.8 },
      },
      {
        id: "unnoticed-perceptions-observation",
        kind: "观察",
        observation: { domain: "个体体验", note: "海浪声等整体知觉包含大量未被单独注意的微小知觉；意识并不穷尽心灵的全部活动。" },
        title: "清楚意识由大量未被单独注意的微小知觉逐渐形成",
        summary: "人听见海浪整体却不分别意识每一道小波；睡眠、习惯和模糊感受也显示心灵活动有清晰度层级。",
        pressure: "若知觉连续而意识断续，个人持续不能只靠每一时刻的明确自觉，也不能把心灵当作空白容器。",
        consequence: "观察提出连续知觉怎样生成反省、记忆和理性。",
        participants: [{ name: "戈特弗里德·威廉·莱布尼茨", philosopherId: "leibniz", role: "以 petites perceptions 说明意识的连续背景" }],
        chapterIds: ["b3-11"], graph: { row: 286, lane: 0.4 },
      },
      {
        id: "how-do-perception-memory-and-reason-emerge",
        kind: "问题",
        title: "持续的微小知觉怎样形成记忆、自我意识与理性？",
        summary: "单子皆有知觉却不是都能反省；需要区分裸单子、具有记忆的灵魂和能把握必要真理的理性精神。",
        pressure: "等级连续若过于平滑，会模糊规范性理性与因果反应之间的差别。",
        consequence: "统觉和反省让部分知觉成为可归属于自我的明确认识。",
        participants: [], chapterIds: ["b3-11"], graph: { row: 287, lane: 0.4 },
      },
      {
        id: "apperception-builds-conscious-continuity",
        kind: "答案", answerRole: "区分",
        title: "知觉提供连续背景，统觉、记忆与理性形成较高层的自我认识",
        summary: "意识不是从无内容起步，而是在内在倾向和微小知觉上变清楚；天赋观念更像结构与能力，而非随时被意识到的完整命题。",
        pressure: "把倾向称为天赋可能过度扩张概念，使任何后来能力都能被追认为先天。",
        consequence: "问题明确转向洛克：观念究竟需要内在倾向，还是可由感觉与反省说明。",
        participants: [{ name: "戈特弗里德·威廉·莱布尼茨", philosopherId: "leibniz", role: "以统觉和倾向论反对被动空白心灵" }],
        chapterIds: ["b3-11"], graph: { row: 288, lane: 0.4 },
      },
      {
        id: "are-ideas-innate-dispositions-or-experiential-materials",
        kind: "问题",
        title: "普遍观念来自内在结构与倾向，还是全部材料都能追溯到感觉和反省？",
        summary: "莱布尼茨认为经验触发而不创造必要结构；洛克则反对把未被共同意识的命题当作天赋内容。",
        pressure: "争论不能只靠‘天赋’一词：必须区分命题内容、认知能力、形成材料和证明根据。",
        consequence: "第三卷第十三章洛克将以观念来源和知识范围分析重写问题，第三卷第十二章先提供其自由主义历史背景。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "将以感觉与反省回应天赋内容和体系知识的主张" }],
        chapterIds: ["b3-11", "b3-12", "b3-13"], graph: { row: 292, lane: 1.5 },
      },
    ],
  },
  {
    id: "liberalism-conscience-commerce-limited-power",
    order: 31,
    label: "自由主义的历史条件",
    title: "从宗派冲突、财产独立和革命经验提出个人领域与有限权力",
    question: "共同权威分裂后，怎样保护个人判断和社会合作，而不把自由误写成无条件私利？",
    transition: "罗素以宗教战争、商业社会、科学精神和英国革命解释哲学自由主义的兴起。图谱把这些条件拆开：良心不可被直接强迫、财产可形成独立空间、政府需要法律与同意，但早期自由主义仍带有阶级、性别、宗教和殖民排除。",
    nodes: [
      {
        id: "religious-conflict-and-belief-coercion-observation",
        kind: "观察",
        observation: { domain: "历史变化", note: "长期宗派冲突显示，国家可以强迫服从或仪式，却不能可靠制造真诚信念；不同统治者还会宣布不同正统。", historyLinks: [{ stageId: "early-modern", responseId: "locke", label: "宗教冲突与有限政府", note: "进入历史概览查看商业社会、英国革命和宽容争论如何形成自由主义条件。" }] },
        title: "宗派战争和正统更替使强迫信仰的可靠性与正当性同时受疑",
        summary: "信念并不随命令直接改变；若每个统治者都强制自己判断的真理，公民的救赎与安全将取决于出生地点。",
        pressure: "强制无效不足以证明所有表达和行动都不受规则；仍需划定政治权力的正当目的。",
        consequence: "观察提出良心、教会和国家是否属于不同权限。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以信念非意志性和政府目的限制宗教强制" }],
        chapterIds: ["b3-12"], graph: { row: 293, lane: 4.1 },
      },
      {
        id: "what-domain-must-remain-outside-civil-coercion",
        kind: "问题",
        title: "哪些个人判断与实践不应由国家强制统一？",
        summary: "若政府成立是为保护世俗利益，它是否有资格裁决救赎真理；自愿教会又能否拥有国家式惩罚权？",
        pressure: "私人领域不能成为伤害、支配或拒绝公共义务的自动豁免；边界需要按权力目的和行为后果说明。",
        consequence: "早期自由主义区分公民利益、宗教社团和内心信念。",
        participants: [], chapterIds: ["b3-12"], graph: { row: 294, lane: 4.1 },
      },
      {
        id: "civil-ends-limit-coercive-authority",
        kind: "答案", answerRole: "区分",
        title: "政治强制以生命、自由、财产和公共和平为限，不直接统治救赎判断",
        summary: "教会被理解为自愿社团，国家则负责可公共判断的世俗利益；强迫表面信仰既不能产生真诚，也超出受托目的。",
        pressure: "洛克实际排除部分群体，宽容论也不等同今日宗教平等；谁被视为威胁公共信任仍受时代偏见影响。",
        consequence: "有限权限成为政治自由主义的一条边，但还需财产、同意与法律结构。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以政治目的和信念性质区分国家与教会权限" }],
        chapterIds: ["b3-12", "b3-15"], graph: { row: 295, lane: 4.1 },
      },
      {
        id: "commerce-property-independence-observation",
        kind: "观察",
        observation: { domain: "社会与制度", note: "商业、契约、土地收益和出版市场扩大了不完全依赖宫廷职位的活动空间，也同时制造财富集中与殖民扩张。" },
        title: "财产和交换扩大部分人的独立空间，也产生不平等、占有与殖民压力",
        summary: "资源控制可使个人抵抗任意命令，却也可使没有财产者受私人权力支配；商业自由与普遍自由不是同义词。",
        pressure: "若财产被当作自然自由的简单尺度，既有分配就会被提前正当化。",
        consequence: "观察提出权利怎样限制国家而不冻结不平等。",
        participants: [], chapterIds: ["b3-12", "b3-14", "b3-15"], graph: { row: 294, lane: 2.2 },
      },
      {
        id: "can-property-secure-independence-without-justifying-domination",
        kind: "问题",
        title: "财产权怎样保护个人独立，又不把无限占有和不平等自动正当化？",
        summary: "劳动、先占、共同资源和货币同意可被组合成财产说明，但每一步都改变他人可用资源与谈判能力。",
        pressure: "抽象自然状态容易遮蔽殖民土地制度、奴役和家庭内部依赖。",
        consequence: "权利语言必须与自然法限制、公共善和政府受托目的共同阅读。",
        participants: [], chapterIds: ["b3-12", "b3-14", "b3-15"], graph: { row: 295, lane: 2.2 },
      },
      {
        id: "rights-protect-agency-but-remain-historically-partial",
        kind: "答案", answerRole: "区分",
        title: "权利为个人建立抗专断边界，但早期适用范围仍狭窄且矛盾",
        summary: "生命、自由、财产与同意提供批评统治的标准；同时，性别、阶级、宗教和殖民实践显示这些普遍词没有自动实现普遍资格。",
        pressure: "后世扩大权利不能被倒写成洛克时代已具完整平等制度，也不能因此抹除概念的批判潜力。",
        consequence: "自由主义成为可扩展也可被既得利益占用的争论语言。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以自然权利限制政治权力，同时留下历史排除与殖民矛盾" }],
        chapterIds: ["b3-12", "b3-15"], graph: { row: 296, lane: 2.2 },
      },
      {
        id: "english-revolution-settlement-observation",
        kind: "观察",
        observation: { domain: "历史变化", note: "内战、复辟、排斥危机与光荣革命反复改变王权、议会、宗教和财产联盟；政府可被更换成为真实政治经验。" },
        title: "英国革命与政体更替显示，统治者和政府形式并非不可撤回的自然所有权",
        summary: "王权、议会和宗派集团争夺最终权威，使神授继承与政治义务都必须给出超出传统的理由。",
        pressure: "革命成功不能自行证明新秩序正当，也不能把胜利一方利益等同全体同意。",
        consequence: "观察提出政府是否是受条件限制的公共委托。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "在反绝对王权语境中发展同意与受托政府论" }],
        chapterIds: ["b3-12", "b3-14", "b3-15"], graph: { row: 296, lane: 3.2 },
      },
      {
        id: "is-government-a-revocable-trust",
        kind: "问题",
        title: "政府权力是统治者的所有物，还是人民为特定目的设立的可撤回委托？",
        summary: "若个人原本自由平等，任何人取得公共强制都需要说明授权、目的和违反条件后的处理。",
        pressure: "同意可能只是默示或历史虚构，多数决也可能压迫少数；委托论必须提供制度而非只提供口号。",
        consequence: "洛克将以自然法、同意、立法边界和反抗权构造有限政府。",
        participants: [], chapterIds: ["b3-12", "b3-14"], graph: { row: 297, lane: 3.2 },
      },
      {
        id: "fallible-individuals-need-bounded-knowledge-and-power",
        kind: "答案", answerRole: "转向",
        title: "会犯错的个人需要共同法律，也需要把知识主张与政治权力限制在可辩护范围",
        summary: "自由主义不是宣布个人永远正确，而是拒绝让某一人的错误判断获得无限强制；同一限制作风也推动洛克检查观念来源和知识程度。",
        pressure: "认识论谦逊不会自动推出某套政治制度，权利也不能仅由观念发生史证明。",
        consequence: "两条洛克支线由此分开：一条追问观念和知识，一条追问自然权利与政府委托。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "分别以知识限度和政府受托论反对无边界权威" }],
        chapterIds: ["b3-12", "b3-13", "b3-14"], graph: { row: 298, lane: 3.2 },
      },
    ],
  },
  {
    id: "locke-experience-ideas-knowledge-identity",
    order: 32,
    label: "经验、观念与知识边界",
    title: "由感觉与反省提供材料，再区分观念操作、知识程度和人格同一",
    question: "拒绝天赋命题后，心灵怎样形成复杂知识，又怎样承认实体与外部对象超出直接把握？",
    transition: "洛克把任务限定为考察观念的来源、知识的确定性与范围，而不先决定心灵的物理本性。感觉与反省提供简单观念，心灵通过组合、比较和抽象形成复杂内容；知识是对观念一致或不一致的把握，大量自然判断只能达到概率。",
    nodes: [
      {
        id: "sensation-and-reflection-supply-idea-materials",
        kind: "答案", answerRole: "反驳",
        title: "观念材料来自感觉与对心灵自身活动的反省，而非预装命题",
        summary: "外感给予颜色、形状、坚实等材料，反省给予思考、怀疑、意愿和比较等活动观念；普遍同意不能证明天赋，因为并不存在无例外的共同意识。",
        pressure: "反对天赋内容不等于心灵没有能力和结构；感觉与反省怎样形成一般概念仍需主动操作。",
        consequence: "问题由材料来源推进到简单观念如何组成复杂观念。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以感觉与反省反对既成天赋命题" }],
        chapterIds: ["b3-13"], graph: { row: 299, lane: 1.5 },
      },
      {
        id: "how-do-simple-ideas-form-complex-general-thought",
        kind: "问题",
        title: "被动获得的简单观念怎样形成关系、实体、一般种类和论证？",
        summary: "经验材料本身不会自动排列为金、原因、人格或正义；心灵必须重复、结合、分离并使用名称。",
        pressure: "若心灵的操作完全不受材料约束，会重新引入未经检验的体系；若完全被动，又无法解释抽象与判断。",
        consequence: "组合、比较与抽象提供有限而主动的认知加工。",
        participants: [], chapterIds: ["b3-13"], graph: { row: 300, lane: 1.5 },
      },
      {
        id: "combination-comparison-abstraction-organize-experience",
        kind: "答案", answerRole: "综合",
        title: "心灵组合、比较并抽象经验材料，形成复杂观念、关系和一般名称",
        summary: "心灵不能发明全新的简单内容，却能把既有观念组织为模式、关系和实体观念；抽象留下多个个体共享的可命名特征。",
        pressure: "一般观念如何表征多样个体、名称怎样遮蔽差异，以及自然种类是否仅由名义本质划分仍有争议。",
        consequence: "主动组织开放两条问题：知识能达到什么程度，以及同一对象怎样跨时间被归类。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以观念操作说明经验主义并非被动感觉堆积" }],
        chapterIds: ["b3-13"], graph: { row: 301, lane: 1.5 },
      },
      {
        id: "color-shape-vary-with-conditions-observation",
        kind: "观察",
        observation: { domain: "个体体验", note: "同一对象的颜色、温度、大小和形状会随光线、距离、身体状态和观察关系变化，但坚实、数量和运动被用于解释这些变化。" },
        title: "对象显现的颜色、温度和大小随观察条件改变",
        summary: "冷水对一只手显热、对另一只手显冷；远处圆形物可能呈椭圆，显现差异要求区分对象结构与感受效果。",
        pressure: "把某些性质列为对象本身、另一些列为引起感受的能力，需要物理解释而非只靠直觉。",
        consequence: "观察提出第一性质与第二性质的区分是否可靠。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以感受变化和微粒机械论区分性质" }],
        chapterIds: ["b3-13"], graph: { row: 300, lane: 0.1 },
      },
      {
        id: "which-qualities-belong-to-objects-themselves",
        kind: "问题",
        title: "哪些性质属于对象本身，哪些只是对象在感知者中造成的效果？",
        summary: "形状、数量、运动和坚实似乎随物体保留，颜色、声音和味道则更明显依赖感官组织。",
        pressure: "第一性质也通过感知进入心灵并随尺度、位置变化；代表相似性不能由跳出经验直接比较来证明。",
        consequence: "洛克以第一性质结构和第二性质因果能力作工作区分。",
        participants: [], chapterIds: ["b3-13"], graph: { row: 301, lane: 0.1 },
      },
      {
        id: "primary-structures-secondary-powers-distinction",
        kind: "答案", answerRole: "区分",
        title: "第一性质被归于物体结构，第二性质是结构在感官中产生观念的能力",
        summary: "微粒的大小、形状、数量与运动被用于解释颜色、味道和声音观念；后者不必像对象中的某个同色复制品。",
        pressure: "区分依赖当时微粒机械论，并没有让心灵直接接触不可感知结构；贝克莱将据此攻击第一性质的独立地位。",
        consequence: "代表观念背后究竟有什么承担性质，成为物质实体问题。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以第一／第二性质区分连接经验与机械自然" }],
        chapterIds: ["b3-13"], graph: { row: 302, lane: 0.1 },
      },
      {
        id: "what-supports-clustered-qualities",
        kind: "问题",
        title: "一组经常共同出现的性质由什么承担，实体观念到底包含什么？",
        summary: "人把颜色、重量、延展和可熔性归于金，却没有独立经验到一个位于这些性质之后的裸支撑。",
        pressure: "若完全取消支撑，性质如何同属一物；若保留不可知基质，它又是否真正增加解释。",
        consequence: "洛克谨慎保留未知的‘某物’，同时承认实体实在本质通常不可知。",
        participants: [], chapterIds: ["b3-13"], graph: { row: 303, lane: 0.6 },
      },
      {
        id: "substance-as-unknown-support-and-real-essence",
        kind: "答案", answerRole: "修复",
        title: "实体被设为性质的未知支撑，自然种类的实在本质通常超出当前知识",
        summary: "名义本质按可观察特征组织名称，实在本质则是产生这些性质的内部构造；人往往只知道前者和部分因果线索。",
        pressure: "‘不知道是什么的某物’可能只是语法需求的实体化；这正给贝克莱取消物质基质留下入口。",
        consequence: "知识必须区分对观念关系的确定把握与对外物结构的概率判断。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以名义／实在本质和未知基质标出自然知识边界" }],
        chapterIds: ["b3-13"], graph: { row: 304, lane: 0.6 },
      },
      {
        id: "how-far-does-knowledge-extend-beyond-ideas",
        kind: "问题",
        title: "知识若是把握观念间的一致或不一致，怎样超出观念抵达现实？",
        summary: "直觉与证明可把握观念关系，但外物存在、自然因果和他人心灵常需要感觉证据与概率推理。",
        pressure: "只在观念内部的确定性可能与世界脱节；把稳定经验都称为知识又会掩盖证据等级。",
        consequence: "洛克区分直觉、证明、感觉知识与实践概率。",
        participants: [], chapterIds: ["b3-13"], graph: { row: 302, lane: 2.3 },
      },
      {
        id: "knowledge-as-agreement-probability-for-practice",
        kind: "答案", answerRole: "区分",
        title: "知识把握观念关系，超出确定范围时则以证言、经验一致和概率指导行动",
        summary: "自我存在可直觉把握，上帝存在被视为可证明，外物存在依当前感觉获得较低层确定；大量自然研究和生活判断属于合理信念。",
        pressure: "感觉知识的资格、证明上帝的有效性和概率标准都可争论；谦逊不等于任意相信。",
        consequence: "认识主体还需说明跨时间责任：今天的我凭什么承担过去行为。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "按证据强度区分知识与概率，限制体系野心" }],
        chapterIds: ["b3-13"], graph: { row: 303, lane: 2.3 },
      },
      {
        id: "what-makes-one-person-same-over-time",
        kind: "问题",
        title: "身体、灵魂物质都可能变化时，什么使一个人跨时间保持同一并承担责任？",
        summary: "同一个人、同一个生物体、同一团物质和同一思维实体是不同判断；王子与鞋匠思想实验把人格与意识归属放到中心。",
        pressure: "若同一只由实际记忆决定，遗忘会切断责任，错误记忆又会循环地依赖既有身份判断。",
        consequence: "人格被定义为能把行动归于自身的反省主体和法责概念。",
        participants: [], chapterIds: ["b3-13"], graph: { row: 304, lane: 2.3 },
      },
      {
        id: "personhood-through-conscious-appropriation",
        kind: "答案", answerRole: "转向",
        title: "人格同一依意识把过去行动归为自己，并承担奖惩责任",
        summary: "‘人格’是能反省、计划并受法律评价的行动者概念；其持续不直接由同一灵魂材料或同一身体粒子决定。",
        pressure: "意识、记忆与归责之间如何避免循环仍有解释竞争，也不能把法律责任完全交给主观自认。",
        consequence: "开放人格边界问题，同时显示经验主义可重写而非简单取消自我。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以意识连续和法责用途重构人格同一" }],
        chapterIds: ["b3-13"], graph: { row: 305, lane: 2.3 },
      },
      {
        id: "how-can-accountability-exceed-explicit-memory",
        kind: "问题",
        title: "遗忘、睡眠和错误记忆存在时，责任怎样超出当前明确回忆？",
        summary: "意识标准揭示人格与实体不同，却不能用一次回忆测试解决所有持续、证据和司法问题。",
        pressure: "扩大意识会把理论改写成因果连续，缩小意识又会让人格断裂；两者都需要额外原则。",
        consequence: "该问题保持开放，并成为后世人格同一争论的接口。",
        participants: [], chapterIds: ["b3-13"], graph: { row: 306, lane: 2.3 },
      },
      {
        id: "if-only-ideas-are-immediate-what-does-matter-explain",
        kind: "问题",
        title: "若心灵直接把握的只有观念，不可经验的物质基质究竟增加了什么解释？",
        summary: "洛克用基质承担性质、用物体结构造成感觉，但我们无法脱离观念比较表象与其原物。",
        pressure: "取消物质不能取消经验世界、因果秩序和其他心灵；保留物质也不能只用一个空词。",
        consequence: "第三卷第十六章贝克莱将以经验主义自身的来源要求推进非物质主义。",
        participants: [{ name: "乔治·贝克莱", philosopherId: "berkeley", role: "将质疑不可被感知的物质支撑及表象鸿沟" }],
        chapterIds: ["b3-13", "b3-16"], graph: { row: 307, lane: 0.8 },
      },
    ],
  },
  {
    id: "locke-rights-property-trust-influence",
    order: 33,
    label: "权利、财产与政府委托",
    title: "以自然权利和同意构造有限政府，再检验财产、宽容与影响的边界",
    question: "个人原本自由平等时，公共强制怎样取得资格，又在何种条件下失去资格？",
    transition: "洛克的自然状态不是霍布斯式持续战争：自然法已经要求尊重生命、自由与财产，但个人兼任自己案件的法官，使权利缺少稳定执行。政治社会因此是受托补救，不是权利的创造者；当立法背离公共善，委托可被撤回。",
    nodes: [
      {
        id: "equal-persons-judge-own-cases-observation",
        kind: "观察",
        observation: { domain: "社会与制度", note: "没有共同裁判时，即使人承认某些相互义务，也会因偏私、证据争议和执行能力不等而无法稳定解决冲突。" },
        title: "平等者在自己的案件中兼任法官，权利规则因偏私和执行不稳而失效",
        summary: "自然状态可以有合作和自然法，却缺少已知共同法律、无偏裁判和可靠执行三项制度保障。",
        pressure: "把制度缺口称为不便不能淡化暴力风险，也不能据此让政府取得超出补救目的的无限权力。",
        consequence: "观察提出自然状态与战争状态应如何区分。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以自然状态的不便而非普遍战争说明政府需要" }],
        chapterIds: ["b3-14"], graph: { row: 308, lane: 3.1 },
      },
      {
        id: "is-state-of-nature-already-war",
        kind: "问题",
        title: "没有共同政府是否就等于人人相互战争？",
        summary: "若自然法在政府之前有效，人可以处于和平自然状态；战争状态则来自无权的强制、伤害和无法上诉。",
        pressure: "自然法如何被认识、执行权为何属于每个人，以及国际关系中的自然状态仍有困难。",
        consequence: "洛克以先政治权利区分自然状态与战争状态。",
        participants: [], chapterIds: ["b3-14"], graph: { row: 309, lane: 3.1 },
      },
      {
        id: "natural-law-rights-precede-government",
        kind: "答案", answerRole: "反驳",
        title: "自然状态受自然法约束，生命、自由和财产权不由政府创造",
        summary: "人因同为自由平等的受造者而不得任意伤害彼此；政府的任务是更稳定地保护这些既有权利。",
        pressure: "神学基础、自然法认识和权利清单并非无争议；抽象平等也与洛克时代实际排除冲突。",
        consequence: "权利先于国家使财产取得与公共裁判成为两条核心问题。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以自然法和先政治权利限制政府目的" }],
        chapterIds: ["b3-14"], graph: { row: 310, lane: 3.1 },
      },
      {
        id: "how-can-common-resources-become-private-property",
        kind: "问题",
        title: "自然资源最初共有时，个人劳动怎样产生排他的财产权？",
        summary: "劳动属于行动者，把劳动与资源结合似乎形成特殊主张；但占有会减少他人可用资源。",
        pressure: "不浪费和给他人留下足够同样好的资源等限制，在货币、土地集中和殖民条件下会被改变。",
        consequence: "劳动、改良、但书和货币同意构成有条件的财产说明。",
        participants: [], chapterIds: ["b3-14"], graph: { row: 311, lane: 2.0 },
      },
      {
        id: "labor-appropriation-proviso-and-money",
        kind: "答案", answerRole: "综合",
        title: "劳动可建立初始占有，但受不浪费和他人机会限制；货币又扩大积累",
        summary: "个人通过劳动改良资源获得主张，耐久货币的共同接受则允许财富超过即时使用；这一步使不平等获得新的制度基础。",
        pressure: "默示货币同意、殖民地‘未改良土地’叙事和奴隶制关联使财产论不能被当作中性普遍规则。",
        consequence: "财产权既限制政府，又要求追问何时私人占有转成支配。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以劳动论证占有，同时留下但书、货币和殖民争议" }],
        chapterIds: ["b3-14", "b3-15"], graph: { row: 312, lane: 2.0 },
      },
      {
        id: "when-do-property-rights-become-private-domination",
        kind: "问题",
        title: "保护财产的制度在何时反而使无财产者受私人支配？",
        summary: "法律安全可保护劳动成果，却也可固定极端资源差距，使形式同意失去实质选择。",
        pressure: "这一问题超出洛克明示体系，是后世对自由主义内部权利—不平等张力的重构。",
        consequence: "开放问题随洛克影响进入共和主义、社会主义和平等自由主义批评。",
        participants: [], chapterIds: ["b3-15"], graph: { row: 313, lane: 2.0 },
      },
      {
        id: "how-do-consent-and-majority-create-government",
        kind: "问题",
        title: "自由个人怎样通过同意形成能约束少数的共同体与多数决定？",
        summary: "一致同意建立政治共同体后，若每项决定仍需一致，任何集体都无法行动；多数规则成为持续运作条件。",
        pressure: "出生、居住和使用道路是否构成默示同意十分可疑；多数权也需受权利和公共善限制。",
        consequence: "政府被构造为有目的、有期限且可问责的信托。",
        participants: [], chapterIds: ["b3-14"], graph: { row: 311, lane: 3.8 },
      },
      {
        id: "fiduciary-government-and-separated-powers",
        kind: "答案", answerRole: "综合",
        title: "共同体以多数行动，政府则作为保护权利与公共善的有限信托",
        summary: "立法权居首却不任意，执行与对外权力承担不同功能；征税、法律和惩罚须在授权目的内。",
        pressure: "权力分工不是今日三权分立的完整模板，人民、共同体和政府之间的授权层次也有解释争议。",
        consequence: "受托权力一旦背离目的，就出现政府解体和反抗资格问题。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以同意、多数与信托构造有限公共权力" }],
        chapterIds: ["b3-14"], graph: { row: 312, lane: 3.8 },
      },
      {
        id: "when-may-people-resist-or-replace-government",
        kind: "问题",
        title: "政府何时因破坏委托而失去服从资格？",
        summary: "立法夺取财产、任意统治、阻止代表机构或把共同体交给外力，都可能显示政府向人民宣战。",
        pressure: "反抗权必须区别长期滥权与普通政策失败，也要处理谁判断委托已破裂及内战风险。",
        consequence: "人民保留在系统性背信时重建政府的最终权力。",
        participants: [], chapterIds: ["b3-14"], graph: { row: 313, lane: 3.8 },
      },
      {
        id: "right-of-resistance-follows-broken-trust",
        kind: "答案", answerRole: "修复",
        title: "反抗不是任意拒绝法律，而是政府持续背弃保护目的后的委托撤回",
        summary: "统治者以无权强制制造战争状态时，人民可诉诸最后手段；责任首先归于破坏既有制度信任的一方。",
        pressure: "实际革命仍会遭遇证据、协调和后果问题；洛克方案不能保证每次自称反抗都正当。",
        consequence: "有限政府、权利和反抗语言经十八世纪革命与宪政争论扩散。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "从政府背信而非日常不满论证反抗权" }],
        chapterIds: ["b3-14", "b3-15"], graph: { row: 314, lane: 3.8 },
      },
      {
        id: "religious-pluralism-observation",
        kind: "观察",
        observation: { domain: "社会与制度", note: "同一政治区域内存在多个自称真教会的群体，统治者的宗派判断随国界和政权改变；强制只能改变外在行为。" },
        title: "多个教会都宣称掌握真理，而政治强制只能直接改变行为",
        summary: "若统治者可能错误，迫害会把偶然政治位置变成救赎条件；教会若是自愿社团，也没有国家刑罚权。",
        pressure: "宽容的适用对象和公共安全例外会被滥用，洛克本人也保留今天不能接受的排除。",
        consequence: "观察提出宗教信念是否属于政治受托权范围。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以信念不可强迫和裁判可错支持宽容" }],
        chapterIds: ["b3-14", "b3-15"], graph: { row: 311, lane: 4.6 },
      },
      {
        id: "can-force-produce-religious-belief",
        kind: "问题",
        title: "国家强制能否产生得救所需的真诚信念？",
        summary: "惩罚可迫使表面服从，却不能直接使证据变好或意志真诚接受教义。",
        pressure: "强制可能间接改变接触信息的机会，因此无效论不是宽容的全部基础；授权范围和统治者可错同样重要。",
        consequence: "国家被限制在公民利益，教会被限制为无强制权的自愿社团。",
        participants: [], chapterIds: ["b3-14", "b3-15"], graph: { row: 312, lane: 4.6 },
      },
      {
        id: "toleration-follows-limited-civil-ends",
        kind: "答案", answerRole: "区分",
        title: "宽容来自信念性质、统治者可错和政府授权目的的共同限制",
        summary: "国家保护世俗利益而不承包灵魂得救，教会通过劝说而非强制维持共同信仰。",
        pressure: "历史上的排除显示原则没有被一致执行；后世必须把普遍权利语言反过来检验其原始边界。",
        consequence: "洛克影响既提供扩展自由的词汇，也保留需要批判的财产与资格结构。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "以有限政府和自愿教会组织宽容论" }],
        chapterIds: ["b3-14", "b3-15"], graph: { row: 313, lane: 4.6 },
      },
      {
        id: "how-universal-are-lockean-rights-in-practice",
        kind: "问题",
        title: "生命、自由、财产与同意的普遍语言，怎样面对其历史上的排除和帝国用途？",
        summary: "洛克词汇能够批评神授专断并影响革命宪政，也曾与殖民占有、奴役投资、父权和有限宽容并存。",
        pressure: "只把洛克封为现代自由先知会抹去矛盾，只把概念归为利益伪装又无法解释其后来的自我扩展能力。",
        consequence: "该开放问题保留自由主义影响的双重遗产，不被并入贝克莱的认识论主线。",
        participants: [{ name: "约翰·洛克", philosopherId: "locke", role: "其权利语言的批判力量与历史排除同时进入后世" }],
        chapterIds: ["b3-15"], graph: { row: 315, lane: 3.8 },
      },
    ],
  },
  {
    id: "berkeley-ideas-spirits-immaterialism",
    order: 34,
    label: "观念、精神与非物质主义",
    title: "用经验来源要求取消物质基质，同时保留普通对象、精神与规律秩序",
    question: "若直接经验只有观念及感知活动，物理世界怎样真实存在并保持公共稳定？",
    transition: "贝克莱不是否认石头、桌子和疼痛，而是否认感性对象背后还需一个不可感知的物质支撑。普通对象是稳定共现的观念组合；观念被动，精神主动，感觉的非自愿秩序则由更强精神和自然规则说明。",
    nodes: [
      {
        id: "material-substratum-adds-no-experiential-content",
        kind: "答案", answerRole: "反驳",
        title: "不可被感知、无法形成观念的物质基质没有增加可理解内容",
        summary: "我们经验颜色、坚实、运动和形状，却没有经验一个脱去全部性质的支撑；观念也只能与观念比较相似。",
        pressure: "取消物质基质不能取消对象、因果和共同世界，否则非物质主义只会变成私人幻觉论。",
        consequence: "贝克莱继续检验洛克认为较独立的第一性质。",
        participants: [{ name: "乔治·贝克莱", philosopherId: "berkeley", role: "以经验来源和相似原则攻击物质基质" }],
        chapterIds: ["b3-16"], graph: { row: 316, lane: 0.8 },
      },
      {
        id: "are-primary-qualities-independent-of-perception",
        kind: "问题",
        title: "形状、大小和运动是否真的比颜色、声音更独立于感知？",
        summary: "同一对象从不同距离和角度呈现不同大小形状，快慢也依比较框架；第一性质同样只能在观念中出现。",
        pressure: "知觉相对性不必自动推出对象没有独立结构；论证还依赖抽象观念和表象理论的其他批评。",
        consequence: "贝克莱把第一／第二性质一同纳入感知依赖。",
        participants: [], chapterIds: ["b3-16"], graph: { row: 317, lane: 0.8 },
      },
      {
        id: "primary-qualities-also-perception-relative",
        kind: "答案", answerRole: "反驳",
        title: "第一性质也以具体感知方式出现，不能抽成完全无感性的物质副本",
        summary: "任何被设想的形状、大小和运动都是某种具体观念；把它们从所有感知条件中抽离，不能产生可表象对象。",
        pressure: "反抽象论不等于语言只能指一个私人图像；一般词仍可通过对多个具体观念的使用发挥作用。",
        consequence: "若所有感性性质都是观念，普通对象的存在方式必须重新表述。",
        participants: [{ name: "乔治·贝克莱", philosopherId: "berkeley", role: "把洛克性质区分推向非物质主义" }],
        chapterIds: ["b3-16"], graph: { row: 318, lane: 0.8 },
      },
      {
        id: "does-immaterialism-deny-stones-and-trees",
        kind: "问题",
        title: "否认物质实体是否等于否认石头、树木和身体真实存在？",
        summary: "日常对象以颜色、触感、形状和可预测作用被认识；取消额外基质并不必取消这些经验组合。",
        pressure: "若对象只等于我当前的观念，无人看见时的持续和多人共享仍无法解释。",
        consequence: "感性对象被界定为按规律组合、可被感知的观念，而非私人幻想。",
        participants: [], chapterIds: ["b3-16"], graph: { row: 319, lane: 1.5 },
      },
      {
        id: "ordinary-objects-as-stable-idea-combinations",
        kind: "答案", answerRole: "修复",
        title: "普通物理对象是真实而稳定的观念组合，其存在方式是被感知",
        summary: "桌子不是桌子观念背后的未知复制品，而是视觉、触觉和行动预期按公共规律结合的对象；梦与想象因较弱、零散和可控而不同。",
        pressure: "esse est percipi 只说明感性对象，不涵盖感知者；对象无人感知时如何持续还需更广精神秩序。",
        consequence: "问题从物质基质转向观念的原因和持续条件。",
        participants: [{ name: "乔治·贝克莱", philosopherId: "berkeley", role: "以稳定观念组合保存常识物理世界" }],
        chapterIds: ["b3-16"], graph: { row: 320, lane: 1.5 },
      },
      {
        id: "sensory-ideas-arrive-involuntarily-observation",
        kind: "观察",
        observation: { domain: "个体体验", note: "人能随意改变部分想象，却不能同样控制强光、疼痛、阻力和连续感觉；感觉观念表现出独立于有限意志的秩序。" },
        title: "感觉观念不由有限意志选择，并以稳定次序和强度到来",
        summary: "闭眼可暂时阻断部分视觉，却不能让世界整体按想象改写；感知具有被给予性和可预测结构。",
        pressure: "非自愿只说明原因不在当前意志，尚不能单凭这一点证明无限精神。",
        consequence: "观察提出被动观念由何种主动者造成。",
        participants: [{ name: "乔治·贝克莱", philosopherId: "berkeley", role: "以感觉非自愿性区分真实经验与想象" }],
        chapterIds: ["b3-16"], graph: { row: 318, lane: 3.0 },
      },
      {
        id: "what-causes-involuntary-sensory-ideas",
        kind: "问题",
        title: "被动观念不能自我产生时，谁造成稳定而非自愿的感觉序列？",
        summary: "观念没有可经验到的主动能力，有限心灵又不能意愿出大部分感觉内容；原因必须属于某种主动精神。",
        pressure: "由秩序复杂性到无限善意精神的推理需要神学前提，有限他心和自然规律也必须区分。",
        consequence: "贝克莱保留有限精神，并以神作为自然观念秩序的首要原因。",
        participants: [], chapterIds: ["b3-16"], graph: { row: 319, lane: 3.0 },
      },
      {
        id: "ideas-passive-spirits-active-god-orders-sense",
        kind: "答案", answerRole: "区分",
        title: "观念是被动内容，精神是感知与意愿的主动者；神组织感觉秩序",
        summary: "有限精神通过自身意愿造成部分想象和身体行动观念，远超有限控制的自然序列则被归于无限精神。",
        pressure: "精神本身不是观念，因而不能用同一观念来源标准直接表象；上帝解释也可能被批评为替代而非分析规律。",
        consequence: "神的持续知觉和规则性使无人注视的对象不依赖某个私人观看者。",
        participants: [{ name: "乔治·贝克莱", philosopherId: "berkeley", role: "以主动精神与神圣秩序补足非物质主义因果" }],
        chapterIds: ["b3-16"], graph: { row: 320, lane: 3.0 },
      },
      {
        id: "do-objects-exist-when-no-human-perceives",
        kind: "问题",
        title: "没有任何人正在观看时，对象是否仍持续存在？",
        summary: "对象若依赖某个有限心灵的当前知觉，就会随眨眼消失；常识和科学却要求稳定可重返的世界。",
        pressure: "诉诸神圣知觉保存对象，会使经验主义依赖一个不能感性观察的保证者。",
        consequence: "持续被理解为对象始终处于无限精神的秩序并可按规则给予有限者。",
        participants: [], chapterIds: ["b3-16"], graph: { row: 321, lane: 2.2 },
      },
      {
        id: "divine-perception-and-natural-signs-preserve-order",
        kind: "答案", answerRole: "修复",
        title: "神持续把握并按自然规则给予观念，使对象不依赖任何单个有限观看者",
        summary: "自然规律像一种稳定符号语言，允许人预测观念序列并进行科学，而不需假设观念背后的无感物质。",
        pressure: "规律为何需要人格神、神的观念与人的观念是否同义，以及异常和痛苦怎样符合善意秩序仍有压力。",
        consequence: "非物质主义宣称缩短心灵与世界距离，但还需面对怀疑论检验。",
        participants: [{ name: "乔治·贝克莱", philosopherId: "berkeley", role: "以神圣知觉和自然符号秩序保存对象持续与科学" }],
        chapterIds: ["b3-16"], graph: { row: 322, lane: 2.2 },
      },
      {
        id: "does-immaterialism-defeat-or-deepen-skepticism",
        kind: "问题",
        title: "取消表象背后的物质，是消除怀疑鸿沟，还是把保证转移给神与精神？",
        summary: "若对象就是被感知的观念，人不再需要证明观念像一个不可接近的物质原物；但精神和神仍不是普通感性观念。",
        pressure: "直接接触经验对象不等于解释其全部原因，也不能用常识真实性证明整个本体论。",
        consequence: "贝克莱以直接观念对象回应物质怀疑，却把精神知识留给内在活动和类比。",
        participants: [], chapterIds: ["b3-16"], graph: { row: 323, lane: 1.5 },
      },
      {
        id: "direct-idea-world-with-notions-of-spirit",
        kind: "答案", answerRole: "转向",
        title: "人直接接触感性世界的观念，并以自身主动活动形成关于精神的概念",
        summary: "非物质主义自称捍卫常识对象而非封闭主体；精神不是被动观念，却通过意愿、感知和行动被把握。",
        pressure: "若所有有意义内容都须有印象来源，精神、神、因果能力和持续自我仍会受到更彻底追问。",
        consequence: "终端开放休谟：经验来源审查是否应同样作用于贝克莱保留的精神和神。",
        participants: [{ name: "乔治·贝克莱", philosopherId: "berkeley", role: "以观念直接性与精神概念回应怀疑主义" }],
        chapterIds: ["b3-16"], graph: { row: 324, lane: 1.5 },
      },
      {
        id: "can-spirit-cause-and-self-survive-strict-experience-test",
        kind: "问题",
        title: "物质基质被经验来源审查取消后，精神、因果能力和持续自我能否免于同样审查？",
        summary: "贝克莱保留主动精神与神来稳定观念，但这些存在者并不是一组可被感知的被动内容。",
        pressure: "若诉诸内在活动即可证明实体自我，需要说明这种把握比物质基质更充分；若不能，经验主义将进一步走向知觉束和因果习惯。",
        consequence: "第三卷第十七章休谟将把来源检验推进到因果、自我、归纳和宗教论证。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "将在下一章把经验主义的审查标准作用于精神、自我和必然联系" }],
        chapterIds: ["b3-16", "b3-17"], graph: { row: 325, lane: 1.5 },
      },
    ],
  },
];

export const enlightenmentProblemEdges: ProblemEdge[] = [
  { id: "e001", from: "can-two-created-substances-fit-one-intelligible-nature", to: "one-substance-god-or-nature", relation: "回应问题", label: "以唯一实体取消两个有限实体的独立地位", connection: "原书线索" },
  { id: "e002", from: "one-substance-god-or-nature", to: "how-can-finite-things-differ-within-one-substance", relation: "产生问题", label: "实体唯一性要求保存有限差异", connection: "原书线索" },
  { id: "e003", from: "how-can-finite-things-differ-within-one-substance", to: "attributes-and-modes-articulate-one-nature", relation: "回应问题", label: "以属性和样态区分无限本质与有限方式", connection: "原书线索", sourceRefs: [{ sourceLabel: "SEP · Baruch Spinoza", locator: "条目关于实体、属性与样态的说明" }] },
  { id: "e004", from: "attributes-and-modes-articulate-one-nature", to: "if-mind-and-body-do-not-interact-how-correspond", relation: "产生问题", label: "同一实体的两种属性仍需说明对应", connection: "原书线索" },
  { id: "e005", from: "if-mind-and-body-do-not-interact-how-correspond", to: "mind-body-parallel-expression", relation: "回应问题", label: "把心身写成同一秩序的两种表达", connection: "原书线索", sourceRefs: [{ sourceLabel: "SEP · Baruch Spinoza", locator: "条目关于思维、广延及心身平行的说明" }] },
  { id: "e006", from: "mind-body-parallel-expression", to: "what-can-freedom-mean-in-necessary-nature", relation: "产生问题", label: "心身自然化重新提出能动自由", connection: "原书线索" },
  { id: "e007", from: "affects-shift-capacity-observation", to: "what-can-freedom-mean-in-necessary-nature", relation: "提出问题", label: "情感能力差异使自由呈现为程度问题", connection: "原书线索" },
  { id: "e008", from: "what-can-freedom-mean-in-necessary-nature", to: "conatus-and-adequate-understanding-increase-agency", relation: "回应问题", label: "以努力和充分理解重写自由", connection: "原书线索" },
  { id: "e009", from: "conatus-and-adequate-understanding-increase-agency", to: "can-understanding-transform-passions-without-suppressing-them", relation: "产生问题", label: "能动性标准需要情感转化机制", connection: "原书线索" },
  { id: "e010", from: "can-understanding-transform-passions-without-suppressing-them", to: "active-affects-through-common-causes", relation: "回应问题", label: "以共同原因和主动情感重组激情", connection: "原书线索" },
  { id: "e011", from: "active-affects-through-common-causes", to: "can-free-thought-strengthen-common-power", relation: "产生问题", label: "共同能力把个人伦理推进到政治自由", connection: "历史回应" },
  { id: "e012", from: "confessional-fear-censorship-observation", to: "can-free-thought-strengthen-common-power", relation: "提出问题", label: "审查与宗派暴力暴露强迫信念的代价", connection: "历史回应" },
  { id: "e013", from: "can-free-thought-strengthen-common-power", to: "freedom-of-philosophizing-supports-peace", relation: "回应问题", label: "以有限行动管制和思想自由增强和平", connection: "原书线索" },
  { id: "e014", from: "freedom-of-philosophizing-supports-peace", to: "can-individuals-and-contingency-survive-complete-intelligibility", relation: "产生问题", label: "共同力量仍需保存个体与偶然性", connection: "后世重构" },
  { id: "e015", from: "attributes-and-modes-articulate-one-nature", to: "can-individuals-and-contingency-survive-complete-intelligibility", relation: "产生问题", label: "样态个体性开放多元实体回应", connection: "后世重构" },
  { id: "e016", from: "can-individuals-and-contingency-survive-complete-intelligibility", to: "monads-as-active-perspectival-unities", relation: "回应问题", label: "以多重活动统一体保存个体", connection: "原书线索" },
  { id: "e017", from: "monads-as-active-perspectival-unities", to: "how-can-windowless-monads-share-one-world", relation: "产生问题", label: "单子独立引出共同世界协调", connection: "原书线索" },
  { id: "e018", from: "how-can-windowless-monads-share-one-world", to: "preestablished-harmony-coordinates-perspectives", relation: "回应问题", label: "以预定和谐协调内在序列", connection: "原书线索" },
  { id: "e019", from: "preestablished-harmony-coordinates-perspectives", to: "does-complete-reason-make-every-truth-necessary", relation: "产生问题", label: "完整发展法则威胁偶然性", connection: "原书线索" },
  { id: "e020", from: "does-complete-reason-make-every-truth-necessary", to: "truths-of-reason-fact-and-possible-worlds", relation: "回应问题", label: "区分矛盾必然与事实真理", connection: "原书线索" },
  { id: "e021", from: "truths-of-reason-fact-and-possible-worlds", to: "why-is-this-world-actual-among-possibilities", relation: "产生问题", label: "可能世界区分要求现实选择理由", connection: "原书线索" },
  { id: "e022", from: "why-is-this-world-actual-among-possibilities", to: "best-compossible-world-as-choice-reason", relation: "回应问题", label: "以最佳可相容整体解释选择", connection: "原书线索" },
  { id: "e023", from: "best-compossible-world-as-choice-reason", to: "can-best-world-justify-evil-and-suffering", relation: "产生问题", label: "整体最优必须容纳具体恶", connection: "原书线索" },
  { id: "e024", from: "can-best-world-justify-evil-and-suffering", to: "evil-permitted-not-good-in-itself", relation: "回应问题", label: "把恶区分为被允许的有限缺陷", connection: "原书线索" },
  { id: "e025", from: "evil-permitted-not-good-in-itself", to: "are-ideas-innate-dispositions-or-experiential-materials", relation: "产生问题", label: "体系理由的不可验证性强化知识限度问题", connection: "本站推演" },
  { id: "e026", from: "unnoticed-perceptions-observation", to: "how-do-perception-memory-and-reason-emerge", relation: "提出问题", label: "微小知觉要求解释意识层级", connection: "原书线索" },
  { id: "e027", from: "how-do-perception-memory-and-reason-emerge", to: "apperception-builds-conscious-continuity", relation: "回应问题", label: "以统觉、记忆和理性区分知觉层级", connection: "原书线索" },
  { id: "e028", from: "apperception-builds-conscious-continuity", to: "are-ideas-innate-dispositions-or-experiential-materials", relation: "产生问题", label: "倾向论直接开放经验来源争论", connection: "原书线索" },
  { id: "e029", from: "religious-conflict-and-belief-coercion-observation", to: "what-domain-must-remain-outside-civil-coercion", relation: "提出问题", label: "强迫信仰的失败要求划定权限", connection: "历史回应" },
  { id: "e030", from: "what-domain-must-remain-outside-civil-coercion", to: "civil-ends-limit-coercive-authority", relation: "回应问题", label: "以世俗目的限制国家和教会强制", connection: "历史回应" },
  { id: "e031", from: "civil-ends-limit-coercive-authority", to: "is-government-a-revocable-trust", relation: "产生问题", label: "有限目的要求受托政府结构", connection: "本站推演" },
  { id: "e032", from: "commerce-property-independence-observation", to: "can-property-secure-independence-without-justifying-domination", relation: "提出问题", label: "财产独立与不平等形成双重压力", connection: "历史回应" },
  { id: "e033", from: "can-property-secure-independence-without-justifying-domination", to: "rights-protect-agency-but-remain-historically-partial", relation: "回应问题", label: "保留权利边界并标出历史排除", connection: "后世重构" },
  { id: "e034", from: "rights-protect-agency-but-remain-historically-partial", to: "is-government-a-revocable-trust", relation: "产生问题", label: "权利保护需要可问责公共权力", connection: "原书线索" },
  { id: "e035", from: "english-revolution-settlement-observation", to: "is-government-a-revocable-trust", relation: "提出问题", label: "政体更替使委托与撤回成为现实问题", connection: "历史回应" },
  { id: "e036", from: "is-government-a-revocable-trust", to: "fallible-individuals-need-bounded-knowledge-and-power", relation: "回应问题", label: "以有限知识和有限权力连接洛克两条支线", connection: "本站推演" },
  { id: "e037", from: "fallible-individuals-need-bounded-knowledge-and-power", to: "are-ideas-innate-dispositions-or-experiential-materials", relation: "产生问题", label: "知识限制要求追踪观念来源", connection: "本站推演" },
  { id: "e038", from: "are-ideas-innate-dispositions-or-experiential-materials", to: "sensation-and-reflection-supply-idea-materials", relation: "回应问题", label: "以感觉与反省解释观念材料", connection: "原书线索" },
  { id: "e039", from: "sensation-and-reflection-supply-idea-materials", to: "how-do-simple-ideas-form-complex-general-thought", relation: "产生问题", label: "经验材料仍需主动组织", connection: "原书线索" },
  { id: "e040", from: "how-do-simple-ideas-form-complex-general-thought", to: "combination-comparison-abstraction-organize-experience", relation: "回应问题", label: "以组合、比较和抽象形成复杂观念", connection: "原书线索" },
  { id: "e041", from: "combination-comparison-abstraction-organize-experience", to: "how-far-does-knowledge-extend-beyond-ideas", relation: "产生问题", label: "观念操作不能自行保证现实符合", connection: "原书线索" },
  { id: "e042", from: "how-far-does-knowledge-extend-beyond-ideas", to: "knowledge-as-agreement-probability-for-practice", relation: "回应问题", label: "按直觉、证明、感觉和概率区分证据", connection: "原书线索" },
  { id: "e043", from: "knowledge-as-agreement-probability-for-practice", to: "what-makes-one-person-same-over-time", relation: "产生问题", label: "认识主体的跨时责任仍需同一标准", connection: "本站推演" },
  { id: "e044", from: "combination-comparison-abstraction-organize-experience", to: "what-makes-one-person-same-over-time", relation: "产生问题", label: "不同种类概念要求不同持续条件", connection: "原书线索" },
  { id: "e045", from: "what-makes-one-person-same-over-time", to: "personhood-through-conscious-appropriation", relation: "回应问题", label: "以意识归属和法责重构人格", connection: "原书线索" },
  { id: "e046", from: "personhood-through-conscious-appropriation", to: "how-can-accountability-exceed-explicit-memory", relation: "产生问题", label: "意识标准遭遇遗忘和错误记忆", connection: "后世重构" },
  { id: "e047", from: "color-shape-vary-with-conditions-observation", to: "which-qualities-belong-to-objects-themselves", relation: "提出问题", label: "感知条件变化要求区分结构与效果", connection: "原书线索" },
  { id: "e048", from: "which-qualities-belong-to-objects-themselves", to: "primary-structures-secondary-powers-distinction", relation: "回应问题", label: "以第一性质结构解释第二性质能力", connection: "原书线索" },
  { id: "e049", from: "primary-structures-secondary-powers-distinction", to: "what-supports-clustered-qualities", relation: "产生问题", label: "性质区分仍预设承担者", connection: "原书线索" },
  { id: "e050", from: "what-supports-clustered-qualities", to: "substance-as-unknown-support-and-real-essence", relation: "回应问题", label: "谨慎保留未知基质与实在本质", connection: "原书线索" },
  { id: "e051", from: "substance-as-unknown-support-and-real-essence", to: "how-far-does-knowledge-extend-beyond-ideas", relation: "产生问题", label: "未知实在本质限制自然知识", connection: "原书线索" },
  { id: "e052", from: "substance-as-unknown-support-and-real-essence", to: "if-only-ideas-are-immediate-what-does-matter-explain", relation: "产生问题", label: "未知支撑开放贝克莱的经验主义批评", connection: "后世重构" },
  { id: "e053", from: "primary-structures-secondary-powers-distinction", to: "if-only-ideas-are-immediate-what-does-matter-explain", relation: "产生问题", label: "表象区分加深观念与原物鸿沟", connection: "后世重构" },
  { id: "e054", from: "equal-persons-judge-own-cases-observation", to: "is-state-of-nature-already-war", relation: "提出问题", label: "无共同裁判不等于没有先政治义务", connection: "原书线索" },
  { id: "e055", from: "is-state-of-nature-already-war", to: "natural-law-rights-precede-government", relation: "回应问题", label: "以自然法区分自然状态与战争状态", connection: "原书线索" },
  { id: "e056", from: "natural-law-rights-precede-government", to: "how-can-common-resources-become-private-property", relation: "产生问题", label: "先政治权利要求说明财产取得", connection: "原书线索" },
  { id: "e057", from: "how-can-common-resources-become-private-property", to: "labor-appropriation-proviso-and-money", relation: "回应问题", label: "以劳动、但书和货币组织占有", connection: "原书线索" },
  { id: "e058", from: "labor-appropriation-proviso-and-money", to: "when-do-property-rights-become-private-domination", relation: "产生问题", label: "积累与殖民语境开放支配问题", connection: "后世重构" },
  { id: "e059", from: "natural-law-rights-precede-government", to: "how-do-consent-and-majority-create-government", relation: "产生问题", label: "既有权利需要公共执行而非让渡殆尽", connection: "原书线索" },
  { id: "e060", from: "how-do-consent-and-majority-create-government", to: "fiduciary-government-and-separated-powers", relation: "回应问题", label: "以多数、信托和权力分工构造政府", connection: "原书线索" },
  { id: "e061", from: "fiduciary-government-and-separated-powers", to: "when-may-people-resist-or-replace-government", relation: "产生问题", label: "受托权力要求背信后的处理", connection: "原书线索" },
  { id: "e062", from: "when-may-people-resist-or-replace-government", to: "right-of-resistance-follows-broken-trust", relation: "回应问题", label: "以系统性背信而非日常不满限定反抗", connection: "原书线索" },
  { id: "e063", from: "right-of-resistance-follows-broken-trust", to: "how-universal-are-lockean-rights-in-practice", relation: "产生问题", label: "革命权语言要求检验实际资格范围", connection: "后世重构" },
  { id: "e064", from: "religious-pluralism-observation", to: "can-force-produce-religious-belief", relation: "提出问题", label: "多宗派与信念非意志性限制强制", connection: "历史回应" },
  { id: "e065", from: "can-force-produce-religious-belief", to: "toleration-follows-limited-civil-ends", relation: "回应问题", label: "以有限政治目的和自愿教会支持宽容", connection: "原书线索" },
  { id: "e066", from: "toleration-follows-limited-civil-ends", to: "how-universal-are-lockean-rights-in-practice", relation: "产生问题", label: "历史排除要求反检普遍权利语言", connection: "后世重构" },
  { id: "e067", from: "if-only-ideas-are-immediate-what-does-matter-explain", to: "material-substratum-adds-no-experiential-content", relation: "回应问题", label: "以来源要求取消不可感知物质基质", connection: "原书线索" },
  { id: "e068", from: "material-substratum-adds-no-experiential-content", to: "are-primary-qualities-independent-of-perception", relation: "产生问题", label: "取消基质后继续检验第一性质", connection: "原书线索" },
  { id: "e069", from: "are-primary-qualities-independent-of-perception", to: "primary-qualities-also-perception-relative", relation: "回应问题", label: "以尺度、位置和反抽象论取消性质特权", connection: "原书线索" },
  { id: "e070", from: "primary-qualities-also-perception-relative", to: "does-immaterialism-deny-stones-and-trees", relation: "产生问题", label: "所有性质感知依赖引出常识对象问题", connection: "原书线索" },
  { id: "e071", from: "does-immaterialism-deny-stones-and-trees", to: "ordinary-objects-as-stable-idea-combinations", relation: "回应问题", label: "以稳定观念组合保存普通对象", connection: "原书线索" },
  { id: "e072", from: "ordinary-objects-as-stable-idea-combinations", to: "do-objects-exist-when-no-human-perceives", relation: "产生问题", label: "对象组合仍需无人观看时持续", connection: "原书线索" },
  { id: "e073", from: "sensory-ideas-arrive-involuntarily-observation", to: "what-causes-involuntary-sensory-ideas", relation: "提出问题", label: "非自愿感觉要求主动原因", connection: "原书线索" },
  { id: "e074", from: "what-causes-involuntary-sensory-ideas", to: "ideas-passive-spirits-active-god-orders-sense", relation: "回应问题", label: "区分被动观念与主动精神", connection: "原书线索" },
  { id: "e075", from: "ideas-passive-spirits-active-god-orders-sense", to: "do-objects-exist-when-no-human-perceives", relation: "产生问题", label: "神圣原因还需说明对象持续", connection: "原书线索" },
  { id: "e076", from: "do-objects-exist-when-no-human-perceives", to: "divine-perception-and-natural-signs-preserve-order", relation: "回应问题", label: "以神圣知觉和规律给予保存持续", connection: "原书线索" },
  { id: "e077", from: "divine-perception-and-natural-signs-preserve-order", to: "does-immaterialism-defeat-or-deepen-skepticism", relation: "产生问题", label: "神圣保证要求重新检验怀疑鸿沟", connection: "本站推演" },
  { id: "e078", from: "ordinary-objects-as-stable-idea-combinations", to: "does-immaterialism-defeat-or-deepen-skepticism", relation: "产生问题", label: "直接对象论声称缩短表象距离", connection: "原书线索" },
  { id: "e079", from: "does-immaterialism-defeat-or-deepen-skepticism", to: "direct-idea-world-with-notions-of-spirit", relation: "回应问题", label: "以观念直接性和精神活动回应怀疑", connection: "原书线索" },
  { id: "e080", from: "direct-idea-world-with-notions-of-spirit", to: "can-spirit-cause-and-self-survive-strict-experience-test", relation: "产生问题", label: "精神概念仍需接受来源审查", connection: "原书线索" },
  { id: "e081", from: "divine-perception-and-natural-signs-preserve-order", to: "can-spirit-cause-and-self-survive-strict-experience-test", relation: "产生问题", label: "神圣秩序保证开放休谟式审查", connection: "后世重构" },
];

export const enlightenmentProblemSources: ProblemMapSource[] = [
  { label: "SEP · Baruch Spinoza", url: "https://plato.stanford.edu/entries/spinoza/", note: "用于核对唯一实体、属性与样态、心身关系、知识、情感和伦理自由，并避免把斯宾诺莎缩成宿命论者。" },
  { label: "SEP · Spinoza’s Political Philosophy", url: "https://plato.stanford.edu/entries/spinoza-political/", note: "用于校正自然权利、共同力量、民主倾向、思想表达和国家和平的关系。" },
  { label: "Spinoza · Ethics", url: "https://www.gutenberg.org/cache/epub/3800/pg3800-images.html", note: "作为《伦理学》公共领域文本入口，用于核对实体、心身平行、情感、努力和自由人的论证次序。" },
  { label: "SEP · Gottfried Wilhelm Leibniz", url: "https://plato.stanford.edu/entries/leibniz/", note: "用于核对单子、活动统一、充足理由、不可分辨者同一、预定和谐、统觉与最佳世界。" },
  { label: "SEP · Principle of Sufficient Reason", url: "https://plato.stanford.edu/entries/sufficient-reason/", note: "用于区分充足理由的逻辑、因果与形而上学用途，并保留其与事实真理和自由的压力。" },
  { label: "SEP · Liberalism", url: "https://plato.stanford.edu/entries/liberalism/", note: "用于限制把早期自由主义直接等同当代完整权利制度，并核对自由、权威、财产和多元生活的长期分叉。" },
  { label: "SEP · John Locke", url: "https://plato.stanford.edu/entries/locke/", note: "用于核对感觉与反省、观念操作、知识与概率、性质、实体和洛克项目的认识论边界。" },
  { label: "SEP · Locke on Personal Identity", url: "https://plato.stanford.edu/entries/locke-personal-identity/", note: "用于保留意识、记忆、人格、实体和法责解释之间的当代争论，不把洛克压成简单记忆理论。" },
  { label: "SEP · Locke’s Political Philosophy", url: "https://plato.stanford.edu/entries/locke-political/", note: "用于校正自然法、权利、财产、同意、多数、政府解体、反抗与宽容，并标出不同解释路线。" },
  { label: "Locke · An Essay Concerning Humane Understanding", url: "https://gutenberg.org/files/10615/10615-h/10615-h.htm", note: "作为《人类理解论》公共领域文本入口，用于核对反天赋观念、观念来源、知识范围、性质、实体和人格同一。" },
  { label: "SEP · George Berkeley", url: "https://plato.stanford.edu/entries/berkeley/", note: "用于核对非物质主义、相似原则、第一性质批评、普通对象、观念被动性、精神和神圣秩序。" },
  { label: "Berkeley · Principles of Human Knowledge", url: "https://www.gutenberg.org/files/4723/4723-h/4723-h.htm", note: "作为《人类知识原理》公共领域文本入口，用于核对抽象观念批评、存在即被感知、物质基质、精神和自然规律。" },
];
