export type ProblemDensityId = "guide" | "backbone" | "standard" | "complete" | "research";

export type ProblemDensityOption = {
  id: ProblemDensityId;
  label: string;
  english: string;
  description: string;
};

export const problemDensityOptions: ProblemDensityOption[] = [
  {
    id: "guide",
    label: "导览",
    english: "ORIENTATION",
    description: "按历史时期与五个问题家族只显示关键接口，用来辨认全书问题从哪里出现、怎样换形。",
  },
  {
    id: "backbone",
    label: "主干",
    english: "BACKBONE",
    description: "保留观察、分叉、汇合、跨阶段接口与开放问题；一进一出的过渡步骤折叠为路径。",
  },
  {
    id: "standard",
    label: "标准",
    english: "STANDARD",
    description: "保留全部分支，并把连续的一进一出论证链压成可展开单位；适合日常阅读。",
  },
  {
    id: "complete",
    label: "完整",
    english: "COMPLETE",
    description: "显示全部原子节点和原始关系，不做折叠；适合检查每一步问题与回答。",
  },
  {
    id: "research",
    label: "研究",
    english: "EVIDENCE",
    description: "在完整图上进一步显示关系标签与证据性质；适合来源核对和内容审核。",
  },
];

export type ProblemFamilyId = "world-change" | "knowledge-language" | "self-agency" | "life-law" | "transcendence-authority";

export type ProblemFamily = {
  id: ProblemFamilyId;
  label: string;
  english: string;
  description: string;
  lane: number;
  anchorNodeIds: string[];
};

export const problemFamilies: ProblemFamily[] = [
  {
    id: "world-change",
    label: "世界、变化与因果",
    english: "WORLD · CHANGE · CAUSE",
    description: "追踪多样、运动、实体、原因与自然秩序怎样得到解释。",
    lane: 0,
    anchorNodeIds: [
      "difference-as-observation",
      "identity-through-change",
      "one-source-many-states",
      "motion-and-plurality-possible",
      "atoms-void-arrangement",
      "immanent-form-matter",
      "potentiality-actuality",
      "one-intellect-soul",
      "created-time-and-two-cities",
      "regular-conjunction-not-logical-necessity",
      "created-causes-real-under-first-cause",
      "experience-certifies-theoretical-conclusions",
      "virtu-adapts-to-fortuna",
      "what-can-publicly-correct-text-church-state-nature",
      "copernican-model-reorders-appearances",
      "keplerian-residuals-revise-geometry",
      "acceleration-and-composed-projectile-motion",
      "artifice-and-experiment-make-causes-visible",
      "causes-and-works-connect-light-fruit-and-power",
      "sensation-imagination-passions-as-bodily-motion",
      "mechanism-constrains-but-does-not-deduce-authority",
      "intellect-judges-extension-beyond-sense-image",
      "matter-as-extension-mechanical-order",
      "one-substance-god-or-nature",
      "attributes-and-modes-articulate-one-nature",
      "monads-as-active-perspectival-unities",
      "primary-structures-secondary-powers-distinction",
      "ordinary-objects-as-stable-idea-combinations",
      "necessary-connection-as-customary-transition",
      "organic-living-nature-as-romantic-countermodel",
      "space-time-a-priori-forms-of-intuition",
      "causality-as-condition-of-objective-succession",
      "reflective-judgment-purposiveness-without-proof",
      "objective-idealism-reason-immanent-in-world",
      "will-as-nonpersonal-striving-across-nature",
      "pessimism-from-endless-willing",
      "production-relations-structure-recurrent-harms",
      "duration-as-qualitative-interpenetration",
      "creative-evolution-marks-novelty-not-scientific-replacement",
    ],
  },
  {
    id: "knowledge-language",
    label: "知识、语言与证明",
    english: "KNOWLEDGE · LANGUAGE · PROOF",
    description: "追踪感觉、判断、逻辑、翻译、共相与证据标准怎样取得公共效力。",
    lane: 1,
    anchorNodeIds: [
      "what-does-perception-reveal",
      "common-standard-of-judgment",
      "what-stabilizes-knowledge",
      "stable-object-of-knowledge",
      "logic-translation-curriculum",
      "true-reason-true-authority-agree",
      "translation-commentary-demonstration-network",
      "how-latin-schools-judge-new-authorities",
      "truth-cannot-contradict-truth",
      "natural-preambles-revealed-mysteries",
      "intuitive-cognition-causes-mental-language",
      "parsimony-bounded-by-reason-experience-scripture",
      "ad-fontes-philology-corrects-inheritance",
      "trained-comparison-with-interpretive-restraint",
      "philology-print-survive-under-confessional-discipline",
      "calibration-record-repetition-stabilize-instruments",
      "idealization-controlled-operation-mathematical-law",
      "plural-methods-form-public-correction-network",
      "four-idols-diagnose-inquiry-obstacles",
      "tables-and-exclusion-build-gradual-induction",
      "first-vintage-remains-provisional-not-algorithmic",
      "names-definitions-reasoning-as-reckoning",
      "made-commonwealth-supports-conditional-civil-science",
      "methodic-doubt-suspends-uncertain-beliefs",
      "cogito-performed-certainty",
      "clear-distinct-perception-provisional-rule",
      "truths-of-reason-fact-and-possible-worlds",
      "sensation-and-reflection-supply-idea-materials",
      "knowledge-as-agreement-probability-for-practice",
      "substance-as-unknown-support-and-real-essence",
      "material-substratum-adds-no-experiential-content",
      "direct-idea-world-with-notions-of-spirit",
      "relations-of-ideas-and-matters-of-fact",
      "uniformity-defense-circular-or-nondemonstrative",
      "custom-naturally-sustains-calibrated-expectation",
      "mitigated-scepticism-limits-and-corrects-inquiry",
      "can-objective-experience-have-necessity-beyond-habit",
      "romantic-critique-synthesizes-reason-and-sensibility",
      "copernican-turn-objects-conform-to-cognition",
      "categories-and-apperception-unify-experience",
      "knowledge-limited-to-phenomena-not-private-illusion",
      "ideas-regulative-not-constitutive-knowledge",
      "can-subject-object-nature-freedom-unify-historically",
      "dialectic-is-immanent-not-fixed-triad",
      "historical-direction-is-diagnostic-not-guarantee",
      "genealogy-links-origin-function-affect-effect",
      "perspectivism-compares-situated-interpretations",
      "truth-grows-through-verification-and-reality-constraint",
      "warranted-assertibility-through-disciplined-inquiry",
      "frege-quantification-function-argument-logic",
      "descriptions-as-quantified-incomplete-symbols",
      "analysis-works-with-relative-simplicity",
    ],
  },
  {
    id: "self-agency",
    label: "心灵、自由与人格",
    english: "MIND · FREEDOM · PERSON",
    description: "追踪灵魂、意志、责任、恩典与个体人格怎样在秩序中保持行动能力。",
    lane: 2,
    anchorNodeIds: [
      "can-soul-survive-body",
      "fate-and-responsibility",
      "assent-as-internal-cause",
      "reason-or-divine-aid",
      "evil-privation-disordered-will",
      "grace-heals-divided-will",
      "eternal-present-knows-contingently",
      "shared-intellect-individual-imagination",
      "each-human-soul-has-intellectual-powers",
      "common-nature-contracted-by-haecceity",
      "will-has-synchronic-alternative-power",
      "how-can-thought-judge-state-classics-scripture-experience",
      "agency-expands-within-religious-patronage",
      "how-free-is-will-before-grace",
      "law-reveals-incapacity-grace-creates-will",
      "sensation-imagination-passions-as-bodily-motion",
      "self-preservation-and-protection-bound-obedience",
      "thinking-thing-before-body",
      "thought-extension-real-distinction",
      "mind-body-union-lived-not-mechanically-resolved",
      "can-two-created-substances-fit-one-intelligible-nature",
      "mind-body-parallel-expression",
      "conatus-and-adequate-understanding-increase-agency",
      "apperception-builds-conscious-continuity",
      "personhood-through-conscious-appropriation",
      "ideas-passive-spirits-active-god-orders-sense",
      "can-spirit-cause-and-self-survive-strict-experience-test",
      "self-as-bundle-and-succession-of-perceptions",
      "association-explains-identity-fiction-not-full-unity",
      "liberty-as-action-according-to-will",
      "bildung-creative-individuality-within-relations",
      "amour-propre-can-be-inflamed-or-egalitarian",
      "negative-education-protects-developmental-agency",
      "autonomy-as-rational-self-legislation",
      "two-standpoints-natural-causality-practical-freedom",
      "mutual-recognition-constitutes-social-selfhood",
      "asymmetric-recognition-undermines-itself",
      "desire-reveals-will-before-rational-purpose",
      "affirmation-revalues-suffering-without-worshipping-it",
      "will-to-power-as-overcoming-and-organization-contested",
      "higher-pleasures-and-competent-judges",
      "free-act-expresses-whole-developing-self",
      "radical-empiricism-includes-experienced-relations",
      "experience-as-organism-environment-transaction",
    ],
  },
  {
    id: "life-law",
    label: "好生活、法律与共同体",
    english: "LIFE · LAW · COMMUNITY",
    description: "追踪幸福、德性、共同善、政治法律与公共生活如何彼此限制。",
    lane: 3,
    anchorNodeIds: [
      "virtue-as-rational-activity",
      "how-live-uncontrollable-world",
      "cynic-low-dependence",
      "epicurean-natural-therapy",
      "cosmopolis-common-reason",
      "law-orders-body-and-soul",
      "practical-reason-first-principles-natural-law",
      "papal-authority-fallible-and-limited",
      "human-legislator-people-prevailing-part",
      "general-council-represents-faithful-secular-enforcement",
      "plural-authorities-replace-single-center",
      "civic-humanism-links-learning-and-action",
      "effectual-truth-of-political-action",
      "republic-secures-vivere-libero",
      "institutions-channel-conflict-into-liberty",
      "property-law-public-use-distinction",
      "division-of-labor-and-salomons-house",
      "organized-inquiry-needs-governance-boundaries",
      "competition-diffidence-glory-create-war-disposition",
      "state-of-nature-tests-absence-of-common-power",
      "mutual-covenant-authorizes-artificial-person",
      "freedom-of-philosophizing-supports-peace",
      "civil-ends-limit-coercive-authority",
      "rights-protect-agency-but-remain-historically-partial",
      "natural-law-rights-precede-government",
      "fiduciary-government-and-separated-powers",
      "toleration-follows-limited-civil-ends",
      "stable-character-links-action-and-attribution",
      "social-pact-creates-equal-citizen-sovereign",
      "general-will-aims-common-interest-not-sum",
      "laws-from-all-apply-to-all-under-equality",
      "civil-freedom-as-nondomination-with-authoritarian-risk",
      "categorical-imperative-universal-law",
      "humanity-as-end-and-kingdom-of-ends",
      "institutions-mediate-capabilities-recognition-right",
      "ethical-life-mediates-family-civil-society-state",
      "actuality-is-critical-standard-not-fact-worship",
      "responsible-rebellion-links-courage-solidarity-limits",
      "compassion-crosses-principium-individuationis",
      "revaluation-tests-creative-flourishing-with-political-risk",
      "rights-and-rules-secure-long-run-utility",
      "harm-principle-protects-experiments-in-living",
      "alienation-separates-product-activity-capacity-others",
      "democracy-as-associated-life-and-public-inquiry",
      "public-inquiry-needs-institutions-and-counterpower",
    ],
  },
  {
    id: "transcendence-authority",
    label: "超越、经文与权威",
    english: "TRANSCENDENCE · SCRIPTURE · AUTHORITY",
    description: "追踪最高原则、启示、教会、制度与纠错权威怎样形成又相互竞争。",
    lane: 4,
    anchorNodeIds: [
      "one-intellect-soul",
      "logos-layered-exegesis-text",
      "can-salvation-community-survive-empire",
      "papal-monastic-network-order",
      "who-reforms-preserving-church",
      "two-orders-mutual-limitation",
      "negative-theology-action-attributes",
      "corporate-privileges-faculty-jurisdictions",
      "nature-grace-ordered-synthesis",
      "what-orders-world-after-universal-authority-fractures",
      "papal-plenitude-unam-sanctam",
      "pisa-fails-constance-restores-unity",
      "dominion-in-grace-poor-church-secular-remedy",
      "plural-authorities-replace-single-center",
      "humanism-reorders-curriculum-within-mixed-world",
      "erasmus-education-ad-fontes-peaceful-reform",
      "justification-by-faith-reorders-works",
      "word-community-without-private-infallibility",
      "reformation-opens-judgment-not-modern-toleration",
      "scripture-accommodation-natural-demonstration-boundary",
      "galileo-affair-evidence-jurisdiction-coercion",
      "four-idols-diagnose-inquiry-obstacles",
      "division-of-labor-and-salomons-house",
      "sovereign-unifies-law-force-representation",
      "self-preservation-and-protection-bound-obedience",
      "nondeceiving-god-secures-attended-clear-perceptions",
      "one-substance-god-or-nature",
      "best-compossible-world-as-choice-reason",
      "evil-permitted-not-good-in-itself",
      "divine-perception-and-natural-signs-preserve-order",
      "proportion-belief-to-total-evidence",
      "ideas-regulative-not-constitutive-knowledge",
      "freedom-practical-postulate-not-theoretical-object",
      "death-of-god-opens-nihilism-crisis",
      "overcoming-nihilism-requires-revaluation-not-substitute-idol",
      "private-experience-permits-commitment-not-universal-proof",
      "how-combine-clarity-history-experience-freedom-public-correction",
    ],
  },
];

export const problemPhaseHistoryStageIds: Record<string, string> = {
  "encounter-difference": "origins",
  "generate-difference": "origins",
  "eleatic-pressure": "origins",
  "preserve-and-recombine": "origins",
  "from-perception-to-knowledge": "athens",
  "aristotelian-reconstruction": "athens",
  "flourishing-and-polis": "athens",
  "hellenistic-therapies": "hellenistic",
  "criteria-freedom-cosmopolis": "hellenistic",
  "roman-inwardness-and-one": "roman",
  "revelation-grace-history": "patristic",
  "consolation-rule-pastoral-order": "early-medieval",
  "reason-reform-two-powers": "early-medieval",
  "translation-demonstration-revelation": "early-medieval",
  "schools-universals-dialectic": "scholastic",
  "universities-aristotle-mendicants": "scholastic",
  "aquinas-nature-grace-order": "scholastic",
  "franciscan-illumination-experience": "scholastic",
  "scotus-ockham-individual-signs": "scholastic",
  "territorial-law-papal-eclipse": "scholastic",
  "schism-conciliar-reform-transition": "scholastic",
  "renaissance-texts-cities-human-agency": "renaissance-science",
  "machiavelli-fortune-virtue-republic": "renaissance-science",
  "humanism-reformation-conscience-authority": "renaissance-science",
  "mathematized-nature-models-observation": "renaissance-science",
  "bacon-idols-induction-collaborative-discovery": "renaissance-science",
  "hobbes-motion-language-covenant-sovereignty": "early-modern",
  "descartes-doubt-cogito-mind-body": "early-modern",
  "spinoza-one-substance-affects-freedom": "early-modern",
  "leibniz-monads-reasons-possible-worlds": "early-modern",
  "liberalism-conscience-commerce-limited-power": "early-modern",
  "locke-experience-ideas-knowledge-identity": "early-modern",
  "locke-rights-property-trust-influence": "early-modern",
  "berkeley-ideas-spirits-immaterialism": "early-modern",
  "hume-impressions-causation-self-scepticism": "early-modern",
  "romanticism-reason-nature-individuality": "revolution-idealism",
  "rousseau-inequality-education-general-will": "revolution-idealism",
  "kant-experience-autonomy-judgment": "revolution-idealism",
  "nineteenth-century-history-system-reaction": "revolution-idealism",
  "hegel-dialectic-recognition-ethical-life-history": "revolution-idealism",
  "byron-romantic-rebellion-individuality": "revolution-idealism",
  "schopenhauer-representation-will-suffering-release": "revolution-idealism",
  "nietzsche-genealogy-nihilism-revaluation": "industrial-modern",
  "utilitarianism-welfare-liberty-reform": "industrial-modern",
  "marx-production-alienation-capital-practice": "industrial-modern",
  "bergson-duration-memory-intuition-creation": "industrial-modern",
  "james-pragmatism-truth-belief-pluralism": "industrial-modern",
  "dewey-inquiry-education-democracy": "industrial-modern",
  "logical-analysis-logic-language-structure": "industrial-modern",
};

export type ProblemBoundaryNote = {
  label: string;
  note: string;
};

export const problemBoundaryNotes: Record<string, ProblemBoundaryNote[]> = {
  "avignon-centralization-and-national-dependence": [{
    label: "制度边界",
    note: "阿维尼翁时期可以同时出现行政集中与地域依赖疑虑，不能简化成教廷已经完全受法国王权控制。",
  }],
  "human-legislator-people-prevailing-part": [{
    label: "概念边界",
    note: "马西略以公民整体或其较有分量部分说明法源，不等于现代普选、个人平权或完整人民主权。",
  }],
  "dominion-in-grace-poor-church-secular-remedy": [{
    label: "因果边界",
    note: "威克里夫的财产与恩典论影响改革语言，但没有证据证明他直接组织或单独造成 1381 年农民起义。",
  }],
  "individuals-and-universal-mental-signs": [{
    label: "解释边界",
    note: "奥卡姆拒绝实在共相有独立论证，不能把唯名论简化成一句‘如无必要勿增实体’。",
  }],
  "humanism-reorders-curriculum-within-mixed-world": [{
    label: "时代边界",
    note: "人文主义改变课程、文本实践和公共表达，但长期与经院训练及基督教改革重叠，不能直接写成一次完成的世俗化。",
  }],
  "political-goods-bound-instrumental-exceptions": [{
    label: "解释边界",
    note: "马基雅维利承认非常手段可能有效，不等于把邪恶本身宣布为善；《君主论》的统治分析还须与《论李维》的共和国自由并读。",
  }],
  "utopia-as-dialogic-countermodel": [{
    label: "文本边界",
    note: "《乌托邦》包含对话框架、反讽与结尾保留，岛上制度不能直接等同莫尔本人的完整政策蓝图。",
  }],
  "reformation-opens-judgment-not-modern-toleration": [{
    label: "概念边界",
    note: "路德诉诸经文、信仰与良心改变了服从结构，但宗教改革也产生宗派纪律和属地强制，不能提前等同现代普遍宗教自由。",
  }],
  "copernican-model-reorders-appearances": [{
    label: "证据边界",
    note: "哥白尼日心体系重组行星次序和视运动，但 1543 年并未凭更简洁或更精确立即击败所有地心与混合模型。",
  }],
  "calibration-record-repetition-stabilize-instruments": [{
    label: "观察边界",
    note: "望远镜不是透明延长的肉眼；新现象要经过校准、记录、重复和他人复看，现象可靠也不等于它唯一证明某个宇宙体系。",
  }],
  "galileo-affair-evidence-jurisdiction-coercion": [{
    label: "历史边界",
    note: "伽利略案包含真实的审查与强制，也交织未完成证据、教会内部差异、解释管辖和教廷政治，不能压成两个同质阵营的单次战争。",
  }],
  "plural-methods-form-public-correction-network": [{
    label: "方法边界",
    note: "科学革命没有一套由三位人物共同执行的万能方法；模型、残差、仪器、实验和数学在不同问题中形成交叉纠错网络。",
  }],
  "four-idols-diagnose-inquiry-obstacles": [{
    label: "文本边界",
    note: "培根在《新工具》中正式区分种族、洞穴、市场和剧场四类偶像；罗素本章另列‘学校偶像’的说法不应作为培根的第五种正式分类。",
  }],
  "first-vintage-remains-provisional-not-algorithmic": [{
    label: "方法边界",
    note: "培根的表格与排除不是现代科学的无假说算法；资料分类、相关性、概念发明、数学和推导仍需判断，历史上也很难把重要科学成果归为严格执行一套培根程序。",
  }],
  "causes-and-works-connect-light-fruit-and-power": [{
    label: "概念边界",
    note: "‘知识就是力量’在培根计划中连接原因知识与产生效果的能力，也以改善人的处境为目标；它不能单独充当任意支配自然或人的正当化口号。",
  }],
  "division-of-labor-and-salomons-house": [{
    label: "制度边界",
    note: "所罗门宫是《新大西岛》的虚构研究机构，展示分工、设施与跨代积累，也保留秘密和发布权；它不是已经实现的中立现代科学院。",
  }],
  "mechanism-constrains-but-does-not-deduce-authority": [{
    label: "推导边界",
    note: "霍布斯的唯物论与机械心理学提供政治行动的因果条件，却不能单独从‘一切是身体运动’推出绝对主权；自然状态、自然律、契约与授权承担独立论证工作。",
  }],
  "competition-diffidence-glory-create-war-disposition": [{
    label: "人性边界",
    note: "霍布斯的战争风险不要求人人天生邪恶；大致平等、有限善意、私人判断和不可信保证足以使自保者进入竞争、不信任与预防性行动。‘战争’也指持续的武力倾向，不是每刻实际交战。",
  }],
  "state-of-nature-tests-absence-of-common-power": [{
    label: "历史边界",
    note: "自然状态首先是缺少公认裁判与执行权的分析条件，不是全体人类共同经历过的可靠史前编年；霍布斯援引美洲居民的文字还带有其时代的殖民偏见。",
  }],
  "sovereign-unifies-law-force-representation": [{
    label: "制度边界",
    note: "霍布斯偏好君主制，但绝对主权可以由个人或会议承载；其核心主张是最终权威不可分割，不是只有世袭君主才可能形成国家。",
  }],
  "self-preservation-and-protection-bound-obedience": [{
    label: "权利边界",
    note: "授权不表示主权者在事实或道德上天然正确。霍布斯保留臣民抵抗直接生命威胁的自由，并使政治义务随保护能力消失而终止；这不是完整的一般革命权。",
  }],
  "methodic-doubt-suspends-uncertain-beliefs": [{
    label: "方法边界",
    note: "方法怀疑是为重建知识而暂时撤回同意，不是断言外部世界永久不存在，也不等同古代怀疑主义的持续悬置。",
  }],
  "cogito-performed-certainty": [{
    label: "推导边界",
    note: "我思首先依靠否认行为仍在执行思考的第一人称把握，不宜压成一个依赖预设大前提的普通三段论；它也只直接保证思考当下的存在。",
  }],
  "nondeceiving-god-secures-attended-clear-perceptions": [{
    label: "论证边界",
    note: "神圣非欺骗保证的范围与所谓“笛卡尔循环”长期有竞争解释；图谱保留这一步在体系中的功能，不把其有效性写成现代研究共识。",
  }],
  "thought-extension-real-distinction": [{
    label: "概念边界",
    note: "从思维与广延的清楚概念到两者实在区分，需要额外的存在论与神学前提；认识次序上先把握心灵，并不自动证明它能离身存在。",
  }],
  "mind-body-union-lived-not-mechanically-resolved": [{
    label: "解释边界",
    note: "笛卡尔明确说人不是像船长住在船中那样外在连接身体，并诉诸心身联合经验与生理机制；这些回应仍未给出公认的跨实体互动模型。",
  }],
  "one-substance-god-or-nature": [{
    label: "神学边界",
    note: "“上帝或自然”不是把自然整体拟人成一个会计划、奖惩和破例的人格神；斯宾诺莎以唯一无限实体重写了传统创造者—受造物区分。",
  }],
  "conatus-and-adequate-understanding-increase-agency": [{
    label: "自由边界",
    note: "理解必然性不等于消极接受一切现状。充分观念、主动情感、身体能力和共同制度会改变一个人由自身本性行动的程度。",
  }],
  "truths-of-reason-fact-and-possible-worlds": [{
    label: "模态边界",
    note: "莱布尼茨的可能世界是上帝理智中的完整可相容秩序，不是同时运行、只因观察者位置不同而都称为“现实”的平行宇宙。",
  }],
  "best-compossible-world-as-choice-reason": [{
    label: "价值边界",
    note: "“最佳可能世界”不表示每个局部事件都好，也不取消受苦者的实践要求；它是关于完整世界比较的神义论主张，论证有效性长期受争议。",
  }],
  "rights-protect-agency-but-remain-historically-partial": [{
    label: "时代边界",
    note: "早期自由主义提供反专断的权利与同意语言，却没有自动包含今日完整的性别、宗教、种族和经济平等；其殖民及财产语境必须同时保留。",
  }],
  "sensation-and-reflection-supply-idea-materials": [{
    label: "概念边界",
    note: "洛克反对的是预装的天赋命题和观念内容，不是把心灵写成没有比较、组合、抽象、语言和反省能力的被动空盒。",
  }],
  "primary-structures-secondary-powers-distinction": [{
    label: "科学边界",
    note: "第一／第二性质区分与洛克接受的微粒机械论相连，不是仅凭内省完成的永恒分类；贝克莱正会质疑第一性质能否脱离感知。",
  }],
  "personhood-through-conscious-appropriation": [{
    label: "解释边界",
    note: "洛克的人格同一以意识和法责为中心，但不宜简化成一次明确记忆就是同一性的充分必要条件；意识、记忆、实体和归责之间仍有多种解释。",
  }],
  "labor-appropriation-proviso-and-money": [{
    label: "历史边界",
    note: "劳动取得论必须与不浪费但书、给他人留下足够资源、货币积累以及洛克参与的殖民政治和奴役经济一并审视。",
  }],
  "ordinary-objects-as-stable-idea-combinations": [{
    label: "常见误读",
    note: "贝克莱否认的是感性对象背后必需一个不可感知的物质基质，并不否认石头、树木、身体、疼痛或公共物理世界的经验真实性。",
  }],
  "ideas-passive-spirits-active-god-orders-sense": [{
    label: "论证边界",
    note: "由观念被动、感觉非自愿和秩序复杂到主动精神及上帝的推理需要额外前提；图谱保留其体系功能，不把它写成经验来源原则无争议的直接结论。",
  }],
  "simple-ideas-copy-impressions-source-test": [{
    label: "方法边界",
    note: "复制原则主要审查简单观念的经验来源；休谟本人随即承认‘缺失蓝色阴影’这一罕见反例，因此不能把它机械化为毫无例外的意义判决程序。",
  }],
  "necessary-connection-as-customary-transition": [{
    label: "解释边界",
    note: "习惯是重复经验引起的非自愿心理倾向，不是懒惰、随意联想或拒绝科学训练。休谟是否进一步否认客观因果力量，仍有怀疑主义与因果实在论等竞争解释。",
  }],
  "self-as-bundle-and-succession-of-perceptions": [{
    label: "理论边界",
    note: "‘知觉束’不是已无代价解决人格同一。休谟在《人性论》附录中明确承认自己的说明仍有困难；图谱区分同一信念的心理生成与主体统一的完整理论。",
  }],
  "proportion-belief-to-total-evidence": [{
    label: "证据边界",
    note: "休谟的奇迹论证比较见证错误与事件违反稳定经验的相对证据，不是以定义宣布所有异常事件逻辑不可能；其概率框架和具体历史判断仍可被批评。",
  }],
  "mitigated-scepticism-limits-and-corrects-inquiry": [{
    label: "常见误读",
    note: "缓和怀疑不是停止生活、科学或一切断言，而是承认自然信念不可避免，同时让判断按证据强弱、反例和人类理解力范围保持克制。",
  }],
  "romantic-critique-synthesizes-reason-and-sensibility": [{
    label: "时代边界",
    note: "浪漫主义不是成员持同一学说的单一反理性阵营；许多路线继承自主批判，同时扩展感性、想象、历史意识和审美判断的地位。",
  }],
  "organic-living-nature-as-romantic-countermodel": [{
    label: "方法边界",
    note: "有机自然是对机械还原的反模型，不会自动取代物理因果、实验和测量；从生命组织推广到宇宙目的或人格化自然还需要额外论证。",
  }],
  "conjectural-genealogy-of-property-law-inequality": [{
    label: "历史边界",
    note: "卢梭的自然状态与不平等生成是批判现存制度的猜想性历史，不是有档案可逐阶段验证的史前编年，也不要求现实回到孤立自然状态。",
  }],
  "amour-propre-can-be-inflamed-or-egalitarian": [{
    label: "概念边界",
    note: "amour-propre 不只是虚荣：它会被地位竞争煽动，也可能在平等制度与教育中转成相互尊重的要求；不能与自我保存的 amour de soi 混为一谈。",
  }],
  "general-will-aims-common-interest-not-sum": [{
    label: "制度边界",
    note: "公意指向共同利益，不等于私人意见的简单总和、一次多数票或领袖自称代表整体；它还依赖法律由全体制定并普遍适用、相对平等和公民判断等条件。",
  }],
  "civil-freedom-as-nondomination-with-authoritarian-risk": [{
    label: "权利边界",
    note: "‘迫使自由’只有在公民同等参与共同法律且强制阻止私人支配时才可能成立；现实中的代表垄断、异议压制与不平等会使它迅速滑向威权正当化。",
  }],
  "categories-and-apperception-unify-experience": [{
    label: "主体边界",
    note: "先验统觉说明表象必须能够属于同一判断主体，不是对灵魂实体、永恒人格或可脱离身体自我的理论证明。",
  }],
  "knowledge-limited-to-phenomena-not-private-illusion": [{
    label: "常见误读",
    note: "康德限制知识于现象，不等于个人心灵任意创造或幻想世界；现象世界在共同的时空与范畴条件下具有经验实在性，可被公共检验与纠错。",
  }],
  "two-standpoints-natural-causality-practical-freedom": [{
    label: "论证边界",
    note: "自然因果与实践自由的两种立场旨在避免矛盾，并不等于理论上观察或证明了超经验自由怎样产生经验效果。",
  }],
  "historical-direction-is-diagnostic-not-guarantee": [{
    label: "历史边界",
    note: "把历史按自由意识和制度形式比较，不表示年代较晚、军事胜利或国家成功天然更合理；倒退、并行可能和不可补偿损失必须保留。",
  }],
  "post-kantian-programs-share-pressure-not-destiny": [{
    label: "谱系边界",
    note: "费希特、谢林、早期浪漫派与黑格尔共享后康德问题，却没有共同命定的黑格尔式终点；图谱连接的是压力与回应，不是单线师承。",
  }],
  "dialectic-is-immanent-not-fixed-triad": [{
    label: "常见误读",
    note: "黑格尔辩证法不能机械化成到处套用的‘正题—反题—合题’口诀；推进必须说明一种规定如何因自身承诺而失败，以及新规定保存了什么。",
  }],
  "asymmetric-recognition-undermines-itself": [{
    label: "文本边界",
    note: "主人—奴隶段落首先是《精神现象学》中的自我意识图式，不等于对某一具体奴隶制度、全部劳动史或革命必然性的完整经验叙述。",
  }],
  "actuality-is-critical-standard-not-fact-worship": [{
    label: "政治边界",
    note: "‘现实的即合理的’不应读成凡存在者皆正当；但区分 Wirklichkeit 与偶然存在也不能抹去黑格尔具体国家论中的保守安排和权力风险。",
  }],
  "totality-must-remain-answerable-to-unreconciled-lives": [{
    label: "重构边界",
    note: "让整体持续回应未调和生命带有后世批判理论的修复方向，不等于黑格尔文本已经完整接受这一限制，也不替罗素的整体主义批评背书。",
  }],
  "byronic-figure-exposes-conformity-without-system": [{
    label: "人物边界",
    note: "拜伦在哲学史中的功能是文化人格、文学问题和政治情感，不是拥有与黑格尔同类的封闭体系；作品角色、叙述者、作者生平与后世‘拜伦式英雄’必须分开。",
  }],
  "charisma-mobilizes-but-cannot-legitimate-rule": [{
    label: "政治边界",
    note: "诗人名望与英雄魅力能够动员声援，却不自动产生代表权、统治正当性或对当地行动者的解释优先权。",
  }],
  "world-double-aspect-representation-and-will": [{
    label: "论证边界",
    note: "从身体的内外双重经验到‘意志是物自身’，再推广到全部自然，包含有争议的形而上学类推；不能把它当作康德结论或现代物理学发现。",
  }],
  "pessimism-is-metaphysical-evaluation-not-measurement": [{
    label: "价值边界",
    note: "叔本华的悲观主义不是统计快乐与痛苦后得到的中性测量；从欲求结构到生命不值得肯定仍依赖可争论的价值前提。",
  }],
  "asian-thought-selectively-reconstructed-in-european-system": [{
    label: "跨传统边界",
    note: "叔本华经十九世纪欧洲译介选择性吸收印度思想，不能直接称作‘西方佛教’或用其意志本体替代佛教无我、业与具体修行传统。",
  }],
  "death-of-god-opens-nihilism-crisis": [{
    label: "常见误读",
    note: "‘上帝死了’主要诊断最高价值的文化根据失效及其延迟后果，不是关于神发生生物学死亡的断言，也不表示所有宗教实践在同一时刻消失。",
  }],
  "genealogy-links-origin-function-affect-effect": [{
    label: "方法边界",
    note: "谱系不应由一个价值的偶然或不体面起源直接推出其现在为假；它还必须追踪功能转移、情感训练和现实效果，并接受具体历史证据校正。",
  }],
  "ressentiment-creates-reactive-good-evil": [{
    label: "政治边界",
    note: "ressentiment 类型学不能把所有受压者诉求、平等原则或关怀伦理一律病理化，也不能因贵族价值具有主动性就替暴力和支配免责。",
  }],
  "perspectivism-compares-situated-interpretations": [{
    label: "认识边界",
    note: "视角主义反对无位置的上帝视角，不等于所有解释同样正确；证据阻力、解释范围、容纳更多视角和自我校正仍构成比较条件。",
  }],
  "will-to-power-as-overcoming-and-organization-contested": [{
    label: "概念边界",
    note: "权力意志不只等于政治统治欲，可指驱力克服阻力与组织能力；其究竟是心理学、价值论还是形而上学主张仍有竞争解释。",
  }],
  "eternal-recurrence-as-affirmation-test-not-proven-cosmology": [{
    label: "解释边界",
    note: "永恒轮回可作为生命肯定测试，但尼采是否主张并证明了字面宇宙循环仍有争议；图谱不把它写成现代宇宙学事实。",
  }],
  "nietzsche-not-nazi-but-political-dangers-remain": [{
    label: "接受史边界",
    note: "尼采反民族主义、反反犹主义，且遭妹妹和纳粹选择性挪用，因此不能直接等同纳粹；其贵族主义、反平等和残酷表达仍属于文本自身，不能全部推给误读。",
  }],
  "felicific-calculus-as-revisable-comparison": [{
    label: "方法边界",
    note: "边沁的快乐维度可迫使改革者公开比较后果，但不是能把所有体验无误换算为单一数字的心理仪器；不确定性、分配与遗漏利益必须另行处理。",
  }],
  "harm-principle-protects-experiments-in-living": [{
    label: "自由边界",
    note: "伤害原则不能由‘我不喜欢’直接触发，也不表示自涉与涉他行动总能机械分开；依赖、操纵、公共风险和累积后果仍需具体制度判断。",
  }],
  "historical-materialism-constrains-without-mechanical-determinism": [{
    label: "常见误读",
    note: "历史唯物主义强调生产与物质生活条件，不等于经济变量单向决定法律、政治和文化；人的组织、观念、冲突与偶然仍参与历史结果。",
  }],
  "marx-legacy-needs-text-institution-outcome-separation": [{
    label: "接受史边界",
    note: "后继威权政权不能直接充当马克思每项论证的必然推论，也不能与其思想完全切断；应分别检验文本承诺、制度欠说明、组织选择和具体历史后果。",
  }],
  "intuition-enters-process-analysis-still-needed": [{
    label: "方法边界",
    note: "柏格森的直觉不是无证据灵感，而是改变注意方式以进入过程；它仍需分析、表达和公共校正，也不能替代实验科学。",
  }],
  "creative-evolution-marks-novelty-not-scientific-replacement": [{
    label: "科学边界",
    note: "生命冲力和创造进化强调不可预成的新颖性，不能写成已获现代生物学证实的机制，更不能用来取消自然选择与实验研究。",
  }],
  "truth-grows-through-verification-and-reality-constraint": [{
    label: "常见误读",
    note: "詹姆斯没有主张‘任何对我有用的信念都是真的’；验证、对象阻力、既有知识协调和后续纠错共同限制可依赖的真观念。",
  }],
  "will-to-believe-bounded-live-forced-momentous-options": [{
    label: "适用边界",
    note: "信仰意志只针对真实可活、无法回避、意义重大且证据暂不能决定的选项，不为任意事实愿望、公共谣言或拒绝反证提供许可。",
  }],
  "education-guides-experience-toward-growth": [{
    label: "教育边界",
    note: "杜威的‘做中学’不是取消教师、课程和知识结构；活动必须由环境设计、学科资源和反思引导，才能增加继续探究的能力。",
  }],
  "democracy-as-associated-life-and-public-inquiry": [{
    label: "制度边界",
    note: "把民主理解为联合生活并不降低选举、权利和制衡的重要性；开放沟通本身也会受资源不平等、专家垄断和媒体权力扭曲。",
  }],
  "frege-quantification-function-argument-logic": [{
    label: "史学边界",
    note: "弗雷格对现代量化逻辑影响巨大，但其原始记号与今日谓词逻辑并不相同，现代逻辑的形成也包括布尔、德摩根、皮尔士等人的并行贡献。",
  }],
  "analysis-works-with-relative-simplicity": [{
    label: "方法边界",
    note: "逻辑分析不必保证发现绝对简单的世界原子；相对简单性足以支持特定重构，但形式清晰不能单独裁决经验事实、历史因果或规范价值。",
  }],
};

export type ProblemComparisonFan = {
  questionId: string;
  label: string;
  note: string;
  answerIds: string[];
};

export const problemComparisonFans: ProblemComparisonFan[] = [
  {
    questionId: "how-live-uncontrollable-world",
    label: "四种竞争性生活方案",
    note: "四条支线回答同一实践压力，但不构成单一师承路线；选择任一答案可继续查看它留下的代价与新问题。",
    answerIds: ["cynic-low-dependence", "skeptical-suspension", "epicurean-natural-therapy", "stoic-virtue-in-order"],
  },
  {
    questionId: "change-as-reconfiguration",
    label: "三种保存不变者的重构",
    note: "四根、混合物与原子论都保存不变构成，却以不同机制解释可见变化。",
    answerIds: ["roots-love-strife", "mixture-nous-separation", "atoms-void-arrangement"],
  },
  {
    questionId: "how-can-rulers-study-political-survival",
    label: "三种政治生存接口",
    note: "实际效果、virtù—fortuna 与自己的武备分别处理知识、行动和制度依赖；三者共同构成分析面，不是互斥学派。",
    answerIds: ["effectual-truth-of-political-action", "virtu-adapts-to-fortuna", "own-arms-before-borrowed-force"],
  },
  {
    questionId: "how-should-christian-society-be-reformed",
    label: "三种共享批评、分歧行动的改革路线",
    note: "伊拉斯谟、莫尔与路德共享部分弊端批评和文本资源，却对统一、法律、自由意志与教会断裂承担不同承诺。",
    answerIds: ["erasmus-education-ad-fontes-peaceful-reform", "more-dialogue-law-comparative-reform", "luther-word-faith-church-reform"],
  },
  {
    questionId: "what-can-publicly-correct-text-church-state-nature",
    label: "三种科学公共纠错接口",
    note: "哥白尼的可重算模型、开普勒的残差修订和伽利略的仪器—实验—数学组合分别改变不同证据环节，不能合并成一句‘观察取代权威’。",
    answerIds: ["copernican-model-reorders-appearances", "keplerian-residuals-revise-geometry", "galilean-instruments-idealization-mathematics"],
  },
  {
    questionId: "how-can-discovery-be-organized-beyond-genius",
    label: "四种有组织发现接口",
    note: "偶像诊断、排除式归纳、实验干预和知识分工分别处理误差、比较、操作与规模；它们共同构成培根纲领，但不合并为自动产生真理的一条规则。",
    answerIds: ["four-idols-diagnose-inquiry-obstacles", "tables-and-exclusion-build-gradual-induction", "artifice-and-experiment-make-causes-visible", "division-of-labor-and-salomons-house"],
  },
  {
    questionId: "can-civil-order-be-reconstructed-as-systematic-artifice",
    label: "四种人工秩序构造接口",
    note: "身体运动、语言定义、自然状态压力测试和授权人工人格分别处理行动者、推理、风险与共同权力；四者是体系层次，不是从机械论一步推出绝对君主。",
    answerIds: ["sensation-imagination-passions-as-bodily-motion", "names-definitions-reasoning-as-reckoning", "competition-diffidence-glory-create-war-disposition", "mutual-covenant-authorizes-artificial-person"],
  },
  {
    questionId: "how-can-subject-loosen-service-to-will",
    label: "三种松脱意志的实践路线",
    note: "审美静观、同情行动和禁欲否定分别提供暂时注意转换、伦理去利己与更彻底退出欲望循环；它们强度不同，也承担不同代价。",
    answerIds: ["aesthetic-contemplation-suspends-personal-striving", "compassion-crosses-principium-individuationis", "ascetic-negation-reduces-will-to-life"],
  },
];
