import type { ProblemEdge, ProblemMapSource, ProblemPhase } from "./problem-map-data";

export const humeProblemPhases: ProblemPhase[] = [
  {
    id: "hume-impressions-causation-self-scepticism",
    order: 35,
    label: "经验来源、因果习惯与缓和怀疑",
    title: "把经验来源审查推进到因果、自我与实践信念，再限制怀疑的适用范围",
    question: "若经验只给出当下知觉与重复次序，因果、自我、责任和科学预期凭什么成立？",
    transition: "休谟沿用经验主义的来源追问，却不以物质或精神实体填补经验之外的空位。他区分印象与观念、观念关系与事实问题，把因果必然定位到重复经验引起的心理倾向，并用知觉束检验实体自我；结论不是停止推理，而是承认自然习惯先于哲学证明，并让判断接受证据强度和共同生活的约束。",
    nodes: [
      {
        id: "simple-ideas-copy-impressions-source-test",
        kind: "答案",
        answerRole: "转向",
        title: "简单观念须能追溯到较鲜明的印象，复杂观念则由心灵组合",
        summary: "感觉与内在情感提供印象，记忆和想象保存较弱的观念；面对含混概念，可把它拆开并追问各简单成分来自何种经验。",
        pressure: "复制原则有著名的‘缺失蓝色阴影’例外，也不能单独说明观念怎样指向对象；它更适合作为概念审查工具，而不是逐项机械目录。",
        consequence: "精神、能力和持续自我不能只因语言中有相应名词就获得实体地位；仍需判断哪些命题能由经验或推理支持。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以印象—观念区分和复制原则推进经验来源审查" }],
        chapterIds: ["b3-17"],
        graph: { row: 326, lane: 1.5 },
      },
      {
        id: "what-judgments-survive-experience-source-test",
        kind: "问题",
        title: "经过经验来源审查后，哪些判断仍具有清楚的知识资格？",
        summary: "概念来源只是第一关；数学证明、当下感觉和关于远方或未来的事实判断，显然不依赖同一种根据。",
        pressure: "若把所有判断都降为感觉副本，就无法解释数学必然性；若让纯理性推出事实，又会越过经验边界。",
        consequence: "休谟把认识对象区分为观念关系与事实问题。",
        participants: [],
        chapterIds: ["b3-17"],
        graph: { row: 327, lane: 1.5 },
      },
      {
        id: "relations-of-ideas-and-matters-of-fact",
        kind: "答案",
        answerRole: "区分",
        title: "观念关系凭概念与证明成立，事实问题只能由经验获得且反面总可设想",
        summary: "数学和定义关系具有必然性；关于世界实际如何的判断则是偶然的，其否定不会仅因概念矛盾而被排除。",
        pressure: "事实知识远超当前感觉与记忆；若不能靠演绎跨出当下，就必须说明经验推断的实际机制和资格。",
        consequence: "问题集中到因果推理：人为何从已见事件推向未见事件。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以观念关系／事实问题区分限制纯理性的事实使用" }],
        chapterIds: ["b3-17"],
        graph: { row: 328, lane: 1.5 },
      },
      {
        id: "novel-object-effects-not-a-priori-observation",
        kind: "观察",
        observation: {
          domain: "自然经验",
          note: "面对从未经验的新对象，只看其颜色、形状或运动，不能演绎出它将燃烧、滋养、致毒或产生何种后果。",
          historyLinks: [{
            stageId: "early-modern",
            responseId: "hume",
            label: "经验主义终点与因果限度",
            note: "进入历史概览查看科学成功与经验基础的有限性怎样共同形成休谟问题。",
          }],
        },
        title: "初见一个对象时，仅凭可见性质无法推出它将造成什么结果",
        summary: "火焰的热、食物的营养或撞击后的运动，必须在某种经验之后才形成预期；效果不是从原因概念中透明展开。",
        pressure: "人仍不断对未见结果作出行动攸关的判断，说明事实推理有一套非演绎的推进方式。",
        consequence: "观察提出人怎样从当前或过去经验跨到缺席事实。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以陌生对象思想实验显示因果知识依赖经验" }],
        chapterIds: ["b3-17"],
        graph: { row: 328, lane: 0.3 },
      },
      {
        id: "how-infer-beyond-memory-and-present-sense",
        kind: "问题",
        title: "人怎样从记忆和当前感觉推断未见的过去、远方与未来？",
        summary: "看到烟便相信有火、读到信件便相信作者存在、播种便期待收成，这些判断都超出眼前知觉。",
        pressure: "若没有连接当前证据与缺席事实的关系，推断只是想象跳跃；若关系是必然的，又应能先验发现。",
        consequence: "休谟把事实推断定位为因果推断。",
        participants: [],
        chapterIds: ["b3-17"],
        graph: { row: 329, lane: 0.9 },
      },
      {
        id: "fact-inference-depends-on-cause-effect",
        kind: "答案",
        answerRole: "提出",
        title: "超出感觉与记忆的事实推断，都借助原因与结果关系前进",
        summary: "证据之所以支持缺席事实，是因为人把两类事件视为有规律地相连；因果由此成为经验知识和日常行动的关键桥梁。",
        pressure: "指出桥梁存在还没有说明它为何可靠，也没有说明一次观察能否揭示必然力量。",
        consequence: "下一步必须检验因果关系能否由理性独立证明。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "把事实推理分析为因果推理" }],
        chapterIds: ["b3-17"],
        graph: { row: 330, lane: 0.9 },
      },
      {
        id: "can-reason-demonstrate-causal-effect",
        kind: "问题",
        title: "理性能否只分析原因概念，就证明某种特定结果必会出现？",
        summary: "若结果内含于原因，否定它应造成矛盾；但同一表面原因伴随不同结果在逻辑上总可设想。",
        pressure: "把可设想等同真实可能本身有争议，但它至少阻止人把经验规律偷换成纯定义真理。",
        consequence: "因果效果不能像数学关系那样由演绎单独发现。",
        participants: [],
        chapterIds: ["b3-17"],
        graph: { row: 331, lane: 0.9 },
      },
      {
        id: "causal-effect-not-demonstrable-a-priori",
        kind: "答案",
        answerRole: "反驳",
        title: "原因与结果是可分别设想的事实，特定连接不能由先验演绎证明",
        summary: "第一次看到两球碰撞时，理性可以想象多种后续；只有实际经验让某个结果取得预期优势。",
        pressure: "诉诸过去经验仍需说明过去的相同联合为何能约束尚未观察的情形。",
        consequence: "演绎道路关闭后，统一性原则自身成为审查对象。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以结果可分离设想反对先验因果证明" }],
        chapterIds: ["b3-17"],
        graph: { row: 332, lane: 0.9 },
      },
      {
        id: "can-experience-prove-future-resembles-past",
        kind: "问题",
        title: "过去经验能否不循环地证明未观察情形会继续类似过去？",
        summary: "经验推断预设自然在相关方面保持一致；但这一预设既不是概念必然，也不是当前感觉直接呈现的对象。",
        pressure: "若用‘过去归纳曾成功’作证明，就已经从过去成功推向未来成功，重复使用了待证明的推理。",
        consequence: "经验主义必须承认归纳没有演绎证明，也没有不循环的概率证明。",
        participants: [],
        chapterIds: ["b3-17"],
        graph: { row: 333, lane: 0.9 },
      },
      {
        id: "uniformity-defense-circular-or-nondemonstrative",
        kind: "答案",
        answerRole: "反驳",
        title: "自然齐一性既非观念关系，用经验为它辩护又会循环",
        summary: "未来不同于过去并不矛盾；过去的规律若被用来保证未来规律，论证已经假定经验推断可以跨到未观察对象。",
        pressure: "这并未证明所有归纳都同样糟，也未给出停止归纳的可行方案；它区分的是理性证明与人实际形成信念的机制。",
        consequence: "问题转向心理层面：重复经验究竟在心灵中改变了什么。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "揭示归纳为自身辩护时的循环结构" }],
        chapterIds: ["b3-17"],
        graph: { row: 334, lane: 0.9 },
      },
      {
        id: "repetition-produces-expectation-observation",
        kind: "观察",
        observation: { domain: "个体体验", note: "一次相随只呈现先后；多次相似相随以后，看到前项会自动唤起对后项的更鲜明期待，即使没有新增可见力量。" },
        title: "相似事件反复相随以后，心灵会由前项自动转向对后项的期待",
        summary: "重复没有在外部对象表面添加一条可见纽带，却改变了知觉之间的联想强度和信念活力。",
        pressure: "心理期待可能解释人为什么相信，却不自动证明世界必须服从期待。",
        consequence: "观察提出必然联系观念的印象来源。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "从恒常结合与期待形成追踪必然联系观念" }],
        chapterIds: ["b3-17"],
        graph: { row: 331, lane: 2.5 },
      },
      {
        id: "what-impression-supplies-necessary-connection",
        kind: "问题",
        title: "人从哪一种印象获得原因必然产生结果的‘必然联系’观念？",
        summary: "单次外部事件只显示接近、先后和变化；内在意志经验也没有揭示命令怎样使身体或观念发生。",
        pressure: "若完全没有相应印象，必然联系可能只是无内容词语；若来自重复，就要说明新增内容为何属于心灵。",
        consequence: "休谟把来源定位在重复引起的内在决定与期待感。",
        participants: [],
        chapterIds: ["b3-17"],
        graph: { row: 332, lane: 2.5 },
      },
      {
        id: "necessary-connection-as-customary-transition",
        kind: "答案",
        answerRole: "转向",
        title: "必然联系观念来自恒常结合后心灵的习惯性过渡，而非被看见的隐秘力量",
        summary: "看到类似原因时，习惯使相关结果的观念更鲜明地出现；人再把这种内在决定投射到对象关系上。",
        pressure: "休谟是否因此否认任何不可观察因果力量，还是只限制人对它的观念与知识，长期存在竞争解释。",
        consequence: "因果信念获得自然史解释，却仍需回答这种机制是否具有认识资格。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以恒常结合、习惯和期待重构必然联系" }],
        chapterIds: ["b3-17"],
        graph: { row: 333, lane: 2.5 },
      },
      {
        id: "does-custom-explain-or-justify-induction",
        kind: "问题",
        title: "习惯说明人为何归纳，是否也足以说明归纳为何值得信赖？",
        summary: "心理成因与规范根据不是同一问题；稳定习惯可能成功，也可能固化偏见和小样本误差。",
        pressure: "要求一种完全不依赖归纳的归纳证明会设下不可能标准，但仅描述倾向也不足以区分谨慎科学与轻率猜测。",
        consequence: "休谟的怀疑性解决转向人类自然、概率校准和经验纠错，而非演绎奠基。",
        participants: [],
        chapterIds: ["b3-17"],
        graph: { row: 335, lane: 2.0 },
      },
      {
        id: "custom-naturally-sustains-calibrated-expectation",
        kind: "答案",
        answerRole: "修复",
        title: "自然习惯不可由论证替代，判断仍可按经验数量、稳定性与反例调整",
        summary: "因果预期不是数学证明，却是行动和实验不可避免的心灵机制；更广样本、竞争经验与概率权衡可以校正其强弱。",
        pressure: "这是一种自然化而有限的回答，不提供世界必然继续齐一的外部保证，也不能让所有习惯自动获得同等正当性。",
        consequence: "怀疑从摧毁经验推理转为限制其声称，并开放科学客观必然性是否需要另一种解释。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以习惯、概率和经验校准给出怀疑性解决" }],
        chapterIds: ["b3-17"],
        graph: { row: 336, lane: 2.0 },
      },
      {
        id: "stream-of-perceptions-no-constant-self-observation",
        kind: "观察",
        observation: { domain: "个体体验", note: "内省时出现冷热、爱憎、疼痛、记忆和想象等具体知觉，却没有一个与所有知觉分离、始终以同样方式出现的自我印象。" },
        title: "转向内心时，人总遇见具体知觉，却找不到不变的实体自我印象",
        summary: "睡眠、情绪变化和注意转移使心灵内容不断更替；所谓自我若是一个额外对象，应说明它怎样被经验。",
        pressure: "找不到恒常印象不等于行动者不存在；语言、身体、记忆和社会归责仍把经历视为某个人的经历。",
        consequence: "观察把贝克莱保留的主动精神推进为人格统一问题。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以内省检验持续实体自我的经验来源" }],
        chapterIds: ["b3-17"],
        graph: { row: 329, lane: 4.2 },
      },
      {
        id: "what-unifies-person-without-self-impression",
        kind: "问题",
        title: "若没有恒常自我印象，跨时间的思想、记忆和行动为何仍属于同一个人？",
        summary: "经验内容彼此可区分，个人同一却要求把它们联成一段可追责、可计划和可叙述的生活。",
        pressure: "假设一个不可经验实体会绕过来源标准；只列知觉又可能遗漏‘这些知觉属于谁’的统一关系。",
        consequence: "休谟以知觉束及其联想次序替代单一实体持有者。",
        participants: [],
        chapterIds: ["b3-17"],
        graph: { row: 330, lane: 4.2 },
      },
      {
        id: "self-as-bundle-and-succession-of-perceptions",
        kind: "答案",
        answerRole: "反驳",
        title: "思考中的自我是相互关联的知觉束与连续序列，不是其后的简单实体",
        summary: "相似、因果、记忆和想象把不同知觉连接成较稳定历史；心灵更像不断换景的舞台，但不能再把舞台本身实体化。",
        pressure: "联想关系如何在不先假定同一心灵时组成一个知觉束，以及记忆怎样确认而非制造同一，仍有困难。",
        consequence: "知觉束论自身产生统一、所有权和责任持续问题。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以知觉束和联想关系反对不可经验的简单自我实体" }],
        chapterIds: ["b3-17"],
        graph: { row: 331, lane: 4.2 },
      },
      {
        id: "can-association-explain-one-mind-and-responsibility",
        kind: "问题",
        title: "相似、因果与记忆能否在不预设主体时组成一个心灵并保存责任？",
        summary: "知觉之间的关系可以解释叙事连续，却仍须区分我的记忆与他人的记忆、真实记忆与想象，以及改变中的责任主体。",
        pressure: "若关系必须先被某个主体把握，实体自我似乎返回；若关系自行成束，又要说明束的边界。",
        consequence: "休谟承认《人性论》中的人格同一说明留下难以调和之处。",
        participants: [],
        chapterIds: ["b3-17"],
        graph: { row: 332, lane: 4.2 },
      },
      {
        id: "association-explains-identity-fiction-not-full-unity",
        kind: "答案",
        answerRole: "区分",
        title: "联想与记忆解释同一信念怎样形成，却未给出公认的主体统一理论",
        summary: "人把平滑相关的变化误认或重构为严格同一；这一诊断能解释想象活动，但休谟后来明确表示其早期说明仍有未解决矛盾。",
        pressure: "不能把‘知觉束’当作休谟已经无代价解决人格同一，也不能从理论困难直接推出日常人格与责任虚假。",
        consequence: "怀疑必须说明理论保留与日常归责如何同时存在。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以联想说明同一信念，同时在附录中保留自我批评" }],
        chapterIds: ["b3-17"],
        graph: { row: 333, lane: 4.2 },
      },
      {
        id: "extraordinary-testimony-conflicts-experience-observation",
        kind: "观察",
        observation: { domain: "知识实践", note: "见证报告的可靠性来自以往对记忆、诚实、误解、利益和传播的经验；异常报告会与更稳定的自然经验发生证据冲突。" },
        title: "见证可能可靠也可能出错，异常报告必须与既有经验强度共同权衡",
        summary: "人依据证人数量、独立性、能力、动机与事件规律判断报告，不会只因一句见证就把所有可能性视为相等。",
        pressure: "把罕见直接当作不可能会循环排除新发现；只看报告数量又会忽视共同来源、群体激情和传播失真。",
        consequence: "观察提出奇迹见证应接受怎样的概率检验。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "把奇迹争论改写为见证与经验之间的证据比较" }],
        chapterIds: ["b3-17"],
        graph: { row: 334, lane: 4.6 },
      },
      {
        id: "how-weigh-miracle-testimony-without-dogmatism",
        kind: "问题",
        title: "怎样检验奇迹见证，既不预先宣布绝不可能，也不让惊奇取代证据？",
        summary: "报告若描述违反高度稳定经验的事件，其可信度必须超过证人误判、欺骗或文本流变的综合可能。",
        pressure: "背景概率的设定、独立见证的累计和何为自然规律都可争论；休谟的具体论证并非没有现代批评。",
        consequence: "信念强度应随整体证据而变化，而非由权威身份或事件奇异度直接决定。",
        participants: [],
        chapterIds: ["b3-17"],
        graph: { row: 335, lane: 4.6 },
      },
      {
        id: "proportion-belief-to-total-evidence",
        kind: "答案",
        answerRole: "区分",
        title: "把见证本身也当作经验材料，并让信念比例服从相互竞争的证据",
        summary: "评估既比较事件规律，也比较证人的可靠性、独立性和传播环境；休谟认为实际宗教奇迹见证未达到压倒反向经验的程度。",
        pressure: "这不是对所有异常事件的演绎禁令；具体概率比较仍可能受样本、偏见和对证言传统的低估影响。",
        consequence: "宗教和形而上学主张同样需要接受有限理解力与证据范围的约束。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以证据权衡批评奇迹见证与自然神学越界" }],
        chapterIds: ["b3-17"],
        graph: { row: 336, lane: 4.6 },
      },
      {
        id: "motives-character-actions-regular-observation",
        kind: "观察",
        observation: { domain: "社会与制度", note: "历史、法律和日常交往都依据动机、性格、处境与行动之间的相对稳定关系进行解释、预测和归责。" },
        title: "人们像依赖自然规律一样，依赖性格、动机与行动之间的稳定联系",
        summary: "承诺、惩罚、教育和历史解释都预设人在相似动机与处境下呈现一定规律，同时允许概率和差异。",
        pressure: "若规律等于强制，责任似乎消失；若行动完全无规律，行动也难以归属于稳定性格。",
        consequence: "观察把因果分析推进到自由与责任。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以人类行动的经验规律重审自由与必然争论" }],
        chapterIds: ["b3-17"],
        graph: { row: 334, lane: 3.3 },
      },
      {
        id: "are-liberty-and-causal-necessity-compatible",
        kind: "问题",
        title: "行动有稳定原因时，自由是否必然被取消？",
        summary: "若必然性只是恒常结合与心理推断，它并不是一条可见锁链；自由也可区别于行动完全没有原因。",
        pressure: "仅重新定义术语不能解决强迫、操纵、成瘾和结构限制；自愿行动仍有程度和条件。",
        consequence: "休谟把自由界定为在没有外在强制时依意志行动的能力。",
        participants: [],
        chapterIds: ["b3-17"],
        graph: { row: 335, lane: 3.3 },
      },
      {
        id: "liberty-as-action-according-to-will",
        kind: "答案",
        answerRole: "区分",
        title: "自由是能够依意志行动，因果必然则是动机、性格与行动的规律联系",
        summary: "一个人若想行动便能行动、想不行动便能不行动，可在休谟意义上自由；其意志有原因并不自动等于被外力强迫。",
        pressure: "这一相容论聚焦行动自由，未完整回答意志形成中的支配、不平等或深层自我问题。",
        consequence: "责任不再依赖无原因选择，而依赖行动是否表达可归属于人的性格和动机。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以行动自由与经验必然的区分提出相容论" }],
        chapterIds: ["b3-17"],
        graph: { row: 336, lane: 3.3 },
      },
      {
        id: "can-caused-actions-ground-responsibility",
        kind: "问题",
        title: "若行动由性格和动机造成，道德责任为何不是被因果解释消解？",
        summary: "归责需要把行为连接到行动者，而不是把它当作与人格无关的偶然爆发；因果联系可能正是这种归属的条件。",
        pressure: "稳定性格本身也有形成原因，惩罚和赞责还须受公平、能力与社会条件限制。",
        consequence: "休谟以行动表现性格及其引发的情感反应保存责任实践。",
        participants: [],
        chapterIds: ["b3-17"],
        graph: { row: 337, lane: 3.3 },
      },
      {
        id: "stable-character-links-action-and-attribution",
        kind: "答案",
        answerRole: "修复",
        title: "行动与较稳定性格的因果联系，使赞责能够指向行动者而非孤立事件",
        summary: "完全随机的行动反而不能表达人格；责任实践依赖人类规律、情感与可改变行为的社会回应。",
        pressure: "这说明归责为何需要规律，却不自动证明任何现行惩罚都正当，也不消除知觉束论留下的跨时主体问题。",
        consequence: "认识、人格与责任支线共同要求一种不越界但仍可生活的怀疑立场。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以性格—行动联系说明必然性与责任可以相容" }],
        chapterIds: ["b3-17"],
        graph: { row: 338, lane: 3.3 },
      },
      {
        id: "can-scepticism-guide-life-without-paralysis",
        kind: "问题",
        title: "因果、自我和外部世界缺少终极证明时，怀疑是否会使科学与生活瘫痪？",
        summary: "彻底论证可能动摇一切经验跨越，但饥饿、交谈、游戏、职业和实验会让人继续形成信念与行动。",
        pressure: "把自然不可抗拒当作真理保证会混淆必然相信与值得相信；把怀疑只当午后情绪又低估其批判力量。",
        consequence: "休谟把怀疑限制为校正独断的工具，并把研究范围收回共同生活和经验。",
        participants: [],
        chapterIds: ["b3-17"],
        graph: { row: 339, lane: 2.2 },
      },
      {
        id: "mitigated-scepticism-limits-and-corrects-inquiry",
        kind: "答案",
        answerRole: "综合",
        title: "自然信念恢复行动，缓和怀疑则让研究保持证据比例、谦逊与范围限制",
        summary: "哲学不能永久压倒习惯和情感，却能比较证据、暴露循环、降低独断，并优先研究与经验和共同生活相称的问题。",
        pressure: "自然主义说明和认识规范之间仍有距离；科学为何具有超出心理习惯的客观普遍性，尚未得到休谟式必然保证。",
        consequence: "第三卷第一部以经验主义的自我限制收束，并把必然性、对象统一和主体条件开放给康德。",
        participants: [{ name: "大卫·休谟", philosopherId: "hume", role: "以共同生活、自然习惯和证据校准形成缓和怀疑" }],
        chapterIds: ["b3-17"],
        graph: { row: 340, lane: 2.2 },
      },
      {
        id: "can-objective-experience-have-necessity-beyond-habit",
        kind: "问题",
        title: "若经验只给出知觉与习惯，科学对象、因果必然和统一主体还能有非心理习惯的条件吗？",
        summary: "休谟说明人怎样由经验形成信念，却没有以演绎方式保证自然齐一，也没有完成持续主体的无循环说明。",
        pressure: "回到理性主义实体会恢复旧越界，停在心理联想又似乎不能解释数学化自然科学所要求的客观统一。",
        consequence: "第三卷第二十章康德将不再从对象中抽取必然性，而追问经验对象得以成立的先天条件。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "将把休谟留下的因果与统一问题转化为经验可能条件的先验问题" }],
        chapterIds: ["b3-17", "b3-20"],
        graph: { row: 341, lane: 2.2 },
      },
    ],
  },
];

export const humeProblemEdges: ProblemEdge[] = [
  { id: "h001", from: "can-spirit-cause-and-self-survive-strict-experience-test", to: "simple-ideas-copy-impressions-source-test", relation: "回应问题", label: "以印象来源检验精神、能力与自我概念", connection: "原书线索" },
  { id: "h002", from: "simple-ideas-copy-impressions-source-test", to: "what-judgments-survive-experience-source-test", relation: "产生问题", label: "概念来源审查开放知识资格区分", connection: "原书线索" },
  { id: "h003", from: "what-judgments-survive-experience-source-test", to: "relations-of-ideas-and-matters-of-fact", relation: "回应问题", label: "区分观念关系与事实问题", connection: "原书线索" },
  { id: "h004", from: "relations-of-ideas-and-matters-of-fact", to: "how-infer-beyond-memory-and-present-sense", relation: "产生问题", label: "偶然事实知识必须说明如何越出当下", connection: "原书线索" },
  { id: "h005", from: "novel-object-effects-not-a-priori-observation", to: "how-infer-beyond-memory-and-present-sense", relation: "提出问题", label: "陌生对象的效果不能由表面性质预读", connection: "原书线索" },
  { id: "h006", from: "how-infer-beyond-memory-and-present-sense", to: "fact-inference-depends-on-cause-effect", relation: "回应问题", label: "以因果关系连接当前证据与缺席事实", connection: "原书线索" },
  { id: "h007", from: "fact-inference-depends-on-cause-effect", to: "can-reason-demonstrate-causal-effect", relation: "产生问题", label: "事实桥梁要求检验其证明根据", connection: "原书线索" },
  { id: "h008", from: "can-reason-demonstrate-causal-effect", to: "causal-effect-not-demonstrable-a-priori", relation: "回应问题", label: "以结果可分别设想排除先验演绎", connection: "原书线索" },
  { id: "h009", from: "causal-effect-not-demonstrable-a-priori", to: "can-experience-prove-future-resembles-past", relation: "产生问题", label: "转而检验经验能否为自身跨越辩护", connection: "原书线索" },
  { id: "h010", from: "can-experience-prove-future-resembles-past", to: "uniformity-defense-circular-or-nondemonstrative", relation: "回应问题", label: "指出齐一性经验辩护的循环", connection: "原书线索" },
  { id: "h011", from: "repetition-produces-expectation-observation", to: "what-impression-supplies-necessary-connection", relation: "提出问题", label: "重复改变期待却未显示外在纽带", connection: "原书线索" },
  { id: "h012", from: "causal-effect-not-demonstrable-a-priori", to: "what-impression-supplies-necessary-connection", relation: "产生问题", label: "先验道路关闭后追问必然观念来源", connection: "原书线索" },
  { id: "h013", from: "what-impression-supplies-necessary-connection", to: "necessary-connection-as-customary-transition", relation: "回应问题", label: "把来源定位到心灵的习惯性过渡", connection: "原书线索" },
  { id: "h014", from: "necessary-connection-as-customary-transition", to: "does-custom-explain-or-justify-induction", relation: "产生问题", label: "心理解释仍需面对认识资格", connection: "后世重构" },
  { id: "h015", from: "uniformity-defense-circular-or-nondemonstrative", to: "does-custom-explain-or-justify-induction", relation: "产生问题", label: "无循环证明使说明与辩护分离", connection: "后世重构" },
  { id: "h016", from: "does-custom-explain-or-justify-induction", to: "custom-naturally-sustains-calibrated-expectation", relation: "回应问题", label: "以自然倾向、概率和经验校准给出有限回答", connection: "历史回应" },
  { id: "h017", from: "simple-ideas-copy-impressions-source-test", to: "what-unifies-person-without-self-impression", relation: "产生问题", label: "来源原则转向恒常自我印象检验", connection: "原书线索" },
  { id: "h018", from: "stream-of-perceptions-no-constant-self-observation", to: "what-unifies-person-without-self-impression", relation: "提出问题", label: "内省只呈现变化知觉而非恒常实体", connection: "原书线索" },
  { id: "h019", from: "what-unifies-person-without-self-impression", to: "self-as-bundle-and-succession-of-perceptions", relation: "回应问题", label: "以知觉束和序列替代简单实体", connection: "原书线索" },
  { id: "h020", from: "self-as-bundle-and-succession-of-perceptions", to: "can-association-explain-one-mind-and-responsibility", relation: "产生问题", label: "知觉复数留下束的统一与边界", connection: "原书线索" },
  { id: "h021", from: "can-association-explain-one-mind-and-responsibility", to: "association-explains-identity-fiction-not-full-unity", relation: "回应问题", label: "以联想说明同一信念并保留理论缺口", connection: "历史回应" },
  { id: "h022", from: "extraordinary-testimony-conflicts-experience-observation", to: "how-weigh-miracle-testimony-without-dogmatism", relation: "提出问题", label: "异常见证与稳定经验形成证据竞争", connection: "原书线索" },
  { id: "h023", from: "how-weigh-miracle-testimony-without-dogmatism", to: "proportion-belief-to-total-evidence", relation: "回应问题", label: "把见证可靠性纳入整体概率权衡", connection: "原书线索" },
  { id: "h024", from: "proportion-belief-to-total-evidence", to: "can-scepticism-guide-life-without-paralysis", relation: "产生问题", label: "证据比例要求一种可实践的怀疑尺度", connection: "本站推演" },
  { id: "h025", from: "motives-character-actions-regular-observation", to: "are-liberty-and-causal-necessity-compatible", relation: "提出问题", label: "人类行动规律使自由与必然需要重定义", connection: "原书线索" },
  { id: "h026", from: "necessary-connection-as-customary-transition", to: "are-liberty-and-causal-necessity-compatible", relation: "产生问题", label: "经验必然概念被应用到人类行动", connection: "原书线索" },
  { id: "h027", from: "are-liberty-and-causal-necessity-compatible", to: "liberty-as-action-according-to-will", relation: "回应问题", label: "区分行动自由与无原因意志", connection: "原书线索" },
  { id: "h028", from: "liberty-as-action-according-to-will", to: "can-caused-actions-ground-responsibility", relation: "产生问题", label: "相容论仍需说明归责条件", connection: "原书线索" },
  { id: "h029", from: "can-caused-actions-ground-responsibility", to: "stable-character-links-action-and-attribution", relation: "回应问题", label: "以性格—行动联系保存归责对象", connection: "原书线索" },
  { id: "h030", from: "custom-naturally-sustains-calibrated-expectation", to: "can-scepticism-guide-life-without-paralysis", relation: "产生问题", label: "自然信念与有限辩护要求实践定位", connection: "原书线索" },
  { id: "h031", from: "association-explains-identity-fiction-not-full-unity", to: "can-scepticism-guide-life-without-paralysis", relation: "产生问题", label: "自我理论缺口不能直接取消日常人格", connection: "本站推演" },
  { id: "h032", from: "stable-character-links-action-and-attribution", to: "can-scepticism-guide-life-without-paralysis", relation: "产生问题", label: "责任实践要求在理论保留中继续判断", connection: "本站推演" },
  { id: "h033", from: "can-scepticism-guide-life-without-paralysis", to: "mitigated-scepticism-limits-and-corrects-inquiry", relation: "回应问题", label: "以自然信念、证据校准和范围限制回应", connection: "原书线索" },
  { id: "h034", from: "mitigated-scepticism-limits-and-corrects-inquiry", to: "can-objective-experience-have-necessity-beyond-habit", relation: "产生问题", label: "缓和怀疑仍留下客观必然与统一条件", connection: "后世重构" },
  { id: "h035", from: "necessary-connection-as-customary-transition", to: "can-objective-experience-have-necessity-beyond-habit", relation: "产生问题", label: "心理期待开放康德的因果条件问题", connection: "历史回应" },
  { id: "h036", from: "uniformity-defense-circular-or-nondemonstrative", to: "can-objective-experience-have-necessity-beyond-habit", relation: "产生问题", label: "归纳难题要求重新说明经验普遍性", connection: "历史回应" },
];

export const humeProblemSources: ProblemMapSource[] = [
  { label: "SEP · David Hume", url: "https://plato.stanford.edu/entries/hume/", note: "用于核对印象与观念、复制原则及其例外、观念关系／事实问题、归纳、因果、自我、自由与缓和怀疑，并保留自然主义和怀疑主义解释之间的争论。" },
  { label: "Hume · An Enquiry Concerning Human Understanding", url: "https://www.gutenberg.org/cache/epub/9662/pg9662-images.html", note: "作为《人类理解研究》公共领域文本入口，用于核对观念来源、事实推理、归纳、必然联系、自由与必然、奇迹见证及缓和怀疑。" },
  { label: "Hume · A Treatise of Human Nature", url: "https://www.gutenberg.org/ebooks/62856", note: "作为《人性论》公共领域文本入口，用于核对知觉束、人格同一、联想原则及附录中的自我批评；不以早期文本自动覆盖休谟后期表述。" },
];
