import type { ProblemEdge, ProblemMapSource, ProblemPhase } from "./problem-map-data";

export const idealismWillProblemPhases: ProblemPhase[] = [
  {
    id: "nineteenth-century-history-system-reaction",
    order: 39,
    label: "历史、体系与反体系",
    title: "革命与工业化使历史成为哲学对象，后康德思想却分裂为体系、反叛和意志诊断",
    question: "康德划定主体与对象、自然与自由的边界后，十九世纪思想应保存这些界限，还是把它们放进历史发展重新解释？",
    transition: "第三卷第二十一章是罗素对十九世纪思想气候的总览，不是一套由所有思想家共享的理论。法国革命、拿破仑战争、民族国家、工业化和科学权威改变了自由的制度条件；德国观念论、浪漫主义、功利主义、社会主义与意志哲学由此形成竞争回应。",
    nodes: [
      {
        id: "post-kantian-reconstructs-divisions-as-development",
        kind: "答案", answerRole: "转向",
        title: "把康德的固定分界改写为主体、对象、自然与自由相互形成的过程",
        summary: "后康德思想家不满足于把物自身留在认识之外，尝试说明思想和世界为何能够属于同一可理解结构。",
        pressure: "从认识条件推进到现实本身的结构需要额外论证；费希特、谢林、浪漫派和黑格尔也没有形成一条无分歧直线。",
        consequence: "问题转为：对立能否从自身限制中发生可论证的转化。",
        participants: [{ name: "格奥尔格·威廉·弗里德里希·黑格尔", philosopherId: "hegel", role: "把康德分界重构为概念与历史的发展问题" }],
        chapterIds: ["b3-20", "b3-21", "b3-22"], graph: { row: 375, lane: 1.8 },
      },
      {
        id: "can-reason-transform-fixed-oppositions-from-within",
        kind: "问题",
        title: "主体／对象、自由／自然等对立能否由自身规定发生转化，而非由外部折中拼合？",
        summary: "若两端绝对分离，思想无法说明它们为何仍互相指涉；若直接宣布统一，又只是跳过康德提出的合法性问题。",
        pressure: "真正的转化必须显示旧规定为何不充分、新规定怎样保存其有效部分。",
        consequence: "这一压力进入黑格尔的规定性否定与扬弃。",
        participants: [{ name: "格奥尔格·威廉·弗里德里希·黑格尔", philosopherId: "hegel", role: "以概念的内在否定回应固定二分" }],
        chapterIds: ["b3-21", "b3-22"], graph: { row: 376, lane: 1.8 },
      },
      {
        id: "revolution-restoration-nationalism-observation",
        kind: "观察",
        observation: {
          domain: "历史变化",
          note: "法国革命、拿破仑战争、复辟和民族运动在一代人内反复改变法律、身份与疆界，使制度不再显得天然恒常。",
          historyLinks: [{ stageId: "revolution-idealism", responseId: "hegel", label: "革命、复辟与历史理性", note: "进入历史概览查看革命自由怎样转成制度与历史方向问题。" }],
        },
        title: "革命、战争、复辟和民族运动使制度在一代人内经历建立、崩溃与重组",
        summary: "自由和平等从哲学原则进入军队、法典和国家组织，也与征服、动员和排除并行。",
        pressure: "事件变化本身不证明历史有方向；胜利者也不能仅凭成功自称代表理性。",
        consequence: "观察提出历史是否能够按自由的学习过程理解。",
        participants: [], chapterIds: ["b3-21"], graph: { row: 375, lane: 0.3 },
      },
      {
        id: "is-history-intelligible-beyond-chronicle-and-fate",
        kind: "问题",
        title: "历史除了事件编年或命运循环，能否呈现制度学习与自由意识的可理解变化？",
        summary: "革命者使用普遍自由语言，后继制度却常只让部分人取得权利；失败和反动也可能暴露抽象原则的不足。",
        pressure: "赋予历史方向容易把偶然、受害者和未实现可能性吸收到胜利叙事。",
        consequence: "十九世纪历史哲学尝试以社会形式而非单个英雄说明自由的发展。",
        participants: [], chapterIds: ["b3-21", "b3-22"], graph: { row: 376, lane: 0.3 },
      },
      {
        id: "history-as-development-of-freedom-consciousness",
        kind: "答案", answerRole: "提出",
        title: "比较制度允许谁被承认为自由者，把历史读作自由意识及其社会形式的变化",
        summary: "历史的可理解性不只来自年代顺序，而来自权利、法律、劳动和政治参与怎样改变自由的实际内容。",
        pressure: "这仍可能把欧洲经验当作唯一尺度，也不能保证较晚制度必定在所有方面更自由。",
        consequence: "必须区分可批判的发展尺度与预定的自动进步。",
        participants: [{ name: "格奥尔格·威廉·弗里德里希·黑格尔", philosopherId: "hegel", role: "以自由意识和客观精神组织世界历史" }],
        chapterIds: ["b3-21", "b3-22"], graph: { row: 377, lane: 0.3 },
      },
      {
        id: "does-historical-direction-guarantee-moral-progress",
        kind: "问题",
        title: "能够重建一种历史方向，是否就证明后来者必然更好、现实胜利必然合理？",
        summary: "制度可以扩大一种自由同时制造新的贫困、殖民和行政支配；历史解释不能把时间先后当作价值证明。",
        pressure: "若完全拒绝比较尺度，压迫与解放只剩不同叙事；若把尺度写成必然终点，又取消现实批判。",
        consequence: "历史方向被限制为可争论的诊断框架，而非自动道德保证。",
        participants: [], chapterIds: ["b3-21", "b3-22"], graph: { row: 378, lane: 0.3 },
      },
      {
        id: "historical-direction-is-diagnostic-not-guarantee",
        kind: "答案", answerRole: "区分",
        title: "以自由是否获得更具体实现评价制度，不把年代、胜利或国家成功当作进步保证",
        summary: "历史哲学可以追踪学习和倒退，也必须允许现实制度因未兑现自身自由承诺而受到批判。",
        pressure: "什么算作具体自由仍需要制度理论，不能只由宏大历史叙事决定。",
        consequence: "问题进入权利、社会依赖和国家之间的中介结构。",
        participants: [], chapterIds: ["b3-21", "b3-22"], graph: { row: 379, lane: 0.3 },
      },
      {
        id: "post-kantian-system-rivalry-observation",
        kind: "观察",
        observation: {
          domain: "知识实践",
          note: "大学、期刊和讲演推动费希特、谢林、黑格尔及浪漫派提出相互竞争的系统；同属德国观念论语境不等于共享一个结论。",
        },
        title: "康德之后，多套体系竞争解释自我、自然、艺术、宗教与历史怎样属于同一整体",
        summary: "思想家共同面对物自身和自由问题，却分别从自我活动、自然生产、审美开放或精神历史出发。",
        pressure: "把他们压成‘康德之后必然走向黑格尔’会删除真实分歧，也把后见之明伪装成逻辑必然。",
        consequence: "观察要求把共享问题与单线师承分开。",
        participants: [], chapterIds: ["b3-21"], graph: { row: 375, lane: 2.9 },
      },
      {
        id: "is-german-idealism-one-continuous-system",
        kind: "问题",
        title: "德国观念论是否是一套由康德自然完成于黑格尔的单一体系？",
        summary: "共同术语掩盖了对物自身、知识界限、自然和绝对者的深刻争论，浪漫主义者还拒绝体系封闭。",
        pressure: "只强调差异会看不见他们都在重建主体能动性和对象性，只讲连续又会制造目的论史。",
        consequence: "较稳妥的组织是共享压力下的分叉方案。",
        participants: [], chapterIds: ["b3-21"], graph: { row: 376, lane: 2.9 },
      },
      {
        id: "post-kantian-programs-share-pressure-not-destiny",
        kind: "答案", answerRole: "区分",
        title: "后康德方案共享克服固定二分的压力，却没有共同命定的终点",
        summary: "费希特强调自我活动，谢林重构自然，浪漫派保留开放形式，黑格尔则追求概念与历史的系统统一。",
        pressure: "黑格尔方案仍须独立证明其方法，而不能借‘时代必然’取得优先权。",
        consequence: "下一步检验辩证法怎样从概念内部推进。",
        participants: [{ name: "德国观念论与早期浪漫主义者", role: "在共享问题下形成多条相互批评的体系与反体系路线" }],
        chapterIds: ["b3-21"], graph: { row: 377, lane: 2.9 },
      },
      {
        id: "industrial-civil-society-observation",
        kind: "观察",
        observation: {
          domain: "社会与制度",
          note: "市场扩张、工业劳动、城市贫困、行政国家和社团生活使个人权利依赖大量并非由单个契约建立的制度条件。",
          historyLinks: [{ stageId: "industrial-modern", responseId: "nietzsche", label: "工业社会与价值分化", note: "进入历史概览查看十九世纪制度变化怎样同时推动历史体系、社会改革和价值批判。" }],
        },
        title: "形式平等扩大时，市场依赖、工业贫困和行政组织也在重塑个人能力",
        summary: "拥有权利不等于实际拥有教育、收入、承认和公共发言条件；私人选择总在家庭、市场和国家中发生。",
        pressure: "制度支持能扩展自由，也能以家长主义、纪律和民族名义压制具体个人。",
        consequence: "观察提出抽象权利是否足够说明现实自由。",
        participants: [], chapterIds: ["b3-21", "b3-22"], graph: { row: 375, lane: 4.4 },
      },
      {
        id: "are-abstract-rights-sufficient-for-social-freedom",
        kind: "问题",
        title: "只保证财产、契约和免受干涉，是否足以让人在社会中真正自由？",
        summary: "形式权利保护个人边界，却不能自行解决贫困、照护、教育和承认依赖，也不能协调私人利益的系统后果。",
        pressure: "增加制度中介必须说明它怎样服务自由，而非由国家替个人规定善。",
        consequence: "十九世纪制度哲学把自由放入家庭、市民社会和公共权力。",
        participants: [], chapterIds: ["b3-21", "b3-22"], graph: { row: 376, lane: 4.4 },
      },
      {
        id: "institutions-mediate-capabilities-recognition-right",
        kind: "答案", answerRole: "综合",
        title: "自由需要权利边界，也需要形成能力、相互承认和纠正系统依赖的制度",
        summary: "家庭、教育、市场组织、社团、法院和政治机构分别提供个人无法单独制造的行动条件。",
        pressure: "制度越被赋予伦理任务，越需要防止代表垄断、国家崇拜和对异议生活的压缩。",
        consequence: "问题转为制度整体何时实现自由、何时以整体之名吞没个人。",
        participants: [{ name: "格奥尔格·威廉·弗里德里希·黑格尔", philosopherId: "hegel", role: "以伦理生活说明自由的制度性条件" }],
        chapterIds: ["b3-21", "b3-22"], graph: { row: 377, lane: 4.4 },
      },
      {
        id: "can-institutional-whole-secure-without-absorbing-individual",
        kind: "问题",
        title: "制度整体怎样扩展个人自由，又不把异议、痛苦和独特生活降为整体工具？",
        summary: "没有共同制度，权利难以执行；若整体拥有不受检验的最高解释权，个人又失去批评它的立足点。",
        pressure: "需要同时检验概念方法、承认关系、经济结构和国家权力。",
        consequence: "这一综合压力进入黑格尔的法哲学，也将激发拜伦和叔本华式反体系回应。",
        participants: [], chapterIds: ["b3-21", "b3-22", "b3-23", "b3-24"], graph: { row: 378, lane: 4.4 },
      },
    ],
  },
  {
    id: "hegel-dialectic-recognition-ethical-life-history",
    order: 40,
    label: "辩证法、承认与制度自由",
    title: "让概念在自身失败中转化，并把个人自由落实为承认、权利与伦理生活",
    question: "若理性不是外加在世界上的固定表格，概念和制度怎样通过自身矛盾发展，又不把现实成功误认作理性？",
    transition: "黑格尔的辩证法不是到处套用‘正题—反题—合题’的固定模板。它要求一种规定因自身内容而显出不足，再由规定性否定和扬弃进入更具体关系；法哲学则把抽象权利、主观道德与家庭—市民社会—国家组织成自由的不同层次。",
    nodes: [
      {
        id: "determinate-negation-transforms-opposition",
        kind: "答案", answerRole: "提出",
        title: "规定在贯彻自身含义时暴露不足，否定因此产生包含旧真理的更具体规定",
        summary: "辩证运动不是从外部给观点配一个反面，而是检验一种概念或生活形态能否按自己的标准成立。",
        pressure: "从局部概念失败到特定新规定的推导常有争议，不能用‘矛盾推动一切’替代逐步论证。",
        consequence: "必须澄清扬弃与教科书三段式之间的差别。",
        participants: [{ name: "格奥尔格·威廉·弗里德里希·黑格尔", philosopherId: "hegel", role: "以规定性否定说明概念的内在发展" }],
        chapterIds: ["b3-22"], graph: { row: 380, lane: 1.8 },
      },
      {
        id: "is-dialectic-fixed-thesis-antithesis-synthesis",
        kind: "问题",
        title: "辩证法是否只是先列正题、再造反题、最后折中成合题的固定公式？",
        summary: "这种口诀易记，却无法说明反面为何由原概念产生，也常把新的具体规定误写成两边平均。",
        pressure: "若没有可重复检验的方法，反对口诀也可能让辩证法变成事后叙事。",
        consequence: "需要把抽象、否定和具体化理解为对象依赖的运动。",
        participants: [], chapterIds: ["b3-22"], graph: { row: 381, lane: 1.8 },
      },
      {
        id: "dialectic-is-immanent-not-fixed-triad",
        kind: "答案", answerRole: "区分",
        title: "辩证法是对规定自身承诺的内在检验，不是可机械套用的正反合口诀",
        summary: "扬弃同时取消旧规定的独占、保存其有效内容并提升到更丰富关系；不同对象的推进方式不能由统一三格预先决定。",
        pressure: "‘内在’检验仍需读者判断哪些承诺真正属于对象、哪种后继规定足以回应失败。",
        consequence: "方法问题进一步转向思想结构与现实结构为何相通。",
        participants: [{ name: "格奥尔格·威廉·弗里德里希·黑格尔", philosopherId: "hegel", role: "以扬弃和具体普遍性反对外在折中" }],
        chapterIds: ["b3-22"],
        sourceRefs: [{ sourceLabel: "SEP · Hegel’s Dialectics", locator: "条目关于规定性否定、扬弃与固定三段式误读的说明", evidenceNote: "用于限制把辩证法压缩成可机械套用的正反合公式。" }],
        graph: { row: 382, lane: 1.8 },
      },
      {
        id: "can-conceptual-dialectic-describe-objective-world",
        kind: "问题",
        title: "概念的内在转化为什么不只是思想游戏，而能够揭示对象和社会现实？",
        summary: "若范畴只属于主体，辩证逻辑无法直接推出世界；若现实本来就是理性结构，又需避免把一切事实神圣化。",
        pressure: "从可理解性到现实与思想同构，是黑格尔体系最有力量也最受争议的跨越。",
        consequence: "客观观念论把理性理解为思想与世界共同的关系结构。",
        participants: [], chapterIds: ["b3-22"], graph: { row: 383, lane: 1.8 },
      },
      {
        id: "objective-idealism-reason-immanent-in-world",
        kind: "答案", answerRole: "综合",
        title: "理性不是私人心灵投射，而是对象、行动和制度能够成为可理解整体的内在关系",
        summary: "主体可以认识世界，因为两者并非绝对异质；概念工作试图把现实中已经起作用的普遍关系说清。",
        pressure: "这一立场不等于每个现实细节都合理，体系的存在论论证也远非学界共识。",
        consequence: "抽象认识主体必须通过与其他主体的承认关系形成。",
        participants: [{ name: "格奥尔格·威廉·弗里德里希·黑格尔", philosopherId: "hegel", role: "把理性理解为主体与对象共同的结构" }],
        chapterIds: ["b3-22"], graph: { row: 384, lane: 1.8 },
      },
      {
        id: "self-consciousness-seeks-recognition-observation",
        kind: "观察",
        observation: { domain: "个体体验", note: "自我声称独立时仍需要他人理解其行动、权利和身份；单方面自信不能建立公共有效的自我地位。" },
        title: "自我只有在他人回应中才能稳定地把自己理解为有地位、有能力的主体",
        summary: "语言、承诺、权利和人格都要求他人承认；被完全忽视或物化会破坏行动者的自我关系。",
        pressure: "依赖承认不表示他人的任何评价都正确，也不要求个体服从既有共同体。",
        consequence: "观察提出自我意识为何必须通过相互承认。",
        participants: [], chapterIds: ["b3-22"], graph: { row: 380, lane: 0.3 },
      },
      {
        id: "why-self-consciousness-needs-mutual-recognition",
        kind: "问题",
        title: "一个主体为何不能独自确认自由，而必须从另一个同样自由的主体获得承认？",
        summary: "来自被当作物件者的服从无法证明我的自由；只有能自行判断者的承认才具有规范意义。",
        pressure: "主体都要求独立时，承认关系可能先表现为斗争、支配和不对称。",
        consequence: "承认把自由从内心确信推进到主体间制度。",
        participants: [], chapterIds: ["b3-22"], graph: { row: 381, lane: 0.3 },
      },
      {
        id: "mutual-recognition-constitutes-social-selfhood",
        kind: "答案", answerRole: "提出",
        title: "自由主体通过相互承认形成可持续的自我意识、权利和共同规范",
        summary: "我承认他人有能力回应理由，才能从其承认中确认自己的地位；承认因此必须原则上双向。",
        pressure: "现实承认受阶级、性别、种族和劳动分工扭曲，抽象互惠不能掩盖权力差异。",
        consequence: "问题转向支配关系为何不能提供稳定承认。",
        participants: [{ name: "格奥尔格·威廉·弗里德里希·黑格尔", philosopherId: "hegel", role: "以承认说明自我意识的社会形成" }],
        chapterIds: ["b3-22"], graph: { row: 382, lane: 0.3 },
      },
      {
        id: "can-domination-secure-recognition",
        kind: "问题",
        title: "主人迫使他人服从时，能否从这种服从中获得真正承认？",
        summary: "主人需要被承认为独立者，却把承认者降为不独立工具；承认来源因而被自己破坏。",
        pressure: "主奴段落是意识形态的逻辑图式，不能直接等同某一具体奴隶制度的完整历史。",
        consequence: "不对称承认因自身目标而不稳定，劳动也改变依赖关系。",
        participants: [], chapterIds: ["b3-22"], graph: { row: 383, lane: 0.3 },
      },
      {
        id: "asymmetric-recognition-undermines-itself",
        kind: "答案", answerRole: "反驳",
        title: "把他人降为工具会同时取消其承认的价值，支配无法完成主人追求的独立",
        summary: "依赖他人劳动而否认其主体性形成结构矛盾；被支配者在劳动和对象改造中发展新的自我关系。",
        pressure: "这不保证现实支配会自动终结，也不能把受苦浪漫化为必然解放。",
        consequence: "相互承认需要获得法律和制度形态，而非停留在两人关系。",
        participants: [{ name: "格奥尔格·威廉·弗里德里希·黑格尔", philosopherId: "hegel", role: "以不对称承认的失败推进自由的社会条件" }],
        chapterIds: ["b3-22"], graph: { row: 384, lane: 0.3 },
      },
      {
        id: "market-family-state-dependence-observation",
        kind: "观察",
        observation: { domain: "社会与制度", note: "现代个人同时是家庭成员、财产与契约主体、职业劳动者和公民；每种角色提供自由条件，也制造不同义务与依赖。" },
        title: "个人自由实际分布在家庭、市场、社团、法院和政治国家等多种制度中",
        summary: "抽象个人在现实中必须被抚育、谋生、交换、组织和代表；不同制度不能由一次契约完全解释。",
        pressure: "制度分工也会固化父权、贫困和排除，存在并不等于正当。",
        consequence: "观察要求把权利和良心推进到伦理生活。",
        participants: [], chapterIds: ["b3-22"], graph: { row: 380, lane: 3.5 },
      },
      {
        id: "why-abstract-right-and-private-conscience-insufficient",
        kind: "问题",
        title: "抽象权利和个人善意为什么仍不足以协调现代社会的相互依赖？",
        summary: "权利界定外在边界，良心评价动机，但复杂后果、公共资源和利益冲突需要稳定的共同规则。",
        pressure: "诉诸共同伦理不能让传统习俗免于普遍自由与异议检验。",
        consequence: "黑格尔以伦理生活连接个人认同和客观制度。",
        participants: [], chapterIds: ["b3-22"], graph: { row: 381, lane: 3.5 },
      },
      {
        id: "ethical-life-mediates-family-civil-society-state",
        kind: "答案", answerRole: "综合",
        title: "伦理生活让自由分别在家庭照护、市民社会特殊利益和政治共同规则中获得现实形式",
        summary: "三层不是把个人献给国家的阶梯，而是处理直接共同性、差异化需求和普遍公共权力的相互限制。",
        pressure: "黑格尔对家庭性别角色、君主制和民族国家的具体安排带有时代局限。",
        consequence: "必须区分‘现实的即合理’与对任何现存国家的服从。",
        participants: [{ name: "格奥尔格·威廉·弗里德里希·黑格尔", philosopherId: "hegel", role: "以客观精神和伦理生活说明制度自由" }],
        chapterIds: ["b3-22"], graph: { row: 382, lane: 3.5 },
      },
      {
        id: "does-actual-rational-mean-every-state-is-right",
        kind: "问题",
        title: "‘现实的即合理的’是否意味着凡存在的国家、法律和胜利者都已正当？",
        summary: "德文 Wirklichkeit 指充分实现概念的现实性，不只是碰巧存在；但这一差别仍可能被政治保守主义利用。",
        pressure: "若只有体系解释者能宣布何者真正现实，批判标准会变得不透明。",
        consequence: "合理性必须成为检验制度是否实现自由的标准，而非事实认证章。",
        participants: [], chapterIds: ["b3-22"], graph: { row: 383, lane: 3.5 },
      },
      {
        id: "actuality-is-critical-standard-not-fact-worship",
        kind: "答案", answerRole: "区分",
        title: "合理现实性要求制度兑现自由概念，不是给一切既存权力盖章",
        summary: "制度若系统破坏承认、权利和公共参与，就因未实现自己的自由主张而可被批判。",
        pressure: "黑格尔对普鲁士制度的具体评价仍可受批评，概念区分不能抹去文本的保守部分。",
        consequence: "检验转入市民社会自身产生的贫困与排除。",
        participants: [], chapterIds: ["b3-22"], graph: { row: 384, lane: 3.5 },
      },
      {
        id: "can-civil-society-correct-poverty-it-produces",
        kind: "问题",
        title: "市场相互依赖不断产生财富与贫困时，市民社会能否靠自身机制实现普遍自由？",
        summary: "分工提高生产和选择，也使个人受价格、失业和无人负责的系统后果支配。",
        pressure: "慈善可能维持依赖，单纯增长又可能扩大过剩和贫困；黑格尔本人承认这一难题没有轻易解法。",
        consequence: "社团、公共监管和福利中介被用于限制市场的无中介后果。",
        participants: [], chapterIds: ["b3-22"], graph: { row: 385, lane: 3.5 },
      },
      {
        id: "institutions-contain-market-without-abolishing-particularity",
        kind: "答案", answerRole: "修复",
        title: "以社团、公共权力和社会保障纠正市场依赖，同时保留职业与私人选择",
        summary: "制度任务不是取消一切特殊利益，而是让它们在可承认的普遍规则下获得代表、保障和责任。",
        pressure: "具体方案可能不足以解决结构性贫困，也不能证明国家中介天然无支配。",
        consequence: "历史整体的合理性必须接受被排除者和未调和冲突的反证。",
        participants: [{ name: "格奥尔格·威廉·弗里德里希·黑格尔", philosopherId: "hegel", role: "诊断市民社会贫困并寻求制度中介" }],
        chapterIds: ["b3-22"], graph: { row: 386, lane: 3.5 },
      },
      {
        id: "does-world-history-redeem-suffering-and-exclusion",
        kind: "问题",
        title: "把世界历史理解为自由发展，会不会把战争、殖民和被排除者降为整体进步的代价？",
        summary: "宏大叙事能够连接制度变化，却容易只让成功国家发言，并把不可补偿损失解释成理性手段。",
        pressure: "拒绝任何整体会失去跨制度比较，接受封闭整体则可能让受害经验失去否决力。",
        consequence: "需要把整体理解保持为可受反例修订的解释，而非历史无罪证明。",
        participants: [], chapterIds: ["b3-21", "b3-22"], graph: { row: 387, lane: 2.7 },
      },
      {
        id: "totality-must-remain-answerable-to-unreconciled-lives",
        kind: "答案", answerRole: "修复",
        title: "整体解释只有持续回应未获承认的生命与制度失败，才可能是自由理论而非胜利神学",
        summary: "黑格尔工具可用于揭示制度自我矛盾；它不能让任何历史结果仅因进入体系就获得正当性。",
        pressure: "这一修复带有后世批判理论色彩，不等于罗素或黑格尔文本已经完整接受它。",
        consequence: "个体激情和不可替代生命将以拜伦式反叛直接挑战体系调和。",
        participants: [], chapterIds: ["b3-22", "b3-23"], graph: { row: 388, lane: 2.7 },
      },
      {
        id: "can-rebellion-protect-individual-without-glorifying-power",
        kind: "问题",
        title: "反叛能否保护被整体压缩的个体，又不把魅力、危险和支配本身美化为自由？",
        summary: "体系的制度语言可能听不见羞辱和激情，个人英雄语言又可能让普通幸福和共同责任消失。",
        pressure: "必须区分揭露虚伪的文化反叛、实际政治自由和以强者姿态支配他人。",
        consequence: "第三卷第二十三章以拜伦及拜伦式英雄检验浪漫个人主义。",
        participants: [{ name: "乔治·戈登·拜伦", philosopherId: "byron", role: "以文学人格和政治行动把个体反叛推到欧洲公共文化中心" }],
        chapterIds: ["b3-22", "b3-23"], graph: { row: 389, lane: 2.7 },
      },
    ],
  },
  {
    id: "byron-romantic-rebellion-individuality",
    order: 41,
    label: "拜伦式反叛与个人自由",
    title: "让诗人、角色和公共行动共同揭露社会虚伪，也检验魅力型反叛的责任边界",
    question: "文学人格如何成为哲学史中的自由问题，而不被误写成一套严密体系？",
    transition: "罗素为拜伦设专章，重点不是把诗人伪装成系统哲学家，而是追踪‘拜伦式英雄’怎样把骄傲、孤独、罪感、反习俗和政治自由变成跨欧洲的文化类型。作品中的叙述者、角色、作者生平与后世神话必须分开。",
    nodes: [
      {
        id: "byronic-figure-exposes-conformity-without-system",
        kind: "答案", answerRole: "转向",
        title: "拜伦式人物以局外人、讽刺和自我冲突暴露礼俗虚伪，不以封闭理论取代它",
        summary: "文化形象能让羞辱、欲望和反抗获得公共语言，其哲学功能在提出生活类型和价值冲突。",
        pressure: "感染力、名声和真实感不能直接证明角色的选择正确，也不能把作者与人物合并。",
        consequence: "需要检验反叛人格怎样形成、又怎样被公众消费。",
        participants: [{ name: "乔治·戈登·拜伦", philosopherId: "byron", role: "以诗歌、讽刺和公共形象形成反叛个体类型" }],
        chapterIds: ["b3-23"], graph: { row: 390, lane: 2.7 },
      },
      {
        id: "celebrity-scandal-authorship-observation",
        kind: "观察",
        observation: { domain: "社会与制度", note: "大众出版、评论、沙龙与丑闻新闻把诗人生活变成作品接受的一部分；公众同时消费反叛并惩罚越界。" },
        title: "拜伦的作品角色、贵族身份、丑闻与流亡在大众传播中互相塑造",
        summary: "读者常把恰尔德·哈罗尔德、曼弗雷德或唐璜与作者本人重叠，反叛人格由作品和媒体共同生产。",
        pressure: "传记解释能说明接受史，却不能把作品还原为作者性格或把传闻当作哲学论证。",
        consequence: "观察提出自我神话是否仍能保留批判距离。",
        participants: [{ name: "乔治·戈登·拜伦", philosopherId: "byron", role: "成为作品、生活与公共名声交叠的浪漫主义人物" }],
        chapterIds: ["b3-23"], graph: { row: 390, lane: 0.5 },
      },
      {
        id: "can-self-mythology-preserve-self-critique",
        kind: "问题",
        title: "以自身生活塑造反叛神话时，作者还能否讽刺和拆解这个神话？",
        summary: "自我表演能拒绝社会强加身份，也能把复杂生活包装成魅力品牌并逃避责任。",
        pressure: "若作品只有坦白，角色就被传记吞没；若全是面具，真实政治承诺又难以判断。",
        consequence: "拜伦的多声部、讽刺和自我打断让人格保持不稳定。",
        participants: [], chapterIds: ["b3-23"], graph: { row: 391, lane: 0.5 },
      },
      {
        id: "irony-splits-author-hero-public-image",
        kind: "答案", answerRole: "区分",
        title: "讽刺和多重叙述声音不断拆开作者、英雄与公众期待，使反叛形象不能完全封闭",
        summary: "《唐璜》等作品既使用浪漫姿态又嘲弄它，让读者看见英雄的自欺、欲望与社会交易。",
        pressure: "自我讽刺可以增加复杂性，也可能成为不承担立场的逃逸手段。",
        consequence: "真实性不再等于毫无反思地表达最强激情。",
        participants: [{ name: "乔治·戈登·拜伦", philosopherId: "byron", role: "用讽刺抵消拜伦式英雄的自我绝对化" }],
        chapterIds: ["b3-23"], graph: { row: 392, lane: 0.5 },
      },
      {
        id: "does-transgression-prove-authentic-freedom",
        kind: "问题",
        title: "违反习俗、冒险或自我毁灭本身，是否足以证明一个人真实而自由？",
        summary: "习俗会维护双重标准，越界因此可能揭露压迫；但冲动也会伤害他人并受新的英雄规范驱使。",
        pressure: "把不服从一律赞为自由，会让最有资源承担后果者垄断‘真实’姿态。",
        consequence: "反习俗的否定功能必须与行动后果和共同责任分开评价。",
        participants: [], chapterIds: ["b3-23"], graph: { row: 393, lane: 0.5 },
      },
      {
        id: "transgression-reveals-hypocrisy-not-automatic-freedom",
        kind: "答案", answerRole: "区分",
        title: "越界可以揭露虚伪和不平等，却不因危险、激情或少数性自动成为自由",
        summary: "反叛的价值取决于它打开何种生活可能、怎样对待他人，而非只看行动者是否足够强烈。",
        pressure: "共同标准若由既有社会制定，又可能重新驯化真正异议。",
        consequence: "问题转向公共自由是否能由魅力型个人代表。",
        participants: [], chapterIds: ["b3-23"], graph: { row: 394, lane: 0.5 },
      },
      {
        id: "romantic-hero-audience-observation",
        kind: "观察",
        observation: { domain: "个体体验", note: "拜伦式英雄以骄傲、忧郁、隐秘罪感、流亡和反抗吸引读者；受众可以借角色想象拒绝自身受限处境。" },
        title: "孤独、危险而有魅力的反叛英雄让受众体验一种替代性自由",
        summary: "文学角色扩展想象，却也容易把自由与卓越少数、男性支配和他人牺牲绑定。",
        pressure: "审美认同不是实际政治行动，英雄的独特性也难以普遍化为共同制度。",
        consequence: "观察提出魅力和英雄崇拜是否会复制支配。",
        participants: [], chapterIds: ["b3-23"], graph: { row: 390, lane: 3.9 },
      },
      {
        id: "can-charismatic-hero-represent-public-liberty",
        kind: "问题",
        title: "魅力型反叛者能否代表公共自由，还是会让他人只作为其伟大人格的背景？",
        summary: "英雄可动员反压迫情感，却常把耐心组织、照护和普通人的安全写成平庸。",
        pressure: "否认个人勇气会看不见政治行动需要承担风险，神化勇气则会取消平等判断。",
        consequence: "必须把象征动员与可问责的公共方案分开。",
        participants: [], chapterIds: ["b3-23"], graph: { row: 391, lane: 3.9 },
      },
      {
        id: "charisma-mobilizes-but-cannot-legitimate-rule",
        kind: "答案", answerRole: "区分",
        title: "魅力能够动员反抗和跨国声援，却不能单独产生代表权或统治正当性",
        summary: "诗人可以让远方压迫变得可感，但共同决策仍需要平等参与、持续组织和责任机制。",
        pressure: "文化影响与政治效果很难精确分离，后世也会选择性塑造英雄形象。",
        consequence: "拜伦实际介入自由政治成为检验，而非只看角色姿态。",
        participants: [], chapterIds: ["b3-23"], graph: { row: 392, lane: 3.9 },
      },
      {
        id: "byron-political-solidarity-observation",
        kind: "观察",
        observation: {
          domain: "历史变化",
          note: "拜伦在上议院反对把织机破坏定为死罪，参与意大利自由派网络，并投入希腊独立事业；这些行动与英雄神话相关但不能互相替代。",
          historyLinks: [{ stageId: "revolution-idealism", responseId: "romantics", label: "浪漫反叛与民族自由", note: "进入历史概览查看拜伦式个人主义怎样进入革命后的自由运动。" }],
        },
        title: "拜伦把文学声望、金钱和个人风险投入工人辩护与跨国自由事业",
        summary: "其公共行动显示浪漫反叛不只有私人任性，也能转成对受压迫者的声援和组织资源。",
        pressure: "希腊独立等运动同时包含民族排除和大国政治，不能只写成诗人英雄史。",
        consequence: "观察要求从生活姿态转向行动承担的实际关系。",
        participants: [{ name: "乔治·戈登·拜伦", philosopherId: "byron", role: "把反叛人格部分转化为自由派政治行动" }],
        chapterIds: ["b3-23"], graph: { row: 393, lane: 3.9 },
      },
      {
        id: "can-poetic-solidarity-become-responsible-action",
        kind: "问题",
        title: "诗性同情和自由激情怎样成为对他人负责的行动，而非借他人斗争完成自我神话？",
        summary: "投入资源和风险可以支持运动，也可能让名人遮蔽当地行动者与复杂目标。",
        pressure: "动机并非唯一标准；需要同时看合作方式、后果和对他人主体性的承认。",
        consequence: "负责任反叛把个体勇气与具体团结相连。",
        participants: [], chapterIds: ["b3-23"], graph: { row: 394, lane: 3.9 },
      },
      {
        id: "responsible-rebellion-links-courage-solidarity-limits",
        kind: "答案", answerRole: "修复",
        title: "反叛只有在承认他人目标、承担后果并接受限度时，才从英雄姿态转为政治团结",
        summary: "个人名声可以贡献资源和关注，但不能替代共同体自己的判断与组织。",
        pressure: "拜伦生平同时保留慷慨、支配和自我戏剧化，不能整理成无矛盾道德榜样。",
        consequence: "反叛的内部矛盾把问题推向欲望本身是否能带来自由。",
        participants: [], chapterIds: ["b3-23"], graph: { row: 395, lane: 3.9 },
      },
      {
        id: "does-intensified-desire-liberate-or-enslave",
        kind: "问题",
        title: "若反叛以更强烈欲望和自我扩张对抗规训，欲望会解放主体，还是制造新的奴役？",
        summary: "压抑欲望可能服务虚伪秩序，但欲望满足短暂、相互冲突，也会让行动者依赖对象和他人。",
        pressure: "不能从某些破坏性欲望直接推出一切生命冲动都应被否定。",
        consequence: "第三卷第二十四章叔本华把欲望—匮乏结构扩展为世界的意志。",
        participants: [{ name: "阿图尔·叔本华", philosopherId: "schopenhauer", role: "将欲望冲突重构为意志、痛苦与解脱问题" }],
        chapterIds: ["b3-23", "b3-24"], graph: { row: 396, lane: 2.7 },
      },
    ],
  },
  {
    id: "schopenhauer-representation-will-suffering-release",
    order: 42,
    label: "表象、意志与痛苦",
    title: "由身体的双重经验把物自身解释为盲目意志，再以审美、同情和禁欲寻找松脱",
    question: "若理性历史与浪漫欲望都不能消除匮乏，世界的内在动力是否就是无目的追求？",
    transition: "叔本华继承康德的现象条件，却越过康德界限，把身体从外部所见的表象和内部所感的意愿视为同一现实的两面，并类推世界内在本性为意志。这一大胆形而上学及其对印度传统的吸收都须标明争议。",
    nodes: [
      {
        id: "desire-reveals-will-before-rational-purpose",
        kind: "答案", answerRole: "转向",
        title: "欲望先以匮乏、冲动和身体行动出现，理性目的往往只是意志寻找对象的形式",
        summary: "主体并非先完成理性判断再产生全部欲求；许多行动从身体倾向和不透明动机出发。",
        pressure: "理性不总是主宰，不等于理由从不起因果或规范作用。",
        consequence: "身体成为从表象世界接近内在意愿的特殊入口。",
        participants: [{ name: "阿图尔·叔本华", philosopherId: "schopenhauer", role: "以身体意愿回应浪漫欲望的自由难题" }],
        chapterIds: ["b3-24"], graph: { row: 397, lane: 2.7 },
      },
      {
        id: "body-double-aspect-observation",
        kind: "观察",
        observation: { domain: "个体体验", note: "自己的手臂既可像其他对象一样被观看，也可在行动中被直接体验为欲求与用力；两种把握针对同一身体。" },
        title: "身体既作为时空中的对象被观察，也从内部被体验为意愿、努力和疼痛",
        summary: "外部知识给出因果表象，第一人称行动则不像观看一个陌生物体那样中介。",
        pressure: "特殊的身体自知是否真能越过表象条件，还是仍属于经验意识，存在竞争解释。",
        consequence: "观察提出身体能否提供物自身的线索。",
        participants: [], chapterIds: ["b3-24"], graph: { row: 398, lane: 0.4 },
      },
      {
        id: "can-body-give-access-to-thing-in-itself",
        kind: "问题",
        title: "身体的内部意愿经验能否让主体认识康德认为不可知的物自身？",
        summary: "同一身体有外在表象和内在意愿两面，似乎提供其他对象缺少的双重入口。",
        pressure: "从‘不同认识方式’到‘意志就是物自身’并非无缝推导，内部经验仍有时间性和心理形式。",
        consequence: "叔本华把意志作为世界的内在方面，而非一个经验对象。",
        participants: [], chapterIds: ["b3-24"], graph: { row: 399, lane: 0.4 },
      },
      {
        id: "world-double-aspect-representation-and-will",
        kind: "答案", answerRole: "提出",
        title: "世界对认识主体呈现为表象，从内部类比则被解释为无目的的意志",
        summary: "空间、时间和因果组织对象多样；意志被设为这些个体化形式之前的同一内在冲动。",
        pressure: "把意志命名为统一物自身可能重新犯康德所禁止的超经验断言。",
        consequence: "必须说明为何能从人的身体推广到自然整体。",
        participants: [{ name: "阿图尔·叔本华", philosopherId: "schopenhauer", role: "建立作为表象与作为意志的双重世界" }],
        chapterIds: ["b3-24"], graph: { row: 400, lane: 0.4 },
      },
      {
        id: "can-human-will-be-extended-to-all-nature",
        kind: "问题",
        title: "人的身体意愿为何能类推到动物、植物乃至无机自然的内在本性？",
        summary: "自然呈现竞争、生长和力的持续作用，但这些现象也可由非心理物理机制解释。",
        pressure: "拟人化自然会把目的和欲望倒灌给无意识过程，纯机械解释又可能遗漏内在行动体验。",
        consequence: "意志被扩展为非人格、非理性目的的普遍趋力。",
        participants: [], chapterIds: ["b3-24"], graph: { row: 401, lane: 0.4 },
      },
      {
        id: "will-as-nonpersonal-striving-across-nature",
        kind: "答案", answerRole: "转向",
        title: "把意志理解为非人格的盲目趋力，而非自然中处处存在有意识目的",
        summary: "生命欲求是最清楚表现，物理力和有机竞争则被解释为同一内在活动的不同客体化。",
        pressure: "这种类推具有统一想象力，却缺乏独立经验检验，现代读者不能把它当作物理学结论。",
        consequence: "若意志没有终极目的，满足就难以终止追求。",
        participants: [{ name: "阿图尔·叔本华", philosopherId: "schopenhauer", role: "把意志去人格化并扩展为自然内在趋力" }],
        chapterIds: ["b3-24"], graph: { row: 402, lane: 0.4 },
      },
      {
        id: "striving-satisfaction-boredom-observation",
        kind: "观察",
        observation: { domain: "个体体验", note: "欲望未满足时表现为缺乏和痛苦，满足后快感短暂，新的欲望或无聊又出现；这一循环在日常生活中反复可见。" },
        title: "欲望在匮乏、短暂满足、新欲望与无聊之间反复循环",
        summary: "某个目标实现会解除局部压力，却很少让欲求能力整体停止；生活继续寻找新的差异和刺激。",
        pressure: "反复欲望并不证明所有生活负价值，创造、关系和活动也可在追求本身具有意义。",
        consequence: "观察提出痛苦是偶然挫折还是意志结构。",
        participants: [], chapterIds: ["b3-24"], graph: { row: 398, lane: 2.7 },
      },
      {
        id: "is-suffering-accident-or-structure-of-willing",
        kind: "问题",
        title: "痛苦主要来自可修复的坏条件，还是来自一切意愿都以缺乏为起点的结构？",
        summary: "制度改善能减少疾病、贫困和暴力，却不能让有限生命永远不失去、不冲突或不再欲求。",
        pressure: "把痛苦形而上学化可能轻视可避免的不公，把它全归制度又忽略有限性和欲望冲突。",
        consequence: "叔本华把持续追求视为悲观主义的本体根据。",
        participants: [], chapterIds: ["b3-24"], graph: { row: 399, lane: 2.7 },
      },
      {
        id: "pessimism-from-endless-willing",
        kind: "答案", answerRole: "提出",
        title: "无终极目的的意志不断再生产匮乏、竞争和损失，使痛苦具有结构性",
        summary: "快乐多是压力的暂时解除，个体化又让同一意志在生命之间互相争夺。",
        pressure: "由痛苦普遍存在到‘生命不值得’的评价仍需价值前提，不能仅凭心理观察完成。",
        consequence: "问题转为悲观主义是经验比较、形而上学判断还是实践诊断。",
        participants: [{ name: "阿图尔·叔本华", philosopherId: "schopenhauer", role: "由无尽意愿建立哲学悲观主义" }],
        chapterIds: ["b3-24"], graph: { row: 400, lane: 2.7 },
      },
      {
        id: "does-pessimism-follow-without-value-premise",
        kind: "问题",
        title: "从生命包含无尽欲求和痛苦，能否直接推出生命整体不值得肯定？",
        summary: "同一追求可被解释为奴役，也可被解释为活动、创造与关系的条件。",
        pressure: "悲观结论需要说明为何无痛或静止优先于具有风险和痛苦的积极生命。",
        consequence: "叔本华的诊断保持挑战力，但结论不能伪装成纯经验事实。",
        participants: [], chapterIds: ["b3-24"], graph: { row: 401, lane: 2.7 },
      },
      {
        id: "pessimism-is-metaphysical-evaluation-not-measurement",
        kind: "答案", answerRole: "区分",
        title: "悲观主义是关于意志结构和生命价值的形而上学评价，不是把快乐痛苦简单计数后的科学结论",
        summary: "它迫使乐观进步论说明痛苦为何可接受，却也必须接受肯定生命方案的反驳。",
        pressure: "若只争论世界总量，容易忽略当下怎样减少具体痛苦的伦理任务。",
        consequence: "实践问题转为主体能否暂时或持续松脱意志支配。",
        participants: [], chapterIds: ["b3-24"], graph: { row: 402, lane: 2.7 },
      },
      {
        id: "how-can-subject-loosen-service-to-will",
        kind: "问题",
        title: "若意志贯穿主体和自然，人怎样可能不再完全按匮乏、竞争和自我保存行动？",
        summary: "理性通常为欲望选择手段，不能单靠更精确计算解除欲望结构。",
        pressure: "彻底脱离意志似乎与任何有目的行动矛盾，需要区分暂时静观、伦理转向和极端禁欲。",
        consequence: "叔本华提出审美、同情与否定意志三条不同强度的松脱路线。",
        participants: [], chapterIds: ["b3-24"], graph: { row: 403, lane: 2.7 },
      },
      {
        id: "aesthetic-contemplation-suspends-personal-striving",
        kind: "答案", answerRole: "提出",
        title: "审美静观暂时停止对象与私人欲望的工具关系，使主体成为无利害的观看者",
        summary: "艺术把注意从‘它对我有什么用’转向形式、关系和普遍经验，音乐尤其直接表现意志运动。",
        pressure: "短暂解脱依赖文化和闲暇条件，也不能自动改变造成他人痛苦的制度。",
        consequence: "无利害观看提供非利己态度的体验，但尚非完整伦理。",
        participants: [{ name: "阿图尔·叔本华", philosopherId: "schopenhauer", role: "以审美经验说明暂时无意志状态" }],
        chapterIds: ["b3-24"], graph: { row: 404, lane: 1.2 },
      },
      {
        id: "compassion-crosses-principium-individuationis",
        kind: "答案", answerRole: "提出",
        title: "同情让行动者不再把他者痛苦视为完全外在，从而限制利己伤害",
        summary: "个体分离属于表象形式；在他人受苦中直觉共同意志，能够产生不以奖惩为条件的伦理动机。",
        pressure: "共同本体不必是同情的唯一根据，同情也会偏私、疲劳或保留不平等照护关系。",
        consequence: "伦理松脱比审美更直接减少痛苦，却仍处在行动世界。",
        participants: [{ name: "阿图尔·叔本华", philosopherId: "schopenhauer", role: "以同情建立非利己伦理" }],
        chapterIds: ["b3-24"], graph: { row: 404, lane: 2.7 },
      },
      {
        id: "ascetic-negation-reduces-will-to-life",
        kind: "答案", answerRole: "提出",
        title: "禁欲通过减少欲求、占有与个体执著，追求对生命意志更持久的否定",
        summary: "圣者不以更大满足结束痛苦，而以不再强化欲望循环和个体对立寻求安静。",
        pressure: "否定意志可能贬低身体、关系和积极改变，也难解释一个意志主体怎样意愿停止意志。",
        consequence: "三条路线共同开放‘否定生命是否仍是虚无主义’的反驳。",
        participants: [{ name: "阿图尔·叔本华", philosopherId: "schopenhauer", role: "以禁欲和否定意志提出最彻底解脱" }],
        chapterIds: ["b3-24"], graph: { row: 404, lane: 4.2 },
      },
      {
        id: "is-schopenhauer-equivalent-to-buddhism-hinduism",
        kind: "问题",
        title: "叔本华使用印度文本、同情和禁欲，是否就等同佛教或吠檀多传统？",
        summary: "他从当时欧洲可得译本吸收轮回、摩耶和解脱词汇，却嵌入自己的康德式表象—意志体系。",
        pressure: "相似主题不能取消无我、业、梵、修行共同体和文本传统之间的重大差异。",
        consequence: "现代校正把这种关系写成选择性接受和重构。",
        participants: [], chapterIds: ["b3-24"], graph: { row: 405, lane: 4.2 },
      },
      {
        id: "asian-thought-selectively-reconstructed-in-european-system",
        kind: "答案", answerRole: "区分",
        title: "印度思想为叔本华提供反基督教与解脱资源，却经过有限译介并被重构进欧洲形而上学",
        summary: "应承认跨传统影响，同时避免用‘西方版佛教’抹平各传统内部概念和实践。",
        pressure: "校正接受史不能否认这些阅读确实改变了欧洲哲学问题。",
        consequence: "剩余压力是：面对痛苦，否定是否比肯定更有理由。",
        participants: [], chapterIds: ["b3-24"], graph: { row: 406, lane: 4.2 },
      },
      {
        id: "does-negating-will-repeat-nihilism",
        kind: "问题",
        title: "以否定意志回应痛苦，是否把不再欲求和退出生命偷偷设为最高价值？",
        summary: "解脱路线减少伤害，却也可能把力量、创造、身体和承担痛苦的能力解释为需要克服的错误。",
        pressure: "反对禁欲不能退化为赞美残酷或要求受苦者肯定一切遭遇。",
        consequence: "第三卷第二十五章尼采把悲观主义转成虚无主义与生命肯定的价值问题。",
        participants: [{ name: "弗里德里希·尼采", philosopherId: "nietzsche", role: "由早期敬仰转向批判叔本华的生命否定" }],
        chapterIds: ["b3-24", "b3-25"], graph: { row: 407, lane: 2.7 },
      },
    ],
  },
  {
    id: "nietzsche-genealogy-nihilism-revaluation",
    order: 43,
    label: "谱系、虚无主义与价值重估",
    title: "追问价值由何种生命、情感与权力生成，再以肯定和自我克服回应旧基础崩塌",
    question: "传统道德失去超越根据后，怎样批判其历史效果并创造价值，而不把力量等同统治或把重估变成任意选择？",
    transition: "尼采不是用一套新道德法典替换旧法典。他以格言、谱系、心理诊断和文学实验追踪价值怎样形成；‘权力意志’、永恒轮回和视角主义都有竞争解释。《权力意志》是身后编选，尼采与纳粹不能简单等同，但其等级、残酷和反民主文字也不能只归咎误读。",
    nodes: [
      {
        id: "affirmation-revalues-suffering-without-worshipping-it",
        kind: "答案", answerRole: "反驳",
        title: "不把痛苦证明为善，也不以逃离生命为最高价值，而检验人能否转化和承担有限生命",
        summary: "尼采反对叔本华由痛苦推出否定意志，转而追问一种生命怎样把阻力变成创造、自我克服和更丰富能力。",
        pressure: "肯定语言容易被误用为要求弱者忍受伤害，或把成功者力量当作价值证明。",
        consequence: "必须先诊断欧洲为何在旧价值失效后走向虚无主义。",
        participants: [{ name: "弗里德里希·尼采", philosopherId: "nietzsche", role: "以生命肯定反驳叔本华的否定意志" }],
        chapterIds: ["b3-25"], graph: { row: 408, lane: 2.7 },
      },
      {
        id: "erosion-of-transcendent-values-observation",
        kind: "观察",
        observation: {
          domain: "历史变化",
          note: "历史批判、自然科学、宗派分裂和世俗制度削弱传统基督教—形而上学权威，但日常道德仍继续使用其绝对价值语言。",
          historyLinks: [{ stageId: "industrial-modern", responseId: "nietzsche", label: "价值基础衰退与尼采", note: "进入历史概览查看现代科学和工业社会怎样使价值来源成为独立问题。" }],
        },
        title: "最高价值的旧根据失去可信力，人们却仍依赖其道德语汇和生活目标",
        summary: "超越世界、神圣命令和目的论不再普遍可信，平等、罪责、真理与进步仍像拥有无条件基础那样运作。",
        pressure: "权威衰退不是一夜完成，也不意味着所有信仰者或共同价值已经消失。",
        consequence: "观察提出‘上帝死了’究竟诊断什么文化事件。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 409, lane: 0.3 },
      },
      {
        id: "what-does-death-of-god-diagnose",
        kind: "问题",
        title: "‘上帝死了’是无神论口号，还是关于欧洲价值体系失去最高保证的历史诊断？",
        summary: "证明某个神学命题为假，与一个文化不再能从超越者获得意义、真理和道德等级，是不同层次。",
        pressure: "若旧基础消失而评价习惯原样保留，人可能同时否认根据又继续要求其效果。",
        consequence: "尼采把这种延迟后果称为虚无主义危机。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 410, lane: 0.3 },
      },
      {
        id: "death-of-god-opens-nihilism-crisis",
        kind: "答案", answerRole: "提出",
        title: "‘上帝死了’诊断最高价值失去约束力，而人尚未学会在其后评价和生活",
        summary: "虚无主义不是简单悲伤或不信教，而是旧目标自行贬值、世界显得没有为何值得的尺度。",
        pressure: "从共享基础瓦解到所有人必然虚无没有逻辑必然，不同传统能够重构价值。",
        consequence: "问题变为虚无主义是被动放弃、主动破坏，还是重估的过渡。",
        participants: [{ name: "弗里德里希·尼采", philosopherId: "nietzsche", role: "以‘上帝死了’诊断欧洲虚无主义" }],
        chapterIds: ["b3-25"], graph: { row: 411, lane: 0.3 },
      },
      {
        id: "can-nihilism-be-overcome-with-new-dogma",
        kind: "问题",
        title: "克服虚无主义是否只需宣布一套新的绝对教义或政治信仰？",
        summary: "新教义可以恢复方向，却可能只是用民族、国家、种族或进步替代旧神，继续逃避价值来源审查。",
        pressure: "不断拆解一切也会使行动瘫痪；重估必须能形成持久承诺。",
        consequence: "尼采用谱系揭露价值生成，再要求承担创造价值的责任。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 412, lane: 0.3 },
      },
      {
        id: "overcoming-nihilism-requires-revaluation-not-substitute-idol",
        kind: "答案", answerRole: "转向",
        title: "克服虚无主义需要重估价值的生命效果，而非用新偶像填补旧权威位置",
        summary: "价值必须接受它如何塑造身体、情感、创造和关系的检验，承担没有超越保证的评价责任。",
        pressure: "‘生命效果’本身含义多义，不能免除对伤害、平等与公共后果的讨论。",
        consequence: "谱系学成为审查现有价值取得权威方式的方法。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 413, lane: 0.3 },
      },
      {
        id: "moral-concepts-change-observation",
        kind: "观察",
        observation: { domain: "知识实践", note: "‘善／恶’、罪责、责任和禁欲理想的词义与制度功能随社会关系、宗教实践和惩罚方式变化，并非一直表达同一内涵。" },
        title: "道德概念拥有可追踪的语言、惩罚、宗教和情感形成史",
        summary: "一种评价成为常识后会隐藏自己的发生条件，把历史胜利呈现为永恒真理。",
        pressure: "发现起源复杂或不体面，并不能单凭发生谬误证明当前价值为假。",
        consequence: "观察提出谱系与普通历史、逻辑反驳的区别。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 409, lane: 1.8 },
      },
      {
        id: "what-can-genealogy-show-about-value",
        kind: "问题",
        title: "追踪一种价值的历史和心理来源，能说明它现在是否值得继续接受吗？",
        summary: "起源调查可揭示权力和情感功能，却不能仅因来源偶然而直接决定规范结论。",
        pressure: "若谱系只有历史描述，它难以完成重估；若由起源直接判罪，又犯发生谬误。",
        consequence: "尼采把起源、功能变化和对生命类型的效果结合。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 410, lane: 1.8 },
      },
      {
        id: "genealogy-links-origin-function-affect-effect",
        kind: "答案", answerRole: "提出",
        title: "谱系追踪起源、功能转移、情感训练与现实效果，使价值重新暴露于评价",
        summary: "它不只问谁首次发明一个词，而问惩罚、记忆、怨恨和制度怎样让某种解释取得支配。",
        pressure: "尼采的历史例证有时推测性强，现代研究须将方法洞见与具体史实分开。",
        consequence: "善／恶与善／坏的转换成为第一组检验。",
        participants: [{ name: "弗里德里希·尼采", philosopherId: "nietzsche", role: "以谱系方法重开价值来源和效果问题" }],
        chapterIds: ["b3-25"], graph: { row: 411, lane: 1.8 },
      },
      {
        id: "how-ressentiment-revalues-noble-power",
        kind: "问题",
        title: "无力直接行动者的怨恨，怎样把强者的‘好／坏’评价翻转成普遍的‘善／恶’？",
        summary: "受压者可能通过道德谴责获得解释和反抗资源，把敌人的力量重新命名为邪恶。",
        pressure: "不能因此把一切平等、关怀或受压者批判都贬成病态怨恨，也不能为贵族暴力免责。",
        consequence: "奴隶道德被解释为反应性价值创造，同时保留其保护功能与代价。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 412, lane: 1.8 },
      },
      {
        id: "ressentiment-creates-reactive-good-evil",
        kind: "答案", answerRole: "提出",
        title: "怨恨把不能直接释放的敌意内化并道德化，以‘恶’定义对手、再反向定义自身为善",
        summary: "这种重估给无力者以精神反抗，却可能让价值持续依赖敌人，并把力量和差异本身视为罪。",
        pressure: "尼采的类型学具有精英偏见，具体平等规范必须按其理由和效果独立评价。",
        consequence: "问题推进到惩罚、债务和冲动内化怎样形成罪责主体。",
        participants: [{ name: "弗里德里希·尼采", philosopherId: "nietzsche", role: "以 ressentiment 解释反应性价值形成" }],
        chapterIds: ["b3-25"], graph: { row: 413, lane: 1.8 },
      },
      {
        id: "how-debt-punishment-becomes-guilt",
        kind: "问题",
        title: "外在债务、承诺和惩罚实践怎样转化为内在罪责与自我惩罚？",
        summary: "能作承诺的主体需要记忆和可预测性，社会惩罚又把痛苦连接到欠债与责任。",
        pressure: "历史语言联系不能证明全部罪责只来自经济债务，也不能取消合理责任。",
        consequence: "坏良心被解释为被迫向内释放的行动冲动。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 414, lane: 1.8 },
      },
      {
        id: "bad-conscience-internalizes-aggression-and-debt",
        kind: "答案", answerRole: "提出",
        title: "社会驯化限制冲动外放，攻击性转向自身并与债务—罪责解释结合成坏良心",
        summary: "内在化创造深度、记忆和责任能力，也制造自我残酷与需要惩罚的主体。",
        pressure: "文明化并非只有压抑，内在反思也支持承诺、关怀和自我修正。",
        consequence: "价值诊断需要多重视角，而非以单一深层原因解释全部行动。",
        participants: [{ name: "弗里德里希·尼采", philosopherId: "nietzsche", role: "以冲动内化说明罪责主体的双重形成" }],
        chapterIds: ["b3-25"], graph: { row: 415, lane: 1.8 },
      },
      {
        id: "is-perspectivism-simple-relativism",
        kind: "问题",
        title: "知识总从身体、情感和价值视角出发，是否意味着所有解释同样正确？",
        summary: "不存在无位置的上帝视角，不等于证据、范围、解释力和自我校正失去差别。",
        pressure: "若尼采自己的谱系也只是一种任意视角，它就无法要求读者优先接受。",
        consequence: "视角主义被理解为扩大和比较视角，而非取消真伪。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 409, lane: 3.2 },
      },
      {
        id: "perspectivism-compares-situated-interpretations",
        kind: "答案", answerRole: "区分",
        title: "承认认识受视角组织，同时以更多视角、证据阻力和解释能力比较解释",
        summary: "情感和价值参与注意与分类；更强认识不是消灭位置，而是能控制偏见并容纳更多对象面向。",
        pressure: "尼采没有给出一套完整公共认识论，视角优劣标准仍需重构。",
        consequence: "问题转向解释活动为何常表现为组织和克服阻力的力量。",
        participants: [{ name: "弗里德里希·尼采", philosopherId: "nietzsche", role: "以视角主义批判无位置客观性" }],
        chapterIds: ["b3-25"], graph: { row: 410, lane: 3.2 },
      },
      {
        id: "does-will-to-power-mean-political-domination",
        kind: "问题",
        title: "‘权力意志’是否只表示征服他人、夺取国家权力或强者统治弱者？",
        summary: "尼采用权力语言描述驱力、解释、艺术、自我控制和克服阻力，其范围远超政治统治。",
        pressure: "扩展含义不能洗去文本中真实的等级和支配赞美，概念本体论地位也有争议。",
        consequence: "较谨慎的读法把它视为多种驱力组织与扩展能力的结构。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 411, lane: 3.2 },
      },
      {
        id: "will-to-power-as-overcoming-and-organization-contested",
        kind: "答案", answerRole: "区分",
        title: "权力意志可指驱力通过克服阻力、组织自身和扩展能力的方式，不等同单一统治欲",
        summary: "创作、自律和解释也包含力量关系；学界仍争论它是心理假说、价值承诺还是形而上学主张。",
        pressure: "‘自我克服’若忽略照护和物质条件，仍可能成为精英自我塑造神话。",
        consequence: "价值创造必须说明强度之外还有什么评价边界。",
        participants: [{ name: "弗里德里希·尼采", philosopherId: "nietzsche", role: "以多义的权力意志重构驱力与创造" }],
        chapterIds: ["b3-25"], graph: { row: 412, lane: 3.2 },
      },
      {
        id: "can-revaluation-avoid-arbitrary-cruelty",
        kind: "问题",
        title: "没有普遍超越法则时，价值重估怎样避免任意、残酷和强者自我授权？",
        summary: "创造价值要求摆脱旧保证，却仍会影响他人；生命、力量或健康也可能被用来排除脆弱者。",
        pressure: "尼采拒绝传统普遍道德，没有提供现代平等政治可直接采用的完整保障。",
        consequence: "重估只能以是否增加复杂能力、诚实和非反应性创造等内部标准受检验，并保留政治风险。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 413, lane: 3.2 },
      },
      {
        id: "revaluation-tests-creative-flourishing-with-political-risk",
        kind: "答案", answerRole: "修复",
        title: "重估以创造力、诚实、自我克服和生命丰富度检验价值，同时不能抹去其反平等风险",
        summary: "尼采要求评价价值产生何种人和生活，而非任意宣布偏好；这些标准本身仍需面对公共伤害和制度权力。",
        pressure: "现代修复不能把尼采无缝改造成自由民主理论家，也不能把一切批判交给罗素的政治归罪。",
        consequence: "永恒轮回把价值判断压缩为对整个有限生命的肯定测试。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 414, lane: 3.2 },
      },
      {
        id: "what-does-eternal-recurrence-test",
        kind: "问题",
        title: "设想同一生命及每个细节无限重复，是宇宙学理论，还是检验肯定程度的思想实验？",
        summary: "尼采既认真考虑过宇宙学表达，也让恶魔假设直接询问人能否愿意此生重来。",
        pressure: "文本证据不足以让一种解释独占；即使是假设，也可能对遭受极端伤害者提出不公要求。",
        consequence: "较稳妥的图谱保留宇宙论争议，突出其评价功能。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 415, lane: 3.2 },
      },
      {
        id: "eternal-recurrence-as-affirmation-test-not-proven-cosmology",
        kind: "答案", answerRole: "区分",
        title: "永恒轮回至少可作为最严厉的生命肯定测试，不应写成已证明的宇宙学事实",
        summary: "它要求价值创造者不仅选择理想片段，也面对偶然、失败和有限性构成的整个生命。",
        pressure: "肯定不能替代改变可避免苦难，更不能要求受害者赞同伤害。",
        consequence: "最终还须处理尼采作品的政治挪用和自身等级表达。",
        participants: [{ name: "弗里德里希·尼采", philosopherId: "nietzsche", role: "以永恒轮回检验 amor fati 与生命肯定" }],
        chapterIds: ["b3-25"], graph: { row: 416, lane: 3.2 },
      },
      {
        id: "is-nietzsche-source-of-nazism",
        kind: "问题",
        title: "尼采被法西斯主义挪用，是否证明其思想与纳粹主义可以直接等同？",
        summary: "妹妹的选择性编辑、身后《权力意志》编本和政治宣传放大了某些主题；尼采本人反民族主义和反反犹主义。",
        pressure: "纠正挪用不能删除他对等级、残酷、民主和平等的敌意表达。",
        consequence: "需要把直接文本、编辑史、政治接受和规范批评分别判断。",
        participants: [], chapterIds: ["b3-25"], graph: { row: 409, lane: 4.5 },
      },
      {
        id: "nietzsche-not-nazi-but-political-dangers-remain",
        kind: "答案", answerRole: "区分",
        title: "尼采不是纳粹主义者，身后编辑与挪用必须校正；其反平等和等级政治风险仍须正面批评",
        summary: "反反犹主义和反民族主义文本排除简单同一，贵族主义、残酷修辞和反民主立场又阻止无害化阅读。",
        pressure: "思想影响通常经过选择和重构，不能由后来罪行自动证明原论证，也不能假装接受史无关。",
        consequence: "价值谱系最终进入公共评价：制度应以何种可共同检验的后果或权利尺度判断。",
        participants: [{ name: "弗里德里希·尼采", philosopherId: "nietzsche", role: "其作品经历复杂政治挪用，同时保留自身可批评的等级立场" }],
        chapterIds: ["b3-25"], graph: { row: 410, lane: 4.5 },
      },
      {
        id: "can-created-values-be-judged-by-shared-consequences",
        kind: "问题",
        title: "价值被揭示为历史创造后，能否按所有受影响者的幸福、自由和伤害进行共同评价？",
        summary: "尼采警惕共同尺度压平卓越，公共制度却不能只服从少数价值创造者的自我评价。",
        pressure: "单一后果总量可能牺牲少数和人格差异，拒绝共同尺度又会让权力免于问责。",
        consequence: "第三卷第二十六章将由边沁和密尔以功利、自由与人格发展回应这一开放接口。",
        participants: [
          { name: "杰里米·边沁", philosopherId: "bentham", role: "将把价值评价转向所有相关者的快乐与痛苦后果" },
          { name: "约翰·斯图亚特·密尔", philosopherId: "mill", role: "将以自由、个性和较高能力修正单一数量尺度" },
        ],
        chapterIds: ["b3-25", "b3-26"], graph: { row: 417, lane: 2.7 },
      },
    ],
  },
];

export const idealismWillProblemEdges: ProblemEdge[] = [
  { id: "ik001", from: "can-subject-object-nature-freedom-unify-historically", to: "post-kantian-reconstructs-divisions-as-development", relation: "回应问题", label: "把固定分界改写为相互形成的历史过程", connection: "历史回应" },
  { id: "ik002", from: "post-kantian-reconstructs-divisions-as-development", to: "can-reason-transform-fixed-oppositions-from-within", relation: "产生问题", label: "历史化仍须说明转化方法", connection: "本站推演" },
  { id: "ik003", from: "revolution-restoration-nationalism-observation", to: "is-history-intelligible-beyond-chronicle-and-fate", relation: "提出问题", label: "制度剧变使历史方向成为可追问对象", connection: "历史回应" },
  { id: "ik004", from: "is-history-intelligible-beyond-chronicle-and-fate", to: "history-as-development-of-freedom-consciousness", relation: "回应问题", label: "以自由意识和制度形式组织历史比较", connection: "原书线索" },
  { id: "ik005", from: "history-as-development-of-freedom-consciousness", to: "does-historical-direction-guarantee-moral-progress", relation: "产生问题", label: "发展叙事开放进步保证的疑问", connection: "后世重构" },
  { id: "ik006", from: "does-historical-direction-guarantee-moral-progress", to: "historical-direction-is-diagnostic-not-guarantee", relation: "回应问题", label: "区分自由诊断尺度与年代目的论", connection: "后世重构" },
  { id: "ik007", from: "post-kantian-system-rivalry-observation", to: "is-german-idealism-one-continuous-system", relation: "提出问题", label: "体系竞争反对单线完成史", connection: "历史回应" },
  { id: "ik008", from: "is-german-idealism-one-continuous-system", to: "post-kantian-programs-share-pressure-not-destiny", relation: "回应问题", label: "以共享压力和分叉方案重写连续性", connection: "后世重构" },
  { id: "ik009", from: "post-kantian-programs-share-pressure-not-destiny", to: "can-reason-transform-fixed-oppositions-from-within", relation: "产生问题", label: "黑格尔方案必须独立证明内在转化", connection: "本站推演" },
  { id: "ik010", from: "industrial-civil-society-observation", to: "are-abstract-rights-sufficient-for-social-freedom", relation: "提出问题", label: "制度依赖暴露形式权利的不足", connection: "历史回应" },
  { id: "ik011", from: "are-abstract-rights-sufficient-for-social-freedom", to: "institutions-mediate-capabilities-recognition-right", relation: "回应问题", label: "以能力、承认和制度中介扩展自由", connection: "历史回应" },
  { id: "ik012", from: "institutions-mediate-capabilities-recognition-right", to: "can-institutional-whole-secure-without-absorbing-individual", relation: "产生问题", label: "制度支持同时开放整体压迫风险", connection: "本站推演" },

  { id: "ik013", from: "can-reason-transform-fixed-oppositions-from-within", to: "determinate-negation-transforms-opposition", relation: "回应问题", label: "以规定性否定让对立从内部转化", connection: "原书线索" },
  { id: "ik014", from: "determinate-negation-transforms-opposition", to: "is-dialectic-fixed-thesis-antithesis-synthesis", relation: "产生问题", label: "内在否定要求清除机械三段式误读", connection: "后世重构" },
  { id: "ik015", from: "is-dialectic-fixed-thesis-antithesis-synthesis", to: "dialectic-is-immanent-not-fixed-triad", relation: "回应问题", label: "把辩证法限定为对象依赖的内在检验", connection: "后世重构", sourceRefs: [{ sourceLabel: "SEP · Hegel’s Dialectics", locator: "条目关于规定性否定、扬弃与固定三段式误读的说明" }] },
  { id: "ik016", from: "dialectic-is-immanent-not-fixed-triad", to: "can-conceptual-dialectic-describe-objective-world", relation: "产生问题", label: "概念方法仍须取得现实效力", connection: "本站推演" },
  { id: "ik017", from: "can-conceptual-dialectic-describe-objective-world", to: "objective-idealism-reason-immanent-in-world", relation: "回应问题", label: "以主客共享理性结构建立客观观念论", connection: "原书线索" },
  { id: "ik017a", from: "objective-idealism-reason-immanent-in-world", to: "why-self-consciousness-needs-mutual-recognition", relation: "产生问题", label: "主客关系进入主体间承认结构", connection: "本站推演" },
  { id: "ik018", from: "self-consciousness-seeks-recognition-observation", to: "why-self-consciousness-needs-mutual-recognition", relation: "提出问题", label: "自我地位依赖他人回应", connection: "原书线索" },
  { id: "ik019", from: "why-self-consciousness-needs-mutual-recognition", to: "mutual-recognition-constitutes-social-selfhood", relation: "回应问题", label: "以双向承认建立社会自我", connection: "原书线索" },
  { id: "ik020", from: "mutual-recognition-constitutes-social-selfhood", to: "can-domination-secure-recognition", relation: "产生问题", label: "承认互惠要求检验支配关系", connection: "原书线索" },
  { id: "ik021", from: "can-domination-secure-recognition", to: "asymmetric-recognition-undermines-itself", relation: "回应问题", label: "不对称承认破坏主人追求的确认", connection: "原书线索" },
  { id: "ik021a", from: "asymmetric-recognition-undermines-itself", to: "why-abstract-right-and-private-conscience-insufficient", relation: "产生问题", label: "承认失败要求稳定法律与伦理制度", connection: "历史回应" },
  { id: "ik022", from: "market-family-state-dependence-observation", to: "why-abstract-right-and-private-conscience-insufficient", relation: "提出问题", label: "多重制度角色超出抽象权利和动机", connection: "历史回应" },
  { id: "ik023", from: "can-institutional-whole-secure-without-absorbing-individual", to: "ethical-life-mediates-family-civil-society-state", relation: "回应问题", label: "以伦理生活分层组织制度整体", connection: "历史回应" },
  { id: "ik024", from: "why-abstract-right-and-private-conscience-insufficient", to: "ethical-life-mediates-family-civil-society-state", relation: "回应问题", label: "由权利和良心进入伦理生活", connection: "原书线索" },
  { id: "ik025", from: "ethical-life-mediates-family-civil-society-state", to: "does-actual-rational-mean-every-state-is-right", relation: "产生问题", label: "制度自由开放现实与合理的边界", connection: "原书线索" },
  { id: "ik026", from: "does-actual-rational-mean-every-state-is-right", to: "actuality-is-critical-standard-not-fact-worship", relation: "回应问题", label: "区分合理现实性与事实崇拜", connection: "后世重构" },
  { id: "ik027", from: "actuality-is-critical-standard-not-fact-worship", to: "can-civil-society-correct-poverty-it-produces", relation: "产生问题", label: "批判标准转向市场系统性失败", connection: "历史回应" },
  { id: "ik028", from: "industrial-civil-society-observation", to: "can-civil-society-correct-poverty-it-produces", relation: "提出问题", label: "财富与贫困并生要求制度修复", connection: "历史回应" },
  { id: "ik029", from: "can-civil-society-correct-poverty-it-produces", to: "institutions-contain-market-without-abolishing-particularity", relation: "回应问题", label: "以社团和公共保障限制市场后果", connection: "历史回应" },
  { id: "ik030", from: "institutions-contain-market-without-abolishing-particularity", to: "does-world-history-redeem-suffering-and-exclusion", relation: "产生问题", label: "不完整调和要求受害经验反证整体", connection: "后世重构" },
  { id: "ik031", from: "historical-direction-is-diagnostic-not-guarantee", to: "does-world-history-redeem-suffering-and-exclusion", relation: "产生问题", label: "历史方向必须接受不可补偿损失检验", connection: "后世重构" },
  { id: "ik032", from: "does-world-history-redeem-suffering-and-exclusion", to: "totality-must-remain-answerable-to-unreconciled-lives", relation: "回应问题", label: "让整体持续回应未调和生命", connection: "后世重构" },
  { id: "ik033", from: "totality-must-remain-answerable-to-unreconciled-lives", to: "can-rebellion-protect-individual-without-glorifying-power", relation: "产生问题", label: "未调和个体推动浪漫反叛检验", connection: "历史回应" },

  { id: "ik034", from: "can-rebellion-protect-individual-without-glorifying-power", to: "byronic-figure-exposes-conformity-without-system", relation: "回应问题", label: "以文学人格暴露礼俗并保留开放性", connection: "历史回应" },
  { id: "ik035", from: "celebrity-scandal-authorship-observation", to: "can-self-mythology-preserve-self-critique", relation: "提出问题", label: "作品与名声交叠触发自我神话问题", connection: "历史回应" },
  { id: "ik036", from: "can-self-mythology-preserve-self-critique", to: "irony-splits-author-hero-public-image", relation: "回应问题", label: "以讽刺拆开作者、角色和公众形象", connection: "原书线索" },
  { id: "ik037", from: "irony-splits-author-hero-public-image", to: "does-transgression-prove-authentic-freedom", relation: "产生问题", label: "自我反讽要求重新判断越界真实性", connection: "本站推演" },
  { id: "ik038", from: "does-transgression-prove-authentic-freedom", to: "transgression-reveals-hypocrisy-not-automatic-freedom", relation: "回应问题", label: "区分揭露虚伪与自动取得自由", connection: "后世重构" },
  { id: "ik039", from: "romantic-hero-audience-observation", to: "can-charismatic-hero-represent-public-liberty", relation: "提出问题", label: "替代性自由体验开放英雄代表风险", connection: "历史回应" },
  { id: "ik040", from: "byronic-figure-exposes-conformity-without-system", to: "can-charismatic-hero-represent-public-liberty", relation: "产生问题", label: "文化反叛尚不能提供公共代表权", connection: "本站推演" },
  { id: "ik041", from: "can-charismatic-hero-represent-public-liberty", to: "charisma-mobilizes-but-cannot-legitimate-rule", relation: "回应问题", label: "区分象征动员与统治正当性", connection: "后世重构" },
  { id: "ik042", from: "byron-political-solidarity-observation", to: "can-poetic-solidarity-become-responsible-action", relation: "提出问题", label: "真实政治介入要求检验合作与责任", connection: "历史回应" },
  { id: "ik043", from: "can-poetic-solidarity-become-responsible-action", to: "responsible-rebellion-links-courage-solidarity-limits", relation: "回应问题", label: "以勇气、团结与限度修复反叛", connection: "后世重构" },
  { id: "ik044", from: "charisma-mobilizes-but-cannot-legitimate-rule", to: "can-poetic-solidarity-become-responsible-action", relation: "产生问题", label: "动员力必须转成可问责行动", connection: "本站推演" },
  { id: "ik045", from: "responsible-rebellion-links-courage-solidarity-limits", to: "does-intensified-desire-liberate-or-enslave", relation: "产生问题", label: "责任边界重新打开欲望自由问题", connection: "本站推演" },
  { id: "ik046", from: "transgression-reveals-hypocrisy-not-automatic-freedom", to: "does-intensified-desire-liberate-or-enslave", relation: "产生问题", label: "越界并非自由迫使检查欲望结构", connection: "本站推演" },

  { id: "ik047", from: "does-intensified-desire-liberate-or-enslave", to: "desire-reveals-will-before-rational-purpose", relation: "回应问题", label: "以身体意愿揭示理性之前的驱力", connection: "历史回应" },
  { id: "ik048", from: "body-double-aspect-observation", to: "can-body-give-access-to-thing-in-itself", relation: "提出问题", label: "身体双重经验开放物自身入口", connection: "原书线索" },
  { id: "ik049", from: "desire-reveals-will-before-rational-purpose", to: "can-body-give-access-to-thing-in-itself", relation: "产生问题", label: "身体意愿要求确定其认识地位", connection: "原书线索" },
  { id: "ik050", from: "can-body-give-access-to-thing-in-itself", to: "world-double-aspect-representation-and-will", relation: "回应问题", label: "以表象—意志双面解释同一世界", connection: "原书线索" },
  { id: "ik051", from: "world-double-aspect-representation-and-will", to: "can-human-will-be-extended-to-all-nature", relation: "产生问题", label: "身体入口开放向自然整体的类推", connection: "原书线索" },
  { id: "ik052", from: "can-human-will-be-extended-to-all-nature", to: "will-as-nonpersonal-striving-across-nature", relation: "回应问题", label: "把意志去人格化为普遍趋力", connection: "原书线索" },
  { id: "ik053", from: "striving-satisfaction-boredom-observation", to: "is-suffering-accident-or-structure-of-willing", relation: "提出问题", label: "欲望循环使痛苦结构可见", connection: "原书线索" },
  { id: "ik054", from: "will-as-nonpersonal-striving-across-nature", to: "is-suffering-accident-or-structure-of-willing", relation: "产生问题", label: "无目的趋力要求评价其生命后果", connection: "原书线索" },
  { id: "ik055", from: "is-suffering-accident-or-structure-of-willing", to: "pessimism-from-endless-willing", relation: "回应问题", label: "由无尽匮乏建立结构性悲观", connection: "原书线索" },
  { id: "ik056", from: "pessimism-from-endless-willing", to: "does-pessimism-follow-without-value-premise", relation: "产生问题", label: "痛苦事实仍需价值前提才能推出悲观", connection: "后世重构" },
  { id: "ik057", from: "does-pessimism-follow-without-value-premise", to: "pessimism-is-metaphysical-evaluation-not-measurement", relation: "回应问题", label: "区分形而上学评价与经验计量", connection: "后世重构" },
  { id: "ik058", from: "pessimism-is-metaphysical-evaluation-not-measurement", to: "how-can-subject-loosen-service-to-will", relation: "产生问题", label: "悲观诊断转向可能的实践松脱", connection: "原书线索" },
  { id: "ik059", from: "how-can-subject-loosen-service-to-will", to: "aesthetic-contemplation-suspends-personal-striving", relation: "回应问题", label: "以审美静观暂时中止私人欲求", connection: "原书线索" },
  { id: "ik060", from: "how-can-subject-loosen-service-to-will", to: "compassion-crosses-principium-individuationis", relation: "回应问题", label: "以同情越过个体利己边界", connection: "原书线索" },
  { id: "ik061", from: "how-can-subject-loosen-service-to-will", to: "ascetic-negation-reduces-will-to-life", relation: "回应问题", label: "以禁欲追求持久否定意志", connection: "原书线索" },
  { id: "ik062", from: "world-double-aspect-representation-and-will", to: "is-schopenhauer-equivalent-to-buddhism-hinduism", relation: "产生问题", label: "双面体系要求校正跨传统来源", connection: "后世重构" },
  { id: "ik063", from: "is-schopenhauer-equivalent-to-buddhism-hinduism", to: "asian-thought-selectively-reconstructed-in-european-system", relation: "回应问题", label: "区分跨传统影响与概念等同", connection: "后世重构" },
  { id: "ik064", from: "aesthetic-contemplation-suspends-personal-striving", to: "does-negating-will-repeat-nihilism", relation: "产生问题", label: "无意志体验开放生命否定疑问", connection: "历史回应" },
  { id: "ik065", from: "compassion-crosses-principium-individuationis", to: "does-negating-will-repeat-nihilism", relation: "产生问题", label: "减少痛苦仍需说明是否必须否定生命", connection: "历史回应" },
  { id: "ik066", from: "ascetic-negation-reduces-will-to-life", to: "does-negating-will-repeat-nihilism", relation: "产生问题", label: "彻底禁欲直接触发虚无主义批评", connection: "历史回应" },
  { id: "ik067", from: "asian-thought-selectively-reconstructed-in-european-system", to: "does-negating-will-repeat-nihilism", relation: "产生问题", label: "解脱重构仍须接受生命价值检验", connection: "本站推演" },

  { id: "ik068", from: "does-negating-will-repeat-nihilism", to: "affirmation-revalues-suffering-without-worshipping-it", relation: "回应问题", label: "以生命肯定反驳否定意志", connection: "历史回应" },
  { id: "ik069", from: "erosion-of-transcendent-values-observation", to: "what-does-death-of-god-diagnose", relation: "提出问题", label: "旧价值根据衰退触发上帝之死诊断", connection: "历史回应" },
  { id: "ik070", from: "what-does-death-of-god-diagnose", to: "death-of-god-opens-nihilism-crisis", relation: "回应问题", label: "把口号解释为文化虚无主义危机", connection: "原书线索" },
  { id: "ik071", from: "death-of-god-opens-nihilism-crisis", to: "can-nihilism-be-overcome-with-new-dogma", relation: "产生问题", label: "基础崩塌要求检验替代偶像", connection: "本站推演" },
  { id: "ik072", from: "can-nihilism-be-overcome-with-new-dogma", to: "overcoming-nihilism-requires-revaluation-not-substitute-idol", relation: "回应问题", label: "以重估而非新绝对教义回应", connection: "历史回应" },
  { id: "ik073", from: "moral-concepts-change-observation", to: "what-can-genealogy-show-about-value", relation: "提出问题", label: "概念变迁使价值起源可追问", connection: "原书线索" },
  { id: "ik074", from: "overcoming-nihilism-requires-revaluation-not-substitute-idol", to: "what-can-genealogy-show-about-value", relation: "产生问题", label: "重估需要谱系方法揭露权威形成", connection: "原书线索" },
  { id: "ik075", from: "what-can-genealogy-show-about-value", to: "genealogy-links-origin-function-affect-effect", relation: "回应问题", label: "结合起源、功能、情感与效果", connection: "原书线索" },
  { id: "ik076", from: "genealogy-links-origin-function-affect-effect", to: "how-ressentiment-revalues-noble-power", relation: "产生问题", label: "谱系进入善恶评价翻转", connection: "原书线索" },
  { id: "ik077", from: "how-ressentiment-revalues-noble-power", to: "ressentiment-creates-reactive-good-evil", relation: "回应问题", label: "以怨恨说明反应性价值创造", connection: "原书线索" },
  { id: "ik078", from: "ressentiment-creates-reactive-good-evil", to: "how-debt-punishment-becomes-guilt", relation: "产生问题", label: "价值翻转推进到罪责主体形成", connection: "原书线索" },
  { id: "ik079", from: "how-debt-punishment-becomes-guilt", to: "bad-conscience-internalizes-aggression-and-debt", relation: "回应问题", label: "以债务、惩罚和内化解释坏良心", connection: "原书线索" },
  { id: "ik080", from: "bad-conscience-internalizes-aggression-and-debt", to: "is-perspectivism-simple-relativism", relation: "产生问题", label: "深层诊断要求反思解释自身视角", connection: "本站推演" },
  { id: "ik081", from: "is-perspectivism-simple-relativism", to: "perspectivism-compares-situated-interpretations", relation: "回应问题", label: "以视角扩展和比较反对简单相对主义", connection: "后世重构" },
  { id: "ik082", from: "perspectivism-compares-situated-interpretations", to: "does-will-to-power-mean-political-domination", relation: "产生问题", label: "解释的组织性开放权力概念边界", connection: "原书线索" },
  { id: "ik083", from: "does-will-to-power-mean-political-domination", to: "will-to-power-as-overcoming-and-organization-contested", relation: "回应问题", label: "区分克服阻力与单一政治统治", connection: "后世重构" },
  { id: "ik084", from: "will-to-power-as-overcoming-and-organization-contested", to: "can-revaluation-avoid-arbitrary-cruelty", relation: "产生问题", label: "力量多义性要求价值创造边界", connection: "本站推演" },
  { id: "ik085", from: "affirmation-revalues-suffering-without-worshipping-it", to: "can-revaluation-avoid-arbitrary-cruelty", relation: "产生问题", label: "生命肯定必须防止强者自我授权", connection: "本站推演" },
  { id: "ik086", from: "can-revaluation-avoid-arbitrary-cruelty", to: "revaluation-tests-creative-flourishing-with-political-risk", relation: "回应问题", label: "保留创造标准并标注反平等风险", connection: "后世重构" },
  { id: "ik087", from: "revaluation-tests-creative-flourishing-with-political-risk", to: "what-does-eternal-recurrence-test", relation: "产生问题", label: "价值创造进入整体生命肯定测试", connection: "原书线索" },
  { id: "ik088", from: "what-does-eternal-recurrence-test", to: "eternal-recurrence-as-affirmation-test-not-proven-cosmology", relation: "回应问题", label: "保留宇宙论争议并突出评价功能", connection: "后世重构" },
  { id: "ik089", from: "will-to-power-as-overcoming-and-organization-contested", to: "is-nietzsche-source-of-nazism", relation: "产生问题", label: "权力语言进入编辑与政治挪用审查", connection: "后世重构" },
  { id: "ik090", from: "is-nietzsche-source-of-nazism", to: "nietzsche-not-nazi-but-political-dangers-remain", relation: "回应问题", label: "区分文本、编辑史、挪用与规范风险", connection: "后世重构" },
  { id: "ik091", from: "nietzsche-not-nazi-but-political-dangers-remain", to: "can-created-values-be-judged-by-shared-consequences", relation: "产生问题", label: "政治风险要求共同后果尺度", connection: "后世重构" },
  { id: "ik092", from: "eternal-recurrence-as-affirmation-test-not-proven-cosmology", to: "can-created-values-be-judged-by-shared-consequences", relation: "产生问题", label: "个人肯定仍须进入公共评价", connection: "本站推演" },
];

export const idealismWillProblemSources: ProblemMapSource[] = [
  { label: "SEP · Idealism", url: "https://plato.stanford.edu/entries/idealism/", note: "用于区分认识论与本体论观念论，并把康德、后康德德国观念论、叔本华及后来分析批评放入非单线发展史。" },
  { label: "IEP · German Idealism", url: "https://iep.utm.edu/germidea/", note: "用于核对康德、费希特、谢林与黑格尔共享的问题语境及体系差异，避免把后康德思想写成黑格尔的必然前史。" },
  { label: "SEP · Georg Wilhelm Friedrich Hegel", url: "https://plato.stanford.edu/entries/hegel/", note: "用于核对黑格尔的逻辑、精神现象学、承认、客观精神和历史哲学，并保留体系解释的竞争路线。" },
  { label: "SEP · Hegel’s Social and Political Philosophy", url: "https://plato.stanford.edu/entries/hegel-social-political/", note: "用于核对抽象法、道德、伦理生活、家庭、市民社会、国家与自由实现，限制把黑格尔直接写成凡现存国家皆合理。" },
  { label: "SEP · Hegel’s Dialectics", url: "https://plato.stanford.edu/entries/hegel-dialectics/", note: "用于校正规定性否定、扬弃与辩证推进，避免把黑格尔方法机械化为通用的正题—反题—合题口诀。" },
  { label: "Poetry Foundation · Lord Byron", url: "https://www.poetryfoundation.org/poets/lord-byron", note: "用于核对拜伦的作品类型、拜伦式英雄、自由派政治、意大利与希腊行动，以及作品人格和作者生平之间的边界。" },
  { label: "SEP · Arthur Schopenhauer", url: "https://plato.stanford.edu/entries/schopenhauer/", note: "用于核对表象—意志双面论、身体入口、悲观主义、同情和禁欲，并标明由身体经验扩展到世界意志的争议。" },
  { label: "SEP · Schopenhauer’s Aesthetics", url: "https://plato.stanford.edu/entries/schopenhauer-aesthetics/", note: "用于核对审美无利害观看、音乐、同情与不同程度的意志否定，不把短暂审美解脱等同完整伦理方案。" },
  { label: "SEP · Friedrich Nietzsche", url: "https://plato.stanford.edu/entries/nietzsche/", note: "用于核对虚无主义、谱系、视角主义、权力意志与永恒轮回的竞争解释，以及《权力意志》身后编选问题。" },
  { label: "SEP · Nietzsche’s Moral and Political Philosophy", url: "https://plato.stanford.edu/entries/nietzsche-moral-political/", note: "用于核对尼采的道德批判、贵族主义和政治风险；既不把他直接等同纳粹，也不因编辑史而删除其反平等表达。" },
];
