import type { ProblemEdge, ProblemMapSource, ProblemPhase } from "./problem-map-data";

export const romanticKantProblemPhases: ProblemPhase[] = [
  {
    id: "romanticism-reason-nature-individuality",
    order: 36,
    label: "浪漫主义的理性、自然与个体性",
    title: "以情感、想象和有机自然补充启蒙批判，同时保留反独断的理性要求",
    question: "当计算理性、商业秩序和机械自然不能容纳全部生活经验时，个体与世界怎样重新取得意义？",
    transition: "这里的‘浪漫主义’不是一个成员都持相同命题的严格学派，也不等于简单反理性。它包含多个国家、世代与艺术形式；共同压力在于：抽象规则、功利计算和机械自然图景会遗漏情感、想象、具体个体、历史归属和活的自然。",
    nodes: [
      {
        id: "progress-status-alienation-observation",
        kind: "观察",
        observation: {
          domain: "历史变化",
          note: "识字、市场、城市消费和公共舆论扩大个人选择，也强化名望比较、职业分工与被他人评价的依赖。",
          historyLinks: [{ stageId: "revolution-idealism", responseId: "rousseau", label: "文明批判与浪漫主义压力", note: "进入历史概览查看启蒙进步、革命政治和商业社会怎样共同重组自由问题。" }],
        },
        title: "文明进步扩大知识与选择，也扩大比较、分工和疏离感",
        summary: "更多书籍、商品和职业并不自动带来更完整生活；个人可能更自由地选择，却更依赖匿名市场、舆论和地位竞争。",
        pressure: "怀旧不能证明旧等级社会更好，进步叙事也不能用总量增长抹去个体经验与依赖结构。",
        consequence: "观察提出启蒙式理性与进步衡量遗漏了什么。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 342, lane: 0.4 },
      },
      {
        id: "what-do-calculation-and-progress-miss",
        kind: "问题",
        title: "若理性只被理解为计算、分类和效用衡量，它会遗漏人的哪些能力？",
        summary: "情感、想象、记忆、审美经验和具体关系不容易化成同一尺度，却持续组织行动和意义。",
        pressure: "指出遗漏不等于这些能力永远正确；激情、传统和想象同样会制造偏见与暴力。",
        consequence: "浪漫主义把感受力与创造想象提升为认识和自我形成的必要部分。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 343, lane: 0.8 },
      },
      {
        id: "sensibility-imagination-complete-reason",
        kind: "答案", answerRole: "修复",
        title: "感受力与想象让抽象原则重新接触具体生命、自然和历史经验",
        summary: "诗、音乐与审美注意不是逃离判断，而是显露概念分类难以独自把握的关系、整体和个体意义。",
        pressure: "审美洞见缺少统一证明程序，作品感染力也不能直接充当事实或政治正当性的证据。",
        consequence: "必须区分补充理性与用激情取消批判。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 344, lane: 0.8 },
      },
      {
        id: "is-romanticism-simple-irrationalism",
        kind: "问题",
        title: "重视情感与想象是否等于拒绝理性、证据和自我批评？",
        summary: "浪漫文本反对孤立的计算理性，却常继承启蒙关于自主批判、反教条和个体发展的要求。",
        pressure: "不同浪漫主义者差异极大；把全部运动写成一个反理性阵营，会复制罗素叙事中最整齐也最危险的概括。",
        consequence: "较稳妥的答案是扩展理性主体，而非把理性换成冲动。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 345, lane: 0.8 },
      },
      {
        id: "romantic-critique-synthesizes-reason-and-sensibility",
        kind: "答案", answerRole: "区分",
        title: "浪漫批判试图综合理性与感性，而非给未经检验的激情无限主权",
        summary: "独立批评仍然重要，但完整判断还需感觉、想象、历史意识和对具体个体的注意。",
        pressure: "综合没有自动规则；天才、真诚或民族情感若免于公共批评，仍可能成为新权威。",
        consequence: "开放性和反讽被用来防止任何单一作品或体系自称最终完成。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 346, lane: 0.8 },
      },
      {
        id: "mechanistic-nature-alienation-observation",
        kind: "观察",
        observation: { domain: "知识实践", note: "数学物理成功描述运动和可测关系，但若把这套方法当作自然全部本体，自组织生命、审美价值和人的归属感会显得只是附带幻觉。" },
        title: "机械自然图景解释可测运动，却容易把生命与意义排除为主观附属",
        summary: "把自然当作可预测部件系统带来强大科学成果，也可能让人把自身理解成与自然对立的孤立观察者。",
        pressure: "反还原不能用诗意类比替代物理解释；有机整体也不能成为拒绝实验的万能词。",
        consequence: "观察提出自然是否只能被理解为外在机械装置。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 343, lane: 2.5 },
      },
      {
        id: "is-nature-only-mechanical-system",
        kind: "问题",
        title: "自然是否只是外在因果推动的机械系统，还是也呈现整体、自组织与生命？",
        summary: "生物各部分相互维持，风景和生命经验又使自然呈现不易还原为部件相加的整体。",
        pressure: "从生物组织扩展到整个宇宙有目的或有精神，需要额外论证；局部整体性不证明人格化自然。",
        consequence: "浪漫自然观以有机整体和生成过程补充机械模型。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 344, lane: 2.5 },
      },
      {
        id: "organic-living-nature-as-romantic-countermodel",
        kind: "答案", answerRole: "转向",
        title: "把自然理解为相互依赖、生成和自组织的活整体，而不只是一堆外在部件",
        summary: "有机模型强调部分由整体关系取得功能，自然持续产生形式；审美经验使这种统一首先成为可感而非可演绎的方向。",
        pressure: "有机比喻可启发研究，也可能遮蔽冲突、偶然和不可逆损失；它不能取消机械解释的有效范围。",
        consequence: "艺术被赋予连接概念、感受与整体经验的哲学功能。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 345, lane: 2.5 },
      },
      {
        id: "can-art-yield-knowledge-without-final-system",
        kind: "问题",
        title: "艺术能否显露真实关系，又不冒充已经完成的科学或形而上学体系？",
        summary: "作品通过形式、视角和情感改变人看待对象的方式，却通常不能把其洞见化成一组穷尽性的命题。",
        pressure: "若只有私人感动，艺术失去公共批评；若必须翻译成概念证明，又会消除其独特作用。",
        consequence: "浪漫诗学以开放形式、象征和反讽保存可交流但未封闭的真理追求。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 346, lane: 2.5 },
      },
      {
        id: "aesthetic-form-keeps-whole-open-to-critique",
        kind: "答案", answerRole: "提出",
        title: "作品以开放形式和反讽逼近整体，同时展示自身视角仍有限",
        summary: "审美形式能组织多种相反力量而不立即消除差异；反讽则让创作者与受众保持对作品自我绝对化的距离。",
        pressure: "开放性可能退化为永不承担主张，天才崇拜也可能让作者人格取代作品和公共判断。",
        consequence: "个体创造怎样进入共同生活成为下一支线。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 347, lane: 2.5 },
      },
      {
        id: "revolution-rank-individuality-observation",
        kind: "观察",
        observation: { domain: "社会与制度", note: "革命和平等语言削弱出生等级的当然性，出版、艺术市场和公共名声又使独特人格成为可追求的社会身份。" },
        title: "旧等级受到挑战后，个人被要求自己形成身份，却仍依赖公共承认",
        summary: "自由不再只是占据既定角色，也包括发展独特能力；但独特性只有在语言、教育和他人回应中才可见。",
        pressure: "孤立自我不能创造全部意义，社会承认又可能把真实性变成新的表演和竞争。",
        consequence: "观察提出个体发展与共同体是否能够互相支持。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 344, lane: 4.3 },
      },
      {
        id: "can-individuality-and-sociality-support-each-other",
        kind: "问题",
        title: "独特个体怎样在社会关系中形成，而不被习俗同化或退回孤立任性？",
        summary: "教育、语言和承认使个体能力成为现实，但同一社会也能通过名望、规范和从众压扁差异。",
        pressure: "把真实自我设想成社会之前已经完成，会忽略成长条件；把自我完全交给共同体，又会取消批判距离。",
        consequence: "浪漫主义以形成、创造和相互承认而非静态本性理解个体。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 345, lane: 4.3 },
      },
      {
        id: "bildung-creative-individuality-within-relations",
        kind: "答案", answerRole: "综合",
        title: "个体性是在教育、创造和关系中形成的开放能力，不是反社会的原始冲动",
        summary: "自我形成需要吸收传统又重写传统，通过作品和行动让独特视角接受他人回应。",
        pressure: "形成理想可能只服务有教育资源者；民族、阶级和性别共同体也会把排除包装成有机统一。",
        consequence: "真实性必须继续接受权力和普遍自由的检验。",
        participants: [], chapterIds: ["b3-18"], graph: { row: 346, lane: 4.3 },
      },
      {
        id: "can-authentic-feeling-legitimate-political-power",
        kind: "问题",
        title: "真诚情感、共同文化或有机归属能否直接使政治权力正当？",
        summary: "共同记忆和情感可以支持团结，却不能证明谁有权代表整体，也不能让异议者自动成为不真实的人。",
        pressure: "只以抽象个人权利理解政治可能忽略依赖和公民形成，只以共同情感则可能吞没具体个人。",
        consequence: "问题回到卢梭：文明怎样制造依赖，社会契约又能否把共同体变成非支配自由。",
        participants: [{ name: "让-雅克·卢梭", philosopherId: "rousseau", role: "以文明批判、公意和教育成为浪漫主义与共和自由的共同前史" }],
        chapterIds: ["b3-18", "b3-19"], graph: { row: 348, lane: 3.7 },
      },
    ],
  },
  {
    id: "rousseau-inequality-education-general-will",
    order: 37,
    label: "文明、不平等与公意",
    title: "用假设性起源诊断社会依赖，再以教育和共同立法重建自由",
    question: "社会既使人成为可发展的道德主体，又制造比较、财产和支配；怎样在社会内部恢复自由？",
    transition: "卢梭不要求人实际返回孤立自然状态，也没有使用后来流行的‘高贵野蛮人’作为固定概念。他用起源叙事分离自然需要与社会制造的欲望，再分别在《爱弥儿》和《社会契约论》中探索个人形成与公共自由。",
    nodes: [
      {
        id: "civilization-can-refine-taste-yet-corrupt-virtue",
        kind: "答案", answerRole: "反驳",
        title: "科学、艺术和礼貌可以进步，却不保证德性、独立与公共自由同步增长",
        summary: "精致文化可能遮蔽依赖和虚荣，使人更关心他人评价而非真实需要与公民责任。",
        pressure: "文化批判不能忽略知识、艺术和公共讨论本身的解放能力，也不能把历史复杂性归罪于单一文明化过程。",
        consequence: "需要区分人的自然能力与特定社会关系造成的欲望和不平等。",
        participants: [{ name: "让-雅克·卢梭", philosopherId: "rousseau", role: "以《论科学与艺术》反驳文明进步自动等于德性进步" }],
        chapterIds: ["b3-18", "b3-19"], graph: { row: 349, lane: 3.7 },
      },
      {
        id: "are-humans-naturally-competitive-and-dominating",
        kind: "问题",
        title: "竞争、虚荣和支配是人的固定自然，还是特定社会关系的历史产物？",
        summary: "霍布斯式自然状态把互惧和竞争置于政治之前；卢梭怀疑这已把成熟社会人的欲望倒投给前社会人。",
        pressure: "自然状态不是可直接观察的史前报告；任何起源重建都依赖关于能力、环境和发展顺序的假设。",
        consequence: "卢梭从自我保存、怜悯与可完善性建立一条假设性生成路线。",
        participants: [], chapterIds: ["b3-19"], graph: { row: 350, lane: 1.0 },
      },
      {
        id: "amour-de-soi-pity-perfectibility-before-comparison",
        kind: "答案", answerRole: "转向",
        title: "前社会人首先由自我保存、自然怜悯和开放的可完善性组织",
        summary: "有限需要不必自动造成持续战争；学习和改变能力使语言、合作与文明可能，也使比较、依赖和新的欲望可能。",
        pressure: "这些能力的组合是批判性模型而非经验证实的人类学；自然怜悯也不能单独产生稳定公正制度。",
        consequence: "问题转向历史条件怎样把差异放大为制度性不平等。",
        participants: [{ name: "让-雅克·卢梭", philosopherId: "rousseau", role: "以 amour de soi、pitié 与 perfectibilité 重写自然人模型" }],
        chapterIds: ["b3-19"], graph: { row: 351, lane: 1.0 },
      },
      {
        id: "property-comparison-dependence-observation",
        kind: "观察",
        observation: { domain: "社会与制度", note: "稳定占有、劳动分工、财富积累与公共评价把偶然差异变成可继承地位，使生活资料和自我价值越来越依赖他人。" },
        title: "财产、分工与比较把自然差异转化为持续的依赖和等级",
        summary: "当资源可排他占有、名望可累积时，人不仅想生活，还想在他人眼中更有价值并控制合作条件。",
        pressure: "私有财产并非单一时刻由一句宣告创造；制度形成、农业、法律和暴力需要更复杂历史说明。",
        consequence: "观察提出自然不平等与道德—政治不平等应怎样区分。",
        participants: [{ name: "让-雅克·卢梭", philosopherId: "rousseau", role: "以财产、比较和分工诊断制度性不平等" }],
        chapterIds: ["b3-19"], graph: { row: 350, lane: 2.7 },
      },
      {
        id: "how-natural-difference-becomes-political-inequality",
        kind: "问题",
        title: "体力、年龄等自然差异怎样被转化为财富、荣誉和服从的政治不平等？",
        summary: "差异本身不决定谁能制定规则、继承资源或要求他人劳动；制度使偶然优势获得持续和正当化外观。",
        pressure: "制度并非只有压迫功能，也能稳定合作与权利；批判需要区分共同规则与私人支配。",
        consequence: "卢梭用一条猜想性历史说明财产、法律和政府怎样固化不平等。",
        participants: [], chapterIds: ["b3-19"], graph: { row: 351, lane: 2.7 },
      },
      {
        id: "conjectural-genealogy-of-property-law-inequality",
        kind: "答案", answerRole: "提出",
        title: "财产、法律和政府在历史发展中把比较优势固化为道德—政治不平等",
        summary: "起源叙事不是编年史，而是揭示现存等级并非自然必然：合作、占有、法律和权力逐步改变人的需要与自我理解。",
        pressure: "模型容易把复杂社会压成单线堕落史，也可能浪漫化前国家生活；其批判力量不依赖每一阶段都曾按顺序发生。",
        consequence: "社会依赖的心理机制集中到 amour-propre。",
        participants: [{ name: "让-雅克·卢梭", philosopherId: "rousseau", role: "以猜想性历史区分自然差异与制度不平等" }],
        chapterIds: ["b3-19"], graph: { row: 352, lane: 2.7 },
      },
      {
        id: "is-amour-propre-only-corrupting-vanity",
        kind: "问题",
        title: "依赖他人承认的 amour-propre 是否只能产生虚荣、嫉妒和支配？",
        summary: "社会人需要被视为有价值；这种比较欲常追求优越，却也可能转成对平等尊重和公正地位的要求。",
        pressure: "若完全消除承认需要，社会人格和尊严难以形成；若让比较任意扩张，平等永远被地位竞赛破坏。",
        consequence: "卢梭区分被煽动的优越欲与可由教育制度调节的平等承认。",
        participants: [], chapterIds: ["b3-19"], graph: { row: 353, lane: 2.7 },
      },
      {
        id: "amour-propre-can-be-inflamed-or-egalitarian",
        kind: "答案", answerRole: "区分",
        title: "社会性自爱既会追求优越，也可能被教育为相互尊重与平等地位",
        summary: "问题不只是个人压抑欲望，而是社会怎样分配尊重、依赖和发言资格，使人的自我价值不必建立在贬低他人上。",
        pressure: "卢梭没有给出现代多元社会中稳定调节承认冲突的完整制度，也保留明显的性别等级。",
        consequence: "个人形成问题进入《爱弥儿》的教育实验。",
        participants: [{ name: "让-雅克·卢梭", philosopherId: "rousseau", role: "把 amour-propre 作为可被制度塑形的社会激情" }],
        chapterIds: ["b3-19"], graph: { row: 354, lane: 2.7 },
      },
      {
        id: "how-educate-agency-without-premature-dependence",
        kind: "问题",
        title: "怎样让儿童形成判断与自制，而不以命令、虚荣和奖惩过早制造依赖？",
        summary: "直接灌输可能只训练服从；完全放任又不能提供安全、技能和接触现实后果的条件。",
        pressure: "教育环境由成人精心安排，本身并非没有权力；‘自然成长’不能遮蔽教师的隐性控制。",
        consequence: "卢梭以延迟抽象说教、让经验后果引导学习的消极教育回应。",
        participants: [], chapterIds: ["b3-19"], graph: { row: 355, lane: 1.8 },
      },
      {
        id: "negative-education-protects-developmental-agency",
        kind: "答案", answerRole: "提出",
        title: "消极教育先保护发展节奏，以安排后的经验而非虚荣奖惩培养自主判断",
        summary: "教育者减少不必要命令，让儿童通过事物阻力学习，再逐步进入情感、社会和道德关系。",
        pressure: "《爱弥儿》的性别分工、精英资源和全程操控限制其普遍性；经验学习也不自动产生公民平等。",
        consequence: "个人自主仍需与公共立法结构连接。",
        participants: [{ name: "让-雅克·卢梭", philosopherId: "rousseau", role: "以《爱弥儿》探索不由比较和命令主导的主体形成" }],
        chapterIds: ["b3-19"], graph: { row: 356, lane: 1.8 },
      },
      {
        id: "can-social-order-preserve-freedom",
        kind: "问题",
        title: "个人无法退出相互依赖时，什么社会秩序能让服从规则仍不等于服从他人？",
        summary: "安全契约若把权利永久让给统治者，只把私人依赖改成公共支配；财产权若先于共同规则固定，又会锁定不平等。",
        pressure: "共同体需要统一行动，却必须说明统一意志从何而来、怎样限制代表者并保存成员平等。",
        consequence: "社会契约把每个人同等交给整体，并让每个人作为公民共同拥有主权。",
        participants: [], chapterIds: ["b3-19"], graph: { row: 353, lane: 4.3 },
      },
      {
        id: "social-pact-creates-equal-citizen-sovereign",
        kind: "答案", answerRole: "转向",
        title: "每个人同等地把自身与权力交给共同体，并作为公民共同组成不可让渡的主权",
        summary: "没有成员把自己交给另一个私人；每个人以臣民身份服从法律，又以公民身份参与形成法律。",
        pressure: "形式上同等让渡不保证现实资源与发言能力平等，规模、派系和代表制度也会使共同立法困难。",
        consequence: "合法性集中到公意与众意的区分。",
        participants: [{ name: "让-雅克·卢梭", philosopherId: "rousseau", role: "以社会契约和人民主权重构政治自由" }],
        chapterIds: ["b3-19"], graph: { row: 354, lane: 4.3 },
      },
      {
        id: "how-general-will-differs-from-will-of-all",
        kind: "问题",
        title: "公意怎样区别于私人偏好的总和、即时多数意见或统治者自称的共同利益？",
        summary: "每个人都有私人利益，也能以公民身份考虑所有人共同受其约束的规则；两种立场不会自动一致。",
        pressure: "若公意独立于实际公民判断，解释者可垄断它；若只等于投票多数，又无法区分派系优势和共同利益。",
        consequence: "公意被界定为公民面向共同利益、制定普遍法律的意志。",
        participants: [], chapterIds: ["b3-19"], graph: { row: 355, lane: 4.3 },
      },
      {
        id: "general-will-aims-common-interest-not-sum",
        kind: "答案", answerRole: "区分",
        title: "公意指向共同利益和普遍法律，不是所有私人欲望的算术相加",
        summary: "公民不是预测哪一派获胜，而是判断自己与所有人都将受其约束的规则；法律不能点名给特定个人特权。",
        pressure: "共同利益存在多种合理解释，高度不平等会使同一法律对各人产生完全不同后果。",
        consequence: "公意需要程序、相对平等和公民德性等社会条件。",
        participants: [{ name: "让-雅克·卢梭", philosopherId: "rousseau", role: "区分 volonté générale 与 volonté de tous" }],
        chapterIds: ["b3-19"], graph: { row: 356, lane: 4.3 },
      },
      {
        id: "what-conditions-let-general-will-emerge",
        kind: "问题",
        title: "哪些程序与社会条件能让公民真正从共同立场判断？",
        summary: "投票本身不能消除派系、经济支配、信息不平等和操纵；公意需要成员能够把自己视为平等共同体的一部分。",
        pressure: "小规模、共同习俗和低不平等的要求难以直接移植到大型多元社会；立法者角色又可能凌驾公民。",
        consequence: "卢梭要求法律来自全体并普遍适用，同时依赖公民形成与相对平等。",
        participants: [], chapterIds: ["b3-19"], graph: { row: 357, lane: 4.3 },
      },
      {
        id: "laws-from-all-apply-to-all-under-equality",
        kind: "答案", answerRole: "修复",
        title: "法律须来自全体、适用于全体，并由相对平等和公民德性支持",
        summary: "普遍适用迫使公民考虑自己也可能承受法律后果；限制极端财富和依附有助于共同判断不被私人权力劫持。",
        pressure: "实质共同利益不能只靠法律形式保证，公民德性培养也可能滑向强制同质化。",
        consequence: "最尖锐的压力转向异议者与‘被迫自由’。",
        participants: [{ name: "让-雅克·卢梭", philosopherId: "rousseau", role: "以普遍法律、公民德性和相对平等说明公意条件" }],
        chapterIds: ["b3-19"], graph: { row: 358, lane: 4.3 },
      },
      {
        id: "can-citizen-be-forced-to-be-free",
        kind: "问题",
        title: "共同体声称迫使异议者‘获得自由’时，如何避免把压迫重新命名为公意？",
        summary: "若契约义务使每人免受私人支配，执行共同法律似乎保护自由；但谁解释公意、怎样承认持续异议仍是危险接口。",
        pressure: "把任何实际国家等同公意会取消批判；把自由只等于退出，又忽略规则共同制定和防止支配的价值。",
        consequence: "卢梭式自由须被限定为参与普遍法律的公民自律，而非统治者无条件替人民定义真实意志。",
        participants: [], chapterIds: ["b3-19"], graph: { row: 359, lane: 4.0 },
      },
      {
        id: "civil-freedom-as-nondomination-with-authoritarian-risk",
        kind: "答案", answerRole: "区分",
        title: "公民自由是服从自己共同制定的普遍法律，但执行逻辑始终带有整体主义风险",
        summary: "正当强制针对契约内共同规则而非私人任性；公意不能由领袖、党派或多数身份自动垄断。",
        pressure: "卢梭没有充分解决现代多元社会的权利保障、代表、反对派和退出问题，性别排除也违背其普遍语言。",
        consequence: "自由从不受干涉推进为自我立法，并直接影响康德的道德自律问题。",
        participants: [{ name: "让-雅克·卢梭", philosopherId: "rousseau", role: "把自然独立转化为共同立法下的公民自由" }],
        chapterIds: ["b3-19"], graph: { row: 360, lane: 4.0 },
      },
      {
        id: "can-self-legislation-be-universal-without-one-community",
        kind: "问题",
        title: "自我立法能否成为每个理性者的普遍自由，而不依赖单一共同体的同质公意？",
        summary: "卢梭把自由与共同立法相连，却依赖特定公民共同体；道德义务似乎还要求一种跨地域、身份和利益的普遍标准。",
        pressure: "标准若来自经验共同体便可能地方化，若来自纯理性又必须说明它怎样约束有欲望、处于因果自然中的人。",
        consequence: "康德将把公民自律转化为理性意志给自身制定普遍法则。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "将把卢梭的自我立法问题推进为道德自主" }],
        chapterIds: ["b3-19", "b3-20"], graph: { row: 361, lane: 4.0 },
      },
    ],
  },
  {
    id: "kant-experience-autonomy-judgment",
    order: 38,
    label: "经验条件、道德自律与判断",
    title: "不从经验抽取必然性，而追问经验与自由得以可能的主体条件",
    question: "怎样同时保存经验科学的客观性、人的道德自由与理性不可越界的限度？",
    transition: "康德没有在理性主义和经验主义之间简单折中。他接受休谟关于经验不能给出必然联系的挑战，却反问：若没有先天统一规则，连一个可判断的经验对象和客观事件次序都不能形成。卢梭的自我立法则使自由从满足欲望转向普遍规范。",
    nodes: [
      {
        id: "copernican-turn-objects-conform-to-cognition",
        kind: "答案", answerRole: "转向",
        title: "先检验对象作为经验对象必须符合哪些认识条件，而非假定认识被动复制对象",
        summary: "感性提供材料，主体的直观形式与知性规则使材料成为有时空位置、可判断、彼此关联的经验对象。",
        pressure: "这不等于个人想象创造现实，也不能把认识条件未经论证地当作事物自身属性。",
        consequence: "康德必须说明哪些先天结构使扩展知识而又具有必然性的判断可能。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "以哥白尼式转向回应休谟并重设认识问题" }],
        chapterIds: ["b3-20"], graph: { row: 342, lane: 1.9 },
      },
      {
        id: "how-are-synthetic-a-priori-judgments-possible",
        kind: "问题",
        title: "扩展知识却不依赖逐次归纳的综合先天判断怎样可能？",
        summary: "数学和基础自然科学似乎既增加内容又要求普遍必然；它们不能只是定义分析，也不能由有限样本获得必然性。",
        pressure: "康德对数学和牛顿科学结构的判断带有时代性；具体科学定律仍需经验，不能全部称作先天。",
        consequence: "答案先从感性接受任何对象时已经使用的空间与时间形式展开。",
        participants: [], chapterIds: ["b3-20"], graph: { row: 362, lane: 0.8 },
      },
      {
        id: "appearances-arrive-spatiotemporally-observation",
        kind: "观察",
        observation: { domain: "个体体验", note: "任何外部对象都呈现为空间中的并列与关系，任何内外经验都呈现为时间中的先后；经验不能退到一个完全无时空组织的感觉材料。" },
        title: "人所经验的一切现象已经处于空间并列与时间先后之中",
        summary: "空间和时间不是从若干对象比较后才添加的普通性质，而是对象能够被给予和区分的普遍框架。",
        pressure: "从经验不可脱离时空到时空属于主体直观形式，需要先验论证；非人类认识是否共享同一形式也不能由此决定。",
        consequence: "观察提出空间与时间是对象自身容器还是人的感性形式。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "从经验给予方式分析空间与时间" }],
        chapterIds: ["b3-20"], graph: { row: 362, lane: 0.1 },
      },
      {
        id: "are-space-time-things-or-forms-of-intuition",
        kind: "问题",
        title: "空间与时间是独立事物、对象性质，还是主体接受现象的直观形式？",
        summary: "它们具有普遍结构并支持数学，却不能像普通对象那样被经验为其中一个对象。",
        pressure: "若只称主观，容易被误解为私人幻觉；康德必须说明它们为何对所有可能人类经验具有客观有效性。",
        consequence: "空间与时间被界定为感性的先天形式，适用于现象而不宣称描述物自身。",
        participants: [], chapterIds: ["b3-20"], graph: { row: 363, lane: 0.5 },
      },
      {
        id: "space-time-a-priori-forms-of-intuition",
        kind: "答案", answerRole: "区分",
        title: "空间与时间是人类感性的先天直观形式，对一切现象有效而不规定物自身",
        summary: "几何与算术的结构建立在对象被给予的形式上；这种‘先验观念论’同时主张经验世界的时空关系真实有效。",
        pressure: "怎样理解现象与物自身、不同主体共享对象，以及非欧几何和现代物理对先天性主张的影响，均有后续争论。",
        consequence: "时空材料仍需概念统一，才能成为判断中的对象。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "以先验感性论说明空间与时间的经验有效性和认识限度" }],
        chapterIds: ["b3-20"], graph: { row: 364, lane: 0.5 },
      },
      {
        id: "how-manifold-becomes-one-objective-experience",
        kind: "问题",
        title: "多样感觉怎样被综合成同一对象和可由‘我思’伴随的经验？",
        summary: "只有颜色、声音和先后流动，还没有稳定对象、数量、实体或原因；知觉必须按规则结合。",
        pressure: "若统一来自实体灵魂，会重回无经验形而上学；若只是联想习惯，又难以说明客观判断的必然形式。",
        consequence: "康德以想象的综合、范畴和统觉统一说明对象性。",
        participants: [], chapterIds: ["b3-20"], graph: { row: 365, lane: 1.5 },
      },
      {
        id: "categories-and-apperception-unify-experience",
        kind: "答案", answerRole: "综合",
        title: "知性范畴按规则综合多样表象，统觉统一使它们属于一个可判断经验",
        summary: "实体、因果、共同作用等不是从孤立感觉复制的图像，而是把表象组合成对象判断的基本功能。",
        pressure: "范畴表及其推导是否完备、统觉论证是否成功，长期存在争议；统一意识也不是对灵魂实体的知识。",
        consequence: "休谟的因果问题被改写为客观事件次序怎样可能。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "以范畴和先验统觉重构对象与主体统一" }],
        chapterIds: ["b3-20"], graph: { row: 366, lane: 1.5 },
      },
      {
        id: "how-subjective-succession-becomes-objective-event",
        kind: "问题",
        title: "知觉总是先后出现时，什么使某些先后成为对象自身不可逆的事件次序？",
        summary: "看房屋可从屋顶转向地基，也可反向；看船顺流则事件顺序不能任意倒转。仅有心理先后无法区分两者。",
        pressure: "客观次序原则不直接告诉我们哪条具体因果定律为真，仍需观察和实验。",
        consequence: "因果范畴被视为经验事件能够被客观判断的先天规则。",
        participants: [], chapterIds: ["b3-20"], graph: { row: 367, lane: 1.5 },
      },
      {
        id: "causality-as-condition-of-objective-succession",
        kind: "答案", answerRole: "修复",
        title: "因果规则不是从重复感觉抽出的力量，而是把变化判断为客观事件的条件",
        summary: "每个事件必须能在某条规则下由先行状态确定，才不只是我的表象偶然先后；具体规则则由经验研究发现。",
        pressure: "这一先验论证能否建立普遍因果原则、以及现代概率科学怎样理解因果，仍需独立评估。",
        consequence: "康德声称回应休谟，却把范畴有效性严格限制在可能经验内。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "以第二类比把因果性重建为客观经验条件" }],
        chapterIds: ["b3-20"], graph: { row: 368, lane: 1.5 },
      },
      {
        id: "do-cognitive-conditions-describe-things-in-themselves",
        kind: "问题",
        title: "经验对象服从时空与范畴，是否意味着物自身也必定如此？",
        summary: "先验结构保证现象对象性，却只在人的接受和判断条件下获得合法使用。",
        pressure: "物自身若完全不可知，为何还要设定；若可说它影响感性，又似乎越过范畴限度。",
        consequence: "康德区分现象知识与物自身作为限制概念。",
        participants: [], chapterIds: ["b3-20"], graph: { row: 369, lane: 1.5 },
      },
      {
        id: "knowledge-limited-to-phenomena-not-private-illusion",
        kind: "答案", answerRole: "区分",
        title: "知识限于现象，但现象是公共而客观的经验世界，不是私人幻觉",
        summary: "对象在共同时空和范畴规则中可被判断、检验和纠错；‘物自身’标记这些条件不能被无界限外推。",
        pressure: "现象／物自身的两世界或两方面解释存在竞争；界限若固定不清，也会刺激后继观念论者试图超越。",
        consequence: "传统理性心理学、宇宙论和自然神学必须接受批判。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "以先验观念论兼顾经验实在与形而上学限界" }],
        chapterIds: ["b3-20"], graph: { row: 370, lane: 1.5 },
      },
      {
        id: "what-status-for-soul-world-god-ideas",
        kind: "问题",
        title: "灵魂、世界整体和上帝不能成为经验对象时，理性为何仍不断形成这些理念？",
        summary: "理性追求无条件整体，把每条解释继续推向最后主体、完整世界和最高根据。",
        pressure: "若把理念当对象知识，会产生谬误和二律背反；若完全删除，系统探究和实践方向又失去整体目标。",
        consequence: "理念被保留为规约探究的方向，而非构成对象的理论知识。",
        participants: [], chapterIds: ["b3-20"], graph: { row: 371, lane: 1.5 },
      },
      {
        id: "ideas-regulative-not-constitutive-knowledge",
        kind: "答案", answerRole: "区分",
        title: "理性理念可规约知识追求系统统一，却不能构成超经验对象的理论证明",
        summary: "研究可以像世界具有更完整秩序那样继续寻找解释，但不能仅凭这一需要证明灵魂实体、宇宙全体或上帝存在。",
        pressure: "理论限制与实践信念的关系必须另行说明，否则批判哲学会在后门恢复被禁止的对象。",
        consequence: "认识论支线为实践理性的自由问题腾出空间。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "批判理性理念的构成性越界并保留规约功能" }],
        chapterIds: ["b3-20"], graph: { row: 372, lane: 1.5 },
      },
      {
        id: "duty-can-conflict-with-inclination-observation",
        kind: "观察",
        observation: { domain: "个体体验", note: "人会把某些行为认作应当，即使它违背即时利益、情感或外部命令；道德要求以无条件语气出现。" },
        title: "道德义务有时要求人反对自己的利益、欲望和社会压力",
        summary: "若规范只表达最强欲望或奖惩计算，就难以说明人为何批评自身欲望并要求同类理由适用于所有人。",
        pressure: "义务体验可能受历史教育塑造；从其无条件表象到纯理性法则仍需论证。",
        consequence: "观察提出普遍道德约束的来源。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "从善良意志与义务意识寻找道德最高原则" }],
        chapterIds: ["b3-20"], graph: { row: 362, lane: 3.0 },
      },
      {
        id: "what-makes-moral-law-universal",
        kind: "问题",
        title: "什么原则能无条件约束每个理性者，而不依赖欲望内容、权威命令或地方习俗？",
        summary: "经验目标只在行动者欲求它时给出条件性理由；道德义务则声称不因偏好改变而失效。",
        pressure: "纯形式原则若过于抽象，可能无法区分现实处境中的义务；应用仍需要判断和经验知识。",
        consequence: "康德以可普遍立法的行动准则表达定言命令。",
        participants: [], chapterIds: ["b3-20"], graph: { row: 363, lane: 3.0 },
      },
      {
        id: "categorical-imperative-universal-law",
        kind: "答案", answerRole: "提出",
        title: "只按自己同时能够意愿成为普遍法则的准则行动",
        summary: "行动者不能为自己保留一个若人人采用便破坏行动目的或无法共同意愿的例外。",
        pressure: "准则描述方式会影响检验结果，冲突义务与后果敏感性也需要更完整的道德判断。",
        consequence: "普遍立法进一步要求每个理性者都不能只被当作工具。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "以定言命令的普遍法则公式说明道德形式" }],
        chapterIds: ["b3-20"], graph: { row: 364, lane: 3.0 },
      },
      {
        id: "can-persons-be-used-merely-as-means",
        kind: "问题",
        title: "普遍立法为什么要求把每个人视为目的，而不能只当作实现他人计划的工具？",
        summary: "能够设定目的和审查理由的行动者具有不可由价格完全替代的地位；欺骗和强迫绕过其同意能力。",
        pressure: "尊严原则仍需处理依赖、照护、制度不平等和非理性生命的道德地位。",
        consequence: "人格被置于目的王国的共同立法者位置。",
        participants: [], chapterIds: ["b3-20"], graph: { row: 365, lane: 3.0 },
      },
      {
        id: "humanity-as-end-and-kingdom-of-ends",
        kind: "答案", answerRole: "综合",
        title: "把自己和他人的人格始终同时当作目的，并设想平等立法的目的王国",
        summary: "道德共同体不是把私人偏好相加，而是每个成员既服从又制定可普遍认可的法则；卢梭的公民自律被普遍化。",
        pressure: "康德本人在人类学、种族和性别文字中没有一致实践这一普遍原则，历史矛盾必须保留。",
        consequence: "自律成为道德法则的根基，也使自由问题重新出现。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "以人格目的和目的王国扩展自我立法" }],
        chapterIds: ["b3-20"], graph: { row: 366, lane: 3.0 },
      },
      {
        id: "autonomy-as-rational-self-legislation",
        kind: "答案", answerRole: "转向",
        title: "自由不是满足欲望，而是理性意志为自己制定并服从普遍法则",
        summary: "他律让行动由欲望对象、奖惩或外部权威决定；自律则让行动者只接受自己作为理性者也能共同立法的原则。",
        pressure: "抽象自律不能替代真实政治参与，也可能低估情感、身体、关系和物质条件对能动性的支持。",
        consequence: "道德自由必须与现象世界中的自然因果相容。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "把卢梭式自我立法普遍化为道德自主" }],
        chapterIds: ["b3-20"], graph: { row: 362, lane: 4.2 },
      },
      {
        id: "how-can-freedom-coexist-with-natural-causality",
        kind: "问题",
        title: "一切现象事件服从因果规则时，人怎样仍能被视为自由行动者？",
        summary: "作为可观察的人，行动有心理、生理和社会原因；作为道德主体，人又必须把自己视为能够依理由行动。",
        pressure: "把自由移到不可知领域可能只避免逻辑矛盾，未说明自由怎样在经验行动中产生差异。",
        consequence: "康德以现象与理智立场区分理论因果说明和实践自我理解。",
        participants: [], chapterIds: ["b3-20"], graph: { row: 367, lane: 3.6 },
      },
      {
        id: "two-standpoints-natural-causality-practical-freedom",
        kind: "答案", answerRole: "区分",
        title: "同一行动在现象层可受自然因果说明，在实践立场又须按自由自律归责",
        summary: "理论知识不能观察超经验自由，但道德审议要求行动者把自己视为能开始一条依理性法则的因果序列。",
        pressure: "两种立场怎样属于同一行动者并非透明；后继者会批评物自身自由造成无法统一的二分。",
        consequence: "实践理性获得优先地位，却不把自由变成理论对象知识。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "以两种立场协调自然必然与道德自由" }],
        chapterIds: ["b3-20"], graph: { row: 368, lane: 3.6 },
      },
      {
        id: "can-practical-reason-know-transcendent-freedom",
        kind: "问题",
        title: "道德实践需要自由，是否等于理论理性已经证明一个超经验自由对象？",
        summary: "行动者必须在审议中预设自由，否则义务失去意义；但预设的实践资格不同于对自由机制的认识。",
        pressure: "若实践需要可以证明存在，其他愿望也可能被误用为形而上学证据；边界必须清楚。",
        consequence: "自由被合理地信取为实践理性的条件，而非扩展理论知识。",
        participants: [], chapterIds: ["b3-20"], graph: { row: 369, lane: 3.6 },
      },
      {
        id: "freedom-practical-postulate-not-theoretical-object",
        kind: "答案", answerRole: "区分",
        title: "自由具有实践必需性，却不是可由纯理论理性描述的经验或超经验对象",
        summary: "道德法则使人有资格从实践立场信取自由；这一信取不撤销《纯粹理性批判》对知识范围的限制。",
        pressure: "理论与实践的分工是否稳定，以及自由如何落实于历史制度，将成为德国观念论的后续压力。",
        consequence: "自由与自然之间仍需要判断力搭桥。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "限制实践信取与理论知识的混同" }],
        chapterIds: ["b3-20"], graph: { row: 370, lane: 3.6 },
      },
      {
        id: "beauty-organisms-purposiveness-observation",
        kind: "观察",
        observation: { domain: "自然经验", note: "审美对象呈现无需确定概念即可共享讨论的合目的性，生物部分又像彼此既是原因又是结果；机械因果说明在这些经验前显得不够完整。" },
        title: "美与有机体使自然呈现仿佛合目的的整体，却没有直接给出一个已知目的",
        summary: "人在美中感到想象与知性自由协调，在生物中则必须把部分放回自组织整体理解。",
        pressure: "‘仿佛有目的’不能直接证明设计者或整个自然真的有意图；判断方式与对象本体必须区分。",
        consequence: "观察提出判断力怎样在自然必然与自由目的之间搭桥。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "以审美与目的论判断处理自然—自由过渡" }],
        chapterIds: ["b3-20"], graph: { row: 371, lane: 4.5 },
      },
      {
        id: "how-judgment-bridges-nature-and-freedom",
        kind: "问题",
        title: "不把目的强加为自然知识时，判断力怎样使自然可被看作容纳自由与生命？",
        summary: "知性给自然立法，理性给自由立法；两域若完全断裂，道德目的似乎无法在经验世界中实现。",
        pressure: "桥梁若只是主观感受，不能完成体系统一；若成为客观目的论，又越出批判界限。",
        consequence: "反思判断以无确定目的的合目的性规约审美和生命研究。",
        participants: [], chapterIds: ["b3-20"], graph: { row: 372, lane: 4.5 },
      },
      {
        id: "reflective-judgment-purposiveness-without-proof",
        kind: "答案", answerRole: "修复",
        title: "反思判断把合目的性作为寻找整体秩序的原则，而不把它当作设计的理论证明",
        summary: "审美判断要求可交流而不靠概念演绎，有机研究则像自然有目的那样寻找部分—整体关系。",
        pressure: "浪漫主义者会把康德保留为反思原则的有机自然进一步实在化；这种推进并非康德结论本身。",
        consequence: "康德体系提供浪漫主义资源，也留下自然、自由和历史统一是否只在主体中完成的问题。",
        participants: [{ name: "伊曼努尔·康德", philosopherId: "kant", role: "以反思判断限制并保存审美和目的论的哲学功能" }],
        chapterIds: ["b3-20"], graph: { row: 373, lane: 4.5 },
      },
      {
        id: "can-subject-object-nature-freedom-unify-historically",
        kind: "问题",
        title: "主体与对象、自然与自由、现象与物自身的分界能否在一个历史发展中得到统一？",
        summary: "康德说明各分界为何必要，却留下多个彼此限制的二元结构；浪漫主义和后康德思想要求整体不能只是不可达到的规约目标。",
        pressure: "取消界限可能重启无约束体系形而上学，固定界限又会使理性无法说明自身与世界的共同历史。",
        consequence: "第三卷第二十一至二十二章将经十九世纪思想潮流进入黑格尔的辩证—历史整体。",
        participants: [{ name: "格奥尔格·威廉·弗里德里希·黑格尔", philosopherId: "hegel", role: "将批评康德固定二分并把自由放入历史制度发展" }],
        chapterIds: ["b3-20", "b3-21", "b3-22"], graph: { row: 374, lane: 2.8 },
      },
    ],
  },
];

export const romanticKantProblemEdges: ProblemEdge[] = [
  { id: "rk001", from: "progress-status-alienation-observation", to: "what-do-calculation-and-progress-miss", relation: "提出问题", label: "进步与疏离并存暴露单一衡量尺度", connection: "历史回应" },
  { id: "rk002", from: "what-do-calculation-and-progress-miss", to: "sensibility-imagination-complete-reason", relation: "回应问题", label: "以感受力和想象补充抽象计算", connection: "历史回应" },
  { id: "rk003", from: "sensibility-imagination-complete-reason", to: "is-romanticism-simple-irrationalism", relation: "产生问题", label: "补充理性不能滑向取消批判", connection: "本站推演" },
  { id: "rk004", from: "is-romanticism-simple-irrationalism", to: "romantic-critique-synthesizes-reason-and-sensibility", relation: "回应问题", label: "区分综合理性感性与激情主权", connection: "后世重构" },
  { id: "rk005", from: "mechanistic-nature-alienation-observation", to: "is-nature-only-mechanical-system", relation: "提出问题", label: "机械解释的成功与还原代价并存", connection: "历史回应" },
  { id: "rk006", from: "is-nature-only-mechanical-system", to: "organic-living-nature-as-romantic-countermodel", relation: "回应问题", label: "以有机生成整体补充机械模型", connection: "历史回应" },
  { id: "rk007", from: "organic-living-nature-as-romantic-countermodel", to: "can-art-yield-knowledge-without-final-system", relation: "产生问题", label: "有机统一首先经审美形式呈现", connection: "历史回应" },
  { id: "rk008", from: "can-art-yield-knowledge-without-final-system", to: "aesthetic-form-keeps-whole-open-to-critique", relation: "回应问题", label: "以开放形式和反讽保存有限整体", connection: "历史回应" },
  { id: "rk009", from: "romantic-critique-synthesizes-reason-and-sensibility", to: "can-art-yield-knowledge-without-final-system", relation: "产生问题", label: "扩展理性要求说明艺术的认识资格", connection: "本站推演" },
  { id: "rk010", from: "revolution-rank-individuality-observation", to: "can-individuality-and-sociality-support-each-other", relation: "提出问题", label: "身份自主扩大同时增加承认依赖", connection: "历史回应" },
  { id: "rk011", from: "can-individuality-and-sociality-support-each-other", to: "bildung-creative-individuality-within-relations", relation: "回应问题", label: "以形成和创造连接个体与关系", connection: "历史回应" },
  { id: "rk012", from: "bildung-creative-individuality-within-relations", to: "can-authentic-feeling-legitimate-political-power", relation: "产生问题", label: "真实性仍需公共正当性检验", connection: "本站推演" },
  { id: "rk013", from: "aesthetic-form-keeps-whole-open-to-critique", to: "can-authentic-feeling-legitimate-political-power", relation: "产生问题", label: "审美整体不能直接授权政治代表", connection: "后世重构" },
  { id: "rk014", from: "can-authentic-feeling-legitimate-political-power", to: "civilization-can-refine-taste-yet-corrupt-virtue", relation: "回应问题", label: "先以文明批判揭示共同情感的社会塑形", connection: "历史回应" },
  { id: "rk015", from: "civilization-can-refine-taste-yet-corrupt-virtue", to: "are-humans-naturally-competitive-and-dominating", relation: "产生问题", label: "文明腐化论要求区分自然与社会欲望", connection: "原书线索" },
  { id: "rk016", from: "are-humans-naturally-competitive-and-dominating", to: "amour-de-soi-pity-perfectibility-before-comparison", relation: "回应问题", label: "以自存、怜悯和可完善性重写自然人", connection: "原书线索" },
  { id: "rk017", from: "amour-de-soi-pity-perfectibility-before-comparison", to: "how-natural-difference-becomes-political-inequality", relation: "产生问题", label: "开放能力使历史分化成为可能", connection: "原书线索" },
  { id: "rk018", from: "property-comparison-dependence-observation", to: "how-natural-difference-becomes-political-inequality", relation: "提出问题", label: "财产和比较把差异固化为等级", connection: "原书线索" },
  { id: "rk019", from: "how-natural-difference-becomes-political-inequality", to: "conjectural-genealogy-of-property-law-inequality", relation: "回应问题", label: "以猜想性历史揭示制度生成", connection: "原书线索" },
  { id: "rk020", from: "conjectural-genealogy-of-property-law-inequality", to: "is-amour-propre-only-corrupting-vanity", relation: "产生问题", label: "制度依赖内化为比较性自爱", connection: "原书线索" },
  { id: "rk021", from: "is-amour-propre-only-corrupting-vanity", to: "amour-propre-can-be-inflamed-or-egalitarian", relation: "回应问题", label: "区分优越竞争与平等承认", connection: "历史回应" },
  { id: "rk022", from: "amour-propre-can-be-inflamed-or-egalitarian", to: "how-educate-agency-without-premature-dependence", relation: "产生问题", label: "可塑社会激情要求教育条件", connection: "历史回应" },
  { id: "rk023", from: "how-educate-agency-without-premature-dependence", to: "negative-education-protects-developmental-agency", relation: "回应问题", label: "以发展节奏和经验后果替代虚荣奖惩", connection: "原书线索" },
  { id: "rk024", from: "conjectural-genealogy-of-property-law-inequality", to: "can-social-order-preserve-freedom", relation: "产生问题", label: "不平等生成史要求非支配制度回应", connection: "原书线索" },
  { id: "rk025", from: "negative-education-protects-developmental-agency", to: "can-social-order-preserve-freedom", relation: "产生问题", label: "个人自主必须进入公共立法", connection: "本站推演" },
  { id: "rk026", from: "can-social-order-preserve-freedom", to: "social-pact-creates-equal-citizen-sovereign", relation: "回应问题", label: "以同等交付和共同主权重构自由", connection: "原书线索" },
  { id: "rk027", from: "social-pact-creates-equal-citizen-sovereign", to: "how-general-will-differs-from-will-of-all", relation: "产生问题", label: "共同主权要求界定公意", connection: "原书线索" },
  { id: "rk028", from: "how-general-will-differs-from-will-of-all", to: "general-will-aims-common-interest-not-sum", relation: "回应问题", label: "区分共同利益与私人欲望总和", connection: "原书线索" },
  { id: "rk029", from: "general-will-aims-common-interest-not-sum", to: "what-conditions-let-general-will-emerge", relation: "产生问题", label: "公意概念需要现实形成条件", connection: "历史回应" },
  { id: "rk030", from: "what-conditions-let-general-will-emerge", to: "laws-from-all-apply-to-all-under-equality", relation: "回应问题", label: "以普遍法律、平等和公民德性约束", connection: "历史回应" },
  { id: "rk031", from: "laws-from-all-apply-to-all-under-equality", to: "can-citizen-be-forced-to-be-free", relation: "产生问题", label: "共同执行开放异议与强制风险", connection: "原书线索" },
  { id: "rk032", from: "can-citizen-be-forced-to-be-free", to: "civil-freedom-as-nondomination-with-authoritarian-risk", relation: "回应问题", label: "限定为共同立法下的非支配自由", connection: "后世重构" },
  { id: "rk033", from: "civil-freedom-as-nondomination-with-authoritarian-risk", to: "can-self-legislation-be-universal-without-one-community", relation: "产生问题", label: "公民自律开放普遍道德自律", connection: "历史回应" },
  { id: "rk034", from: "can-objective-experience-have-necessity-beyond-habit", to: "copernican-turn-objects-conform-to-cognition", relation: "回应问题", label: "把必然性转为经验对象的先天条件", connection: "历史回应" },
  { id: "rk035", from: "copernican-turn-objects-conform-to-cognition", to: "how-are-synthetic-a-priori-judgments-possible", relation: "产生问题", label: "主体条件必须解释综合先天知识", connection: "原书线索" },
  { id: "rk036", from: "appearances-arrive-spatiotemporally-observation", to: "are-space-time-things-or-forms-of-intuition", relation: "提出问题", label: "经验不可脱离时空组织", connection: "原书线索" },
  { id: "rk037", from: "how-are-synthetic-a-priori-judgments-possible", to: "space-time-a-priori-forms-of-intuition", relation: "回应问题", label: "数学先由直观先天形式获得条件", connection: "原书线索" },
  { id: "rk038", from: "are-space-time-things-or-forms-of-intuition", to: "space-time-a-priori-forms-of-intuition", relation: "回应问题", label: "把时空限定为现象的直观形式", connection: "原书线索" },
  { id: "rk039", from: "space-time-a-priori-forms-of-intuition", to: "how-manifold-becomes-one-objective-experience", relation: "产生问题", label: "被给予的多样仍需概念综合", connection: "原书线索" },
  { id: "rk040", from: "how-manifold-becomes-one-objective-experience", to: "categories-and-apperception-unify-experience", relation: "回应问题", label: "以范畴和统觉统一建立对象性", connection: "原书线索" },
  { id: "rk041", from: "categories-and-apperception-unify-experience", to: "how-subjective-succession-becomes-objective-event", relation: "产生问题", label: "一般统一要求因果次序个案", connection: "原书线索" },
  { id: "rk042", from: "how-subjective-succession-becomes-objective-event", to: "causality-as-condition-of-objective-succession", relation: "回应问题", label: "以规则性因果区分事件与知觉次序", connection: "原书线索" },
  { id: "rk043", from: "causality-as-condition-of-objective-succession", to: "do-cognitive-conditions-describe-things-in-themselves", relation: "产生问题", label: "先天有效性必须限定使用范围", connection: "原书线索" },
  { id: "rk044", from: "do-cognitive-conditions-describe-things-in-themselves", to: "knowledge-limited-to-phenomena-not-private-illusion", relation: "回应问题", label: "区分经验实在与物自身限界", connection: "原书线索" },
  { id: "rk045", from: "knowledge-limited-to-phenomena-not-private-illusion", to: "what-status-for-soul-world-god-ideas", relation: "产生问题", label: "知识限界要求重审理性整体理念", connection: "原书线索" },
  { id: "rk046", from: "what-status-for-soul-world-god-ideas", to: "ideas-regulative-not-constitutive-knowledge", relation: "回应问题", label: "保留规约统一并拒绝对象化证明", connection: "原书线索" },
  { id: "rk047", from: "can-self-legislation-be-universal-without-one-community", to: "autonomy-as-rational-self-legislation", relation: "回应问题", label: "把公民自律普遍化为理性意志自律", connection: "历史回应" },
  { id: "rk048", from: "duty-can-conflict-with-inclination-observation", to: "what-makes-moral-law-universal", relation: "提出问题", label: "无条件义务经验要求非欲望根据", connection: "原书线索" },
  { id: "rk049", from: "what-makes-moral-law-universal", to: "categorical-imperative-universal-law", relation: "回应问题", label: "以可普遍立法准则表达定言命令", connection: "原书线索" },
  { id: "rk050", from: "categorical-imperative-universal-law", to: "can-persons-be-used-merely-as-means", relation: "产生问题", label: "普遍立法要求说明立法者地位", connection: "原书线索" },
  { id: "rk051", from: "can-persons-be-used-merely-as-means", to: "humanity-as-end-and-kingdom-of-ends", relation: "回应问题", label: "以人格目的和共同立法保存尊严", connection: "原书线索" },
  { id: "rk052", from: "humanity-as-end-and-kingdom-of-ends", to: "how-can-freedom-coexist-with-natural-causality", relation: "产生问题", label: "道德归责与自然因果形成二律背反", connection: "原书线索" },
  { id: "rk053", from: "autonomy-as-rational-self-legislation", to: "how-can-freedom-coexist-with-natural-causality", relation: "产生问题", label: "自律要求说明自由的可能性", connection: "原书线索" },
  { id: "rk054", from: "how-can-freedom-coexist-with-natural-causality", to: "two-standpoints-natural-causality-practical-freedom", relation: "回应问题", label: "以现象与实践立场区分协调", connection: "原书线索" },
  { id: "rk055", from: "two-standpoints-natural-causality-practical-freedom", to: "can-practical-reason-know-transcendent-freedom", relation: "产生问题", label: "两立场仍需限制实践信取范围", connection: "原书线索" },
  { id: "rk056", from: "can-practical-reason-know-transcendent-freedom", to: "freedom-practical-postulate-not-theoretical-object", relation: "回应问题", label: "区分实践必需与理论对象知识", connection: "原书线索" },
  { id: "rk057", from: "beauty-organisms-purposiveness-observation", to: "how-judgment-bridges-nature-and-freedom", relation: "提出问题", label: "审美与生命整体要求反思判断", connection: "原书线索" },
  { id: "rk058", from: "how-judgment-bridges-nature-and-freedom", to: "reflective-judgment-purposiveness-without-proof", relation: "回应问题", label: "以无证明的合目的性规约搭桥", connection: "原书线索" },
  { id: "rk059", from: "organic-living-nature-as-romantic-countermodel", to: "how-judgment-bridges-nature-and-freedom", relation: "产生问题", label: "浪漫有机自然回接康德判断力边界", connection: "后世重构" },
  { id: "rk060", from: "ideas-regulative-not-constitutive-knowledge", to: "can-subject-object-nature-freedom-unify-historically", relation: "产生问题", label: "规约整体仍留下体系统一压力", connection: "历史回应" },
  { id: "rk061", from: "freedom-practical-postulate-not-theoretical-object", to: "can-subject-object-nature-freedom-unify-historically", relation: "产生问题", label: "实践自由与理论自然仍待统一", connection: "历史回应" },
  { id: "rk062", from: "reflective-judgment-purposiveness-without-proof", to: "can-subject-object-nature-freedom-unify-historically", relation: "产生问题", label: "判断力桥梁开放后康德历史体系", connection: "历史回应" },
];

export const romanticKantProblemSources: ProblemMapSource[] = [
  { label: "SEP · 19th Century Romantic Aesthetics", url: "https://plato.stanford.edu/entries/aesthetics-19th-romantic/", note: "用于限制把浪漫主义写成单一反理性运动，并核对审美优先、感性—理性综合、开放形式、个体形成和有机自然等多条路线。" },
  { label: "SEP · Jean-Jacques Rousseau", url: "https://plato.stanford.edu/entries/rousseau/", note: "用于核对自然状态的假设性质、可完善性、amour de soi／amour-propre、不平等、教育、公意和公民自由，并保留公意解释争议。" },
  { label: "Rousseau · The Social Contract and Discourses", url: "https://www.gutenberg.org/files/46333/46333-h/46333-h.htm", note: "作为《社会契约论》与相关论述的公共领域文本入口，用于核对社会契约、公意／众意、主权、普遍法律与自由。" },
  { label: "Rousseau · Discourse on Inequality", url: "https://www.gutenberg.org/cache/epub/11136/pg11136-images.html", note: "作为《论人类不平等的起源和基础》公共领域文本入口，用于核对自然差异、可完善性、财产、比较和制度不平等的猜想性生成。" },
  { label: "SEP · Kant’s Transcendental Idealism", url: "https://plato.stanford.edu/entries/kant-transcendental-idealism/", note: "用于核对先验观念论、经验实在、空间时间、现象／物自身和竞争解释，避免把康德写成个人心灵创造世界。" },
  { label: "SEP · Kant’s View of Mind and Consciousness of Self", url: "https://plato.stanford.edu/entries/kant-mind/", note: "用于核对综合、范畴、统觉统一和自我意识，不把先验统觉误写成灵魂实体证明。" },
  { label: "SEP · Kant’s Moral Philosophy", url: "https://plato.stanford.edu/entries/kant-moral/", note: "用于核对定言命令、自律、人格目的、自由与责任，并保留形式主义、应用与历史排除问题。" },
  { label: "Kant · Critique of Pure Reason", url: "https://www.gutenberg.org/ebooks/4280", note: "作为《纯粹理性批判》公共领域文本入口，用于核对综合先天判断、先验转向、范畴、因果、理念与理性限界。" },
  { label: "Kant · Groundwork of the Metaphysics of Morals", url: "https://www.gutenberg.org/files/5682/5682-h/5682-h.htm", note: "作为《道德形而上学奠基》公共领域文本入口，用于核对普遍法则、人格目的、目的王国和意志自律。" },
];
