import { argument as a, group as g } from "./topic-unit";

export const societySummaryTree = [
  g("society-5-common-life", "希腊城邦至罗马", "我们为什么共同生活，怎样才算生活得好？",
    "柏拉图把正义联系到灵魂与城邦的秩序；亚里士多德认为德性的活动需要共同生活的条件。城邦自主衰落后，犬儒派、伊壁鸠鲁派与斯多葛派重新安排个人和共同体的关系：减少依赖、经营友谊，或承担更广泛的角色。共同生活不是只有一种尺度。",
    "当共同体还承担救赎与信仰，精神目标和政治权力怎样划界？", [
      g("society-10-justice-polis", "苏格拉底、柏拉图与亚里士多德", "公共争论怎样找到关于正义的共同理由？", "苏格拉底式追问要求超越个别例子说明概念；柏拉图与亚里士多德分别用整体秩序、德性活动和实践判断讨论正义生活。共同问善，不表示对政体与人的能力已有共识。", "这种生活又依赖哪些实际的共同条件？", [
        a("society-20-justice", "苏格拉底与柏拉图", "谁都能提出意见，怎样判断正义的说法？", "公共分歧使共同标准成为问题。柏拉图以灵魂各部分和城邦职能的秩序解释正义。这提供整体性的标准，却也要求检验谁界定职能、个人是否只能服从预定位置。", "同一论证也进入自我，讨论欲望和判断怎样安排。", `common-standard-of-judgment public-disagreement-observation definition-beyond-instance how-order-soul-and-polis justice-as-ordered-whole`),
        a("society-20-flourishing", "亚里士多德", "好的个人生活能否脱离共同体条件？", "亚里士多德把幸福理解为合乎德性的活动；法律、习惯和政体参与塑造判断与行动。共同生活不只是保护已经完成的个人，也参与培养能力。但古代城邦的成员资格有边界，不能直接等同于现代平等公民社会。", "城邦失去自主后，个人还可依靠什么？", `what-is-human-flourishing actions-aim-goods-observation virtue-as-rational-activity constitutions-shape-character-observation can-good-life-be-private polis-practical-wisdom polis-autonomy-collapse how-live-uncontrollable-world`),
      ]),
      g("society-10-beyond-polis", "希腊化至罗马", "共同体失去安全时，应退出还是承担角色？", "减少需求、保留朋友和履行角色是不同的应对方式。世界公民的理想扩大了道德关切，却不等于帝国已经实现普遍平等。", "道德共同体扩大后，权力的正当范围仍须另行说明。", [
        a("society-20-withdrawal-role", "犬儒、怀疑、伊壁鸠鲁与斯多葛传统", "摆脱外部依赖，是否意味着退出共同生活？", "犬儒主义压低对财富和地位的需要；皮浪式怀疑减少教条断言；伊壁鸠鲁主义重视宁静与友谊；斯多葛主义强调在不能控制的世界中履行角色。它们对参与公共生活的态度有差异，不能都归为逃避政治。", "无论参与多少，都要说明我对哪些人负有责任。", `cynic-low-dependence epicurean-natural-therapy stoic-virtue-in-order freedom-withdrawal-or-role role-and-inner-freedom how-live-uncontrollable-world skeptical-suspension tranquility-needs-knowledge natural-knowledge-removes-fear is-natural-explanation-enough`),
        a("society-20-community", "伊壁鸠鲁主义与斯多葛主义", "共同规则依赖契约，还是人人共有的理性？", "伊壁鸠鲁传统从相互不伤害的约定与友谊理解共同生活；斯多葛传统诉诸共同理性和世界城邦。两者都可超出单一城邦，却对规则的根据和共同体范围给出不同解释。", "罗马与基督教语境还把共同体带入帝国与救赎的关系。", `friendship-contract-without-providence imperial-law-observation who-belongs-moral-community cosmopolis-common-reason is-inner-freedom-enough`),
      ]),
    ], "从正义与德性出发，再看城邦之外的友谊、角色和世界公民。"),

  g("society-5-authority", "教父时期至晚期中世纪", "共同目标能给权威多大的权力？",
    "奥古斯丁区分两种由不同的爱形成的共同体，不能把现存教会与国家直接各配一座城。修道与牧灵传统考察规则怎样约束领导者，阿奎那以共同善限制人法。任命权、教皇权和代表会议的争论则追问：谁有权纠正一个自称最高的权威？",
    "权威分裂不会自动产生自由，还要建立能够承担冲突与纠错的制度。", [
      g("society-10-care-law", "奥古斯丁、修道传统与阿奎那", "照料共同生活，怎样避免变成支配？", "共同体的精神目标不能替代对实际权力的检验。规则约束领导者、照料顾及不同处境、人法限于共同善，是不同传统中可以比较的限制思路。", "当权威之间冲突，谁来执行这些限制？", [
        a("society-20-two-cities", "安布罗斯与奥古斯丁", "帝国或教会的成功，就是最高善的实现吗？", "安布罗斯把皇帝置于教会规范之内。奥古斯丁用两城理解爱与历史，却不把任何现存政治组织的胜利视为救赎完成。精神归属与现实制度相关，但不能简单一一对应。", "共同体仍须在不完美的历史中维持日常实践。", `who-judges-christian-power church-imperial-observation emperor-within-church how-time-history-relate-eternity created-time-and-two-cities can-salvation-community-survive-empire`),
        a("society-20-rule-common-good", "本笃、格里高利与阿奎那", "领导者和法律怎样受到其目的的约束？", "修道规则要求院长接受规则与分辨的约束，牧灵照料要顾及不同的人。阿奎那认为法律为了共同善，人法不能强制所有德性。这些不是现代宪政的现成版本，但都允许追问权威是否违背自身职责。", "规则能约束个人，还须面对组织之间的权力竞争。", `how-can-rule-authority-avoid-domination abbot-bound-by-rule-discernment how-should-office-guide-different-people pastoral-care-discernment-humility how-can-common-good-guide-changing-actions shared-goods-variable-actions-observation practical-reason-first-principles-natural-law why-universal-precepts-not-enough prudence-virtue-apply-principles what-can-human-law-rightly-command law-for-common-good-limited-coercion how-can-practice-survive-fragile-institutions stability-prayer-work-reading routine-shapes-desire-observation can-spiritual-network-carry-public-order papal-monastic-network-order who-reforms-preserving-church`),
      ]),
      g("society-10-limited-powers", "教权争论与晚期中世纪", "最高权威有错时，谁能够纠正它？", "政教两种秩序、领土国家、教会会议与信众代表都进入权威冲突。它们提出不同的纠错安排，不能仅凭出现同意或代表，就认定现代民主已诞生。", "权力边界既取决于理由，也取决于现实组织能力。", [
        a("society-20-two-powers", "教会改革至奥卡姆", "精神与世俗权力能否彼此限制？", "教会改革要求摆脱世俗任命的控制，却也可能走向教权至上。奥卡姆坚持教皇可错，区分通常权限与特殊情形下的纠正。相互限制并不等于两个权力从此不再冲突。", "若教皇、王权都可能滥权，代表与法律能否提供另一层纠错？", `who-appoints-church-office office-property-appointment-entanglement-observation clerical-reform-independent-order can-autonomy-avoid-supremacy two-orders-mutual-limitation can-pope-err-and-be-corrected poverty-property-papal-conflict-observation papal-authority-fallible-and-limited how-distinct-powers-correct-each-other distinct-powers-occasional-intervention`),
        a("society-20-representation", "马西利乌斯与公会议运动", "把裁决交给代表，是否就能防止权力失控？", "马西利乌斯将强制法律的来源联系到政治共同体，限制教士独立使用强制力。公会议试图处理教会分裂，却未建立稳定的会议宪制。这些方案具有中世纪的成员和权力边界，不能当作普选民主。", "从权威多元走向自由制度，还需要新的论证与实践。", `who-makes-coercive-law-for-political-community human-legislator-people-prevailing-part is-human-legislator-modern-democracy late-medieval-consent-not-universal-suffrage what-remains-of-priestly-authority-without-coercion priesthood-teaches-sacraments-no-independent-coercion can-representation-correct-office-without-new-absolutism rival-papal-obediences-observation who-can-judge-self-reproducing-rival-popes council-claims-emergency-superiority does-ending-schism-reform-church constance-unity-not-durable-conciliar-rule does-papal-decline-yield-one-successor-authority plural-authorities-replace-single-center who-decides-scripture-heresy-and-church-rule general-council-represents-faithful-secular-enforcement can-council-end-schism-without-third-papacy pisa-fails-constance-restores-unity why-did-conciliar-constitution-fail papacy-recovers-office-not-medieval-prestige`),
      ]),
    ], "共同善不保证权威无误；规则、政教边界和代表机制都要接受检验。"),

  g("society-5-security-rights", "文艺复兴至洛克", "为什么服从政府，又在何时有权拒绝？",
    "马基雅维利追问政治行动如何面对冲突与偶然，共和制度怎样保存自由。宗教改革使良心与强制的边界更尖锐。霍布斯用授权与共同权力回应不安全；洛克则从先于政府的权利说明有限委托与反抗。契约并不必然导向同一种国家。",
    "保护权利之后，还要问财产、社会依赖和不平等是否妨碍实际自由。", [
      g("society-10-conflict-conscience", "马基雅维利与宗教改革", "现实冲突和良心判断怎样进入公共秩序？", "政治不能只靠道德愿望，宗教判断也不能靠强制自动成为信仰。现实效果与个人良心各自提出要求，却都不能单独取消对权力边界的讨论。", "需要具体说明：共同权力如何建立，以及它可以要求什么。", [
        a("society-20-republic", "马基雅维利", "政治冲突只能毁坏自由吗？", "马基雅维利研究现实行动、武力与偶然，也讨论共和国如何把社会冲突纳入制度。君主在危急处境中的手段，不等于所有公共生活的唯一准则；有效与正当仍须分别讨论。", "制度需要处理意见分歧，尤其是宗教与良心的分歧。", `how-can-rulers-study-political-survival italian-war-mercenary-fortune-observation effectual-truth-of-political-action may-political-necessity-override-ordinary-morality learn-not-good-under-necessity is-machiavelli-praising-evil-as-good political-goods-bound-instrumental-exceptions is-prince-the-only-political-agent republic-secures-vivere-libero does-social-conflict-destroy-or-create-liberty institutions-channel-conflict-into-liberty how-do-effects-become-legitimate-public-order virtu-adapts-to-fortuna`),
        a("society-20-conscience", "人文主义、宗教改革与宽容问题", "摆脱教皇权威，是否就获得了宗教自由？", "人文主义的文本比较和对话可用于纠正制度；宗教改革重排经文、信仰和教会权威，却常由领土统治者推动宗派化。个人良心不等于私人解释无误，宗教改革也不等于现代宽容已经成立。", "宽容需要进一步说明国家强制力的合法目的。", `how-should-christian-society-be-reformed erasmus-education-ad-fontes-peaceful-reform more-dialogue-law-comparative-reform does-scripture-conscience-create-solitary-infallibility word-community-without-private-infallibility who-enforces-reform-after-papal-break territorial-rulers-protect-and-confessionalize does-papal-liberation-equal-religious-freedom reformation-opens-judgment-not-modern-toleration religious-conflict-and-belief-coercion-observation what-domain-must-remain-outside-civil-coercion civil-ends-limit-coercive-authority is-utopia-mores-literal-blueprint utopia-as-dialogic-countermodel does-property-critique-require-abolition property-law-public-use-distinction does-philology-make-each-reader-infallible trained-comparison-with-interpretive-restraint`),
      ]),
      g("society-10-covenant-trust", "霍布斯与洛克", "共同权力是最终裁决者，还是可撤销的委托？", "霍布斯强调没有共同权力时的战争风险，以相互授权建立主权。洛克认为自然权利先于政府，以信托约束政府。两者都讨论同意，却对权力集中与抵抗给出不同界限。", "自然权利的普遍语言，还须与实际成员资格和财产关系核对。", [
        a("society-20-hobbes", "霍布斯", "为了安全授权主权者，就必须服从一切命令吗？", "霍布斯以平等脆弱与不信任解释战争风险，用共同授权建立统一的法律和强制力。自然状态不是对全人类史前社会的简单记录；自我保存和保护关系也使服从存在边界。", "洛克另问：政府是否只能受托保护已经存在的权利？", `why-do-rational-equals-enter-war-risk equal-vulnerability-private-judgment-observation competition-diffidence-glory-create-war-disposition is-state-of-nature-universal-prehistory state-of-nature-tests-absence-of-common-power promises-fail-without-enforcement-observation how-can-covenant-create-binding-common-power mutual-covenant-authorizes-artificial-person why-must-sovereign-judgment-be-final-undivided sovereign-unifies-law-force-representation does-authorization-make-every-command-right self-preservation-and-protection-bound-obedience can-civil-order-be-reconstructed-as-systematic-artifice`),
        a("society-20-locke", "洛克", "政府保护权利，又怎样防止自己侵犯权利？", "洛克从自然法与权利说明政府的限度，以同意、分权和信托解释合法权力，失信则引出抵抗权。劳动取得财产的论证包含限制，也面对货币积累与不平等。其宽容和权利主张仍须核对历史排除，不能把原则上的普遍性当作实践已普遍平等。", "财产保障独立，也可能形成依赖；这可继续连接卢梭的平等问题。", `is-government-a-revocable-trust english-revolution-settlement-observation fallible-individuals-need-bounded-knowledge-and-power equal-persons-judge-own-cases-observation is-state-of-nature-already-war natural-law-rights-precede-government how-can-common-resources-become-private-property labor-appropriation-proviso-and-money when-do-property-rights-become-private-domination how-do-consent-and-majority-create-government fiduciary-government-and-separated-powers when-may-people-resist-or-replace-government right-of-resistance-follows-broken-trust religious-pluralism-observation can-force-produce-religious-belief toleration-follows-limited-civil-ends how-universal-are-lockean-rights-in-practice can-property-secure-independence-without-justifying-domination commerce-property-independence-observation rights-protect-agency-but-remain-historically-partial`),
      ]),
    ], "在安全、良心与权利之间划定权力：霍布斯的授权和洛克的信托并不相同。", [{ label: "SEP · 洛克政治哲学", url: "https://plato.stanford.edu/entries/locke-political/" }]),

  g("society-5-social-freedom", "卢梭、康德与黑格尔", "活在共同规则里，怎样仍是自由的人？",
    "卢梭追问不平等和社会比较怎样制造依赖，公意怎样表达共同利益。康德要求行动原则可普遍成立，并且不把人仅仅当作手段。黑格尔把自由联系到相互承认与制度生活。教育、规范和制度分别说明自由的条件，不能用其中一种替代其余问题。",
    "自由制度的语言还要面对实际的贫困、排斥和权力不对等。", [
      g("society-10-equality-common-will", "卢梭", "社会怎样既塑造个人，又不使人相互支配？", "卢梭区分自然差异与制度化不平等，考察教育、社会自爱和公民资格。公意不是私人愿望的简单相加，而依赖平等和面向共同利益的条件。", "共同意志的名义也可能被滥用，因此要保留强制的风险。", [
        a("society-20-dependence", "卢梭", "不平等怎样从生活差异变成支配关系？", "卢梭用推测性的发生史考察财产、比较和法律如何改变人的依赖。社会自爱可能变成虚荣竞争，也可能朝向平等承认。教育的问题因此不是简单回归野外，而是怎样形成不只追逐评价的判断能力。", "能够判断的个人，还需要不受他人私意支配的共同规则。", `how-natural-difference-becomes-political-inequality property-comparison-dependence-observation conjectural-genealogy-of-property-law-inequality is-amour-propre-only-corrupting-vanity amour-propre-can-be-inflamed-or-egalitarian how-educate-agency-without-premature-dependence negative-education-protects-developmental-agency civilization-can-refine-taste-yet-corrupt-virtue are-humans-naturally-competitive-and-dominating amour-de-soi-pity-perfectibility-before-comparison`),
        a("society-20-general-will", "卢梭", "多数人同意的决定，就一定表达公意吗？", "社会契约使人作为平等公民参与主权。公意面向共同利益，法律应从所有人出发并普遍适用；私人利益的总和不必满足这些条件。“迫使自由”的说法因此需要连同平等条件与威权风险一起理解。", "普遍规则的正当性还能否独立于某个共同体来论证？", `can-social-order-preserve-freedom social-pact-creates-equal-citizen-sovereign how-general-will-differs-from-will-of-all general-will-aims-common-interest-not-sum what-conditions-let-general-will-emerge laws-from-all-apply-to-all-under-equality can-citizen-be-forced-to-be-free civil-freedom-as-nondomination-with-authoritarian-risk can-self-legislation-be-universal-without-one-community`),
      ]),
      g("society-10-respect-recognition", "康德与黑格尔", "尊重个人需要普遍原则，还是具体制度？", "康德的道德论证要求普遍化与人格尊重。黑格尔认为自由还须在相互承认、家庭、市民社会和国家中取得现实条件。这是相关而不同的论证层次。", "制度是否真能承载自由，须用它对个人的实际作用检验。", [
        a("society-20-humanity", "康德", "为了共同目标，可以只把某些人当作工具吗？", "康德要求原则能够成为普遍法则，并把人性作为目的，禁止仅仅把人当作手段。自律不是任意按喜好行动，而是理性立法。这些节点说明道德基础，不冒充已经完整呈现康德的法权与政治理论。", "原则怎样在真实的相互承认与制度关系中实现？", `what-makes-moral-law-universal categorical-imperative-universal-law can-persons-be-used-merely-as-means humanity-as-end-and-kingdom-of-ends autonomy-as-rational-self-legislation how-can-freedom-coexist-with-natural-causality`),
        a("society-20-recognition", "黑格尔", "名义上有权利，为什么仍可能不自由？", "黑格尔认为自我意识需要相互承认，支配关系不能提供稳定的对等承认。家庭、市民社会与国家中介自由的实现；但市场贫困和未获和解的个人经历仍给整体提出问题，不能把任何现存国家自动称为合理。", "用贫困和排除检验制度，也接向功利主义和马克思。", `why-self-consciousness-needs-mutual-recognition self-consciousness-seeks-recognition-observation mutual-recognition-constitutes-social-selfhood can-domination-secure-recognition asymmetric-recognition-undermines-itself market-family-state-dependence-observation why-abstract-right-and-private-conscience-insufficient ethical-life-mediates-family-civil-society-state does-actual-rational-mean-every-state-is-right actuality-is-critical-standard-not-fact-worship can-civil-society-correct-poverty-it-produces institutions-contain-market-without-abolishing-particularity does-world-history-redeem-suffering-and-exclusion totality-must-remain-answerable-to-unreconciled-lives`),
      ]),
    ], "教育减少依赖，原则保障尊重，制度承载承认；三层共同检验社会自由。"),

  g("society-5-correction", "功利主义、马克思与杜威", "怎样发现并改变制度持续造成的伤害？",
    "功利主义以受影响者的利益评价制度，密尔把自由和生活试验看作重要条件。马克思把目光转向生产关系、异化与资本，追问伤害为何反复发生。杜威关注教育与公共探究，要求受间接后果影响的人能够组织、表达和修正共同决策。改革既要有判断标准，也要有参与纠错的能力。",
    "可从教育与经验返回自我，从公共探究返回自然与方法；这里没有宣布历史已经解决冲突。", [
      g("society-10-welfare-structure", "边沁、密尔与马克思", "改进制度应比较后果，还是改变生产关系？", "功利主义比较福利和伤害，密尔同时维护个性与批评的空间。马克思追问契约表面平等如何与结构性支配并存。比较后果和揭示结构可以相互提问，却不是同一种政治哲学。", "无论采取什么改革，都需要能判断、组织并修订行动的人。", [
        a("society-20-utility-liberty", "边沁与密尔", "多数人的收益能否抵消少数人的自由？", "功利主义要求把受影响者的利益纳入评价，但总量计算面对少数人被牺牲的风险。密尔以权利、长期利益和伤害原则维护生活试验；多数舆论也可能压迫个人，因此自由需要制度和批评的支持。", "如果伤害不断从同一种制度产生，只逐项补救是否足够？", `impartial-utility-judges-shared-consequences whose-interests-enter-public-utility equal-consideration-needs-representation-and-revision can-aggregate-welfare-sacrifice-minority rights-and-rules-secure-long-run-utility does-liberty-serve-welfare-beyond-preference harm-principle-protects-experiments-in-living can-majority-opinion-tyrannize-without-law liberty-requires-plural-institutions-and-criticism can-reform-reach-structures-producing-harm can-pleasures-and-pains-be-publicly-compared felicific-calculus-as-revisable-comparison`),
        a("society-20-production", "马克思", "自由签订的契约，为什么仍可能维持支配？", "马克思区分劳动力的买卖与劳动创造的价值，追问所有权如何组织剩余和权力。异化不只是心情不好，而涉及人与产品、活动、能力及他人的关系。历史唯物主义也不能简化成经济自动决定一切，集体行动需要组织与学习。", "结构批判还须说明谁能参与改变，以及如何核对其实际结果。", `production-relations-structure-recurrent-harms wage-contract-industrial-discipline-observation how-equivalent-exchange-yields-surplus-value labour-power-produces-surplus-under-ownership commodity-market-appearance-observation why-social-relations-appear-as-relations-between-things commodity-fetishism-naturalizes-social-relations does-alienation-name-feeling-or-social-condition alienation-separates-product-activity-capacity-others do-ideas-or-material-practices-drive-history historical-materialism-constrains-without-mechanical-determinism does-class-position-automatically-create-agent class-agency-requires-organization-and-learning does-marx-entail-later-authoritarian-regimes marx-legacy-needs-text-institution-outcome-separation`),
      ]),
      g("society-10-learning-publics", "杜威", "共同纠错需要怎样的教育和公共生活？", "教育通过有指导的经验培养继续学习的能力；民主则使受公共后果影响的人能形成问题、交流证据并参与修正。二者相接于能力的培养，却不能用课堂活动替代政治制度。", "共同探究要检验自己的参与条件，尤其是谁被排除在外。", [
        a("society-20-education", "杜威", "学习怎样培养参与共同生活的能力？", "杜威从人与环境的交互理解经验，教育应组织能通向进一步成长的活动。“做中学”并不是放任活动，而要有人引导问题、反思后果和形成判断。个人成长也依赖共同学习的环境。", "有能力的个人，还需有让其声音和证据起作用的公共制度。", `is-experience-private-inner-content experience-as-organism-environment-transaction is-learning-by-doing-unguided-activity education-guides-experience-toward-growth`),
        a("society-20-public-inquiry", "杜威", "受共同后果影响的人，怎样成为能够行动的公众？", "杜威不把民主缩减为投票。工业社会的间接后果使公众需要发现问题、传播信息并组织行动；公共探究必须有参与、制度和抗衡权力的条件。宣称专家知道答案，不能代替这些条件。", "探究仍需要清楚表达和可检验理由，可继续接到方法维度。", `is-democracy-only-voting-and-majority-rule industrial-public-consequences-observation democracy-as-associated-life-and-public-inquiry how-publics-form-around-indirect-consequences public-inquiry-needs-institutions-and-counterpower does-public-inquiry-need-logical-analysis inquiry-transforms-problematic-situation how-institutionalize-fallible-plural-inquiry must-knowledge-begin-with-certainty warranted-assertibility-through-disciplined-inquiry`),
      ]),
    ], "比较福利与自由，追查伤害的制度根源，再培养共同发现和纠正问题的能力。", [{ label: "SEP · 杜威", url: "https://plato.stanford.edu/entries/dewey/" }]),
];
