export type TermCategory = "人物" | "地名" | "学派" | "概念" | "著作";

export type TermEntry = {
  id: string;
  zh: string;
  en: string;
  category: TermCategory;
  alternatives?: string[];
  note: string;
};

export const terminology: TermEntry[] = [
  { id: "thales", zh: "泰勒斯", en: "Thales", category: "人物", note: "米利都哲学家；罗素以他作为希腊哲学史的象征性起点。" },
  { id: "anaximander", zh: "阿那克西曼德", en: "Anaximander", category: "人物", note: "以“无限者”说明万物生成，并尝试用自然过程解释宇宙。" },
  { id: "anaximenes", zh: "阿那克西美尼", en: "Anaximenes", category: "人物", note: "以气的稀释和凝聚解释不同物质形态。" },
  { id: "pythagoras", zh: "毕达哥拉斯", en: "Pythagoras", category: "人物", note: "把数学比例、灵魂净化和宗教共同体连接起来。" },
  { id: "heraclitus", zh: "赫拉克利特", en: "Heraclitus", category: "人物", note: "强调变化、冲突和逻各斯；在罗素叙述中是辩证传统的重要远源。" },
  { id: "parmenides", zh: "巴门尼德", en: "Parmenides", category: "人物", note: "以严格推理主张真正存在不生不灭，公开挑战感官经验。" },
  { id: "empedocles", zh: "恩培多克勒", en: "Empedocles", category: "人物", note: "以四种不变元素及爱、争两种力量解释变化。" },
  { id: "anaxagoras", zh: "阿那克萨哥拉", en: "Anaxagoras", category: "人物", note: "以心灵推动宇宙秩序，并把爱奥尼亚自然哲学带入雅典。" },
  { id: "leucippus", zh: "留基伯", en: "Leucippus", category: "人物", note: "通常被视为古代原子论的早期创始者，其生平与著作归属仍不确定。" },
  { id: "democritus", zh: "德谟克利特", en: "Democritus", category: "人物", note: "以原子与虚空解释自然变化，是古代机械因果传统的重要代表。" },
  { id: "protagoras", zh: "普罗泰戈拉", en: "Protagoras", category: "人物", note: "智者代表人物，以“人是万物的尺度”关联知识、处境和论辩。" },
  { id: "socrates", zh: "苏格拉底", en: "Socrates", category: "人物", note: "以问答和反诘检验信念，把哲学中心转向德性与生活。" },
  { id: "plato", zh: "柏拉图", en: "Plato", category: "人物", note: "以理念、灵魂与理想城邦建立跨越知识、伦理和政治的体系。" },
  { id: "aristotle", zh: "亚里士多德", en: "Aristotle", category: "人物", note: "以观察、分类、逻辑和原因分析建立系统哲学。" },
  { id: "diogenes", zh: "第欧根尼", en: "Diogenes", category: "人物", note: "犬儒派象征人物，以公开生活实践拒绝财富、地位和习俗依赖。" },
  { id: "pyrrho", zh: "皮浪", en: "Pyrrho", category: "人物", note: "古代怀疑主义代表，以悬置判断追求心灵安宁。" },
  { id: "arcesilaus", zh: "阿尔克西劳", en: "Arcesilaus", category: "人物", note: "把柏拉图学院转向怀疑主义，反对斯多葛派的确定知识标准。" },
  { id: "carneades", zh: "卡尔内阿德", en: "Carneades", category: "人物", note: "学院怀疑主义者，以相反论证和或然性回应知识与实践问题。" },
  { id: "epicurus", zh: "伊壁鸠鲁", en: "Epicurus", category: "人物", note: "用原子论、欲望分类和友谊实践解除对神与死亡的恐惧。" },
  { id: "lucretius", zh: "卢克莱修", en: "Lucretius", category: "人物", note: "罗马诗人，以《物性论》传播伊壁鸠鲁主义自然观。" },
  { id: "zeno", zh: "芝诺", en: "Zeno of Citium", category: "人物", note: "斯多葛学派创始人；不要与提出运动悖论的埃利亚芝诺混淆。" },
  { id: "seneca", zh: "塞涅卡", en: "Seneca", category: "人物", note: "罗马斯多葛主义者，把哲学写成面对权力、死亡和情绪的日常操练。" },
  { id: "epictetus", zh: "爱比克泰德", en: "Epictetus", category: "人物", note: "强调区分可控制与不可控制之物，把自由安放在判断和意志。" },
  { id: "aurelius", zh: "马可·奥勒留", en: "Marcus Aurelius", category: "人物", note: "罗马皇帝和斯多葛作者，以自省记录角色义务与内在自由。" },
  { id: "plotinus", zh: "普罗提诺", en: "Plotinus", category: "人物", note: "新柏拉图主义核心人物，以太一、精神和灵魂构造流溢层级。" },
  { id: "paul", zh: "保罗", en: "Paul the Apostle", category: "人物", note: "早期基督教宣教者和书信作者，把救赎信息扩展到非犹太人世界。" },
  { id: "john-evangelist", zh: "约翰", en: "John the Evangelist", category: "人物", note: "本网站以此名称指《约翰福音》传统所代表的早期基督教神学形象。" },
  { id: "augustine", zh: "奥古斯丁", en: "Saint Augustine", category: "人物", note: "把柏拉图主义、内省、意志和基督教救赎史结合起来。" },
  { id: "benedict", zh: "本尼狄克", en: "Saint Benedict", category: "人物", note: "其修道规则成为西欧修道共同生活和知识保存的重要制度基础。" },
  { id: "gregory", zh: "大格列高利", en: "Gregory the Great", category: "人物", note: "教皇、行政者和传教组织者，体现罗马制度向中世纪教会的转移。" },
  { id: "eriugena", zh: "约翰·司各脱", en: "John Scotus Eriugena", category: "人物", alternatives: ["爱留根纳"], note: "九世纪哲学家与译者，强调真正理性与真正启示不会冲突。" },
  { id: "avicenna", zh: "阿维森纳", en: "Avicenna (Ibn Sina)", category: "人物", alternatives: ["伊本·西那"], note: "伊斯兰哲学家和医学家，以存在、必然者和灵魂论重释亚里士多德。" },
  { id: "averroes", zh: "阿威罗伊", en: "Averroes (Ibn Rushd)", category: "人物", alternatives: ["伊本·鲁世德"], note: "安达卢西亚哲学家，其亚里士多德注释深刻影响拉丁经院哲学。" },
  { id: "maimonides", zh: "迈蒙尼德", en: "Maimonides", category: "人物", note: "犹太哲学家，以哲学解释协调摩西传统与亚里士多德思想。" },
  { id: "aquinas", zh: "托马斯·阿奎那", en: "Thomas Aquinas", category: "人物", note: "经院哲学综合者，系统划分自然理性与启示神学的范围。" },
  { id: "roger-bacon", zh: "罗吉尔·培根", en: "Roger Bacon", category: "人物", note: "方济各会学者，强调语言、数学、观察与实验的重要性。" },
  { id: "duns-scotus", zh: "邓斯·司各脱", en: "Duns Scotus", category: "人物", note: "强调个体性、意志和存在概念，是晚期经院哲学的重要转折。" },
  { id: "ockham", zh: "奥卡姆", en: "William of Ockham", category: "人物", note: "以唯名论和简约原则限制经院体系的实体与证明负担。" },
  { id: "machiavelli", zh: "马基雅维利", en: "Machiavelli", category: "人物", note: "把政治权力、稳定与行动后果从完整神学伦理中相对分离。" },
  { id: "luther", zh: "路德", en: "Martin Luther", category: "人物", note: "宗教改革核心人物，强调信仰、经文和个人良心。" },
  { id: "copernicus", zh: "哥白尼", en: "Copernicus", category: "人物", note: "以日心模型重组天文学，动摇传统宇宙秩序。" },
  { id: "kepler", zh: "开普勒", en: "Kepler", category: "人物", note: "以行星椭圆轨道和数学定律推进新天文学。" },
  { id: "galileo", zh: "伽利略", en: "Galileo", category: "人物", note: "结合数学、实验和望远镜观察，改变自然研究的证据标准。" },
  { id: "francis-bacon", zh: "弗朗西斯·培根", en: "Francis Bacon", category: "人物", note: "倡导系统观察、归纳和协作研究；不要与罗吉尔·培根混淆。" },
  { id: "hobbes", zh: "霍布斯", en: "Thomas Hobbes", category: "人物", note: "从恐惧、契约和机械论出发论证不可分割的主权。" },
  { id: "descartes", zh: "笛卡尔", en: "René Descartes", category: "人物", note: "以方法性怀疑和“我思”重建现代知识的主体起点。" },
  { id: "spinoza", zh: "斯宾诺莎", en: "Baruch Spinoza", category: "人物", note: "以单一实体和必然性体系重新理解自然、上帝与自由。" },
  { id: "leibniz", zh: "莱布尼茨", en: "Gottfried Wilhelm Leibniz", category: "人物", note: "以单子、充足理由和预定和谐构造理性主义体系。" },
  { id: "locke", zh: "洛克", en: "John Locke", category: "人物", note: "经验主义和自由主义的重要奠基者，反对天赋观念与绝对权力。" },
  { id: "berkeley", zh: "贝克莱", en: "George Berkeley", category: "人物", note: "以“存在就是被感知”批评物质实体观念。" },
  { id: "hume", zh: "休谟", en: "David Hume", category: "人物", note: "把经验主义推向怀疑结论，重构因果、自我和归纳问题。" },
  { id: "rousseau", zh: "卢梭", en: "Jean-Jacques Rousseau", category: "人物", note: "以文明批判、社会契约和公意重塑现代自由问题。" },
  { id: "kant", zh: "康德", en: "Immanuel Kant", category: "人物", note: "研究经验何以可能，并区分现象知识与实践自由。" },
  { id: "hegel", zh: "黑格尔", en: "G. W. F. Hegel", category: "人物", note: "以辩证法和历史整体解释理性与自由的制度展开。" },
  { id: "schopenhauer", zh: "叔本华", en: "Arthur Schopenhauer", category: "人物", note: "把世界理解为表象与盲目意志，形成悲观主义体系。" },
  { id: "byron", zh: "拜伦", en: "Lord Byron", category: "人物", note: "浪漫主义诗人；罗素用他呈现反习俗、英雄化个人主义的文化类型。" },
  { id: "nietzsche", zh: "尼采", en: "Friedrich Nietzsche", category: "人物", note: "以谱系和心理分析追问价值来源，并诊断现代虚无主义。" },
  { id: "bentham", zh: "边沁", en: "Jeremy Bentham", category: "人物", note: "以最大幸福原则系统化功利主义，并推动法律与制度改革。" },
  { id: "mill", zh: "约翰·斯图亚特·密尔", en: "John Stuart Mill", category: "人物", alternatives: ["穆勒"], note: "发展功利主义、自由论与代议政治，同时强调个性和思想实验。" },
  { id: "marx", zh: "马克思", en: "Karl Marx", category: "人物", note: "从生产关系、阶级与实践解释历史结构及其改变。" },
  { id: "william-james", zh: "威廉·詹姆斯", en: "William James", category: "人物", note: "实用主义代表，以经验与实践后果讨论真理和信念。" },
  { id: "dewey", zh: "约翰·杜威", en: "John Dewey", category: "人物", note: "把认识理解为环境中的探究与调整，并应用于民主教育。" },
  { id: "frege", zh: "弗雷格", en: "Gottlob Frege", category: "人物", note: "现代逻辑奠基者之一，对语言、数学基础和分析哲学影响深远。" },
  { id: "russell", zh: "罗素", en: "Bertrand Russell", category: "人物", note: "本书作者，也是现代逻辑分析哲学的重要代表。" },

  { id: "miletus", zh: "米利都", en: "Miletus", category: "地名", note: "小亚细亚爱奥尼亚商业城邦，米利都学派的思想中心。" },
  { id: "ionia", zh: "爱奥尼亚", en: "Ionia", category: "地名", note: "小亚细亚西岸希腊地区，连接爱琴海与近东知识网络。" },
  { id: "athens-place", zh: "雅典", en: "Athens", category: "地名", note: "古典时期民主、修辞、戏剧和哲学学园的主要中心。" },
  { id: "alexandria", zh: "亚历山大里亚", en: "Alexandria", category: "地名", alternatives: ["亚历山大城"], note: "希腊化与罗马时期重要的图书、科学和多宗教思想中心。" },
  { id: "rome", zh: "罗马", en: "Rome", category: "地名", note: "既指城市，也常指共和国或帝国制度；语境需分别判断。" },

  { id: "milesian", zh: "米利都学派", en: "Milesian School", category: "学派", note: "用自然本原而非神话谱系解释世界的早期哲学传统。" },
  { id: "cynicism", zh: "犬儒派", en: "Cynics / Cynicism", category: "学派", note: "以减少需要和反习俗生活追求不受外物支配的自由。" },
  { id: "scepticism", zh: "怀疑派", en: "Sceptics / Scepticism", category: "学派", alternatives: ["怀疑主义"], note: "通过为相反判断提供理由并悬置断言，降低精神扰动。" },
  { id: "epicureanism", zh: "伊壁鸠鲁派", en: "Epicureans / Epicureanism", category: "学派", alternatives: ["伊壁鸠鲁主义"], note: "把快乐理解为无痛与宁静，以自然知识解除恐惧。" },
  { id: "stoicism", zh: "斯多葛主义", en: "Stoicism", category: "学派", alternatives: ["斯多葛派"], note: "强调德性、自然秩序、判断训练和内在自由。" },
  { id: "neoplatonism", zh: "新柏拉图主义", en: "Neoplatonism", category: "学派", note: "以太一、精神和灵魂的层级重新解释柏拉图传统。" },
  { id: "scholasticism", zh: "经院哲学", en: "Scholasticism", category: "学派", note: "中世纪大学中以问题、反对、回答和反驳组织知识的专业传统。" },
  { id: "rationalism", zh: "理性主义", en: "Rationalism", category: "学派", note: "以理性原则和演绎体系作为知识的重要基础。" },
  { id: "empiricism", zh: "经验主义", en: "Empiricism", category: "学派", note: "要求观念和知识最终说明其经验来源与证据。" },
  { id: "romanticism", zh: "浪漫主义", en: "Romanticism", category: "学派", note: "强调个性、情感、创造和自然，反抗机械理性与抽象秩序。" },
  { id: "utilitarianism", zh: "功利主义", en: "Utilitarianism", category: "学派", note: "按行动或制度对总体幸福的后果进行伦理评价。" },
  { id: "pragmatism", zh: "实用主义", en: "Pragmatism", category: "学派", note: "通过观念在经验、行动和共同探究中的作用理解意义与真理。" },
  { id: "analytic", zh: "分析哲学", en: "Analytic Philosophy", category: "学派", note: "重视逻辑、语言和概念澄清，反对含混的宏大体系。" },

  { id: "arche", zh: "本原", en: "archē / first principle", category: "概念", alternatives: ["始基"], note: "早期希腊哲学中万物由之生成或得到统一解释的根本原则。" },
  { id: "logos", zh: "逻各斯", en: "logos", category: "概念", alternatives: ["理则", "道"], note: "可指言说、理由或秩序；在赫拉克利特和基督教语境中含义不同。" },
  { id: "virtue", zh: "德性", en: "virtue / aretē", category: "概念", alternatives: ["美德"], note: "不仅是道德善，也可指一种事物或人的卓越能力。" },
  { id: "ideas-forms", zh: "理念", en: "Ideas / Forms", category: "概念", alternatives: ["形式", "理型"], note: "柏拉图语境中可知、稳定且作为具体事物标准的存在；英译常用 Forms。" },
  { id: "substance", zh: "实体", en: "substance", category: "概念", note: "能独立存在或作为属性承担者的东西；亚里士多德、笛卡尔和斯宾诺莎定义不同。" },
  { id: "soul", zh: "灵魂", en: "soul / psychē", category: "概念", note: "古希腊可指生命原则，基督教和近代语境则更强调人格与不朽。" },
  { id: "the-one", zh: "太一", en: "the One", category: "概念", alternatives: ["一者"], note: "普罗提诺体系中超越存在与思想、万物由之流出的最高原则。" },
  { id: "natural-law", zh: "自然法", en: "natural law", category: "概念", note: "依据共同理性或人性而成立、并非只由地方成文法创造的规范。" },
  { id: "free-will", zh: "自由意志", en: "free will", category: "概念", note: "人是否能成为行动来源；在奥古斯丁那里与罪、预知和恩典相连。" },
  { id: "grace", zh: "恩典", en: "grace", category: "概念", alternatives: ["恩宠"], note: "来自上帝、使堕落者能够得救或行善的非应得帮助。" },
  { id: "salvation", zh: "救赎", en: "salvation / redemption", category: "概念", note: "从罪、死亡或与上帝分离状态中被拯救；两个英文词侧重点可能不同。" },
  { id: "universals", zh: "共相", en: "universals", category: "概念", alternatives: ["普遍概念"], note: "多个个体共同具有的种类或性质是否真实存在，是经院哲学核心争论。" },
  { id: "faith", zh: "信仰", en: "faith", category: "概念", note: "宗教信赖与接受；并不总等同于缺乏证据的普通相信。" },
  { id: "reason", zh: "理性", en: "reason", category: "概念", note: "推理、原则判断或把握秩序的能力；不同传统对其范围评价不同。" },
  { id: "revelation", zh: "启示", en: "revelation", category: "概念", note: "被认为由上帝主动揭示、不能仅凭自然理性获得的真理。" },
  { id: "experience", zh: "经验", en: "experience", category: "概念", note: "感觉、反省或实践经历的材料；经验主义内部也有不同定义。" },
  { id: "induction", zh: "归纳", en: "induction", category: "概念", note: "从有限观察推广到一般规律；休谟追问这种推广如何获得正当性。" },
  { id: "causation", zh: "因果", en: "causation", category: "概念", alternatives: ["因果性"], note: "事件间是否存在必然联系，而不仅是持续相继发生。" },
  { id: "social-contract", zh: "社会契约", en: "social contract", category: "概念", note: "从个人同意或假想协议说明政治权威如何形成及受何限制。" },
  { id: "sovereignty", zh: "主权", en: "sovereignty", category: "概念", note: "政治共同体中最高且最终的公共决定权。" },
  { id: "natural-rights", zh: "自然权利", en: "natural rights", category: "概念", note: "被认为先于政府、政府应当保护而不能任意取消的个人权利。" },
  { id: "transcendental", zh: "先验", en: "transcendental / a priori", category: "概念", note: "康德语境中 transcendental 研究经验何以可能；a priori 指不依赖具体经验，两者不能简单混同。" },
  { id: "general-will", zh: "公意", en: "general will", category: "概念", note: "卢梭所说面向共同利益的公共意志，不等同于所有私人意见的简单总和。" },
  { id: "dialectic", zh: "辩证法", en: "dialectic", category: "概念", note: "可指问答检验、矛盾推进或历史运动；柏拉图与黑格尔用法差异很大。" },
  { id: "genealogy", zh: "谱系", en: "genealogy", category: "概念", note: "通过价值和制度的生成历史揭示其生命需要与权力来源。" },
  { id: "logical-analysis", zh: "逻辑分析", en: "logical analysis", category: "概念", note: "通过揭示命题的逻辑形式澄清、重构或消除哲学问题。" },
  { id: "freedom", zh: "自由", en: "freedom / liberty", category: "概念", note: "英文两词常可互换，但政治自由、意志自由和内在自由需要按语境区分。" },

  { id: "republic", zh: "《理想国》", en: "Republic", category: "著作", note: "柏拉图讨论正义、教育、灵魂结构和哲学王的核心对话。" },
  { id: "city-of-god", zh: "《上帝之城》", en: "The City of God", category: "著作", note: "奥古斯丁以两座城的区分回应罗马衰落并重构历史意义。" },
  { id: "leviathan", zh: "《利维坦》", en: "Leviathan", category: "著作", note: "霍布斯从自然状态、契约和授权论证强大主权者。" },
];

export const terminologyByZh = new Map(terminology.map((term) => [term.zh, term]));
export const terminologyMatchers = [...terminology]
  .sort((a, b) => b.zh.length - a.zh.length)
  .map((term) => term.zh);
