import { argument as a, group as g } from "./topic-unit";

export const ultimateSummaryTree = [
  g("ultimate-5-ground", "希腊哲学至普罗提诺", "解释许多事物之后，还需要一个最高根据吗？",
    "巴门尼德检验存在能否来自非存在；柏拉图把稳定知识和宇宙秩序联系到形式与善；亚里士多德区分原因的解释任务。普罗提诺进一步以太一、理智与灵魂理解多如何依赖一。存在、原因与最高善在这里相接，但并不是同一个概念。",
    "如果最高根据还是善，为什么世界仍有缺陷、痛苦和恶？", [
      g("ultimate-10-being-good", "巴门尼德与柏拉图", "稳定的存在与善，怎样成为解释的根据？", "巴门尼德从存在与非存在的可思性提出限制；柏拉图则以形式与善理解知识和秩序。二者都越过变化现象追问根据，但不能将存在直接等同于善。", "解释根据还须说明它怎样与具体、多样的事物相关。", [
        a("ultimate-20-being", "巴门尼德", "不存在的东西，能够作为生成的来源吗？", "巴门尼德要求关于存在的说法保持可思与自洽，拒绝诉诸非存在来说明生成。这改变了变化论证的负担，并不直接提供基督教意义的创造者，也不是靠一句“一切不变”就取消经验。", "可以转到自然，比较保留成分、解释重组的回答。", `being-from-nonbeing stable-being motion-and-plurality-possible`),
        a("ultimate-20-form-good", "柏拉图", "可知秩序与最高善之间有什么关系？", "柏拉图以稳定形式回应知识问题，并在宇宙论中以形式与善说明有序世界。这使认识、存在与价值互相联系；但认识不变对象并不自动证明灵魂不朽，宇宙有秩序也不是已经验证了每个目的解释。", "形式与个别事物怎样相关，还须逐项说明。", `what-stabilizes-knowledge stable-object-of-knowledge forms-and-particulars how-can-cosmos-reflect-good cosmos-shaped-by-form-and-good can-soul-survive-body immortal-rational-soul`),
      ]),
      g("ultimate-10-causes-one", "亚里士多德与普罗提诺", "说明事物的原因，与说明多如何来自一有何不同？", "亚里士多德的形式与原因分析说明具体事物的结构和活动；普罗提诺的层级依赖则把多联系到太一。这里先核对两种解释任务，不把一套原因分析当作已经证明另一套最高实体。", "最高根据的善与有限世界的缺陷将成为下一组问题。", [
        a("ultimate-20-causes", "亚里士多德", "说清材料和动力，就已说清事物为什么存在吗？", "四因提醒我们区分材料、形式、变化来源和目的的解释作用。当前节点先提供这种原因框架，帮助进入最高根据的问题；它没有独立展开“不动的推动者”的完整论证，不能把四因表直接当作该论证的结论。", "沿终极路径继续比较：普罗提诺如何说明整个多样世界的依赖。", `what-makes-explanation-complete immanent-form-matter four-causes-teleology how-can-causes-be-known demonstration-classification change-as-actualization-question potentiality-actuality`),
        a("ultimate-20-one", "普罗提诺", "多依赖于一，是否意味着世界本身是恶？", "普罗提诺以太一、理智、灵魂理解层级依赖，流溢并不是源头流失一部分物质。感性世界作为较低层次的像，并不因此全然邪恶。太一也不能未经区分就替换成按时间作选择的创造者。", "基督教创造与救赎叙事将把善和恶放进不同框架。", `is-inner-freedom-enough one-intellect-soul how-many-from-one emanation-without-loss is-sensible-world-evil dependent-image-not-evil reason-or-divine-aid`),
      ]),
    ], "先区分存在、原因和善，再问多样世界是否依赖更高的统一根据。", [{ label: "SEP · 普罗提诺", url: "https://plato.stanford.edu/entries/plotinus/" }, { label: "SEP · 亚里士多德的自然哲学", url: "https://plato.stanford.edu/entries/aristotle-natphil/" }]),

  g("ultimate-5-evil-time", "教父时期与波爱修斯", "若世界来自善，为什么仍有恶、时间与失去？",
    "基督教传统以创造、盟约和救赎理解历史。奥古斯丁把恶解释为善的缺失和意志秩序的偏离，并追问时间与永恒的关系。波爱修斯在命运失落中寻找不随外物变化的善，尝试区分永恒认识与强迫行动。这些答案同时涉及终极根据和人的责任。",
    "这些解释哪些能由理性论证，哪些依赖启示与信仰？", [
      g("ultimate-10-creation-evil", "教父传统与奥古斯丁", "善的创造者与不完善的受造世界怎样相容？", "创造把世界理解为依赖上帝，恶的缺失论拒绝把恶当作同等独立的实体。但这还要解释意志为何偏离、受害者为何承受痛苦，不能把一个定义当作所有困难已经消失。", "对恶的回应又涉及人的能力与恩典。", [
        a("ultimate-20-creation", "犹太—基督教传统与奥利金", "最高善会不会进入具体历史并向人启示？", "创造、盟约与救赎叙事把最高根据与具体历史相连。奥利金借逻各斯和多层经文解释探索信仰与理性的关系。解释文本的层次必须有论证，不能把任何寓意都当作经文已明确说出。", "一位善的创造者如何容许恶，是这套框架内部的追问。", `does-transcendent-good-act-in-history scriptural-history-observation creator-covenant-salvation-history how-can-revelation-enter-reason logos-layered-exegesis-text`),
        a("ultimate-20-evil-grace", "奥古斯丁", "恶是独立力量，还是善与意志的败坏？", "奥古斯丁拒绝把恶看成与善对等的实体，而以缺失和爱的错序解释它。人的意志可能知道善却不能实行，需要恩典医治。这保留了意志与责任问题，而不是把所有错误简单归给身体或知识不足。", "同一论证可转入自我，细看分裂意志与行动能力。", `if-creator-good-whence-evil evil-privation-disordered-will can-will-heal-itself grace-heals-divided-will`),
      ]),
      g("ultimate-10-eternity-providence", "奥古斯丁与波爱修斯", "永恒怎样与时间中的历史和自由相关？", "奥古斯丁把时间也放在创造之内，不把帝国成败直接当作救赎尺度。波爱修斯则区分上帝的永恒认识与人的时间经验，试图保存偶然行动。", "区分概念之后，仍要检验解释是否真的保存自由。", [
        a("ultimate-20-time-history", "奥古斯丁", "永恒是不是无限延长的时间？", "奥古斯丁不把永恒仅当作没有尽头的时间序列，时间属于受造世界。两城的历史理解也不把政治胜利等同于终极完成。因此历史事件有意义，并不表示人能从帝国兴衰直接读出上帝的全部计划。", "若上帝知道时间中的行动，行动为何仍可能自由？", `how-time-history-relate-eternity created-time-and-two-cities can-salvation-community-survive-empire`),
        a("ultimate-20-providence", "波爱修斯", "永恒知道我的选择，会不会使选择成为必然？", "波爱修斯区分随财富地位变化的幸运与最高善，并以永恒当下说明上帝的认识：知道一个行动，不等于在时间中强迫它发生。这个区分意在保留自由，还须继续检查无误知识与偶然性的关系。", "可以沿自我主线比较不同的自由与归责方案。", `what-good-survives-fortune western-institutions-fragment-observation highest-good-not-fortune does-providence-cancel-freedom eternal-present-knows-contingently`),
      ]),
    ], "创造引出恶的问题，永恒引出时间与预知的问题；善的框架并未取消人的责任。"),

  g("ultimate-5-reason-faith", "伊斯兰、犹太与拉丁经院哲学", "理性关于上帝能说到哪一步？",
    "阿维森纳从可能存在者追问必然存在；安瑟尔谟尝试由最伟大的概念论证存在。否定神学警惕把有限事物的属性原样加到上帝身上。阿奎那区分从效果可论证的前导真理与启示的奥秘，也区分创造的依赖和时间的开端。不同论证的起点和终点必须核对。",
    "近代体系把上帝、知识与整体秩序重新连接，论证负担并未消失。", [
      g("ultimate-10-necessity-language", "阿维森纳、爱留根纳与迈蒙尼德", "关于最高存在的论证，能否使用普通事物的语言？", "必然存在的论证追问可能事物为何实际存在；否定神学则提醒我们，对最高根据的命名有边界。证明一个根据与知道其全部性质是两项不同任务。", "把概念推到极致，是否就能证明它有现实对象？", [
        a("ultimate-20-necessary-being", "阿维森纳", "可能不存在的事物，为何实际上存在？", "阿维森纳区分本质与存在，从可能存在者的依赖追问必然存在者。该方案不是说每个被命名的本质都必须实例化，也不能不经论证就把必然秩序等同于有自由选择的创造行为。", "若最高根据不依赖别物，描述它的词语该如何使用？", `why-possible-existents-exist essence-existence-necessary-existent does-necessary-order-leave-divine-choice`),
        a("ultimate-20-negative-theology", "爱留根纳与迈蒙尼德", "说上帝是善，是否与说一个人善含义完全相同？", "爱留根纳通过肯定与否定讨论超越存在的上帝；迈蒙尼德强调否定描述与行动属性，防止把人的复合性质加给神。这不是宣称所有话语都无意义，而是要求分辨哪些说法在限定、哪些在指示作用。", "同一个词能否跨越有限与无限，仍有不同的经院回答。", `how-can-unknowable-god-manifest fourfold-nature-theophany-return does-theophany-dissolve-creation affirmation-negation-beyond-being how-can-language-speak-of-simple-god negative-theology-action-attributes`),
      ]),
      g("ultimate-10-proof-boundaries", "安瑟尔谟与阿奎那", "从概念或效果出发，分别能够证明什么？", "安瑟尔谟考察最伟大者的概念；阿奎那从效果追问第一因并另行说明神的属性。两种路径不能压成一句“哲学证明上帝”，更不能把论证结论无缝扩展为全部教义。", "知识的保证若依赖上帝，还必须证明推理没有循环。", [
        a("ultimate-20-concept-proof", "安瑟尔谟及其批评者", "最伟大的概念，是否必须在现实中存在？", "安瑟尔谟在信仰寻求理解的框架内，论证最伟大者不能只存在于理解中。反对意见追问：定义中的要求能否保证实例？要比较具体推理，不能把论证当作现代共识，也不能仅凭陌生就跳过。", "另一条路径改从经验中的效果追问原因。", `what-can-reason-add-to-faith faith-seeks-understanding-in-love can-concept-of-greatest-show-existence greatest-cannot-exist-only-in-understanding can-definition-guarantee-instance`),
        a("ultimate-20-aquinas", "阿奎那", "由世界的效果出发，能否推出全部信仰内容？", "阿奎那从效果论证第一因，再讨论为何可赋予它神的属性；类比命名避免把受造者与神说成完全同类。理性前导与启示奥秘分工，创造也不同于时间开端，因而不能把五路扩写成对所有教义的独立证明。", "从最高根据走向知识确定性，还需要新的桥梁论证。", `can-reason-and-revelation-divide-labor natural-preambles-revealed-mysteries what-can-effects-prove-first-cause five-ways-from-effects does-first-cause-yet-count-as-god first-cause-to-divine-attributes how-can-creature-words-name-god analogical-names-neither-same-nor-unrelated is-god-one-being-among-others subsistent-being-creatures-participate do-secondary-causes-have-real-power created-causes-real-under-first-cause can-reason-prove-temporal-beginning creation-not-same-as-temporal-beginning where-natural-demonstration-reaches-limit revelation-supplies-saving-truths`),
      ]),
    ], "区分从依赖、概念和效果出发的论证；知道一个根据，不等于知道全部教义。"),

  g("ultimate-5-certainty-limits", "笛卡尔至康德", "完整的世界解释，能否得到我们所要求的保证？",
    "笛卡尔借不欺骗的上帝支持清楚分明的认识。斯宾诺莎以神即自然的必然秩序解释世界；莱布尼茨以充分理由、可能世界和选择解释现实。休谟要求判断服从证据的分量；康德则限制理性把灵魂、世界和上帝当作可知对象。追问最高根据也包括检验这类追问的能力边界。",
    "如果理论知识不能完成终极证明，人还怎样面对意义、痛苦与信仰？", [
      g("ultimate-10-rational-order", "笛卡尔、斯宾诺莎与莱布尼茨", "知识和世界的秩序，能否由最高根据保证？", "笛卡尔把上帝放入知识重建，斯宾诺莎讨论单一实体的必然性，莱布尼茨解释为何这个可能世界成为现实。它们对于自由、偶然与恶的处理不同，必须连同起点比较。", "体系是否自洽之外，还要问我们有何证据接受它。", [
        a("ultimate-20-cartesian-guarantee", "笛卡尔", "从我的确定存在，怎样走到世界可信？", "我思首先确认正在思考者的存在，不能直接恢复整个外部世界。笛卡尔再以无限完满观念和不欺骗的上帝支持清楚分明的认识，并解释错误来自意志超出理解。各步的依赖关系需要核对，不能省成“我思所以世界存在”。", "若自然本身就是统一秩序，还需要怎样的神观？", `does-any-judgment-survive-hyperbolic-doubt cogito-performed-certainty can-cogito-yield-general-truth-rule clear-distinct-perception-provisional-rule can-finite-thinker-secure-clear-distinct-truth infinite-perfect-idea-points-beyond-finite-self would-perfect-god-systematically-deceive nondeceiving-god-secures-attended-clear-perceptions why-error-if-nondeceiving-god error-when-will-outruns-intellect can-external-material-things-be-recovered material-world-recovered-with-sensory-limits`),
        a("ultimate-20-order-evil", "斯宾诺莎与莱布尼茨", "完整理由会不会取消偶然，并把痛苦说成善？", "斯宾诺莎以神即自然说明统一秩序；莱布尼茨区分必然真理与事实真理，并以最佳可共存世界说明选择。允许恶不等于称恶本身为善。两家的神观和自由理论不同，对受苦者的问题也不能只用体系完整来结束。", "这些超出直接经验的断言，需要怎样的检验？", `one-substance-god-or-nature how-can-finite-things-differ-within-one-substance attributes-and-modes-articulate-one-nature what-can-freedom-mean-in-necessary-nature conatus-and-adequate-understanding-increase-agency can-individuals-and-contingency-survive-complete-intelligibility monads-as-active-perspectival-unities does-complete-reason-make-every-truth-necessary truths-of-reason-fact-and-possible-worlds why-is-this-world-actual-among-possibilities best-compossible-world-as-choice-reason can-best-world-justify-evil-and-suffering evil-permitted-not-good-in-itself if-mind-and-body-do-not-interact-how-correspond mind-body-parallel-expression how-can-windowless-monads-share-one-world preestablished-harmony-coordinates-perspectives`),
      ]),
      g("ultimate-10-evidence-critique", "休谟与康德", "理性能够判断证据，也能知道超经验对象吗？", "休谟比较证言与经验的支持力度，节制怀疑要求既不轻信也不拒绝生活。康德区分经验知识、理念的调节作用与实践理性的要求。没有理论证明，不等于任何信念都同样有理。", "理论知识的限度使意义与实践问题更加突出。", [
        a("ultimate-20-testimony", "休谟", "异常证言什么时候值得相信？", "休谟要求按全部证据权衡信念，把奇迹证言与经验中的规则性、证言的可靠性一起比较。这里选读证据与节制怀疑，未据此声称已经完整展开休谟对一切宗教论证的批判。", "检验单个证据之外，还可问理性是否越出了认识能力的范围。", `how-weigh-miracle-testimony-without-dogmatism extraordinary-testimony-conflicts-experience-observation proportion-belief-to-total-evidence can-scepticism-guide-life-without-paralysis mitigated-scepticism-limits-and-corrects-inquiry`),
        a("ultimate-20-critical-limits", "康德", "上帝、灵魂与自由都能成为理论知识吗？", "康德限制知识于可能经验，灵魂、世界和上帝的理念不能直接构成超经验对象的知识。实践立场中的自由具有另一地位，也不是观测得到的对象。不能把限制理论证明写成简单证明不存在，或把实践要求写成科学事实。", "在这种边界内，生活是否仍可能有承诺和方向？", `do-cognitive-conditions-describe-things-in-themselves knowledge-limited-to-phenomena-not-private-illusion what-status-for-soul-world-god-ideas ideas-regulative-not-constitutive-knowledge how-can-freedom-coexist-with-natural-causality two-standpoints-natural-causality-practical-freedom can-practical-reason-know-transcendent-freedom freedom-practical-postulate-not-theoretical-object can-subject-object-nature-freedom-unify-historically`),
      ]),
    ], "体系要求完整理由，经验批判要求证据，康德再追问理性能够知道什么。", [{ label: "SEP · 康德的宗教哲学", url: "https://plato.stanford.edu/entries/kant-religion/" }]),

  g("ultimate-5-meaning", "黑格尔至实用主义与分析哲学", "没有公认的最终答案，怎样面对痛苦并判断意义？",
    "黑格尔追求理解整体，整体仍要面对未获和解的生命。叔本华以意志解释痛苦，尼采诊断最高价值失去约束力后的虚无主义。詹姆斯探讨证据未决时有条件的信仰承诺；实用主义与分析方法要求继续检验后果和论证。这些是不同的出路，不是一条已完成的精神进步史。",
    "从具体困惑重新进入自我、社会或自然，让新的证据和经验继续修正理解。", [
      g("ultimate-10-whole-suffering", "黑格尔与叔本华", "整体的意义能够解释个人承受的痛苦吗？", "黑格尔的整体与历史解释面对自由、排除和苦难的检验；叔本华从意志的无尽追求说明痛苦。他们对理性和世界的评价相反，不能把后者写成前者体系中的一个阶段。", "即使拒绝乐观的整体叙事，仍要判断怎样生活。", [
        a("ultimate-20-totality", "黑格尔", "世界可被理性理解，就意味着一切现状都合理吗？", "黑格尔的客观唯心论把理性放入世界的结构，而非只当作私人想法。“现实合理”不能简化为对所有事实的赞许；贫困、排斥和未获和解的生命仍要求检验整体是否兑现自由。", "一种更悲观的回答把理性之后的冲动看成世界关键。", `can-conceptual-dialectic-describe-objective-world objective-idealism-reason-immanent-in-world does-actual-rational-mean-every-state-is-right actuality-is-critical-standard-not-fact-worship does-world-history-redeem-suffering-and-exclusion totality-must-remain-answerable-to-unreconciled-lives why-self-consciousness-needs-mutual-recognition mutual-recognition-constitutes-social-selfhood can-domination-secure-recognition asymmetric-recognition-undermines-itself why-abstract-right-and-private-conscience-insufficient ethical-life-mediates-family-civil-society-state can-civil-society-correct-poverty-it-produces institutions-contain-market-without-abolishing-particularity`),
        a("ultimate-20-will-suffering", "叔本华", "痛苦只是偶然失败，还是无尽欲求的结果？", "叔本华由身体经验通向意志，把世界理解为表象与意志的双重面向，并以追求、满足和无聊说明痛苦的结构。他讨论审美、同情与禁欲的松动作用。这是形而上评价，不是以统计已经证明人生必然不值得。", "尼采进一步追问：否定意志是否会延续对生命的否定？", `can-body-give-access-to-thing-in-itself body-double-aspect-observation world-double-aspect-representation-and-will can-human-will-be-extended-to-all-nature will-as-nonpersonal-striving-across-nature is-suffering-accident-or-structure-of-willing striving-satisfaction-boredom-observation pessimism-from-endless-willing does-pessimism-follow-without-value-premise pessimism-is-metaphysical-evaluation-not-measurement how-can-subject-loosen-service-to-will aesthetic-contemplation-suspends-personal-striving compassion-crosses-principium-individuationis ascetic-negation-reduces-will-to-life does-negating-will-repeat-nihilism`),
      ]),
      g("ultimate-10-values-belief", "尼采、詹姆斯与开放探究", "失去终极保证，是否只剩任意相信？", "尼采要求重估价值，不能只换一个偶像。詹姆斯讨论特定未决处境中的承诺，而不许可为了有用就任意相信。比较后果、解释和论证，仍为不同立场提供相互批评的可能。", "不封闭结论，也不放弃判断，是继续阅读的要求。", [
        a("ultimate-20-nihilism", "尼采", "旧的最高价值失去力量之后，怎样避免虚无？", "“上帝死了”诊断价值根据的危机，而不只是一句无神论口号。尼采借谱系追问价值的来源与作用，以重估和生命肯定回应虚无。视角主义不是任何解释等价，价值创造也要面对任意残酷和政治风险。", "另一种路线在多元经验中限定何时可以承担信仰。", `what-does-death-of-god-diagnose erosion-of-transcendent-values-observation death-of-god-opens-nihilism-crisis can-nihilism-be-overcome-with-new-dogma overcoming-nihilism-requires-revaluation-not-substitute-idol what-can-genealogy-show-about-value genealogy-links-origin-function-affect-effect is-perspectivism-simple-relativism perspectivism-compares-situated-interpretations can-revaluation-avoid-arbitrary-cruelty revaluation-tests-creative-flourishing-with-political-risk what-does-eternal-recurrence-test eternal-recurrence-as-affirmation-test-not-proven-cosmology how-ressentiment-revalues-noble-power ressentiment-creates-reactive-good-evil how-debt-punishment-becomes-guilt bad-conscience-internalizes-aggression-and-debt does-will-to-power-mean-political-domination will-to-power-as-overcoming-and-organization-contested affirmation-revalues-suffering-without-worshipping-it`),
        a("ultimate-20-open-belief", "詹姆斯与后续方法比较", "证据尚未决定时，个人承诺能否成为公共证明？", "詹姆斯把信仰意志限定于真实可选、无法回避而重大的未决选择。私人宗教经验可以支持个人承诺，却不能自动证明普遍教义。实用主义的检验与逻辑分析也不宣称单独解决历史、价值和全部经验。", "回到原始节点，看承诺的条件与公共判断的标准是否满足。", `how-act-before-evidence-can-settle will-to-believe-bounded-live-forced-momentous-options religious-experience-variety-observation can-private-experience-ground-public-doctrine private-experience-permits-commitment-not-universal-proof is-truth-whatever-is-currently-useful truth-grows-through-verification-and-reality-constraint can-formal-analysis-settle-history-value-experience plural-methods-correct-without-totalizing how-combine-clarity-history-experience-freedom-public-correction`),
      ]),
    ], "整体不能抹去痛苦，价值创造不免于批评，个人承诺也不能冒充公共证明。"),
];
