import { readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Script } from "node:vm";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const readerDir = path.join(projectRoot, "offline-reader");
const htmlPath = path.join(readerDir, "index.html");

let html = await readFile(htmlPath, "utf8");

const scriptTag = html.match(/<script[^>]+src="([^"]+)"[^>]*><\/script>/);
const styleTag = html.match(/<link[^>]+rel="stylesheet"[^>]+href="([^"]+)"[^>]*>/);

if (!scriptTag || !styleTag) {
  throw new Error("Offline build did not contain the expected script and stylesheet assets.");
}

const scriptPath = path.resolve(readerDir, scriptTag[1]);
const stylePath = path.resolve(readerDir, styleTag[1]);
const [script, style] = await Promise.all([
  readFile(scriptPath, "utf8"),
  readFile(stylePath, "utf8"),
]);

new Script(script, { filename: "offline-reader.js" });

html = html
  .replace(styleTag[0], () => `<style>\n${style}\n</style>`)
  .replace(scriptTag[0], () => `<script>\n${script.replaceAll("</script", "<\\/script")}\n</script>`)
  .replace("<head>", "<head>\n    <!-- Generated by npm run build:offline. Edit the source project, not this file. -->");

await writeFile(htmlPath, html, "utf8");
await rm(path.join(readerDir, "assets"), { recursive: true, force: true });
